### ISSUE TITLE
"Started Updated UTMP about System Runlevel Changes"

### ISSUE THREAD

**Issue by hamishjones** [mynodebtc/mynode#10]
Newb question,

I've flashed a new SD card and am trying to set this up on a Pi 3. It's been stuck on the status mentioned in the Subject line for 12 hours. Is this too long or can it take longer?

Just prior to this I had two issues where it:

Failed to start Bitcoin Daemon
Failed to start LND Lightning Daemon

**Comment by tehelsper** [comment]
So, I assume you're looking at the console output via HDMI? That will look like it reports errors when there aren't actually any issues. The real GUI is available via web browser on on your laptop or PC. Try logging into the device by hitting enter a few times and then use the default credentials admin/bolt to log in.

Once logged in a message will appear that gives you a URL like http://10.10.10.1/ or something. Enter that URL into your web browser and you will see the web GUI. It will show the actual status of the device.

Does that resolve this for you?

**Comment by hamishjones** [comment]
Ahh, I didn't think to log in the web gui from another device. Got quick sync started now so we'll see how long this takes with Australia's slow internet.
