### ISSUE TITLE
stuck in quick synch copying files

### ISSUE THREAD

**Issue by haukehess** [mynodebtc/mynode#101]
my hdd has a filesystem error that broke several files. For example

```
$ cd /mnt/hdd/mynode/bitcoin
$ du -h
24G	./indexes/txindex
24G	./indexes
du: cannot read directory './database': Permission denied
4.0K	./database
du: cannot access './chainstate/212611.ldb': Bad message
du: cannot access './chainstate/212916.ldb': Bad message
du: cannot access './chainstate/212720.ldb': Bad message
du: cannot access './chainstate/211941.ldb': Bad message
du: cannot access './chainstate/212284.ldb': Bad message
du: cannot access './chainstate/211983.ldb': Bad message
du: cannot access './chainstate/212798.ldb': Bad message
du: cannot access './chainstate/213307.ldb': Bad message
du: cannot access './chainstate/213553.ldb': Bad message
du: cannot access './chainstate/212486.ldb': Bad message
du: cannot access './chainstate/211875.ldb': Bad message
du: cannot access './chainstate/213348.ldb': Bad message
du: cannot access './chainstate/212168.ldb': Bad message
du: cannot access './chainstate/212880.ldb': Bad message
du: cannot access './chainstate/213306.ldb': Bad message
du: cannot access './chainstate/211790.ldb': Bad message
du: cannot access './chainstate/212629.ldb': Bad message
du: cannot access './chainstate/213116.ldb': Bad message
du: cannot access './chainstate/213557.ldb': Bad message
du: cannot access './chainstate/211789.ldb': Bad message
du: cannot access './chainstate/212238.ldb': Bad message
du: cannot access './chainstate/212853.ldb': Bad message
du: cannot access './chainstate/212479.ldb': Bad message
du: cannot access './chainstate/212237.ldb': Bad message
du: cannot access './chainstate/213214.ldb': Bad message
du: cannot access './chainstate/212350.ldb': Bad message
du: cannot access './chainstate/212772.ldb': Bad message
du: cannot access './chainstate/211985.ldb': Bad message
du: cannot access './chainstate/212167.ldb': Bad message
du: cannot access './chainstate/211984.ldb': Bad message
du: cannot access './chainstate/213215.ldb': Bad message
68K	./chainstate
24G	.

```

I'd have to chkdsk my hdd and maybe even wipe it totally. I tried resynching the blockchain, but it stuck at "copying files" after the torrents were completely downloaded. I guess the process bitches with the broken filesystem and doesn't repair it properly at boot time.

How do I get out of this mess?

**Comment by haukehess** [comment]
one solution might be to unmount the hdd and run fsck on it, but I have no clue how to end all the processes working on hdd. Is there a boot flag or boot command to reboot without mounting the hdd?

**Comment by haukehess** [comment]
the problematic code in mynode.py catches the exception from the "du" "-m" part checking the directories, assumes 0% and 100% for the result and loops. In case of a corrupted file system, there should be a button offering to fsck the drive or even wipe it clean for a do over.

**Comment by haukehess** [comment]
Connecting the external hdd to another raspi and running fsck over /dev/sda1 fixed lots of errors and wiped chainstate while on it. Would be nice if that had been possible from the settings menu of mynode.

**Comment by haukehess** [comment]
btw. "cmdline.txt" contains fsck=true, but this doesn't check external hdds. I have no idea how to pull that off, but it would enhance UX very much

**Comment by tehelsper** [comment]
You could try the "Repair Drive" option on the settings page. It runs fsck on the external drive.

**Comment by haukehess** [comment]
Yes, reading the whole settings page would have given me that clue. I'll try it next time, for now I'm good. But still I'd prefer to have it in the "0% copied data" page as an exception handler instead of ignoring the corrupt file system. Closed for good :-)
