### ISSUE TITLE
myNode failed to find public IP

### ISSUE THREAD

**Issue by johnchisenhall** [mynodebtc/mynode#118]
It's been working pretty seamlessly. Did the latest update to 0.1.75 version and two days ago I noticed the message "failed to find public IP" in the Settings area. I hit the refresh button and it was immediately resolved. Today I got the same message but the refresh button is not helping.

I noticed while trying to learn how to open a lightning channel and realized the lightning wallets were giving a "waiting" message.
Thanks
John

**Comment by johnchisenhall** [comment]
in the VPN area it's giving me an alert to "Please forward port 51194 to your myNode's local IP address"... it seems obvious but i'm not very technically saavy I guess

**Comment by Amiga500** [comment]
You have to create a lightning wallet on LND.
For VPN, you have to enter into router settings and open 51194 for TCP/UPD related to the ip of your rpi/rock64 where myNode is working

**Comment by tehelsper** [comment]
Aged out
