### ISSUE TITLE
Premium without purchase

### ISSUE THREAD

**Issue by cactuska** [mynodebtc/mynode#119]
Hi,
Just wanted to report that not it is easy to gain premium features without actually buying the software.
I have tested it with the Virtual machine version, but I am afraid, all versions are affected.

All I have done is
REMOVED

I would be happy if you would have a bounty program 
BR

**Comment by tehelsper** [comment]
Yes, I am aware that is is possible to bypass premium. As an open source project, it is difficult to force people to purchase a key without there being an option to update the code yourself and bypass the protections. I trust that people do the right thing and purchase a license if they are enjoying the product and want to upgrade.

Please don't post instructions on bypassing premium.

**Comment by cactuska** [comment]
ok, I see you already removed the details.
Thank you for checking
