### ISSUE TITLE
Question / Enhancement: what happens on hdd failure on low voltage?

### ISSUE THREAD

**Issue by haukehess** [mynodebtc/mynode#12]
I used raspibolt before, and there my raspi went in full brick mode after hdd failures (which occur every 2 months, even though I have a separate power adapter plugged to the hdd via y-cabel). I know it's my problem, but rebuilding the blockchain isn't that bad for me, as long as I wouldn't have to recover from brick mode by fully rebuilding the sd card from scratch.

So how would myNode recover from hdd failure? I didn't find a faq or something in the guides on this...

**Comment by tehelsper** [comment]
I haven't had anything near as often as every 2 months, but I have noticed drive issues.

The typical response is for the OS to mark the drive as read-only or for a block to get corrupted. myNode will either auto-correct the corrupted blocks or display as Bitcoin can no longer sync. A reboot will fix the latter issue.

**Comment by tehelsper** [comment]
Long-term though, that issue may continue occurring and a better power supply or more powerful device would be recommended.
