### ISSUE TITLE
Stop MAC randomization on reboot RBP3

### ISSUE THREAD

**Issue by jpduhen** [mynodebtc/mynode#125]
Since myNode is using NetManager, on every reboot my MAC-address is randomized (I'm on WiFi). My router thinks there's a new device (MAC) connecting, hence a new internal IP is assigned to myNode-RBP3. This is very cumbersome.
The solution is given here: https://blog.muench-johannes.de/networkmanager-disable-mac-randomization-314

Would you please implement this 'fix' in future versions of myNode?

**Comment by Amiga500** [comment]
Interesting.. if you want to resolve for now.. you can use a static ip for wifi. Check here:
https://www.reddit.com/r/mynodebtc/comments/e7jki5/how_to_enable_static_ip_and_wifi_connection/

**Comment by tehelsper** [comment]
I've added that file to future releases. You can test now by doing a manual upgrade if you want.

**Comment by jpduhen** [comment]
Thanks for Youri swift reaction! Sofar....Fix seems to work.
