### ISSUE TITLE
One Click Upgrade Not Working

### ISSUE THREAD

**Issue by VwH387RXAF1m61wOtwuU** [mynodebtc/mynode#127]
Still not working for me since the first time I did it after installing MyNode Premium on Christmas. Just tried again, .76 to .79, rebooted, web page said Upgrading, did this for about 10 minutes, took me back to login screen, still on .76. When I do the manual upgrade process, everything works as expected. I have provided logs to help email address before, but my node will not one click upgrade since .74 or whatever version was release on 12/25.

**Comment by tehelsper** [comment]
Can you run this command and send me the output via email?

sudo /usr/bin/mynode_upgrade.sh

**Comment by tehelsper** [comment]
Closing due to age.
