### ISSUE TITLE
GUIDE LIST: Router Port Forwarding

### ISSUE THREAD

**Issue by g0mp** [mynodebtc/mynode#13]
Would it be possible to list all ports (e.g. in the guides section, or web GUI) you may want to forward on your router to allow certain services?

Column description example:
Port | Service | Optional[Y/N] | Required to allow ...

example: 
- If I want other lightning nodes to be able to find and connect to mynode (optional), which ports should I forward.
- Default forwarded ports, none?

**Comment by tehelsper** [comment]
The "Show Rules" button on the settings page will now display all the port info.
