### ISSUE TITLE
mynode fails to start on Raspberry Pi 4

### ISSUE THREAD

**Issue by tril0byte** [mynodebtc/mynode#133]
This issue occurred on a Raspberry Pi 4 4GB with a 0.1.72. Upgraded to 0.1.79, still occurring.

My node is failing to start and gets in a loop. This mynode_startup.sh fails every minute or so.  This has the side effect of never writing the resolv.conf file since it fails before that part, so QuickSync can't start due to using DNS.  It appears to be that dphys-swapfile is calculating 2x the RAM (4GB x 2 = 8GB) and returning with a 1 exit status, causing mynode_startup.sh to terminate early. It is then re-run by systemd on a schedule.  The swapfile is repeatedly re-created and deleted.  The script appears to hard-code a 1GB swap file which causes this conflict with the size calculated by dphys-swapfile.

sudo /usr/bin/mynode_startup.sh
[...]
+ dd if=/dev/zero of=/mnt/hdd/swapfile count=1000 bs=1MiB
1000+0 records in
1000+0 records out
1048576000 bytes (1.0 GB, 1000 MiB) copied, 14.5874 s, 71.9 MB/s
+ chmod 600 /mnt/hdd/swapfile
+ mkswap /mnt/hdd/swapfile
Setting up swapspace version 1, size = 1000 MiB (1048571904 bytes)
no label, UUID=5028392a-54e5-4d60-a5b7-b280993169f8
+ dphys-swapfile setup
computing size, want /mnt/hdd/swapfile=7930MByte, restricting to config limit: 1024MBytes, checking existing: deleting wrong size file (1048576000)

**Comment by tril0byte** [comment]
commenting out the "dphys-swapfile setup" line results in a successful script execution.

**Comment by tehelsper** [comment]
Which line in the script was failing?

**Comment by tril0byte** [comment]
dphys-swapfile setup

**Comment by tehelsper** [comment]
Hopefully the DNS issue is resolved as part of some other changes.

What is in your /etc/dphys-swapfile?

**Comment by tril0byte** [comment]
The DNS issue is that the script terminated when dphys-swapfile returned 1. The next lines after dphys-swapfile in the mynode_startup created the resolv.conf. The script aborted before that, so those lines never got executed and resolv.conf was empty.

Having trouble attaching the whole file, here are the only uncommented lines:
CONF_MAXSWAP=1024
CONF_SWAPFILE=/mnt/hdd/swapfile

**Comment by tehelsper** [comment]
Right, I understand the DNS problem, but I'm trying to figure out why your device is trying to create such a large swapfile.

Can you try:
- Manually deleting the swapfile and rebooting?
- Update the dphys-swapfile to have a different MAXSWAP number - like 1000 or 512?

**Comment by tril0byte** [comment]
The man page for dphys-swapfile says the default is to 2X physical RAM. I have a 4GB RAM model. So it's trying to make an 8GB swap file. But the configuration is hard coded to 1GB, and you also use dd and hard-code it to create a 1 GB file.  It's clearly a conflict between hard-coding the swap size (in the shell script) and then immediately (calling "dphys-swapfile setup") to dynamically determine the swap size. You have to pick one...

**Comment by tehelsper** [comment]
You're right - "swapon" should be the only necessary command. Added to next version.

**Comment by tehelsper** [comment]
Closing issue.
