### ISSUE TITLE
Community donation Splitting

### ISSUE THREAD

**Issue by tril0byte** [mynodebtc/mynode#134]
I notice Whirlpool (as well as VPN, and Remote Tor Access) shows as a premium feature. Since you will be earning Premium purchases from Samourai's hard work (among others), have you approached Samourai to discuss what an appropriate portion of the currently $99 premium should be donated back to support Samourai? I ask this not to stir up trouble but to point out that it looks bad, and Samourai might not be okay with it.

It should be possible to use Lightning to send Samourai a cut with every purchase on your side and publish clearly that you do so.  However, I'd prefer the user to choose the proportion of how much to donate to Samourai, RTL, Tor, etc.  
The myNode would be an ideal platform for recurring donations.  Have the node run a scheduled job every month to: Call "lnurl invoice" on each project the user wishes to donate to and auto-pay it from the wallet.
In this way you can request a donation to myNode and make other people's code included in Community Edition, avoiding any appearance of conflicts of interest by charging money for other people's code they already released.

**Comment by tehelsper** [comment]
tril0byte,

I want to do everything I can to support the community, but the $99 for premium is intended to support my work integrating all of the projects. If a user would like to contribute to other projects, that is fantastic! I believe there is value is combining these solutions and the projects benefit from additional exposure and expanding their userbases. I don't see this as a conflict of interest, but as something that is mutually beneficial.

I check the licenses of each project and make sure that I am not violating any agreements by including their software in each myNode distribution. Most projects can be included without any modifications.

That is a great idea regarding recurring donations to the various projects. It wouldn't be high on my priority list right now, but I'd happily integrate it if it is something you would like to submit a PR for.

Additionally, each project has their own goals and monetization strategies. May be trying to gain popularity or expand the ecosystem, other attempt to monetize their work in various ways:
- Samourai benefits through fees as people use it to mix coins
- LNDHub gets people using Blue Wallet that has a Marketplace built in
- LND Connect gets more people to use Zap and it's upcoming Lightning exchange
- BTCPay Server needs popularity to get large donations for its foundation

Hope that helps explain my reasoning.

Taylor

**Comment by asperks** [comment]
Surely this can be closed.  If we're even talking about a pure licensing discussion, the only requirement from mynodebtc is that the existing source used within the node is attributed, and is freely available for people to access it install directly, and install themselves as they see fit.  All of the services and apps for mynode are open source, and freely available, so anyone can install their own versions of the software if they wish.

The service being offered here is that it is all available in a single place.  And it's a top service indeed.

**Comment by tehelsper** [comment]
Agreed. Closing.
