### ISSUE TITLE
Upgrade from 0.1.71 to 0.1.79 causes VirtualBox deployed myNode to lose disk mountpoint

### ISSUE THREAD

**Issue by yunier2002** [mynodebtc/mynode#136]
Created VirtualBox VM from myNode supplied .ova file. First thing I did was upgrade to 0.1.79 manually and the upgrade process worked fine. After reboot the /dev/sdb1 drive is no longer being mounted to /mnt/hdd. 

myNode UI says HD is missing. Mounting the drive manually fixes the issue but has to be done on each reboot. I'm guessing this is only affecting VirtualBox setups.

If this can be fixed for the next release for those of us that use VirtualBox it would be great.

**Comment by tehelsper** [comment]
Hey, did you ever upgrade to v0.1.78? The issue may have been in that version as well.

How did you mount the drive manually? When the drive is not mounted, does it look like there are any files in /mnt/hdd?

**Comment by yunier2002** [comment]
No I never upgraded to v0.1.78 so don't know about that. When the drive is not mounted there's still a "mynode" folder and "swapfile" in /mnt/hdd/ but the mynode folder only have a docker and settings directories inside it. Not sure where those come from and I'm guessing they get replaced when the disk is mounted.

I mount it manually using this command: sudo mount /dev/sdb1 /mnt/hdd

Sometimes it works (maybe just the first time, still testing) and mynode.service starts after it fine but other times it doesn't and it fails starting that service with this error:

`Jan 18 04:04:06 mynode mynode[18040]: + touch /etc/resolvconf/run/resolv.conf
Jan 18 04:04:06 mynode mynode[18040]: touch: cannot touch '/etc/resolvconf/run/resolv.conf': No such file or directory`

That run directory is missing, other errors in bitcoind too probably corrupt after mount is not available to start.

I guess I'll have to stay on earlier version until this is fixed.

If you need any more specifics to troubleshoot let me know

**Comment by winney123** [comment]
I can affirm that the same problem occurs when manually updating to v0.1.78

![image](https://user-images.githubusercontent.com/42574731/72722214-1441dc00-3b7e-11ea-9c3b-d60903620858.png)

**Comment by tehelsper** [comment]
Thanks, that's helpful and will hopefully be resolved in the next update.

**Comment by winney123** [comment]
Confirm: issue solved in v0.1.83

**Comment by yunier2002** [comment]
upgraded to v0.1.85 and issue resolved. Thanks
