### ISSUE TITLE
HTTPS doesn't stick

### ISSUE THREAD

**Issue by tril0byte** [mynodebtc/mynode#138]
When logging out it, it takes you back to the non-HTTPS login page, so if you log back in you are back on HTTP. Logging out from HTTPS  should go to the HTTPS version of login page.

**Comment by tehelsper** [comment]
Still looking into this. Flask+hitch doesn't make it easy.

**Comment by tehelsper** [comment]
Moved to a flask (HTTP) + gunicorn (HTTPS) to resolve this for now. I want to go to gunicorn + nginx soon though.

Issue resolved in v0.2.12.
