### ISSUE TITLE
HARDENING: MyNode SSH using key-based authentication

### ISSUE THREAD

**Issue by g0mp** [mynodebtc/mynode#14]
Changing the password using http instead of https could possibly leak the new password.
This password can then easily be used for SSH access, because the SSH server is enabled by default and has 'admin' as default username.   

It's fairly easy to create a private and public key on a client and change the policy on the pi to now allow password logins any longer. Only computers / mobiles with the correct private key has access. I tried it and it works for me. Only one computer and a mobile have acces via SSH to MyNode. All other attempts from other computers will be denied. 

The details are described in the section 'Using key-based authentication' on
https://www.raspberrypi.org/documentation/configuration/security.md

There is also a section about the maximum amount of attempts before being blacklisted with the use of fail2ban, maybe also something to look into.

**Comment by tehelsper** [comment]
@g0mp Would you like to write a guide on how you did this specifically for myNode? I could add it to the website.

**Comment by g0mp** [comment]
Hi @tehelsper , it seems I'm unable to upload a document here, zip or pdf. Do you have an alternative I can send the draft guide to? Please verify before making public ;)

**Comment by tehelsper** [comment]
You can email it to admin@mynodebtc.com

Thanks!

**Comment by g0mp** [comment]
Sent. Please let me know if you agree with the content and format, looking at the other guides I tried to keep it as much text based as possible. Cheers

**Comment by tehelsper** [comment]
I didn't seem to get it. Can you send it again or upload it somewhere and send or post the link?

**Comment by g0mp** [comment]
I'll send it again to admin@mynodebtc.com :)

**Comment by g0mp** [comment]
https://we.tl/t-ZWWpbOqQFj
