### ISSUE TITLE
Enable all CPU Cores in Bitcoin when Quicksync Off

### ISSUE THREAD

**Issue by tril0byte** [mynodebtc/mynode#141]
If a user disables quicksync, it would help if myNode automatically changed bitcoind.conf line par=-1 to par=0 (or remove it for the default par=0).  This gives a **noticeable performance boost during the initial block download (IBD)**.  Setting par=-1 as it is now, means to leave one CPU core unused, and that CPU core is doing nothing until the IBD completes. -1 makes sense after block download, to leave an extra CPU core for Lightning and other processes, so you can set it back to -1 after Bitcoin is synced. But it shouldn't make much difference to just leave it as 0, as Bitcoin doesn't use much CPU after IBD.

**Comment by tehelsper** [comment]
It could, but the web GUI performance degraded as well when I was testing (although this was several months ago). It would also require restarting bitcoind dynamically once IBD was done, which would be easy to detect, but I'm concerned it would have false positives when devices are syncing and degrade the UX and introduce instability. I think I'd rather err on the cautious side and leave it at -1.

**Comment by tril0byte** [comment]
For those who want to update this manually, it's not in bitcoind.conf but in /etc/systemd/system/bitcoind.service - just change par=-1 to par=0.  I recommend noting this in a document for those power users like myself who want to speed up block download by 33%, which is significant.  And while we're editing bitcoin params, those users probably want to add -assumevalid=0 to fully validate all scripts.

**Comment by tehelsper** [comment]
If you'd like to update the GitHub Wiki, that would be awesome. I'd like to start putting more info there since it can be updated by the community, but it is still very new.

**Comment by abhiShandy** [comment]
I've added this to the wiki: https://github.com/mynodebtc/mynode/wiki/Tips-and-tricks-for-power-users
Feel free to add more such tips.

Please close this issue.
