### ISSUE TITLE
HTTPS instead of HTTP?

### ISSUE THREAD

**Issue by g0mp** [mynodebtc/mynode#15]
HTTPS would prevent clear text with possible valuable information going over the network when using the web GUI. 

Cheers

**Comment by tehelsper** [comment]
Unfortunately, there are issues using HTTPS on a local network. I'm working on making it an option though. Users will have to click through the "warning" most browsers display when using HTTPS with self-signed certs.

**Comment by tehelsper** [comment]
Added HTTPS option in v0.1.57.

**Comment by bavarianledger** [comment]
HTTPS is not working on RPi4 on 0.1.57 and 0.1.58.
There's the Lock in the top-right corner redirecting to https:// but there is nothing listening on port 443.

**Comment by tehelsper** [comment]
Can you run "sudo systemctl status https"? Is that service enabled on your device?

**Comment by bavarianledger** [comment]
@tehelsper The service was not enabled:

> sudo systemctl status https
```
https.service - Proxy for HTTPS
   Loaded: loaded (/etc/systemd/system/https.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

But you start it manually:
> sudo systemctl start https
> sudo systemctl status https
```
https.service - Proxy for HTTPS
   Loaded: loaded (/etc/systemd/system/https.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-23 02:47:22 CDT; 2s ago
```
How to enable it after each reboot:

> sudo systemctl enable https.service
```
Created symlink /etc/systemd/system/multi-user.target.wants/https.service → /etc/systemd/system/https.service.
```
Maybe because setup_device.sh isn't called when doing a manual upgrade?
