### ISSUE TITLE
Stuck in copying files

### ISSUE THREAD

**Issue by Dolu89** [mynodebtc/mynode#151]
Hello,

I have launched mynode for the first timeyesterday and I got this message today :
```
QuickSync
Copying files... This will take several hours.
0.13%
```

I tried the same as #101 command to verify my case and it seems normal
```
admin@myNode:~ $ cd /mnt/hdd/mynode/bitcoin
admin@myNode:/mnt/hdd/mynode/bitcoin $ du -h
417M    ./blocks
417M    .
```
My version is 0.1.74

Do you have any advice?
Thanks

**Comment by abhiShandy** [comment]
Have you fixed this?
If yes, please close this issue.
If not, try toggling QuickSync from the settings page.

**Comment by Dolu89** [comment]
I found it's because my SSD. If your SSD or HDD is not ~2x bigger than the blockchain size, you can't sync it.
Is it correct?

**Comment by abhiShandy** [comment]
QuickSync and Bitcoin blockchain needs more than 500GB in total? If you disable quicksync, then you can manage with a 500GB drive, but it's recommended to have 1TB.

**Comment by tehelsper** [comment]
If you have an SSD, just disable QuickSync. myNode will actually default to QuickSync disabled if it looks at the drive and can tell it is an SSD (some don't detect properly).

**Comment by tehelsper** [comment]
Closing since this issue is likely due to drive size.
