### ISSUE TITLE
Run mainnet and testnet simultaneously

### ISSUE THREAD

**Issue by justinmoon** [mynodebtc/mynode#157]
Is this possible to run bitcoind on mainnet and testnet simultaneously?

**Comment by Amiga500** [comment]
i don't think is possible

**Comment by tehelsper** [comment]
Nope, you would need to run testnet on a separate device.

**Comment by elDaz2** [comment]
How do you configure mynode to use Testnet ?

**Comment by tehelsper** [comment]
Change the bitcoind config to use testnet would be the first step, but I don't know,  I've never done it.

**Comment by elDaz2** [comment]
When I uncomment 'testnet=1' in Bitcoin.conf I get: "Bitcoin has experienced an error. Please check the logs."
