### ISSUE TITLE
Setting up myNode with previously downloaded blockchain

### ISSUE THREAD

**Issue by chdwlch** [mynodebtc/mynode#163]
I was switching from RaspiBlitz to myNode so I already had a copy of the blockchain that was synced via the Bitcoin network. Following the installation tutorial via https://mynodebtc.com/download wiped my SSD without a warning. There is a warning on the following Getting Started page.

It would be nice if there was a method to use an existing copy of the blockchain to avoid the downtime and bandwidth usage associated with the sync. 

I think it would be a good idea to have an additional warning about the automatic disk wipe attached to the https://mynodebtc.com/download page.

**Comment by tehelsper** [comment]
Added new warning on the download page. There is a guide available on how to re-use blockchain data.

https://mynodebtc.com/guide/using_bitcoin_data_from_existing_node

**Comment by Gtiaom99** [comment]
The link does not work anymore. Has this been solved, I want to change from raspiblitz to MyNode also and I don't want to loose all the data, I just waited 5 days.

**Comment by tehelsper** [comment]
Try this link node:

https://mynodebtc.github.io/bitcoin/using-existing-bitcoin-data.html
