### ISSUE TITLE
Responsive UI using bootstrap

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#17]
Hey Taylor,

I would like to add bootstrap CSS to make the UI responsive to different screen sizes. If you are not working on it already, I'll start refactoring the templates.

Best,
Abhishek

**Comment by tehelsper** [comment]
Abhishek,

I'm not sure I want to go that route yet. I'd rather focus on getting in more features as opposed making widespread UI changes which may cause issues for some users. I do like Bootstrap, but I just don't think the risk/reward is worth it at this point. Thanks for the suggestion! I like the dark mode work so far!

**Comment by abhiShandy** [comment]
No worries. I'll keep it aside in a branch.
