### ISSUE TITLE
Error communicating with bitcoind. Node may be busy syncing.  'result'

### ISSUE THREAD

**Issue by craig5999** [mynodebtc/mynode#172]
Sometimes when using the built in explorer and clicking on an address I get this error message:

Error communicating with bitcoind. Node may be busy syncing. 'result'

It happens with both older and newer blocks. I'm not sure if it's due to syncing, because some addresses show fine and then others not.

Any idea what could be causing it? I'm on a Pi3b+.

**Comment by tehelsper** [comment]
The built-in explorer has been deprecated. Try using BTC RPC Explorer on a recent version of myNode instead. It works very well now that I have fixed a few integration bugs.

Here's a guide on how to upgrade:
https://mynodebtc.com/guide/upgrading_your_device
