### ISSUE TITLE
LND Error on start

### ISSUE THREAD

**Issue by chdwlch** [mynodebtc/mynode#173]
myNode version 0.1.84 on Raspberry Pi 4

After finishing quick sync, I was unable to create a lightning wallet due to waiting on the LND daemon to start.

Jan 30 16:48:08 myNode systemd[1]: Stopped LND Lightning Daemon.
Jan 30 16:48:08 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 1.
Jan 30 16:48:08 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Jan 30 16:48:06 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jan 30 16:48:06 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 16:48:06 myNode lnd[3095]: /home/bitcoin/.lnd/lnd.conf:37: unknown option: nat
Jan 30 16:48:06 myNode lnd[3087]: + exit 0
Jan 30 16:48:06 myNode systemd[1]: Started LND Lightning Daemon.

To fix this I had to comment out `nat=false` in lnd.conf at line 37 under the autopilot section

**Comment by tehelsper** [comment]
Had you upgraded with the manual upgrade process? There was an issue with one of the commits, but it should be fixed if you re-run the manual upgrade process.

**Comment by chdwlch** [comment]
Yeah I had just manually upgraded to 0.1.84. It looks like I have all of the latest commits in my local repo.

**Comment by chdwlch** [comment]
actually I didn't need to comment out `nat=false`. `[Application Options]` on the line above needed a newline in front of it

**Comment by tehelsper** [comment]
Good to know. I'll look into it and add a newline in the upcoming 0.1.85

**Comment by tehelsper** [comment]
I reproduced this issue and fixed in the 0.1.85 release. Can you verify it is resolved?

**Comment by winney123** [comment]
Yep, I can confirm it's solved by upgrading to 0.1.85. 
Tnx!
