### ISSUE TITLE
Feature requests: Blocksat & Veracrypt

### ISSUE THREAD

**Issue by MrPaz** [mynodebtc/mynode#174]
I would like to try myNode, but the main thing stopping me is that I use my current pi node to run Blocksat.  I would love if I could run Blocksat on myNode and get all the additional functionality, Dojo, etc vs my current set up.  And having Blocksat available adds a huge extra level of badassery to myNode!
[https://github.com/Blockstream/satellite#running-on-raspberry-pi](url)

I also like having VeraCrypt handy on devices to store any sensitive crypto files.  Would be another sweet addition.
[https://github.com/veracrypt/VeraCrypt](url)

What is the base OS myNode runs on?  Would it happen to be Ubuntu Mate?  If so it's trivially easy to compile Blocksat and Veracrypt on it, and I could do it myself.  If it's a different distro, perhaps the devs could look into adding these features?

Thanks

**Comment by Amiga500** [comment]
As now myNode is on:

Raspberry pi = Raspbian OS
Rock64 = Armbian OS
VM image = Debian 10

As i saw for pi, you can easily install veracrypt (https://codeyarns.com/2019/05/16/how-to-install-veracrypt-on-raspbian/) and blockstream Satellite through Docker (and https://hub.docker.com/u/blockstream and https://github.com/Blockstream/satellite/pull/14/commits/f903460d24c79a76eca07d9b0a80f1f4606f2fea)

I like it too the idea to have both software.. never say never :)

**Comment by tehelsper** [comment]
Aging out. Not adding soon.
