### ISSUE TITLE
LND doesn't start (RPi3)

### ISSUE THREAD

**Issue by asperks** [mynodebtc/mynode#175]
I've installed from image a few weeks ago on a raspberry pi 3.  LND didn't work.  On the settings page it says : 
   LND Status
   Error 
Today I decided to look at it.  I manually upgraded the software as per update instructions.  Update complete.  Everything is as before.  Bitcoin features work (like core and electrum server) but LND features don't.  When I 'Show' the log in the settings screen, this is what I get :

Feb 01 21:07:15 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Feb 01 21:07:15 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 21:07:14 myNode systemd[1]: Started LND Lightning Daemon.
Feb 01 21:07:14 myNode lnd[2970]: + exit 0
Feb 01 21:07:14 myNode lnd[2970]: }
Feb 01 21:07:14 myNode lnd[2970]:   "warnings": ""
Feb 01 21:07:14 myNode lnd[2970]:   },
Feb 01 21:07:14 myNode lnd[2970]:     }
Feb 01 21:07:14 myNode lnd[2970]:       "since": 481824
Feb 01 21:07:14 myNode lnd[2970]:       "timeout": 1510704000,
Feb 01 21:07:14 myNode lnd[2970]:       "startTime": 1479168000,
Feb 01 21:07:14 myNode lnd[2970]:       "status": "active",
Feb 01 21:07:14 myNode lnd[2970]:     "segwit": {
Feb 01 21:07:14 myNode lnd[2970]:     },
Feb 01 21:07:14 myNode lnd[2970]:       "since": 419328
Feb 01 21:07:14 myNode lnd[2970]:       "timeout": 1493596800,
Feb 01 21:07:14 myNode lnd[2970]:       "startTime": 1462060800,
Feb 01 21:07:14 myNode lnd[2970]:       "status": "active",
Feb 01 21:07:14 myNode lnd[2970]:     "csv": {
Feb 01 21:07:14 myNode lnd[2970]:   "bip9_softforks": {
Feb 01 21:07:14 myNode lnd[2970]:   ],
Feb 01 21:07:14 myNode lnd[2970]:     }
Feb 01 21:07:14 myNode lnd[2970]:       }
Feb 01 21:07:14 myNode lnd[2970]:         "status": true
Feb 01 21:07:14 myNode lnd[2970]:       "reject": {
Feb 01 21:07:14 myNode lnd[2970]:       "version": 4,
Feb 01 21:07:14 myNode lnd[2970]:       "id": "bip65",
Feb 01 21:07:14 myNode lnd[2970]:     {
Feb 01 21:07:14 myNode lnd[2970]:     },
Feb 01 21:07:14 myNode lnd[2970]:       }
Feb 01 21:07:14 myNode lnd[2970]:         "status": true
Feb 01 21:07:14 myNode lnd[2970]:       "reject": {
Feb 01 21:07:14 myNode lnd[2970]:       "version": 3,
Feb 01 21:07:14 myNode lnd[2970]:       "id": "bip66",
Feb 01 21:07:14 myNode lnd[2970]:     {
Feb 01 21:07:14 myNode lnd[2970]:     },
Feb 01 21:07:14 myNode lnd[2970]:       }
Feb 01 21:07:14 myNode lnd[2970]:         "status": true
Feb 01 21:07:14 myNode lnd[2970]:       "reject": {
Feb 01 21:07:14 myNode lnd[2970]:       "version": 2,
Feb 01 21:07:14 myNode lnd[2970]:       "id": "bip34",
Feb 01 21:07:14 myNode lnd[2970]:     {
Feb 01 21:07:14 myNode lnd[2970]:   "softforks": [
Feb 01 21:07:14 myNode lnd[2970]:   "pruned": false,
Feb 01 21:07:14 myNode lnd[2970]:   "size_on_disk": 296185742714,
Feb 01 21:07:14 myNode lnd[2970]:   "chainwork": "00000000000000000000000000000000000000000c4c8fd7fbd899de85b88e6e",
Feb 01 21:07:14 myNode lnd[2970]:   "initialblockdownload": false,
Feb 01 21:07:14 myNode lnd[2970]:   "verificationprogress": 0.9999942017848978,
Feb 01 21:07:14 myNode lnd[2970]:   "mediantime": 1580608233,
Feb 01 21:07:14 myNode lnd[2970]:   "difficulty": 15466098935554.65,
Feb 01 21:07:14 myNode lnd[2970]:   "bestblockhash": "0000000000000000000b1baf5e27e445ace47a0f72fcc6f10737c6a89a545867",
Feb 01 21:07:14 myNode lnd[2970]:   "headers": 615593,
Feb 01 21:07:14 myNode lnd[2970]:   "blocks": 615593,
Feb 01 21:07:14 myNode lnd[2970]:   "chain": "main",
Feb 01 21:07:14 myNode lnd[2970]: {
Feb 01 21:07:14 myNode lnd[2970]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Feb 01 21:07:14 myNode lnd[2970]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:07:14 myNode lnd[2970]: Checking if Bitcoin is synced...
Feb 01 21:07:14 myNode lnd[2970]: + echo 'Checking if Bitcoin is synced...'
Feb 01 21:07:14 myNode lnd[2970]: + set -e
Feb 01 21:07:14 myNode systemd[1]: Starting LND Lightning Daemon...
Feb 01 21:07:14 myNode systemd[1]: Stopped LND Lightning Daemon.
Feb 01 21:07:14 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 2.
Feb 01 21:07:14 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Feb 01 21:07:13 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Feb 01 21:07:13 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 21:07:13 myNode lnd[2911]: unknown flag `ignore-historical-gossip-filters'
Feb 01 21:07:13 myNode lnd[2911]: unknown flag `ignore-historical-gossip-filters'
Feb 01 21:07:13 myNode lnd[2909]: + exit 0
Feb 01 21:07:13 myNode systemd[1]: Started LND Lightning Daemon.
Feb 01 21:07:13 myNode lnd[2909]: }
Feb 01 21:07:13 myNode lnd[2909]:   "warnings": ""
Feb 01 21:07:13 myNode lnd[2909]:   },
Feb 01 21:07:13 myNode lnd[2909]:     }
Feb 01 21:07:13 myNode lnd[2909]:       "since": 481824
Feb 01 21:07:13 myNode lnd[2909]:       "timeout": 1510704000,
Feb 01 21:07:13 myNode lnd[2909]:       "startTime": 1479168000,
Feb 01 21:07:13 myNode lnd[2909]:       "status": "active",
Feb 01 21:07:13 myNode lnd[2909]:     "segwit": {
Feb 01 21:07:13 myNode lnd[2909]:     },
Feb 01 21:07:13 myNode lnd[2909]:       "since": 419328
Feb 01 21:07:13 myNode lnd[2909]:       "timeout": 1493596800,
Feb 01 21:07:13 myNode lnd[2909]:       "startTime": 1462060800,
Feb 01 21:07:13 myNode lnd[2909]:       "status": "active",
Feb 01 21:07:13 myNode lnd[2909]:     "csv": {
Feb 01 21:07:13 myNode lnd[2909]:   "bip9_softforks": {
Feb 01 21:07:13 myNode lnd[2909]:   ],
Feb 01 21:07:13 myNode lnd[2909]:     }
Feb 01 21:07:13 myNode lnd[2909]:       }
Feb 01 21:07:13 myNode lnd[2909]:         "status": true
Feb 01 21:07:13 myNode lnd[2909]:       "reject": {
Feb 01 21:07:13 myNode lnd[2909]:       "version": 4,
Feb 01 21:07:13 myNode lnd[2909]:       "id": "bip65",
Feb 01 21:07:13 myNode lnd[2909]:     {
Feb 01 21:07:13 myNode lnd[2909]:     },
Feb 01 21:07:13 myNode lnd[2909]:       }
Feb 01 21:07:13 myNode lnd[2909]:         "status": true
Feb 01 21:07:13 myNode lnd[2909]:       "reject": {
Feb 01 21:07:13 myNode lnd[2909]:       "version": 3,
Feb 01 21:07:13 myNode lnd[2909]:       "id": "bip66",
Feb 01 21:07:13 myNode lnd[2909]:     {
Feb 01 21:07:13 myNode lnd[2909]:     },
Feb 01 21:07:13 myNode lnd[2909]:       }
Feb 01 21:07:13 myNode lnd[2909]:         "status": true
Feb 01 21:07:13 myNode lnd[2909]:       "reject": {
Feb 01 21:07:13 myNode lnd[2909]:       "version": 2,
Feb 01 21:07:13 myNode lnd[2909]:       "id": "bip34",
Feb 01 21:07:13 myNode lnd[2909]:     {
Feb 01 21:07:13 myNode lnd[2909]:   "softforks": [
Feb 01 21:07:13 myNode lnd[2909]:   "pruned": false,
Feb 01 21:07:13 myNode lnd[2909]:   "size_on_disk": 296185742714,
Feb 01 21:07:13 myNode lnd[2909]:   "chainwork": "00000000000000000000000000000000000000000c4c8fd7fbd899de85b88e6e",
Feb 01 21:07:13 myNode lnd[2909]:   "initialblockdownload": false,
Feb 01 21:07:13 myNode lnd[2909]:   "verificationprogress": 0.9999942091711163,
Feb 01 21:07:13 myNode lnd[2909]:   "mediantime": 1580608233,
Feb 01 21:07:13 myNode lnd[2909]:   "difficulty": 15466098935554.65,
Feb 01 21:07:13 myNode lnd[2909]:   "bestblockhash": "0000000000000000000b1baf5e27e445ace47a0f72fcc6f10737c6a89a545867",
Feb 01 21:07:13 myNode lnd[2909]:   "headers": 615593,
Feb 01 21:07:13 myNode lnd[2909]:   "blocks": 615593,
Feb 01 21:07:13 myNode lnd[2909]:   "chain": "main",
Feb 01 21:07:13 myNode lnd[2909]: {
Feb 01 21:07:12 myNode lnd[2909]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Feb 01 21:07:12 myNode lnd[2909]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:07:12 myNode lnd[2909]: Checking if Bitcoin is synced...
Feb 01 21:07:12 myNode lnd[2909]: + echo 'Checking if Bitcoin is synced...'
Feb 01 21:07:12 myNode lnd[2909]: + set -e
Feb 01 21:07:12 myNode systemd[1]: Starting LND Lightning Daemon...
Feb 01 21:07:12 myNode systemd[1]: Stopped LND Lightning Daemon.
Feb 01 21:07:12 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 1.
Feb 01 21:07:12 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Feb 01 21:07:11 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Feb 01 21:07:11 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 21:07:11 myNode lnd[2845]: unknown flag `ignore-historical-gossip-filters'
Feb 01 21:07:10 myNode systemd[1]: Started LND Lightning Daemon.
Feb 01 21:07:10 myNode lnd[2618]: + exit 0
Feb 01 21:07:10 myNode lnd[2618]: }
Feb 01 21:07:10 myNode lnd[2618]:   "warnings": ""
Feb 01 21:07:10 myNode lnd[2618]:   },
Feb 01 21:07:10 myNode lnd[2618]:     }
Feb 01 21:07:10 myNode lnd[2618]:       "since": 481824
Feb 01 21:07:10 myNode lnd[2618]:       "timeout": 1510704000,
Feb 01 21:07:10 myNode lnd[2618]:       "startTime": 1479168000,
Feb 01 21:07:10 myNode lnd[2618]:       "status": "active",
Feb 01 21:07:10 myNode lnd[2618]:     "segwit": {
Feb 01 21:07:10 myNode lnd[2618]:     },
Feb 01 21:07:10 myNode lnd[2618]:       "since": 419328
Feb 01 21:07:10 myNode lnd[2618]:       "timeout": 1493596800,
Feb 01 21:07:10 myNode lnd[2618]:       "startTime": 1462060800,
Feb 01 21:07:10 myNode lnd[2618]:       "status": "active",
Feb 01 21:07:10 myNode lnd[2618]:     "csv": {
Feb 01 21:07:10 myNode lnd[2618]:   "bip9_softforks": {
Feb 01 21:07:10 myNode lnd[2618]:   ],
Feb 01 21:07:10 myNode lnd[2618]:     }
Feb 01 21:07:10 myNode lnd[2618]:       }
Feb 01 21:07:10 myNode lnd[2618]:         "status": true
Feb 01 21:07:10 myNode lnd[2618]:       "reject": {
Feb 01 21:07:10 myNode lnd[2618]:       "version": 4,
Feb 01 21:07:10 myNode lnd[2618]:       "id": "bip65",
Feb 01 21:07:10 myNode lnd[2618]:     {
Feb 01 21:07:10 myNode lnd[2618]:     },
Feb 01 21:07:10 myNode lnd[2618]:       }
Feb 01 21:07:10 myNode lnd[2618]:         "status": true
Feb 01 21:07:10 myNode lnd[2618]:       "reject": {
Feb 01 21:07:10 myNode lnd[2618]:       "version": 3,
Feb 01 21:07:10 myNode lnd[2618]:       "id": "bip66",
Feb 01 21:07:10 myNode lnd[2618]:     {
Feb 01 21:07:10 myNode lnd[2618]:     },
Feb 01 21:07:10 myNode lnd[2618]:       }
Feb 01 21:07:10 myNode lnd[2618]:         "status": true
Feb 01 21:07:10 myNode lnd[2618]:       "reject": {
Feb 01 21:07:10 myNode lnd[2618]:       "version": 2,
Feb 01 21:07:10 myNode lnd[2618]:       "id": "bip34",
Feb 01 21:07:10 myNode lnd[2618]:     {
Feb 01 21:07:10 myNode lnd[2618]:   "softforks": [
Feb 01 21:07:10 myNode lnd[2618]:   "pruned": false,
Feb 01 21:07:10 myNode lnd[2618]:   "size_on_disk": 296185742714,
Feb 01 21:07:10 myNode lnd[2618]:   "chainwork": "00000000000000000000000000000000000000000c4c8fd7fbd899de85b88e6e",
Feb 01 21:07:10 myNode lnd[2618]:   "initialblockdownload": false,
Feb 01 21:07:10 myNode lnd[2618]:   "verificationprogress": 0.9999942313297725,
Feb 01 21:07:10 myNode lnd[2618]:   "mediantime": 1580608233,
Feb 01 21:07:10 myNode lnd[2618]:   "difficulty": 15466098935554.65,
Feb 01 21:07:10 myNode lnd[2618]:   "bestblockhash": "0000000000000000000b1baf5e27e445ace47a0f72fcc6f10737c6a89a545867",
Feb 01 21:07:10 myNode lnd[2618]:   "headers": 615593,
Feb 01 21:07:10 myNode lnd[2618]:   "blocks": 615593,
Feb 01 21:07:10 myNode lnd[2618]:   "chain": "main",
Feb 01 21:07:10 myNode lnd[2618]: {
Feb 01 21:07:09 myNode lnd[2618]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Feb 01 21:07:09 myNode lnd[2618]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:06:39 myNode lnd[2618]: + /bin/sleep 30s
Feb 01 21:06:39 myNode lnd[2618]: BTC not synced, sleeping 30s
Feb 01 21:06:39 myNode lnd[2618]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:06:39 myNode lnd[2618]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:06:09 myNode lnd[2618]: + /bin/sleep 30s
Feb 01 21:06:09 myNode lnd[2618]: BTC not synced, sleeping 30s
Feb 01 21:06:09 myNode lnd[2618]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:06:09 myNode lnd[2618]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:06:09 myNode lnd[2618]: Checking if Bitcoin is synced...
Feb 01 21:06:09 myNode lnd[2618]: + echo 'Checking if Bitcoin is synced...'
Feb 01 21:06:09 myNode lnd[2618]: + set -e
Feb 01 21:06:09 myNode systemd[1]: Starting LND Lightning Daemon...

**Comment by tehelsper** [comment]
This issue is caused by LND not having been successfully updated. Which version of myNode are you running?

Can you go to the settings page and attempt a re-install of LND? Your version of LND is likely not v0.8.0+.

**Comment by asperks** [comment]
Will do and report.  I don't remember that being an option in the previous settings screen.  I've kicked off the LND update process now.

**Comment by asperks** [comment]
I'm using the latest version of the node.  I updated the node this morning using git, and used the scripts to re-make the install.

Same error.  It completed the update, and the error still was there.  I rebooted the node, and LND still won't start.  This is the log of the node.

Feb 01 21:45:46 myNode lnd[3887]:       "status": "active",
Feb 01 21:45:46 myNode lnd[3887]:     "csv": {
Feb 01 21:45:46 myNode lnd[3887]:   "bip9_softforks": {
Feb 01 21:45:46 myNode lnd[3887]:   ],
Feb 01 21:45:46 myNode lnd[3887]:     }
Feb 01 21:45:46 myNode lnd[3887]:       }
Feb 01 21:45:46 myNode lnd[3887]:         "status": true
Feb 01 21:45:46 myNode lnd[3887]:       "reject": {
Feb 01 21:45:46 myNode lnd[3887]:       "version": 4,
Feb 01 21:45:46 myNode lnd[3887]:       "id": "bip65",
Feb 01 21:45:46 myNode lnd[3887]:     {
Feb 01 21:45:46 myNode lnd[3887]:     },
Feb 01 21:45:46 myNode lnd[3887]:       }
Feb 01 21:45:46 myNode lnd[3887]:         "status": true
Feb 01 21:45:46 myNode lnd[3887]:       "reject": {
Feb 01 21:45:46 myNode lnd[3887]:       "version": 3,
Feb 01 21:45:46 myNode lnd[3887]:       "id": "bip66",
Feb 01 21:45:46 myNode lnd[3887]:     {
Feb 01 21:45:46 myNode lnd[3887]:     },
Feb 01 21:45:46 myNode lnd[3887]:       }
Feb 01 21:45:46 myNode lnd[3887]:         "status": true
Feb 01 21:45:46 myNode lnd[3887]:       "reject": {
Feb 01 21:45:46 myNode lnd[3887]:       "version": 2,
Feb 01 21:45:46 myNode lnd[3887]:       "id": "bip34",
Feb 01 21:45:46 myNode lnd[3887]:     {
Feb 01 21:45:46 myNode lnd[3887]:   "softforks": [
Feb 01 21:45:46 myNode lnd[3887]:   "pruned": false,
Feb 01 21:45:46 myNode lnd[3887]:   "size_on_disk": 296190207905,
Feb 01 21:45:46 myNode lnd[3887]:   "chainwork": "00000000000000000000000000000000000000000c4cba0b180b8b196c3ceb4f",
Feb 01 21:45:46 myNode lnd[3887]:   "initialblockdownload": false,
Feb 01 21:45:46 myNode lnd[3887]:   "verificationprogress": 0.9999957972802096,
Feb 01 21:45:46 myNode lnd[3887]:   "mediantime": 1580609838,
Feb 01 21:45:46 myNode lnd[3887]:   "difficulty": 15466098935554.65,
Feb 01 21:45:46 myNode lnd[3887]:   "bestblockhash": "000000000000000000064e64245f34775eb28492e39dc5206acff83a781409a6",
Feb 01 21:45:46 myNode lnd[3887]:   "headers": 615596,
Feb 01 21:45:46 myNode lnd[3887]:   "blocks": 615596,
Feb 01 21:45:46 myNode lnd[3887]:   "chain": "main",
Feb 01 21:45:46 myNode lnd[3887]: {
Feb 01 21:45:45 myNode lnd[3887]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Feb 01 21:45:45 myNode lnd[3887]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:45:45 myNode lnd[3887]: Checking if Bitcoin is synced...
Feb 01 21:45:45 myNode lnd[3887]: + echo 'Checking if Bitcoin is synced...'
Feb 01 21:45:45 myNode lnd[3887]: + set -e
Feb 01 21:45:45 myNode systemd[1]: Starting LND Lightning Daemon...
Feb 01 21:45:45 myNode systemd[1]: Stopped LND Lightning Daemon.
Feb 01 21:45:45 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 2.
Feb 01 21:45:45 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Feb 01 21:45:44 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Feb 01 21:45:44 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 21:45:44 myNode lnd[3863]: unknown flag `ignore-historical-gossip-filters'
Feb 01 21:45:44 myNode lnd[3863]: unknown flag `ignore-historical-gossip-filters'
Feb 01 21:45:43 myNode systemd[1]: Started LND Lightning Daemon.
Feb 01 21:45:43 myNode lnd[3596]: + exit 0
Feb 01 21:45:43 myNode lnd[3596]: }
Feb 01 21:45:43 myNode lnd[3596]:   "warnings": ""
Feb 01 21:45:43 myNode lnd[3596]:   },
Feb 01 21:45:43 myNode lnd[3596]:     }
Feb 01 21:45:43 myNode lnd[3596]:       "since": 481824
Feb 01 21:45:43 myNode lnd[3596]:       "timeout": 1510704000,
Feb 01 21:45:43 myNode lnd[3596]:       "startTime": 1479168000,
Feb 01 21:45:43 myNode lnd[3596]:       "status": "active",
Feb 01 21:45:43 myNode lnd[3596]:     "segwit": {
Feb 01 21:45:43 myNode lnd[3596]:     },
Feb 01 21:45:43 myNode lnd[3596]:       "since": 419328
Feb 01 21:45:43 myNode lnd[3596]:       "timeout": 1493596800,
Feb 01 21:45:43 myNode lnd[3596]:       "startTime": 1462060800,
Feb 01 21:45:43 myNode lnd[3596]:       "status": "active",
Feb 01 21:45:43 myNode lnd[3596]:     "csv": {
Feb 01 21:45:43 myNode lnd[3596]:   "bip9_softforks": {
Feb 01 21:45:43 myNode lnd[3596]:   ],
Feb 01 21:45:43 myNode lnd[3596]:     }
Feb 01 21:45:43 myNode lnd[3596]:       }
Feb 01 21:45:43 myNode lnd[3596]:         "status": true
Feb 01 21:45:43 myNode lnd[3596]:       "reject": {
Feb 01 21:45:43 myNode lnd[3596]:       "version": 4,
Feb 01 21:45:43 myNode lnd[3596]:       "id": "bip65",
Feb 01 21:45:43 myNode lnd[3596]:     {
Feb 01 21:45:43 myNode lnd[3596]:     },
Feb 01 21:45:43 myNode lnd[3596]:       }
Feb 01 21:45:43 myNode lnd[3596]:         "status": true
Feb 01 21:45:43 myNode lnd[3596]:       "reject": {
Feb 01 21:45:43 myNode lnd[3596]:       "version": 3,
Feb 01 21:45:43 myNode lnd[3596]:       "id": "bip66",
Feb 01 21:45:43 myNode lnd[3596]:     {
Feb 01 21:45:43 myNode lnd[3596]:     },
Feb 01 21:45:43 myNode lnd[3596]:       }
Feb 01 21:45:43 myNode lnd[3596]:         "status": true
Feb 01 21:45:43 myNode lnd[3596]:       "reject": {
Feb 01 21:45:43 myNode lnd[3596]:       "version": 2,
Feb 01 21:45:43 myNode lnd[3596]:       "id": "bip34",
Feb 01 21:45:43 myNode lnd[3596]:     {
Feb 01 21:45:43 myNode lnd[3596]:   "softforks": [
Feb 01 21:45:43 myNode lnd[3596]:   "pruned": false,
Feb 01 21:45:43 myNode lnd[3596]:   "size_on_disk": 296190207905,
Feb 01 21:45:43 myNode lnd[3596]:   "chainwork": "00000000000000000000000000000000000000000c4cba0b180b8b196c3ceb4f",
Feb 01 21:45:43 myNode lnd[3596]:   "initialblockdownload": false,
Feb 01 21:45:43 myNode lnd[3596]:   "verificationprogress": 0.9999958194385693,
Feb 01 21:45:43 myNode lnd[3596]:   "mediantime": 1580609838,
Feb 01 21:45:43 myNode lnd[3596]:   "difficulty": 15466098935554.65,
Feb 01 21:45:43 myNode lnd[3596]:   "bestblockhash": "000000000000000000064e64245f34775eb28492e39dc5206acff83a781409a6",
Feb 01 21:45:43 myNode lnd[3596]:   "headers": 615596,
Feb 01 21:45:43 myNode lnd[3596]:   "blocks": 615596,
Feb 01 21:45:43 myNode lnd[3596]:   "chain": "main",
Feb 01 21:45:43 myNode lnd[3596]: {
Feb 01 21:43:44 myNode lnd[3596]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Feb 01 21:43:44 myNode lnd[3596]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:43:44 myNode lnd[3596]: Checking if Bitcoin is synced...
Feb 01 21:43:44 myNode lnd[3596]: + echo 'Checking if Bitcoin is synced...'
Feb 01 21:43:44 myNode lnd[3596]: + set -e
Feb 01 21:43:44 myNode systemd[1]: Starting LND Lightning Daemon...
Feb 01 21:43:44 myNode systemd[1]: Stopped LND Lightning Daemon.
Feb 01 21:43:44 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 1.
Feb 01 21:43:44 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Feb 01 21:43:43 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Feb 01 21:43:43 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Feb 01 21:43:43 myNode lnd[3532]: unknown flag `ignore-historical-gossip-filters'
Feb 01 21:43:41 myNode systemd[1]: Started LND Lightning Daemon.
Feb 01 21:43:41 myNode lnd[3533]: abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login
Feb 01 21:43:41 myNode lnd[2537]: + exit 0
Feb 01 21:43:41 myNode lnd[2537]: }
Feb 01 21:43:41 myNode lnd[2537]:   "warnings": ""
Feb 01 21:43:41 myNode lnd[2537]:   },
Feb 01 21:43:41 myNode lnd[2537]:     }
Feb 01 21:43:41 myNode lnd[2537]:       "since": 481824
Feb 01 21:43:41 myNode lnd[2537]:       "timeout": 1510704000,
Feb 01 21:43:41 myNode lnd[2537]:       "startTime": 1479168000,
Feb 01 21:43:41 myNode lnd[2537]:       "status": "active",
Feb 01 21:43:41 myNode lnd[2537]:     "segwit": {
Feb 01 21:43:41 myNode lnd[2537]:     },
Feb 01 21:43:41 myNode lnd[2537]:       "since": 419328
Feb 01 21:43:41 myNode lnd[2537]:       "timeout": 1493596800,
Feb 01 21:43:41 myNode lnd[2537]:       "startTime": 1462060800,
Feb 01 21:43:41 myNode lnd[2537]:       "status": "active",
Feb 01 21:43:41 myNode lnd[2537]:     "csv": {
Feb 01 21:43:41 myNode lnd[2537]:   "bip9_softforks": {
Feb 01 21:43:41 myNode lnd[2537]:   ],
Feb 01 21:43:41 myNode lnd[2537]:     }
Feb 01 21:43:41 myNode lnd[2537]:       }
Feb 01 21:43:41 myNode lnd[2537]:         "status": true
Feb 01 21:43:41 myNode lnd[2537]:       "reject": {
Feb 01 21:43:41 myNode lnd[2537]:       "version": 4,
Feb 01 21:43:41 myNode lnd[2537]:       "id": "bip65",
Feb 01 21:43:41 myNode lnd[2537]:     {
Feb 01 21:43:41 myNode lnd[2537]:     },
Feb 01 21:43:41 myNode lnd[2537]:       }
Feb 01 21:43:41 myNode lnd[2537]:         "status": true
Feb 01 21:43:41 myNode lnd[2537]:       "reject": {
Feb 01 21:43:41 myNode lnd[2537]:       "version": 3,
Feb 01 21:43:41 myNode lnd[2537]:       "id": "bip66",
Feb 01 21:43:41 myNode lnd[2537]:     {
Feb 01 21:43:41 myNode lnd[2537]:     },
Feb 01 21:43:41 myNode lnd[2537]:       }
Feb 01 21:43:41 myNode lnd[2537]:         "status": true
Feb 01 21:43:41 myNode lnd[2537]:       "reject": {
Feb 01 21:43:41 myNode lnd[2537]:       "version": 2,
Feb 01 21:43:41 myNode lnd[2537]:       "id": "bip34",
Feb 01 21:43:41 myNode lnd[2537]:     {
Feb 01 21:43:41 myNode lnd[2537]:   "softforks": [
Feb 01 21:43:41 myNode lnd[2537]:   "pruned": false,
Feb 01 21:43:41 myNode lnd[2537]:   "size_on_disk": 296188455996,
Feb 01 21:43:41 myNode lnd[2537]:   "chainwork": "00000000000000000000000000000000000000000c4cabfa0ea53ab074bb7704",
Feb 01 21:43:41 myNode lnd[2537]:   "initialblockdownload": false,
Feb 01 21:43:41 myNode lnd[2537]:   "verificationprogress": 0.9999813870796009,
Feb 01 21:43:41 myNode lnd[2537]:   "mediantime": 1580609126,
Feb 01 21:43:41 myNode lnd[2537]:   "difficulty": 15466098935554.65,
Feb 01 21:43:41 myNode lnd[2537]:   "bestblockhash": "00000000000000000008fa0245174b639da3e8971c5d54e3b4bcaac6f6232743",
Feb 01 21:43:41 myNode lnd[2537]:   "headers": 615596,
Feb 01 21:43:41 myNode lnd[2537]:   "blocks": 615595,
Feb 01 21:43:41 myNode lnd[2537]:   "chain": "main",
Feb 01 21:43:41 myNode lnd[2537]: {
Feb 01 21:43:37 myNode lnd[2537]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Feb 01 21:43:37 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:43:07 myNode lnd[2537]: + /bin/sleep 30s
Feb 01 21:43:07 myNode lnd[2537]: BTC not synced, sleeping 30s
Feb 01 21:43:07 myNode lnd[2537]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:43:07 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:42:37 myNode lnd[2537]: + /bin/sleep 30s
Feb 01 21:42:37 myNode lnd[2537]: BTC not synced, sleeping 30s
Feb 01 21:42:37 myNode lnd[2537]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:42:37 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:42:07 myNode lnd[2537]: + /bin/sleep 30s
Feb 01 21:42:07 myNode lnd[2537]: BTC not synced, sleeping 30s
Feb 01 21:42:07 myNode lnd[2537]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:42:07 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:41:37 myNode lnd[2537]: + /bin/sleep 30s
Feb 01 21:41:37 myNode lnd[2537]: BTC not synced, sleeping 30s
Feb 01 21:41:37 myNode lnd[2537]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:41:37 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:41:07 myNode lnd[2537]: + /bin/sleep 30s
Feb 01 21:41:07 myNode lnd[2537]: BTC not synced, sleeping 30s
Feb 01 21:41:07 myNode lnd[2537]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:41:07 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:40:37 myNode lnd[2537]: + /bin/sleep 30s
Feb 01 21:40:37 myNode lnd[2537]: BTC not synced, sleeping 30s
Feb 01 21:40:37 myNode lnd[2537]: + echo 'BTC not synced, sleeping 30s'
Feb 01 21:40:37 myNode lnd[2537]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Feb 01 21:40:37 myNode lnd[2537]: Checking if Bitcoin is synced...
Feb 01 21:40:37 myNode lnd[2537]: + echo 'Checking if Bitcoin is synced...'
Feb 01 21:40:37 myNode lnd[2537]: + set -e
Feb 01 21:40:37 myNode systemd[1]: Starting LND Lightning Daemon...

**Comment by tehelsper** [comment]
OK, it still looks like your LND version is old, which can happen if any earlier upgrade had failed. Now that you are on v0.1.85, can you go to the settings page and find the option to reinstall an application and re-install LND?

**Comment by asperks** [comment]
That's what I just did.  I did the reinstall LND application (one hour ago) after the v0.1.85 version had been installed (three hours ago).  I'll do it one more time though, just to be sure.

**Comment by asperks** [comment]
And there you have it!  It worked the second time.  Thanks so much for your help.
