### ISSUE TITLE
Virtual Machine upgrade 1.84 -> 1.85 tor not working anymore

### ISSUE THREAD

**Issue by Genesius** [mynodebtc/mynode#178]
When I upgrade MyNodeBTC Virtual Machine from 1.84 to 1.85, TOR give me errors.
I have try to reset TOR config via setting menu but nothing change.

-- Logs begin at Tue 2020-02-04 11:38:57 CST, end at Tue 2020-02-04 11:46:59 CST. --
Feb 04 11:39:09 mynode systemd[1]: /lib/systemd/system/tor@default.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/tor/tor.pid → /run/tor/tor.pid; please update the unit file accordingly.
Feb 04 11:39:09 mynode systemd[1]: /lib/systemd/system/tor@default.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/tor/tor.pid → /run/tor/tor.pid; please update the unit file accordingly.
Feb 04 11:39:09 mynode systemd[1]: /lib/systemd/system/tor@default.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/tor/tor.pid → /run/tor/tor.pid; please update the unit file accordingly.
Feb 04 11:39:00 mynode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Feb 04 11:39:00 mynode systemd[1]: tor@default.service: Failed with result 'exit-code'.
Feb 04 11:39:00 mynode systemd[1]: tor@default.service: Start request repeated too quickly.
Feb 04 11:39:00 mynode systemd[1]: Stopped Anonymizing overlay network for TCP.
Feb 04 11:39:00 mynode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
Feb 04 11:39:00 mynode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Feb 04 11:38:59 mynode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Feb 04 11:38:59 mynode systemd[1]: tor@default.service: Failed with result 'exit-code'.
Feb 04 11:38:59 mynode systemd[1]: tor@default.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.925 [err] Reading config failed--see warnings above.
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.925 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.925 [warn] Directory /var/lib/tor/mynode/ cannot be read: Permission denied
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.923 [notice] Read configuration file "/etc/tor/torrc".
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.923 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.923 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 04 11:38:59 mynode tor[1158]: Feb 04 11:38:59.923 [notice] Tor 0.3.5.8 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Feb 04 11:38:59 mynode tor[1156]: Configuration was valid
Feb 04 11:38:59 mynode tor[1156]: Feb 04 11:38:59.802 [notice] Read configuration file "/etc/tor/torrc".
Feb 04 11:38:59 mynode tor[1156]: Feb 04 11:38:59.802 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Feb 04 11:38:59 mynode tor[1156]: Feb 04 11:38:59.802 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 04 11:38:59 mynode tor[1156]: Feb 04 11:38:59.802 [notice] Tor 0.3.5.8 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Feb 04 11:38:59 mynode systemd[1]: Starting Anonymizing overlay network for TCP...
Feb 04 11:38:59 mynode systemd[1]: Stopped Anonymizing overlay network for TCP.
Feb 04 11:38:59 mynode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 4.
Feb 04 11:38:59 mynode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Feb 04 11:38:59 mynode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Feb 04 11:38:59 mynode systemd[1]: tor@default.service: Failed with result 'exit-code'.
Feb 04 11:38:59 mynode systemd[1]: tor@default.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.408 [err] Reading config failed--see warnings above.
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.408 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.408 [warn] Directory /var/lib/tor/mynode/ cannot be read: Permission denied
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.406 [notice] Read configuration file "/etc/tor/torrc".
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.406 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.406 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 04 11:38:59 mynode tor[1099]: Feb 04 11:38:59.406 [notice] Tor 0.3.5.8 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Feb 04 11:38:59 mynode tor[1079]: Configuration was valid
Feb 04 11:38:59 mynode tor[1079]: Feb 04 11:38:59.253 [notice] Read configuration file "/etc/tor/torrc".
Feb 04 11:38:59 mynode tor[1079]: Feb 04 11:38:59.253 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Feb 04 11:38:59 mynode tor[1079]: Feb 04 11:38:59.253 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 04 11:38:59 mynode tor[1079]: Feb 04 11:38:59.253 [notice] Tor 0.3.5.8 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Feb 04 11:38:59 mynode systemd[1]: Starting Anonymizing overlay network for TCP...
Feb 04 11:38:59 mynode systemd[1]: Stopped Anonymizing overlay network for TCP.
...

**Comment by yunier2002** [comment]
I'm also getting this error after upgrading, permissions issue on /var/lib/tor/mynode/ 

Tried changing the permissions but it gets changed back

**Comment by AmazingDroopy** [comment]
Same here after upgrade from 1.85 to 1.86 on a VM.

Resetting Tor, re-run the upgrade...no luck.

/var/run/tor is empty.
/var/lib/tor does not exist

**Comment by tehelsper** [comment]
The tor upgrade was especially bad on the VM and is causing issues. I am reverting it in the next release.

For now, try this:

sudo apt-get remove tor
sudo apt-get install tor

**Comment by AmazingDroopy** [comment]
The suggested steps to remove and reinstall Tor did work.

**Comment by Genesius** [comment]
update from 1.84 to 1.88 has solved thee issue.
