### ISSUE TITLE
debugging tools

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#18]
Apart from the instructions on the README file, I found helpful options in upgrade script
- `sudo mynode-local-upgrade <IP> www` 
- `sudo mynode-local-upgrade <IP> files`

What else is available for debugging?

**Comment by tehelsper** [comment]
Just those for now. I'd like to add an "upgrade" option as well that runs the mynode_post_upgrade.sh script to better replicate the typical upgrade process.

**Comment by tehelsper** [comment]
Any reason to keep this issue open?

**Comment by abhiShandy** [comment]
I'll create a PR to mention this on README
