### ISSUE TITLE
Does MyNode support fans for Raspberry Pi?

### ISSUE THREAD

**Issue by ImranLorgat** [mynodebtc/mynode#182]
Hi there

I've running v0.1.74 on a Raspberry Pi 4 with 4GB of RAM, and the device is getting pretty hot during the initial block download. Right now I've just got aluminium heat sinks but I'm considering swapping them out for a fan like the one linked below.

I'm not particularly hardware savvy but from the limited I've read, it sounds like you need drivers on the Pi to operate the fan. However, I've flashed the SD with MyNode, so will the fan still work? Or are there alternate fans or cooling solutions I should consider?

https://www.pishop.co.za/store/fan-shim-for-raspberry-pi?keyword=fan&category_id=0

**Comment by tehelsper** [comment]
Fans should work fine. If not, let me know. I had one fan on my Raspi 4 and it worked.

**Comment by tehelsper** [comment]
Please open a new issue if the fan does not work.
