### ISSUE TITLE
Tor not working with zap or zeus 

### ISSUE THREAD

**Issue by rico1881** [mynodebtc/mynode#183]
I cannot get tor to work with both zap and zeus wallets, boh are fine on local ip.

**Comment by asperks** [comment]
I'm having the same problem.  I'm working on version 0.1.86.  I re-installed LND.

It looks like the iptables might be blocking connections?  But I'm not sure which chain any rules need to be attached to.  I've updated the rules to apply to the INPUT chain as per the raspi docs, but it didn't make any difference.

This is for a raspberry pi 3.

**Comment by tehelsper** [comment]
Bitcoin and LND use their own tor connections for their data. External access is via a tor connection for other myNode things. Is the tor status green?

**Comment by asperks** [comment]
Yes, the Tor status is green.  I can connect via Tor to the electrum server with electrum, and to the bitcoin node directly with blockstream greenwallet.

**Comment by asperks** [comment]
The error message in Zap is four lines :

   Unable to connect to LND.

   - make sure the LND daemon is running on your server.

   - make sure your port forwarding is active. (Port: 10009)

   - make sure your certificate is valid

**Comment by lollenderrofler** [comment]
I've read that this happened on LND 0.9. So there seems to be a problem with ne newest LND / LNDconnect and TOR. Hopefully it will get fixed soon.

**Comment by salenjak** [comment]
To connect Zap wallet with mynode via Tor you will have to add tlsextradomain=youraddress.onion in http://mynode.local/lnd/config

**Comment by asperks** [comment]
You can close this.  That solution above is the solution.  

1. Go to Tor from the main menu
2. Copy the onion address of "LND API (gRPC)"
3. Go to Lightning Manage from the main menu
4. Press the button LND Config view/edit
5. Add another line :  tlsextradomain=(your onion address).onion
6. Wait for the node to reboot.
7. Go to LND Connect from the main menu
8. Select the gRPC Tor tab
9. Connect to that QR Code from your Zap installation. 

You'll need to have Tor (i.e. Orbot) running on your android device if you want to connect.

Thanks @salenjak!

**Comment by lollenderrofler** [comment]
This solution didn’t work for me. I’m on iOS with Zap via TestFlight. Btw., Zeus app is also not working (they need the Rest config). Everything works fine on local network and via VPN. 
Did anyone have success with this solution on iOS?

**Comment by asperks** [comment]
I didn't know there was a Tor client for iOS to be fair.  When I used an iphone may years back, there was none available.  One of the reasons I stopped using one.  I understand there's a Tor Browser, but that's still not a Tor client.

Can you confirm that Apple does actually have a Tor Client?  Without it, this simply won't work on an Apple as far as I'm aware.

**Comment by lollenderrofler** [comment]
It is my understanding that you don’t need a separate Tor client on iOS. Every app can establish the connection via Tor on their own. For example, on iOS there is an app called „Fully Noded“ which shows stats of your connected node. I am able to connect Fully Noded via Tor to my node without any problem and without any extra Tor app. And as far as I know, at least Zap is able to do the same (in theory).

**Comment by asperks** [comment]
Not the way it works unfortunately.  Fully noded does it.  So does Green Wallet.

But it is a specific ability of these wallets.  They are special because the can do this, and there are very few other that can.  As far as I'm aware, there is no lightning wallet that can do this natively.

Don't want to be the bearer of bad news, but this isn't a mynodebtc problem.  If you want to use the Tor enabled features of the software suite, you need to have youself a Tor node client.

**Comment by lollenderrofler** [comment]
Oh, I didn’t know that. Thank you for the information! What a shame, I thought Tor support meant exactly this, like Fully Noded does it.
Hopefully this feature will come to iOS with a future update. Until then I‘ll just stick to the VPN connection, this works flawless.

**Comment by asperks** [comment]
Definitely think this issue can be closed now.
