### ISSUE TITLE
How to backup bitcoin core wallet.dat in mynode

### ISSUE THREAD

**Issue by rico1881** [mynodebtc/mynode#184]
i use fully noded via mynode but only small funds atm, is there a way to backup the wallet.dat file onto usb like you do with bitcoin core?
potential backup option would be good

**Comment by abhiShandy** [comment]
Look into the bitcoin folder of myNode at `/home/bitcoin/.bitcoin/` or `/mnt/hdd/mynode/bitcoin/`. You should find what you are looking for. Use SCP to copy it to a USB drive.
In the future, we can add a button on the web UI to download it.

**Comment by rico1881** [comment]
Do i access those folders via ssh?
Yeah i agree download button would be a good option
thanks

**Comment by tehelsper** [comment]
This is definitely possibly and relatively easy, but I do not want to encourage people to store BTC on their device outside LND for a couple reasons.

1. In increases complexity
2. In is easier to forget a backup and lose funds
3. I do not want to encourage storing large amounts of funds on a "hot" wallet like myNode that is connected to the Internet

Without using bitcoin core, it is still very easy to store funds on myNode, either directly or indirectly, via LND, Zap, Blue Wallet, Electrum, etc...

However, if someone wants to store funds via the Bitcoin Core wallet directly (not recommended or desired), I can offer a link to download the wallet.dat file if there are funds on the wallet. If there are no funds (like most users), I do not want them seeing the link thinking that adding funds to bitcoin core, a totally different wallet than lnd, encouraging use of that wallet. It would be FAR too easy for someone to mistakenly add funds and think they could recover them with their LND seed.

**Comment by rico1881** [comment]
iv just been playing around with fully noded and only have small amount of btc in it(and always will be), but couldnt work out how to backup wallet.
Maybe a popup warning or something similiar  regarding storing funds on on myNode bitcoin core wallet, if you do go ahead with link.

**Comment by tehelsper** [comment]
In the latest version, there is a button to download your wallet.dat file if it has any funds in it. It will also show some basic wallet info if it sees it has been used.
