### ISSUE TITLE
BTC Explorer does not utilize ElectrumX to see transactions

### ISSUE THREAD

**Issue by chigginsnc** [mynodebtc/mynode#188]
Version: 1.88

When using the BTC Explorer functionality, and searching for a known address, the transactions are not being displayed.  I have the Electrum Server functionality enabled, running, and synced.

I found that if I change line 27 of ```/usr/share/mynode/btc_rpc_explorer_env``` from:

```BTCEXP_ELECTRUMX_SERVERS=tls://127.0.0.1:50002```

...to...

```BTCEXP_ELECTRUMX_SERVERS=tcp://127.0.0.1:50002```

...and then: ```sudo systemctl restart btc_rpc_explorer```, the transactions are displayed correctly.  I don't know if this is the correct fix or not, but it works for me locally.

Can do a pull request if it is helpful.

**Comment by tehelsper** [comment]
Electrum X is not used. Settings files should be populated properly automatically.
