### ISSUE TITLE
Wish: Booting myNode directly from HDD/SSD on RPi3 and RPi4

### ISSUE THREAD

**Issue by jpduhen** [mynodebtc/mynode#199]
To depend on a SD card for booting with RPi's can be tricky in my experience. SD's are not designed for this purpose and I had several SD failures over time. 
It is possible to boot straight from the SSD on a RPi3, but now Andreas Spiess just posted a nice instruction to get the Rpi4 booting from SDD: https://youtu.be/gp6XW-fGVjo
Think this could help myNode-RPi4 combo getting even more robust ;-)
Is this something on your "roadmap" ? Hope so!
Appreciating your hard work, keep it going!

**Comment by tehelsper** [comment]
I agree that SD cards were not intended for running an OS, but the myNode design has already mitigated many of the concerns. The vast majority of data storage has been moved to the external drive, increasing the lifespan of the SD card, and the IO on the SD card itself is mitigated with things like ramlogs which prevent logs from writing directly to the SD card and instead only write once an hour or so.

Also, by using two drives, the backup capabilities are improved. In case either the SD card or the HDD drive dies, critical info has been backed up. It also offers a convenient way to upgrade by swapping the SD card in case anything bad happens to the OS or drive the OS is on.

Sorry, but I don't have any plans to change this. Thanks for your support and I'm sorry this feature is not something on the roadmap.

**Comment by jpduhen** [comment]
Thanks for your feedback, I see my concerns are not legit. Sorry to have taken up your time with my request.
