### ISSUE TITLE
Change URL to run two or more nodes in local network

### ISSUE THREAD

**Issue by KallerTobias** [mynodebtc/mynode#21]
Hi I want to run two mynodes in my local network. Which webserver you use for hosting mynode? Dosn't seem to be apache2.

**Comment by tehelsper** [comment]
The web server I'm using is flask, but I don't think that is really what you would need to change. Are you trying to get two nodes with names like mynode-1.local and mynode-2.local so they can be accessed independently?

First, you can always access them by IP, but I can definitely add a way to change the hostname via the GUI.

For now, use this to change the hostname:

sudo sed -i 's/myNode/newMyNodeHostname/g' /etc/hosts
echo "newMyNodeHostname" | sudo tee /etc/hostname

**Comment by KallerTobias** [comment]
Thanks that's exacly what I needed... I don't need a option in the GUI.

**Comment by ctrlbreak-** [comment]
So, I've done this with one of my nodes at home, and yet, when I use the GUI to initiate a safe shutdown of one... /both/ go down?  Going to try and figure out what's going on here.

**Comment by tehelsper** [comment]
They should not both go down. Try checking the uptime afterwards and use the IP address to access each independently.
