### ISSUE TITLE
After disabling Tor bitcoind still uses it

### ISSUE THREAD

**Issue by Head** [mynodebtc/mynode#210]
I was just in the initial sync and it was slow, so I thought maybe disabling Tor helps. It restarted, but my bitcoind is still connected to only tor peers. Version 0.1.91

update: It seem to use both now. _should_ be fine?

**Comment by tehelsper** [comment]
Yeah, it should be fine. It likely still had your old peer file, so it was using peers it had from before as well as any new peers.
