### ISSUE TITLE
Doesn't update from 1.8.6 to 1.9.3

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#214]
![image](https://user-images.githubusercontent.com/388716/75178594-612d4b00-5706-11ea-894f-fb597de0b00b.png)

It just reboot and doesn't seems to do anything.

rPI4. haven't put an HDD in yet,

**Comment by abhiShandy** [comment]
Do you see any error message?

**Comment by Transisto** [comment]
I'll try again when I have the 1TB HDD on hand and report.

**Comment by hotdogdad** [comment]
My update got stuck too. I ran it again and it worked but I have not bee able to syn core since. I am running a re-scan of blockchain right now. I am getting the following error while trying to UpdateTip.

 socket send error Broken pipe (32)

**Comment by hotdogdad** [comment]
currently trying a reset blockchain on 0.1.95 after multiple blockchain database errors

**Comment by hotdogdad** [comment]
FYI- resetting blockchain worked for this issue
