### ISSUE TITLE
http://mynode.local/settings/toggle-uploader should redirect before restarting the device

### ISSUE THREAD

**Issue by xavierfiechter** [mynodebtc/mynode#218]
Problem

Device restarts and the page is still on http://mynode.local/settings/toggle-uploader.
Once the device is back up and you reload the page,  the device toggles the switch again and restarts the device.

Solution

Get the command, send a redirect header to 

http://mynode.local/settings/toggle-uploader-done, a page that shows that the switch is now 
on|off after rebooting.

**Comment by Muziekkamer** [comment]
Op 11 mrt. 2020, om 16:19 heeft Taylor Helsper <tehelsper@gmail.com> het volgende geschreven:

I'll look into the bug. For now, click disable and then manually go to myNode.local again in your browser.


Taylor
![Schermafbeelding 2020-03-11 om 16 24 55](https://user-images.githubusercontent.com/57832557/76439726-1de90280-63bd-11ea-8497-4c52c883498c.png)
does not work!

**Comment by tehelsper** [comment]
Toggles are now prevented during a refresh.
