### ISSUE TITLE
Raspberry Pi 4 not connecting via WiFi

### ISSUE THREAD

**Issue by jpduhen** [mynodebtc/mynode#219]
Tried several ways to get myNode running on my new RBPi4 via WiFi, but still no success. The standard img 1.86 does not make contact over WiFi. I tried to build a myNode as described in the wiki: raspbian-Lite has wifi connection, after completing the setup_device.sh script and a reboot....no connection (and no ssh to change things.
Any idea's on what I can do to get myNode running? (I have no network-cable connection available).

**Comment by Amiga500** [comment]
Did you tried this guide? 
https://www.reddit.com/r/mynodebtc/comments/e7jki5/how_to_enable_static_ip_and_wifi_connection/

**Comment by jpduhen** [comment]
No, I will today. Also on a RBPi3 same results, after building the myNode on a Raspbian core, no connection anymore. I report back if this resolves the issue

**Comment by jpduhen** [comment]
Yup, this is the way to go, thanks @Amiga500. Now updating to 1.93, hope to be running in a few hours

**Comment by Amiga500** [comment]
Nice, remember to close this bug! Thanks
