### ISSUE TITLE
Integrate a Shamir's Secret Sharing Sceme Aplication in the GUI

### ISSUE THREAD

**Issue by KallerTobias** [mynodebtc/mynode#22]
It would be awsome if there is a option to integrate a SSSS Application into the GUI, so that users can use this to share any secrets. 
May switch off the network connection, when starting the application and clear the memory before connection to the network again, to get a higher security. There are some python integrations for SSSS.

**Comment by tehelsper** [comment]
Cool idea, but if you switch off network you couldn't access the GUI very easily. I think I'll leave SSSS to non-network devices.
