### ISSUE TITLE
HDD vs SSD, What are the compromises?

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#220]
I find it very hard to figure out what storage to use,
I've heard people say it can take as much as 5 week to download and verify chain on an HDD.

1. 1-2TB HDD
2.  512 SSD, pruned node
3. 1 TB SSD, (How much faster to sync?)
4.  Download and verify on fast laptop+SSD and move over to an HDD.
5. Any other alternative to have a pre-synced HDD?

Was also thinking of syncing it off a fast VirtualBox and cloning the vdisk to an HDD.

I think it's important to get that pain-point sorted out. For most people's use-case a 1TB SSD provide a lot of wasted performance post syncing.

Further savings on storage could also be achieved by integrating support for a Freenas in the app menu. (a 8TB HDD has a much better cost per GB than a 1TB HDD)

I think it'd be worth it to make a comprehensive guide on storage choices.

**Comment by Transisto** [comment]
Useful: Using Bitcoin Data from Existing Node, https://mynodebtc.com/guide/using_bitcoin_data_from_existing_node

Are there other process that benefit from fast diskaccess? like building a full index for Electrs?

**Comment by tehelsper** [comment]
Many features benefit from an SSD:

- IBD (huge benefit)
- Electrum Server (sync and compression)
- Upgrades are faster
- General performance and UI is more responsive
- Explorer and Electrum Wallets are more responsive

**Comment by tehelsper** [comment]
I'm going to close this issue since it's more of a discussion. You could move it to the myNode subreddit.

**Comment by Transisto** [comment]
Nobody provided a quantitative answer.

Pretty useless to help make a decision.

**Comment by tehelsper** [comment]
Use an SSD if you can afford it and want a fast / responsive UI - they are better in every way.
