### ISSUE TITLE
Showing filesystem error

### ISSUE THREAD

**Issue by miningdave** [mynodebtc/mynode#222]
Downloaded the virtualbox image and installed. All was good. Upgraded to 0.1.93 and now there is this error showing:

There may be an error with the filesystem on your drive.
fsck from util-linux 2.33.1 e2fsck 1.44.5 (15-Dec-2018) myNode: clean, 259100/67108864 files, 101497375/268434944 blocks

Everything works and it's a VM so I really can't see it being the drive.

**Comment by lollenderrofler** [comment]
Same thing happens to me, also in VM, and nevertheless everything seems fine.

**Comment by Amiga500** [comment]
Here too!

**Comment by yunier2002** [comment]
I have the same issue on VirtualBox VM.

**Comment by jpduhen** [comment]
Had it on a raspberryPi with 1TB SSD attached. Now formatted the drive and QuickSyncing from scratch

**Comment by patrickvdv** [comment]
Same issue here after upgrade to 0.1.95

There may be an error with the filesystem on your drive.
fsck from util-linux 2.33.1 e2fsck 1.44.5 (15-Dec-2018) myNode: clean, 279615/67108864 files, 102428192/268434944 blocks

Did try a fsck on my VM (KVM) in rescue mode but no luck.

**Comment by tehelsper** [comment]
Should be fixed now. Will still appear if error is found.
