### ISSUE TITLE
LND wallet stuck on logging in, then unable to restore after deleting

### ISSUE THREAD

**Issue by ImranLorgat** [mynodebtc/mynode#224]
Hi 

I'm using MyNode version 0.1.74 on a Raspberry Pi 4

I had the same issue as #156 where my Lightning Wallet was stuck on "Logging in". @fedegmb solved this issue by deleting his Lightning Wallet and then restoring it from the seed. Given that I have the channel backups saved, I tried to do the same. 

I wiped the wallet, restarted the node, however when I try to restore the wallet using the 24-word seed I receive the following error: "Error Creating Wallet!"

Any suggestions?

**Comment by ImranLorgat** [comment]
From the logs, it looks like LND keeps crashing in the background:

Mar 02 09:52:23 myNode lnd[1376]: abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login
Mar 02 09:52:23 myNode systemd[1]: Started LND Lightning Daemon.
Mar 02 09:52:24 myNode lnd[1375]: Attempting automatic RPC configuration to bitcoind
Mar 02 09:52:24 myNode lnd[1375]: Automatically obtained bitcoind's RPC credentials
Mar 02 09:52:24 myNode lnd[1375]: dial tcp 127.0.0.1:9050: connect: connection refused
Mar 02 09:52:24 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 09:52:24 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Mar 02 09:52:25 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Mar 02 09:52:25 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 6.
Mar 02 09:52:25 myNode systemd[1]: Stopped LND Lightning Daemon.
Mar 02 09:52:25 myNode systemd[1]: lnd.service: Start request repeated too quickly.
Mar 02 09:52:25 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Mar 02 09:52:25 myNode systemd[1]: Failed to start LND Lightning Daemon.

**Comment by ImranLorgat** [comment]
I was able to fix this problem by re-flashing the SD card to 0.1.86. Whatever was causing the LND crash bug was fixed seems to have been fixed in the latest update

I was able to recreate my LND wallet from my seed. Now busy trying to restore my channels.

**Comment by tehelsper** [comment]
Glad it's fixed in the latest version. I'm going to close this issue.
