### ISSUE TITLE
borked 16GB SD cards showing up as 32.1MB

### ISSUE THREAD

**Issue by Furunodo** [mynodebtc/mynode#227]
This happened twice, to two different SD cards:

1. flash mynode image on 16GB SD card with balenaEtcher
2. put SD card in raspberry pi 4
3. seems to work ok on attached monitor (but no USB keyboard around now, and no ethernet internet)
4. unplug power (to move to place with ethernet)
5. plug power back
6. 4 LED flashes, repeatedly, meaning [start*.elf not found](https://www.raspberrypi.org/documentation/configuration/led_blink_warnings.md)
7. now SD card is 32.1 MB according to macbook and some windows machine, balenaEtcher doesn't work, can't format it in any way

What to do? How can I fix the SD card? Is there a way I can find some more diagnostics in some way?

<img width="583" alt="image" src="https://user-images.githubusercontent.com/52054596/75915071-23db6280-5e56-11ea-8a55-ad2e4a48371a.png">

**Comment by tehelsper** [comment]
Aging out. Close if issue still occurs - likely a local sd card issue.
