### ISSUE TITLE
[Discussion] Git tag releases

### ISSUE THREAD

**Issue by MitchellCash** [mynodebtc/mynode#228]
I notice that while myNode has a versioning scheme in the source code, we aren't also tagging releases with git.

I believe this is something we should be doing to allow more control over development periods where pull requests/commits get merged into master and the release schedule where the latest commits have had a thorough testing period and can be tagged for the next release.

This also makes upgrading more manageable for those updating from the Community Edition, as we could checkout a specific git tag to build.

For example, version `v0.1.95` was commited in the source code here (https://github.com/mynodebtc/mynode/commit/f7c0ea49922d41ae30abe7fd871474817084b5a0), however, since then there have been around 16 new commits to master (as of right now). For a user performing a self-upgrade on the Community Edition the guide just says to build whatever the latest commit in master is. I think a more ideal goal would be for them to `git checkout v0.1.95` and then build which puts them back at commit https://github.com/mynodebtc/mynode/commit/f7c0ea49922d41ae30abe7fd871474817084b5a0 and not the latest `HEAD` of the `master` branch.

**Comment by abhiShandy** [comment]
I agree. Having branches and tags would definitely help.

I guess, since Taylor is the only developer working regularly on it, he could manage with just master branch. Taylor has added support for beta releases and few users do test it before he creates the release commit. However, we can definitely improve the workflow.

**Comment by tehelsper** [comment]
Yeah, for big new features being working by multiple people branches could help quite a bit. I like the idea of git tagging releases. I'll see if I can add it in my release scripts.

**Comment by tehelsper** [comment]
Done. Last version is tagged.
