### ISSUE TITLE
[LND] Setting alias config value directly from lnd.conf isn't persistent

### ISSUE THREAD

**Issue by MitchellCash** [mynodebtc/mynode#231]
When you change the LND `alias` name directly in the `lnd.conf` file it will never persist as each time myNode reboots it sets the `alias` value to whatever is in `/mnt/hdd/mynode/settings/.lndalias` ([see here](https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/usr/bin/mynode_gen_lnd_config.sh#L19-L20)).

**Comment by tehelsper** [comment]
Closing. Alias issues have been resolved.
