### ISSUE TITLE
LND error

### ISSUE THREAD

**Issue by ostermayer** [mynodebtc/mynode#232]
using RTL this error occurs with transaction send:

Send Payment Failed
Error Code
500
Error Message
checksum failed. Expected v04pvx, got jkv704.
API URL
./api/lnd/channels/transactions

**Comment by tehelsper** [comment]
Have you tried any other wallets, like Zap?

**Comment by ostermayer** [comment]
yes same error.  however the new 1.9.6 fixed the issue
