### ISSUE TITLE
[LND] Removing alias directly from conf and then trying to add a new alias from UI fails

### ISSUE THREAD

**Issue by MitchellCash** [mynodebtc/mynode#233]
When adding an alias from the modal window in the UI on the `/lnd` page it uses regex to find `/alias=.*/` and replace it with the new value.

This is all well and good until someone removes the `alias=` value from the conf. When it tries to find the `alias` key to update it, it will instead just silently fail.

**Comment by tehelsper** [comment]
Alias must be set in the config.
