### ISSUE TITLE
Node does not syncronize with btc network - How to set up the FritzBox?

### ISSUE THREAD

**Issue by JuStAguY2** [mynodebtc/mynode#239]
Hi everyone. 

For some reason my FritzBox won´t let my node connect to the btc network to synchronize (Quick Sync does not work). After I entered my product key I get the message "Checking Key" and this takes forever (like days). 

Is there any Instruction, how to set up the FritzBox in a way that it enables communication of the node with the btc network? 

![grafik](https://user-images.githubusercontent.com/49873429/76162813-3351f880-6141-11ea-8392-92a21bd58968.png)

The nodes webserver is obviously not launching either, I get the message page not found if I type http://mynode.local/

How do I have to set up the IP-Adresses/Ports etc. exactly on the Fritzbox? Is there any Workaround e.g. using Wifi (all Wifi Devices connect to the Internet without any issues). Any help is appreciated.

**Comment by tehelsper** [comment]
Which version of code did you flash? Try flashing the latest image.

Otherwise, can you connect to the device via ssh and run this to see if it helps:

sudo ufw disable

**Comment by JuStAguY2** [comment]
Hi Taylor, 

thank you for your help. I own the myNode One with all hardware and software included, so I did not download or flash anything, I basically left the system untouched. 

For trouble shooting: I ran _sudo ufw disable_ on the device and restarted it - no change - I am still stuck at the "checking key" step. 

So the second thing I might want to do is to flash the current version of the OS onto the MyNode One device. 

So I assume of the four options the RasPi 4 Image v 0.2.00 would be the correct one (the hardware of the MyNode One is a Raspi 4 afaik):
    Rock64 | Download v0.1.95
    RockPro64 | Download v0.1.95
    **Raspberry Pi 4 | Download v0.2.00**
    Virtual Machine OVA | Download v0.1.70
(taken from here: https://mynodebtc.com/download)

Before I do so - will the Hard Drive be deleted? AFAIK the Blockchain is already downloaded and I would really not appreciate to be forced to do that again e.g. after I flashed a new OS version ;-).

**Comment by JuStAguY2** [comment]
So I was in contact with Taylor via e-mail, and I want to post the conversation here to probably help others: 
Here the conversation:

> Hi Taylor,
> it seems my Node somehow does not connect to the internet, I assume I have to set up the ports etc. on my Fritzbox properly. I already tried several adjustments/fixes but nothing worked.
> I documented everything here, so that others having the same trouble will be able to look it up:
> https://github.com/mynodebtc/mynode/issues/239 
> I would be happy if you could help me out here.
> Kind regards
> BTChap

Taylor:

> Hi Btchap,
> What is a fritz box? Can you describe the hardware you are using?
> Reflashing the SD card with the most recent version may help.
>  
> Thanks,
> Taylor
> 

Me:

> The Fritzbox is just a router: 
> https://en.avm.de/products/fritzbox/fritzbox-6490-cable/
> Technical Specs can be found here:
> https://en.avm.de/products/fritzbox/fritzbox-6490-cable/technical-specifications/
> 
> Regarding updating the node: I would use the RasPi 4 image right: 
> •	Rock64 | Download v0.1.95
> •	RockPro64 | Download v0.1.95
> •	Raspberry Pi 4 | Download v0.2.00
> •	Virtual Machine OVA | Download v0.1.70
> 
> Will the downloaded Blockchain be erased after flashing a new image onto the node? I really would like to avoid downloading the complete blockchain again (one reason why I bought the pre installed node).
> 
> I already tried to narrow the problem down here, I guess I need to set up the ports properly but I am really lost here:
> https://github.com/mynodebtc/mynode/issues/239
> 
> 
> Again - help is appreciated :-).
> 
> Regards
> 
> BTChap
> 


Taylor:

> Hi Btchap,
> 
> Sorry, I think I misunderstood your first email. You should not have to make any changes on your router for most apps to work (VPN needs one small change).
> 
> **If it cannot connect at all, that is very unusual. Does your device have ridges on the top or is it smooth? If smooth, it would be the raspi4 image. If ridges, use the rock64 image. I just updated the Raspi4 image to v0.2.07.**
> 
> I would try re-flashing the image and see if that helps. It could be a firewall issue and that had several fixes a few versions back.
> 
> Let me know how that goes.
> Thanks,
> Taylor
> 

So here I am atm - will now flash the Rock64 image - let´s see...

**Comment by tehelsper** [comment]
Aging out.
