### ISSUE TITLE
using the latest commit build, issue on UI

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#245]
using the latest commit build, it was all donwloaded fine, with dark theme.. after some minutes i'll back to my pc and i saw this:

![image](https://user-images.githubusercontent.com/16525337/76319191-2408b180-62df-11ea-961e-ad1f15cae8d5.png)

refreshing the browser, the UI come back to default dark theme and no problem yet

@abhiShandy

**Comment by tehelsper** [comment]
Aging out - not in release.
