### ISSUE TITLE
Problem connecting to whirlpool

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#249]
Entering remote IP, http://11.11.11.11/

![image](https://user-images.githubusercontent.com/388716/76658102-bb713d00-6549-11ea-8ad5-65080910f1a6.png)

Entering remote IP, http://11.11.11.11

![image](https://user-images.githubusercontent.com/388716/76658122-c9bf5900-6549-11ea-8960-2202cdfed1cf.png)

**Comment by Transisto** [comment]
Discovered that the connection has to be made though HTTPS to mynode.local , even though the instructions talks about an HTTP address and an IP.

**Comment by abhiShandy** [comment]
Please close this if it's resolved
