### ISSUE TITLE
LND doesn't upgrade automatically

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#25]
I have downloaded mynode v0.1.51 from the site and started it. After then i have upgraded mynode to v0.1.58.

LND is at 0.7.1, but seeing logs was added the 0.8.0.

It's normal that the script haven't upgraded LND to 0.8.0 ? (I had reboot too the rpi4)

**Comment by tehelsper** [comment]
Nope, you should be at LND 0.8.0. There was a bug in mynode-local-upgrade that wasn't running the post upgrade script properly that will be fixed in the next release.

For now, you can manually run mynode_post_upgrade.sh

**Comment by Amiga500** [comment]
i manually run sudo mynode_post_upgrade.sh
rebooted
Lightning is in "Logging in.." state from a lot of minutes, i wait

**Comment by tehelsper** [comment]
Reboot after running that script.

**Comment by Amiga500** [comment]
Yes, i rebooted.. it's always in "Logging in.." 
I'm thinking to delete the lnd dir from cli.. what do you think?

**Comment by tehelsper** [comment]
What does "sudo systemctl status lnd_unlock" say?

**Comment by Amiga500** [comment]
![IMG_20191026_215324](https://user-images.githubusercontent.com/16525337/67625222-8a62cb00-f83b-11e9-96a4-38d3844cf39b.jpg)
![IMG_20191026_215320](https://user-images.githubusercontent.com/16525337/67625223-8a62cb00-f83b-11e9-868a-c5fbcd8036e5.jpg)

**Comment by tehelsper** [comment]
OK, what about "sudo systemctl status lnd"

**Comment by Amiga500** [comment]
![IMG_20191026_220045](https://user-images.githubusercontent.com/16525337/67625273-360c1b00-f83c-11e9-889f-6be7ad6d71a0.jpg)

**Comment by tehelsper** [comment]
What about "lncli getinfo"

**Comment by Amiga500** [comment]
![IMG_20191026_222939](https://user-images.githubusercontent.com/16525337/67625568-3e665500-f840-11e9-8034-c3b20414a771.jpg)

**Comment by tehelsper** [comment]
If you don't have anything on that LND wallet, try deleting it and making a new one via the GUI

**Comment by Amiga500** [comment]
do it! now 0.8.0 works ;) (even if during the refresh of the page once it appears "string indices must be integers, not str")
