### ISSUE TITLE
RTL password doesn't get changed.

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#251]
Unlike : 
>This will change the password you use in the myNode GUI, the password for SSH, and the password for apps like RTL.

The password is still `bolt` after changing the password and rebooting a few times. I don't know what are the risks to funds or privacy but this service is public facing.

**Comment by tehelsper** [comment]
This service is not public facing (at least in terms of the Internet).

Can you provide more details? I just tried going from default -> non-defauilt and back and did not have any issues logging into myNode or RTL with the correct or incorrect passwords.

**Comment by Transisto** [comment]
Haven't done anything special, started with 0.1.86 then updated to 1.96

To me that service is public facing since I've just DMZ the node's IP

**Comment by Transisto** [comment]
I reinstalled the RTL with **Reinstall Applications** and it worked,

I tried to reproduce by changing the password.  It does change properly now.

**Comment by tehelsper** [comment]
I would seriously reconsider DMZing you node. That's not recommended and creates numerous new security concerns. The better remote access options are tor and VPN.

**Comment by elDaz2** [comment]
Hi ! I have the same problem. I installed on 1.70 using the x86 image. I have upgraded to 2.01. I am not able to change RTL password. I tried uninstalling RTL, changing password in the settings still does not work. I even try to rename all RTL.conf files I found ans reinstall RTL. The reinstallation does not re-create the RTL.conf files.
