### ISSUE TITLE
This is not a open source project

### ISSUE THREAD

**Issue by AugustoResende** [mynodebtc/mynode#257]
This is not a open source project because of license. CC-NC-ND doesn't allow even public forks.

avoid using this

**Comment by tehelsper** [comment]
Augusto,

It is definitely open source, but might not be considered "free". The source code is available, the code can be audited, the code can be used and modified personally, but it cannot be redistributed.

I view the redistribution portion to mean that people cannot publish images or "ready to use" code that bypass the various licensing aspects of myNode. Anyone wanting to expand the code or get their favorite project included are free to fork the code base for additional features, but cannot redistribute it and claim it is "myNode". This would unduly burden myNode support, confuse users, and hinder a business model that has been beneficial to many people by helping on-board them to using Bitcoin and Lightning.'

Thanks,
Taylor
