### ISSUE TITLE
Change password into Settings

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#26]
Into Settings, "Change Password", i try to change password successfully even if it compare a string that said that there was an error changing password.

**Comment by tehelsper** [comment]
Can you clarify or provide some example passwords that fail? I'm assuming your current password is correct and you are saying that two matching new passwords do not update. Is that right?

Are you using any non-English special characters?

**Comment by Amiga500** [comment]
Ehm no, the two matching password was matching but i received a message wrote in red that password didn't change even if it was really update correctly (on v0.1.51 and it happens only one time)
Now I have tried again and it works well. However the password was of 10 normal characters with 1 uppercase (now on v0.1.58)
