### ISSUE TITLE
Connecting Electrum Server with Tor V3

### ISSUE THREAD

**Issue by curly60e** [mynodebtc/mynode#260]
There is an issue when displaying how to connect from Electrum Wallet to Electrum Server through terminal:
The issue I found is this:
![image](https://user-images.githubusercontent.com/55191248/76915915-a6741100-689d-11ea-8eaa-60edb086e174.png)
The space between the onion address and the port.
![image](https://user-images.githubusercontent.com/55191248/76915940-c0adef00-689d-11ea-8695-7f5e8cb33cac.png)
Delete that space:

for Linux
./electrum -1 -s ONIONADRESS.onion:50002:s -p socks5:localhost:9050

for Mac Os
open -a /Applications/electrum.app —args -1 -s ONIONADRESS.onion:50002:s -p socks5:localhost:9050

Hope it's useful.

**Comment by tehelsper** [comment]
Thanks for the feedback! That issue has been fixed and is available in the latest code on Github. It will be in the next release.
