### ISSUE TITLE
Mempool statistics viewer

### ISSUE THREAD

**Issue by lollenderrofler** [mynodebtc/mynode#265]
One of the nicest visual designs of the mempool in my opinion is the mempool statistics viewer by Jochen Hoenicke. Maybe it is possible to add this in a future release?
https://jochen-hoenicke.de/queue/#0,24h
https://github.com/jhoenicke/mempool

**Comment by tehelsper** [comment]
I agree, I really like it as well, but I'm not planning on adding it at this point. I'm trying to keep things simple for the time being to prevent CPU/RAM issues and don't want "duplicate" apps.
