### ISSUE TITLE
Device Sync to current timezone and time

### ISSUE THREAD

**Issue by carlosmassa** [mynodebtc/mynode#268]
Every time the raspberry pi is restarted, it should sync to the current timezone automatically (not sure how to do this) and Enable Network Time Sync (sudo timedatectl set-ntp true)

**Comment by tehelsper** [comment]
Can you set your timezone via raspi-config? AFAIK, there is not an easy way to  determine the timezone automatically.

**Comment by carlosmassa** [comment]
Yes, I can set my timezone via raspi-config, but I thought it would be nice it is done automatically during setup.

Carlos.

**Comment by tehelsper** [comment]
Yeah, I can't really do that because it could only guess at the current location of the device and might get it wrong. I've thought about adding it as something that can be set in the GUI, but it's not high priority.

**Comment by carlosmassa** [comment]
That would be nice to have an option to set the timezone in the GUI.

In any case, and in the meantime, I believe it would be easy to add in the boot the Enable Network Time Sync (sudo timedatectl set-ntp true), which may fix some other issues.

**Comment by tehelsper** [comment]
It already does that on each reboot.

sudo timedatectl set-ntp true

**Comment by tehelsper** [comment]
Issue should be resolved. TZ may need to be set manually.
