### ISSUE TITLE
Write error - ~LZMAFILE (28: No space left on device)

### ISSUE THREAD

**Issue by cactus182** [mynodebtc/mynode#269]
RPI4: Upgrading to latest commit (0.1.97 - 15 March),
E: Write error - ~LZMAFILE (28: No space left on device)

![Screen Shot 2020-03-21 at 1 52 19 PM](https://user-images.githubusercontent.com/61607699/77236389-4621ef80-6b7b-11ea-8370-e22fcc0a7ca8.png)

**Comment by tehelsper** [comment]
Try running this command and then retry the upgrade.

sudo rm -rf /var/log/*

**Comment by cactus182** [comment]
That resolved the issue. Thank you.
