### ISSUE TITLE
UI IMPROVEMENT: into Submenu, home button in the up left side

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#27]
into Submenu, home button in the up left side.

Can i suggest to change it to a new one (even without the word "home") using an image similar to this one:
https://commons.wikimedia.org/wiki/File:Home_icon_iOS.png with a size than the bitcoin logo on the main page?

**Comment by tehelsper** [comment]
I like the icon, but it's a CC license so I'd have to attribute it back to apple. I'd rather stick with MIT licenses, etc...

**Comment by Amiga500** [comment]
Ok, i think that one of the follows can be ok :)

https://www.google.com/search?q=house+icon+png+orange&tbm=isch&ved=2ahUKEwjbloncsrrlAhWG6BQKHbtDA4IQ2-cCegQIABAA&oq=house+icon+png+orange&gs_l=img.3...47577.49446..49750...0.0..0.65.398.7......0....1..gws-wiz-img.......0i19j0i8i30.Dy9JYf3Vg2k&ei=HHu0XduYCYbRU7uHjZAI&bih=1057&biw=1920

**Comment by tehelsper** [comment]
I like it, but now that I look at the icons, I would want them to all be consistent and I use a lot of buttons with the jquery ui icons. Maybe I could switch them all to font-awesome one day, but it's not high priority.
