### ISSUE TITLE
No release file for repository 'https://deb.torproject.org/torproject.org buster Release'

### ISSUE THREAD

**Issue by carlosmassa** [mynodebtc/mynode#271]
When Upgrading the myNode to the latest version, there is an issue with the torproject release. See below:

E: The repository 'https://deb.torproject.org/torproject.org buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by tehelsper** [comment]
Above that, do you see an error similar to this? If so, can you visit the URL in your web browser and see if it loads. It appears there may be an issue with an SSL cert somewhere.

https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc

+ curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
+ gpg --import
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
+ gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
+ apt-key add -
gpg: WARNING: nothing exported
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.

**Comment by carlosmassa** [comment]
Ok, I think I know what happens with this issue.

I am located in a country with strict censorship, where access to www.torproject.org is blocked. Censored websites can only be accessed using Tor browser or a VPN. That's most likely the reson the repository can't be found during the update. 

Would there be any way to run the update through a VPN or using a Tor connection? This would help all people that run the node in countries like China, UAE, etc.

**Comment by carlosmassa** [comment]
> * https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc

**Comment by carlosmassa** [comment]
> Above that, do you see an error similar to this? If so, can you visit the URL in your web browser and see if it loads. It appears there may be an issue with an SSL cert somewhere.
> 
> https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
> 
> * curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
> * gpg --import
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>   curl: (60) SSL certificate problem: unable to get local issuer certificate
>   More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> 
> * gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
> * apt-key add -
>   gpg: WARNING: nothing exported
>   Warning: apt-key output should not be parsed (stdout is not a terminal)
>   gpg: no valid OpenPGP data found.

All I see is this:

Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]                                                  
Get:2 https://download.docker.com/linux/raspbian buster InRelease [29.7 kB]                                                
Get:3 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]                                                   
Ign:4 https://deb.torproject.org/torproject.org buster InRelease                                                         
Err:5 https://deb.torproject.org/torproject.org buster Release                                                 
  Could not handshake: Error in the pull function. [IP: 116.202.120.166 443]
Get:6 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Hit:7 https://deb.nodesource.com/node_11.x buster InRelease
Get:8 http://archive.raspberrypi.org/debian buster/main armhf Packages [330 kB]
Get:9 https://download.docker.com/linux/raspbian buster/stable armhf Packages [6559 B]
Get:10 http://raspbian.raspberrypi.org/raspbian buster/contrib armhf Packages [58.7 kB]         
Get:11 http://raspbian.raspberrypi.org/raspbian buster/non-free armhf Packages [104 kB]
Reading package lists... Done                                                                                              
E: The repository 'https://deb.torproject.org/torproject.org buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
admin@myNode:~ $ 


I tried visiting the two URLs below in my web browser but they don't load:

https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc

curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc

I believe it is not a matter of the certificates. I think it is a matter of where I am connecting from.  I am located in a country with strict censorship, where access to www.torproject.org is blocked. Censored websites can only be accessed using Tor browser or a VPN. That's most likely the reason the repository can't be found during the update.

Would there be any way to run the update through a VPN or using a Tor connection? This would help all people that run the node in countries like China, UAE, etc.

another solution could be to have the repository mirrored in a "mynode" server or any other server that is not blocked in countries with heavy censorship.

Any ideas?

**Comment by tehelsper** [comment]
Added toggle in mynode settings to use tor for checking for debian upgrades.
