### ISSUE TITLE
Using bitcoin-cli loads CPU to 100% and makes it unresponsive

### ISSUE THREAD

**Issue by elkimek** [mynodebtc/mynode#272]
As the title says. Using bitcoin-cli from web UI makes the CPU goes full load and stucked there. Not much debugging to be done, the device is a bit unusable at that point.

Using bitcoin-cli directly from CLI over SSH throws RPC errors etc.

**Comment by tehelsper** [comment]
Closing. IIRC this was due to a CPU-intensive CLI command.
