### ISSUE TITLE
Either notify that any HDD connected to the node will be wiped or wait for user confirmation

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#278]
![image](https://user-images.githubusercontent.com/388716/77831735-44ba6f00-7107-11ea-9f61-1a078970226b.png)
,,,

![image](https://user-images.githubusercontent.com/388716/77831811-c27e7a80-7107-11ea-8f03-5bccc407558f.png)

**Comment by Amiga500** [comment]
I think too that is good to advise that there will be a full wipe of the device connected

**Comment by Transisto** [comment]
Hardware aside, it's the equivalent of connecting a USB stick to a laptop and it right away wiping every drive on the machine to install it's OS.

**Comment by Amiga500** [comment]
Feature was added on latest release with https://github.com/mynodebtc/mynode/commit/c180add8be9ca6ba6db1bf9ddcb1d7da9ae0f74c

You can close this. Thanks
