### ISSUE TITLE
Stuck during Quicksync / Copying files

### ISSUE THREAD

**Issue by sarullo** [mynodebtc/mynode#28]
My node gets stuck at 71.57% copying files during quicksync.  I let it sit for a week so I'm sure it's stuck.  I have a 1TB drive attached to my pi and have rebooted several times.  I have also tried to resync the blockchain but the issue keeps occurring at the same %.  Anyone have a clue?  Thanks.

**Comment by tehelsper** [comment]
Is the drive an SSD or HDD?

**Comment by sarullo** [comment]
HDD, is that the issue?

**Comment by tehelsper** [comment]
No, that should be fine. It may be a power issue. Can you put a powered USB hub in the middle or find another way to power the drive?

**Comment by sarullo** [comment]
Powered hub didn't help, still gets stuck copying.  Guess I'll wait for an
updated version down the road and try again.

**Comment by tehelsper** [comment]
Unfortunately, the download may have been corrupted so it fails when extracting files. You have two options:

- Restart QuickSync (wait a couple days, it's slow now)
- Sync Bitcoin from Scratch

**Comment by sarullo** [comment]
OK will try that, thank you.

**Comment by tehelsper** [comment]
Is it working now?

**Comment by sarullo** [comment]
No still not working. Will be opting for an SSD in the future since the
issue may be due to the slow hard drive.

**Comment by Amiga500** [comment]
Which is the brand and model of your HDD?
I'm using an HDD and it go perfectly.. probably your has some hw issues. If you want a suggestion.. don't spend a lot for an SSD that you use only here.. HDD works good too!

**Comment by sarullo** [comment]
It's a 1tb WD passport, not sure if it's 5400 or 7200 rpm.  I'm going to
try another powered USB hub to see if that works.

**Comment by sarullo** [comment]
Just realized I have a fan plugged in that might be drawing too much power.
Going to unplug the fan and try to sync again

**Comment by sarullo** [comment]
Solved:  Was using a 500gb hard drive which is not big enough.  Since quicksync downloads a tar.gz file then extracts to the same drive you need a 1tb drive at least.  Recommend that the mynodebtc software warn or check drive size prior to proceeding.  I've been struggling with this for weeks and had no idea what was going on!
