### ISSUE TITLE
Edits to /mnt/hdd/mynode/bitcoin/env do not survive reboot

### ISSUE THREAD

**Issue by cbeams** [mynodebtc/mynode#283]
_UPDATE: at time of original writing, it appeared that edits to the mentioned file were wiped out after upgrading mynode. It's since become clear they are wiped out on every reboot._

For reference: mynode's `/etc/systemd/system/bitcoind.service` file references an `EnvironmentFile` which defines a `BTCARGS` environment variable that gets passed to `bitcoind`. This allows the user to customize bitcoind without editing the service file itself:

```
admin@myNode:~ $ grep -A1 EnvironmentFile /etc/systemd/system/bitcoind.service
EnvironmentFile=/mnt/hdd/mynode/bitcoin/env
ExecStart=/usr/local/bin/bitcoind -daemon $BTCARGS -deprecatedrpc=accounts -par=-1 -conf=/home/bitcoin/.bitcoin/bitcoin.conf -printtoconsole -pid=/home/bitcoin/.bitcoin/bitcoind.pid
```

Prior to recently upgrading mynode from 1.96 to 2.0.0, this was the content of my `/mnt/hdd/mynode/bitcoin/env` file:

```
admin@myNode:~ $ cat /mnt/hdd/mynode/bitcoin/env
BTCARGS=-peerbloomfilters=1
```

After upgrading to 2.0.0, my changes had been wiped out and the file had returned to its original state:

```
admin@myNode:~ $ cat /mnt/hdd/mynode/bitcoin/env
BTCARGS=
```

So it appears that changes to the `/mnt/hdd/mynode/bitcoin/env` file do not survive upgrades, which seems to me to be a bug. Please advise.

**Comment by cbeams** [comment]
I had prematurely submitted the issue above such that it did not contain the last few lines of content. I've since updated the description so that it is complete.

**Comment by cbeams** [comment]
Update: I've actually just realized that changes to `/mnt/hdd/mynode/bitcoin/env` do not survive even a reboot. I edited the file, rebooted mynode, and noticed that my edits were no longer there. Please advise as to the preferred method of customizing bitcoind if this isn't it. Note also that the instructions in the guide at http://mynodebtc.com/guide/customizing_bitcoin_lnd_config regarding editing the `/mnt/hdd/mynode/settings/bitcoin_additional_config` file appear to simply be wrong / out of date.

**Comment by cbeams** [comment]
I've updated the title and description to reflect that the problem is that the env file gets reset on every reboot, not just during upgrade.

**Comment by cbeams** [comment]
I've attempted two additional approaches to parameterizing bitcoind:

1. Edit `~bitcoin/.bitcoin/bitcoin.conf`
2. Edit the `/etc/systemd/system/bitcoind.service` file directly, adding the needed options to the invocation of `bitcoind` on the `ExecStart` line.

(1) does not survive a reboot, and (2) does. I do not know if (2) will survive a mynode-managed Bitcoin Core upgrade, however.

Again, please advise as to the best / correct way to customize the invocation of bitcoind such that the changes survive reboots and upgrades. Thanks.

**Comment by tehelsper** [comment]
That file is not meant to be persistent. It is used to trigger certain settings after a reboot, like a re-index.

To customize the config, use the config pages on the Bitcoin and Lightning pages.

**Comment by abhiShandy** [comment]
@cbeams if the method recommended by Taylor works, please close this issue.

**Comment by tehelsper** [comment]
I'm going to go ahead and close this issue.
