### ISSUE TITLE
Display/monitor Dojo sync status

### ISSUE THREAD

**Issue by MitchellCash** [mynodebtc/mynode#284]
First time running Samourai Dojo and I was having a few issues with missing transactions/incorrect info with my Dojo install on myNode. I have realised though that Dojo needs hours/days to sync the Bitcoin data to the MySQL database.

`dojo.sh logs tracker` (full path on myNode device: `/opt/mynode/dojo/docker/my-dojo/dojo.sh logs tracker`) shows the status of that DB sync process. We should monitor the output of this command and put the Dojo app in a "Syncing" state on the UI until it has finished syncing and then becomes "Enabled" to avoid any user confusion about why their transactions are missing etc.

**Comment by tehelsper** [comment]
In the latest version, v0.2.02, the tracker status is displayed on the dojo page.
