### ISSUE TITLE
Errors with TOR, Netdata and Docker

### ISSUE THREAD

**Issue by fedegmb** [mynodebtc/mynode#285]
**Tor Status**
Error

-- Logs begin at Fri 2020-04-03 09:45:36 CDT, end at Fri 2020-04-03 09:50:44 CDT. --
Apr 03 09:45:38 myNode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Failed with result 'resources'.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Start request repeated too quickly.
Apr 03 09:45:38 myNode systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 03 09:45:38 myNode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Failed with result 'resources'.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Failed to run 'start-pre' task: Read-only file system
Apr 03 09:45:38 myNode systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 4.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 03 09:45:38 myNode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Failed with result 'resources'.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Failed to run 'start-pre' task: Read-only file system
Apr 03 09:45:38 myNode systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 3.
Apr 03 09:45:38 myNode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 03 09:45:37 myNode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Failed with result 'resources'.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Failed to run 'start-pre' task: Read-only file system
Apr 03 09:45:37 myNode systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 2.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 03 09:45:37 myNode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Failed with result 'resources'.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Failed to run 'start-pre' task: Read-only file system
Apr 03 09:45:37 myNode systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 1.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 03 09:45:37 myNode systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Failed with result 'resources'.
Apr 03 09:45:37 myNode systemd[1]: tor@default.service: Failed to run 'start-pre' task: Read-only file system

**Netdata Status**
Error 
-- Logs begin at Fri 2020-04-03 09:45:36 CDT, end at Fri 2020-04-03 09:50:44 CDT. --
Apr 03 09:50:36 myNode systemd[1]: netdata.service: Failed with result 'exit-code'.
Apr 03 09:50:36 myNode systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:50:36 myNode netdata[3994]: If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Apr 03 09:50:36 myNode netdata[3994]: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
Apr 03 09:50:35 myNode systemd[1]: Started Netdata.
Apr 03 09:50:35 myNode systemd[1]: Stopped Netdata.
Apr 03 09:50:35 myNode systemd[1]: netdata.service: Scheduled restart job, restart counter is at 4.
Apr 03 09:50:35 myNode systemd[1]: netdata.service: Service RestartSec=1min expired, scheduling restart.
Apr 03 09:49:35 myNode systemd[1]: netdata.service: Failed with result 'exit-code'.
Apr 03 09:49:35 myNode systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:49:35 myNode netdata[3661]: If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Apr 03 09:49:35 myNode netdata[3661]: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
Apr 03 09:49:34 myNode systemd[1]: Started Netdata.
Apr 03 09:49:34 myNode systemd[1]: Stopped Netdata.
Apr 03 09:49:34 myNode systemd[1]: netdata.service: Scheduled restart job, restart counter is at 3.
Apr 03 09:49:34 myNode systemd[1]: netdata.service: Service RestartSec=1min expired, scheduling restart.
Apr 03 09:48:34 myNode systemd[1]: netdata.service: Failed with result 'exit-code'.
Apr 03 09:48:34 myNode systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:48:34 myNode netdata[2904]: If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Apr 03 09:48:34 myNode netdata[2904]: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
Apr 03 09:48:32 myNode systemd[1]: Started Netdata.
Apr 03 09:48:32 myNode systemd[1]: Stopped Netdata.
Apr 03 09:48:32 myNode systemd[1]: netdata.service: Scheduled restart job, restart counter is at 2.
Apr 03 09:48:32 myNode systemd[1]: netdata.service: Service RestartSec=1min expired, scheduling restart.
Apr 03 09:47:32 myNode systemd[1]: netdata.service: Failed with result 'exit-code'.
Apr 03 09:47:32 myNode systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:47:32 myNode netdata[2572]: If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Apr 03 09:47:32 myNode netdata[2572]: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
Apr 03 09:47:31 myNode systemd[1]: Started Netdata.
Apr 03 09:47:31 myNode systemd[1]: Stopped Netdata.
Apr 03 09:47:31 myNode systemd[1]: netdata.service: Scheduled restart job, restart counter is at 1.
Apr 03 09:47:31 myNode systemd[1]: netdata.service: Service RestartSec=1min expired, scheduling restart.
Apr 03 09:46:17 myNode systemd[1]: netdata.service: Failed with result 'exit-code'.
Apr 03 09:46:17 myNode systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:46:17 myNode netdata[1475]: If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Apr 03 09:46:17 myNode netdata[1475]: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
Apr 03 09:46:12 myNode systemd[1]: Started Netdata.

**Docker Status**
Error
-- Logs begin at Fri 2020-04-03 09:45:36 CDT, end at Fri 2020-04-03 09:50:44 CDT. --
Apr 03 09:46:22 myNode systemd[1]: Failed to start Docker Application Container Engine.
Apr 03 09:46:22 myNode systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 03 09:46:22 myNode systemd[1]: docker.service: Start request repeated too quickly.
Apr 03 09:46:22 myNode systemd[1]: Stopped Docker Application Container Engine.
Apr 03 09:46:22 myNode systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Apr 03 09:46:22 myNode systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Apr 03 09:46:20 myNode systemd[1]: Failed to start Docker Application Container Engine.
Apr 03 09:46:20 myNode systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 03 09:46:20 myNode systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:46:20 myNode dockerd[2054]: failed to start daemon: failed to dial "/run/containerd/containerd.sock": unknown service containerd.services.namespaces.v1.Namespaces: not implemented
Apr 03 09:46:20 myNode dockerd[2054]: time="2020-04-03T09:46:20.161573508-05:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 03 09:46:20 myNode dockerd[2054]: time="2020-04-03T09:46:20.161512453-05:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Apr 03 09:46:20 myNode dockerd[2054]: time="2020-04-03T09:46:20.161434786-05:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 03 09:46:20 myNode dockerd[2054]: time="2020-04-03T09:46:20.161346175-05:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 03 09:46:20 myNode dockerd[2054]: time="2020-04-03T09:46:20.149456397-05:00" level=info msg="Starting up"
Apr 03 09:46:19 myNode systemd[1]: Starting Docker Application Container Engine...
Apr 03 09:46:19 myNode systemd[1]: Stopped Docker Application Container Engine.
Apr 03 09:46:19 myNode systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
Apr 03 09:46:19 myNode systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Apr 03 09:46:17 myNode systemd[1]: Failed to start Docker Application Container Engine.
Apr 03 09:46:17 myNode systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 03 09:46:17 myNode systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:46:17 myNode dockerd[1973]: failed to start daemon: failed to dial "/run/containerd/containerd.sock": unknown service containerd.services.namespaces.v1.Namespaces: not implemented
Apr 03 09:46:17 myNode dockerd[1973]: time="2020-04-03T09:46:17.738353788-05:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 03 09:46:17 myNode dockerd[1973]: time="2020-04-03T09:46:17.738167065-05:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Apr 03 09:46:17 myNode dockerd[1973]: time="2020-04-03T09:46:17.738068936-05:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 03 09:46:17 myNode dockerd[1973]: time="2020-04-03T09:46:17.737967343-05:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 03 09:46:17 myNode dockerd[1973]: time="2020-04-03T09:46:17.731506380-05:00" level=info msg="Starting up"
Apr 03 09:46:17 myNode systemd[1]: Starting Docker Application Container Engine...
Apr 03 09:46:17 myNode systemd[1]: Stopped Docker Application Container Engine.
Apr 03 09:46:17 myNode systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
Apr 03 09:46:17 myNode systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Apr 03 09:46:15 myNode systemd[1]: Failed to start Docker Application Container Engine.
Apr 03 09:46:15 myNode systemd[1]: docker.service: Failed with result 'exit-code'.
Apr 03 09:46:15 myNode systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 09:46:15 myNode dockerd[1483]: failed to start daemon: failed to dial "/run/containerd/containerd.sock": unknown service containerd.services.namespaces.v1.Namespaces: not implemented
Apr 03 09:46:15 myNode dockerd[1483]: time="2020-04-03T09:46:15.367011178-05:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 03 09:46:15 myNode dockerd[1483]: time="2020-04-03T09:46:15.366882308-05:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Apr 03 09:46:15 myNode dockerd[1483]: time="2020-04-03T09:46:15.366744308-05:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 03 09:46:15 myNode dockerd[1483]: time="2020-04-03T09:46:15.366658919-05:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 03 09:46:15 myNode dockerd[1483]: time="2020-04-03T09:46:15.321392678-05:00" level=info msg="Starting up"
Apr 03 09:46:12 myNode systemd[1]: Starting Docker Application Container Engine...

It's been several days since I first noticed these errors after a reboot. I tried to reinstall all the components, I upgraded to version 0.2.00. I also tried to reinstall the entire software, bot nothing worked.

**Comment by alanthemarmot** [comment]
Having similar issue and same errors. Only noticed when I upgraded to 0.2.00 when it was released and tested disabling QuickSync. Bitcoin node not syncing now, stuck on block 616470 (Feb. 8th) for some reason.

Apr  4 11:18:09 myNode systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Apr  4 11:18:09 myNode systemd[1]: docker.service: Failed with result 'exit-code'.
Apr  4 11:18:09 myNode systemd[1]: Failed to start Docker Application Container Engine.
Apr  4 11:18:11 myNode systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Apr  4 11:18:11 myNode systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Apr  4 11:18:11 myNode systemd[1]: Stopped Docker Application Container Engine.
Apr  4 11:18:11 myNode systemd[1]: docker.socket: Succeeded.
Apr  4 11:18:11 myNode systemd[1]: Closed Docker Socket for the API.
Apr  4 11:18:11 myNode systemd[1]: Stopping Docker Socket for the API.
Apr  4 11:18:11 myNode systemd[1]: Starting Docker Socket for the API.
Apr  4 11:18:11 myNode systemd[1]: Listening on Docker Socket for the API.
Apr  4 11:18:11 myNode systemd[1]: docker.service: Start request repeated too quickly.
Apr  4 11:18:11 myNode systemd[1]: docker.service: Failed with result 'exit-code'.
Apr  4 11:18:11 myNode systemd[1]: Failed to start Docker Application Container Engine.
Apr  4 11:18:11 myNode systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
Apr  4 11:18:20 myNode vpn[2275]: Reading package lists...
Apr  4 11:18:21 myNode vpn[2275]: Building dependency tree...
Apr  4 11:18:21 myNode vpn[2275]: Reading state information...
Apr  4 11:18:21 myNode vpn[2275]: 55 packages can be upgraded. Run 'apt list --upgradable' to see them.
Apr  4 11:18:21 myNode systemd[1]: systemd-timedated.service: Succeeded.
Apr  4 11:18:22 myNode mempoolspace[2249]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Apr  4 11:18:22 myNode mempoolspace[2249]: + echo 'BTC not synced, sleeping 30s'
Apr  4 11:18:22 myNode mempoolspace[2249]: BTC not synced, sleeping 30s
Apr  4 11:18:22 myNode mempoolspace[2249]: + /bin/sleep 30s

**Comment by alanthemarmot** [comment]
Did a bit of Googling, looks to be an issue with permission on the /tmp directory and the Tor service. Updated permissions and restarted Tor service using below commands and my Bitcoin node is now re-synching and services look to be coming back up.

sudo chmod +t /tmp
sudo systemctl restart tor@default.service

**Comment by tehelsper** [comment]
I've added this line to the startup script to hopefully help going forward.

chmod +t /tmp

**Comment by tehelsper** [comment]
Aging out.
