### ISSUE TITLE
Docker Images Build Status - Failed Retry Later - Never resolves

### ISSUE THREAD

**Issue by ForteUnited** [mynodebtc/mynode#288]
I've got a brand new setup here. Followed all the instruction. All of the bitcoin core block downloaded and quicksync stuff worked fine. I'm now waiting for apps to start up. It seems its suck.

The Docker Images Build Status keeps failing with the below log... any ideas? 

-- Logs begin at Fri 2020-04-03 06:20:48 CDT, end at Sat 2020-04-04 11:56:40 CDT. --
Apr 04 11:56:34 myNode systemd[1]: docker_images.service: Failed with result 'exit-code'.
Apr 04 11:56:34 myNode systemd[1]: docker_images.service: Main process exited, code=exited, status=1/FAILURE
Apr 04 11:56:34 myNode mynode_docker_images[7963]: The command '/bin/sh -c npm install --production' returned a non-zero code: 1
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR!     /root/.npm/_logs/2020-04-04T16_56_34_208Z-debug.log
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR! A complete log of this run can be found in:
Apr 04 11:56:34 myNode mynode_docker_images[7963]: 
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR! exited with error code: 128
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR!
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR! fatal: unable to access 'https://github.com/billchurch/nodejs-read-config.git/': Could not resolve host: github.com
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR!
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR! /usr/bin/git ls-remote -h -t https://github.com/billchurch/nodejs-read-config.git
Apr 04 11:56:34 myNode mynode_docker_images[7963]: npm ERR! Error while executing:
Apr 04 11:55:35 myNode mynode_docker_images[7963]: npm info lifecycle webssh2@0.2.10-0~preinstall: webssh2@0.2.10-0
Apr 04 11:55:34 myNode mynode_docker_images[7963]: npm info using node@v8.6.0
Apr 04 11:55:34 myNode mynode_docker_images[7963]: npm info using npm@5.3.0
Apr 04 11:55:34 myNode mynode_docker_images[7963]: npm info it worked if it ends with ok
Apr 04 11:55:32 myNode mynode_docker_images[7963]:  ---> Running in b7f58c8281cd
Apr 04 11:55:32 myNode mynode_docker_images[7963]: Step 4/6 : RUN npm install --production
Apr 04 11:55:32 myNode mynode_docker_images[7963]:  ---> c5529e8186e6
Apr 04 11:55:32 myNode mynode_docker_images[7963]:  ---> Using cache
Apr 04 11:55:32 myNode mynode_docker_images[7963]: Step 3/6 : COPY app/ /usr/src/
Apr 04 11:55:32 myNode mynode_docker_images[7963]:  ---> 128cf8dbb074
Apr 04 11:55:32 myNode mynode_docker_images[7963]:  ---> Using cache
Apr 04 11:55:32 myNode mynode_docker_images[7963]: Step 2/6 : WORKDIR /usr/src
Apr 04 11:55:32 myNode mynode_docker_images[7963]:  ---> 488338259e86
Apr 04 11:55:32 myNode mynode_docker_images[7963]: Step 1/6 : FROM node:8.6
Apr 04 11:55:32 myNode mynode_docker_images[7963]: Sending build context to Docker daemon  9.271MB
Apr 04 11:55:31 myNode mynode_docker_images[7963]: + docker build -t webssh2 .
Apr 04 11:55:31 myNode mynode_docker_images[7963]: + cd webssh2
Apr 04 11:55:31 myNode mynode_docker_images[7963]: + mv webssh2-0.2.10-0 webssh2
Apr 04 11:55:31 myNode mynode_docker_images[7963]: + rm webssh2.tar.gz
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/ver.sh
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/util.sh
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/push.sh
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/pull.sh
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/env.sh
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/build.sh
Apr 04 11:55:31 myNode mynode_docker_images[7963]: webssh2-0.2.10-0/scripts/

**Comment by Perplex0** [comment]
I looked at a few other issues here and someone mentioned it seemed to be an issue with permissions on the tmp directory. If you perform the following command it should resolve it.
sudo chmod +t /tmp
Then restart the tor service it should slowly resolve itself after the services restart themselves.
For me it did not resolve itself after quite some time so i then decided to re-flash my sd card and reinstall mynode, the data in the ssd remains so there is no long wait for IBD again and all modules were still setup as before.
Now the docker images were able to install properly and all the modules worked after that.
I hope that helps for anyone else running into this issue.

**Comment by OvoNemaSmisla** [comment]
I'd like to try to run myNode on Odroid N2 with Ubuntu 18.04.3 using Docker.

Is there a docker image of myNode?

**Comment by tehelsper** [comment]
Aging out.
