### ISSUE TITLE
RTL password doesn't get changed

### ISSUE THREAD

**Issue by elDaz2** [mynodebtc/mynode#290]
I have the same issue than https://github.com/mynodebtc/mynode/issues/251

I installed on 1.70 using the x86 image. I have upgraded to 2.01. I am not able to change RTL password. I tried uninstalling RTL, changing password in the settings still does not work. I even try to rename all RTL.conf files I found ans reinstall RTL. The reinstallation does not re-create the RTL.conf files.

**Comment by tehelsper** [comment]
Are you trying to change the password in RTL? The RTL password should automatically get set to the myNode password.

**Comment by elDaz2** [comment]
The password is still 'bolt' after I use the change password function

**Comment by elDaz2** [comment]
After upgrading to 2.0.2, I tried something and it worked. What I did is set back the password to "bolt" with the change password feature and change it back to my new password. Maybe the update fixed the problem, or is the fact that I reseted the password back top "bolt".
