### ISSUE TITLE
include option for --accept-key-send

### ISSUE THREAD

**Issue by Astro92** [mynodebtc/mynode#292]
As of LND 0.9 spontaneous payments have been enabled, it would be good to have an option to enable this in settings.

**Comment by tehelsper** [comment]
The argument "--accept-keysend" will in next release, v0.2.03.

**Comment by Astro92** [comment]
Can this be manually done in /etc/systemd/system/lnd.service (--accept-keysend) and /home/bitcoin/.lnd/lnd.conf (accept-keysend=1)? I'm just way too keen to start this.
