### ISSUE TITLE
During Upgrade - Job for docker.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by dschoel** [mynodebtc/mynode#295]
During manual upgrade:

`HTTP request sent, awaiting response... 200 OK
Length: 4112300 (3.9M) [application/octet-stream]
Saving to: ‘/tmp/mynode_rootfs_raspi3.tar.gz’

/tmp/mynode_rootfs_raspi3.tar.gz       100%[=========================================================================>]   3.92M  1.84MB/s    in 2.1s    

2020-04-17 10:10:20 (1.84 MB/s) - ‘/tmp/mynode_rootfs_raspi3.tar.gz’ saved [4112300/4112300]

Extracting rootfs TAR for raspi3... Done!
Syncing filesystem...
Full upgrade, running post upgrade script and rebooting device...
+ set -e
+ date
Fri 17 Apr 10:10:25 CDT 2020
+ /usr/bin/mynode_stop_critical_services.sh
/usr/bin/mynode_stop_critical_services.sh: line 16: /opt/mynode/dojo/docker/my-dojo/dojo.sh: No such file or directory
+ rm -rf '/var/log/*'
+ dpkg --configure -a
Setting up docker-ce (5:19.03.8~3-0~raspbian-buster) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-04-17 10:10:29 CDT; 40ms ago
     Docs: https://docs.docker.com
  Process: 7865 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 7865 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce`

Also:

`systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-04-17 10:10:38 CDT; 3min 5s ago
     Docs: https://docs.docker.com
  Process: 7959 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 7959 (code=exited, status=1/FAILURE)`

**Comment by tehelsper** [comment]
RP3 is no longer supported.
