### ISSUE TITLE
Small typo in /settings page

### ISSUE THREAD

**Issue by IngemarNilsson** [mynodebtc/mynode#30]
"Reset HTTP Certificates
This will regenerate yur HTTPS certificates."

Should "**yur**" be "**your**" ?

Version: 0.1.60

**Comment by Amiga500** [comment]
it was created a new pull request "Update settings.html" with fixed typo

**Comment by Amiga500** [comment]
@IngemarNilsson You can close this bug, as resolved on last release. Thanks!
