### ISSUE TITLE
Bitcoin Blockchain is always resyncing... 

### ISSUE THREAD

**Issue by ikoinu** [mynodebtc/mynode#300]
So I have been running MyNode premium on my Raspberry Pi 4 setup with 1tb ssd hard drive for 6 months. Have been keeping up with the upgrades, using the Tor option, hardware is all functioning normally and Pi is running cool. 

Lately, more often than not when I log in to the node's IP address I see that it is syncing, sometimes 5000 blocks down.  
![Annotation 2020-04-23 151727](https://user-images.githubusercontent.com/55639440/80155026-a094de00-8575-11ea-91e2-3640755601e5.png)

When it is not syncing the interface works fine. 
Anyone seen this lately?
Is there a verification setting in the MyNode software that can be turned off to avoid always resyncing previously synced blocks?

Thanks!

**Comment by tehelsper** [comment]
This means there may be corruption within the blockchain data. You can check the bitcoin logs when it reverts to get more info on the issue.

If the data is corrupt, you can reset the blockchain via the settings page.

Also, if it is corruption, I have some changes in the next release that should reduce the chances of data corruption.

**Comment by ikoinu** [comment]
Thank you. 
I'll check it out once I can access the main page and report back.

**Comment by ikoinu** [comment]
in bitcoin_debug, I'm seeing a lot of:
2020-04-21T21:27:14Z ThreadRPCServer incorrect password attempt from 127.0.0.1:***** 

The ***** numbers will vary.

**Comment by tehelsper** [comment]
In that case, it can be best to disable any extra features like electrs, mempool, dojo, btcpay, etc... if you can and re-enable them once the device is stable again.

**Comment by ikoinu** [comment]
Thanks tehelsper, resetting the blockchain through settings seems to have solved the problem of constant re-syncing.
