### ISSUE TITLE
Is new SSD dead or bad flash of img to sd card? Constantly going back and forth from "Looking for drive" and "repairing drive". 

### ISSUE THREAD

**Issue by LLB123** [mynodebtc/mynode#302]
I am using balen etcher in a Windows 10 machine to make the sd cards. Are Ubuntu flashes more stable? I'm just trying to figure out if I should be focusing on going back to the store and replace the ssd or monkey around with different ways to flash a an sd card. Is it best practices to keep the micros in their branded caddys? Are readers build-in mother boards giving better results than usb pen drive adapters?

I reflashed the micro sd card, connected a monitor and keyboard and was able to see a clean boot up. I changed my password. I rebooted and think I clicked a bitcoin button and it started downloading the blockchain I believe, about half way thru I think the Samsung EVO SSD crashed.  I received

"Looking for Drive"
Please attach a drive to your myNode
I rebooted twice and shutdown twice and it always comes back  saying repairing/resyncing then back to "Looking for the Drive.

Should I try reset, rescan or reindex or is it likely a bad ssd? Im even having a hard time getting a successful flash from etcher. Two out of three of the last etcher flashes were unsuccessful.

Thx llb123

**Comment by tehelsper** [comment]
First, if the device booted and you got access to the myNode user interface, the SD card is good and the flash was successful.

For the looking for drive issue, it is more likely the USB->SATA adapter connecting the the drive to the device. What adapter are you using? Sometimes connecting the cable to a USB 2 port will make the connection more stable. Also, a hard reset by pulling the power plug, waiting 1 minute, and plugging it back in can help.

**Comment by LLB123** [comment]
The caddy is a NexStar TX made by Uantec, a no name brand as far as I'm concerned. Is there a reputable brand in that space, none jump to my attention.

I returned the ssd and bought the next grade up and everything is syncing, time will tell. Bought extra micro sd's as well.

**Comment by LLB123** [comment]
False start. The Pi shut itself off. It was half way thru syncing the 627,000 blocks. I had to power cycle and now it says it is repairing the drive. Does it say repairing the drive for every little hiccup? Is it a catch-all or are these specific error descriptions? 

Now is says Looking for Drive. Are you thinking its the caddy? Have a brand name to recommend?thx

**Comment by LLB123** [comment]
Celebrated to early. Same problem returned, so I tried the USB 2.0 port you mentioned. It seems to be working but it has only done about 500 MB in 8hr. Perhaps I have been throttled by the ISP? Going to buy a usb 3 to SATA cable adapter and forget the caddy design element.

I thought hard resets were bad. Isn't that why you put in a nice Shutdown Button feature?
Thx

**Comment by LLB123** [comment]
OK I have switched out the usb 2.0 with a 3.0 and no difference in speed. Still about 40mb in a minute. I think my earlier number is off.
This is incredibly slow and will take a century or more. This is not 1 week or one month speed.

Any suggestions as to how I can get it back to downloading the blockchain. It was during just fine until the "Looking for Drive" appeared. Now all it does is "sync" at an incredibly slow rate. I thought once it synced what it had already downloaded about 33% of the blockchain it would go back to downloading the rest, but no...  arrrrgh

**Comment by tehelsper** [comment]
Can you explain what you are seeing? Is the sync "QuickSync" or Bitcoin sync? How are you measure the process in MB/minute? Was the 33% number the percent QuickSync had downloaded?

You may want to try a factory reset to wipe the drive and get back to an original state.

**Comment by LLB123** [comment]
This has been all Bitcoin sync. I believe default is for the Pi to bootup with QuickSync disabled correct? That's what I believe I experienced. I inquired about it above but never enabled it.
 
I thought when the node was first turned "On" I saw it say Bitcoin Blockchain "Downloading" Block 0 of 628,xxx. So I was asking how to get it back to "downloading" because all I saw was it "syncing". I'm coming around to the fact that it must have always said "syncing" from the very start. 

This updates every 60 sec. and it seems sometimes you get 1 Block and sometimes 100 Blocks. I've never seen more than 110 blocks a minute and today is a Wednesday. I'd imagine on the weekend when more guys are doing maintenance more are offline and the numbers are worse. If you average 50 blocks every 60sec. that seems to come out to 8.7222 days. Except for days like today when I was gone all day and found it off when I returned. I checked my router traffic meter and figured it shut down as soon as I stepped out the door.

I know the first thing I'm going to want to do when this finishes and that's to know how to copy/clone it. Is it as simple as adding an identical Samsung Evo 860 drive and copying it?
or
If I had used QuickSync would I just copy the QuickSync files to the new drive and when done I could delete the Quicksync files on the original drive to recover the space?
I appreciate you taking the time for these noob questions?
Thx
.

**Comment by LLB123** [comment]
The ethernet port lights are not both green, one is orange. Is there a chance it has an incorrect setting?I can access the terminal, but is there a way to check inside the myNode gui? I would find it normal to be like that after it is set up, but not during the setup. Am I making something out of nothing?

**Comment by tehelsper** [comment]
The two color LEDs are normal. I would suggest disabling Tor for Bitcoin on the settings page and see if the sync speeds up. A HDD should sync at about 3 blocks / min and an SSD should be about 10x faster. QuickSync is only disabled by default if an SSD is detected.

**Comment by LLB123** [comment]
I did turn it off earlier, it does not speed it up, if so it is very minimal. 

I downloaded the mynode zip from its github, but I also saw the 2.00 on the mynode downloads page. Which is the community edition, both? Same file? If my plan is to go Premiere should I have used the 2.00 file on the downloads page and not the github zip?
Thx

**Comment by tehelsper** [comment]
To simplify, you should not ever need to work with github files. Please only follow the instructions on the download page.

**Comment by LLB123** [comment]
Got it, so not the master file, use the mynode_raspi4_0-2-00.img.gz at the website.
I'm assuming I can wait for the syncing to end and switch out the sd card or start over?
Fwiw the download speed did pick up, I guess it took an hour for the other nodes to reconnect and start helping.
Thx

**Comment by tehelsper** [comment]
Yeah, that would work.

**Comment by LLB123** [comment]
I'm assuming  here you're referring to swapping out the microSD and not Starting Over.
To simplify and be clear, the master zip file on Github is slightly different in that the Premiere key will not work on it?

**Comment by tehelsper** [comment]
Yeah, swapping the SD card works fine. It can be re-flashed.

The Premium key will work on any version, whether it is flashed or upgraded via the manual instructions first.

**Comment by bricemcduffie** [comment]
@LLB123 ever fix the issue? im having the same issue.

**Comment by LLB123** [comment]
Bri,

Which issue? I was emailing lots of questions there?

LLB123






On Friday, May 29, 2020, 03:17:50 PM PDT, bricemcduffie <notifications@github.com> wrote: 







@LLB123 ever fix the issue? im having the same issue.

**Comment by bricemcduffie** [comment]
@LLB123 finding drive.... i fixed it though. Thank you. Got a new sada to usb

**Comment by richardcornish** [comment]
@tehelsper Is there a recommended list of hardware anywhere? I went with stock Amazon and high ratings ([Sabrent adapter](https://www.amazon.com/dp/B011M8YACM)) thinking that would be sufficient and I'm having the same problems. [RaspiBlitz](https://github.com/rootzoll/raspiblitz) has a [German recommendation](https://www.amazon.de/gp/product/B06XWSDGP6/) in its [README](https://github.com/rootzoll/raspiblitz/blob/master/README.md).

@bricemcduffie Which adapter ended up working for you?

**Comment by tehelsper** [comment]
@richardcornish There are some recommendations on mynodebtc.com/download

For the adapter, I like a different Sabrent adapter:

https://www.amazon.com/Sabrent-Tool-free-Enclosure-Optimized-EC-UASP/dp/B00OJ3UJ2S/ref=pd_bxgy_img_3/130-0179106-5509951?_encoding=UTF8&pd_rd_i=B00OJ3UJ2S&pd_rd_r=5d13a4e0-c026-42ec-948e-20f58ed07d49&pd_rd_w=5zmYa&pd_rd_wg=z4njs&pf_rd_p=4e3f7fc3-00c8-46a6-a4db-8457e6319578&pf_rd_r=VWR19TKFNV8667GVAQ11&psc=1&refRID=VWR19TKFNV8667GVAQ11

**Comment by richardcornish** [comment]
@tehelsper Thank you for the list, I missed that. Interesting that the recommendation is for HDD and you chose SSD. Is there any benchmarks or official endorsements by myNode for one over the other?

**Comment by tehelsper** [comment]
Oh yeah, I should add suggestions for SSD hardware as well

**Comment by tehelsper** [comment]
I prefer SSDs, but they are more expensive both should work. I'm going to close this issue out. Any new problems can be added to a new issue.
