### ISSUE TITLE
unknown flag `accept-keysend'

### ISSUE THREAD

**Issue by webdiverblue** [mynodebtc/mynode#307]
Hey Guys,

there is a bug in mynode version 0.2.04

### The LND Service doesn't starts properly:

admin@mynode:~/.lnd/data/chain/bitcoin$ sudo systemctl status lnd.service 
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-05-03 05:54:51 CDT; 1min 0s ago
  Process: 8321 ExecStartPre=/usr/bin/is_not_shutting_down.sh (code=exited, status=0/SUCCESS)
  Process: 8322 ExecStartPre=/usr/bin/pre_lnd.sh (code=exited, status=0/SUCCESS)
  Process: 8324 ExecStartPre=/usr/bin/wait_on_bitcoin.sh (code=exited, status=0/SUCCESS)
  **Process: 8326 ExecStart=/usr/local/bin/lnd --caches.channel-cache-size=35000 --ignore-historical-gossip-filters --accept-keysend (code=exited, status=1/FAILURE)**
  Process: 8327 ExecStartPost=/bin/echo abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login (code=exited, status=0/SUCCESS)
 Main PID: 8326 (code=exited, status=1/FAILURE)
____________________________________________________________________________
### The Log says in summary: **unknown flag accept-keysend**

May  3 05:54:46 mynode lnd[8176]: abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login
**May  3 05:54:47 mynode lnd[8175]: unknown flag accept-keysend
May  3 05:54:47 mynode lnd[8175]: unknown flag accept-keysend**
May  3 05:54:48 mynode lnd[8221]: Checking if device is shutting down...
May  3 05:54:48 mynode lnd[8221]: Not shutting down!
May  3 05:54:48 mynode lnd[8224]: + set -e
May  3 05:54:48 mynode lnd[8224]: + echo 'Checking if Bitcoin is synced...'
May  3 05:54:48 mynode lnd[8224]: Checking if Bitcoin is synced...
May  3 05:54:48 mynode lnd[8224]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
May  3 05:54:48 mynode lnd[8224]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
___________________________________________________________________________
**first workaround:**

> 
I deleted the parameter --accept-keysend in the lnd.service 

#lnd service
#/etc/systemd/system/lnd.service

[Unit]
Description=LND Lightning Daemon
Wants=bitcoind.service
After=bitcoind.service

[Service]
ExecStartPre=/usr/bin/is_not_shutting_down.sh
ExecStartPre=/usr/bin/pre_lnd.sh
ExecStartPre=/usr/bin/wait_on_bitcoin.sh
#ExecStart=/usr/local/bin/lnd --caches.channel-cache-size=35000 --ignore-historical-gossip-filters --accept-keysend
**ExecStart=/usr/local/bin/lnd --caches.channel-cache-size=35000 --ignore-historical-gossip-filters**
ExecStartPost=/bin/echo 'abc' > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login
______________________________________________________________________________
after that the lnd.service starts problery
but there is no way to accept keysend for now.
is there a some bugfixing around? 
_______________________________________________________________________________
Facts:
- mynode version  0.2.04 in a virtual machine.
- Host system is ubuntu.
- blockchain fully synced
- all other services running well
- community_edition

**Comment by tehelsper** [comment]
The lnd upgrade must have failed. Can you send me the upgrade log or try to re-install lnd?

That argument is only accepted on lnd version 0.9.0+

**Comment by webdiverblue** [comment]
Hey Taylor,

> "That argument is only accepted on lnd version 0.9.0+"
that make sence... 

... but i running mynode 0.2.04 with LND version 0.8.0 <-- that make no sence

What i did:

I installed downloaded the version 0.2.02, installed it from scratch 
and let it alone for couple of days without 
doing anything, after that i did an upgrade to version 0.2.04.
Than i started to sync and setup all services. Was wondering cause most of
the services where waiting on LND to start so i checked that service.

I see the LND Upgrade to version v0.9.2 comes with mynode upgrade v0.1.97 
how does is happen, that my node runs LND version 0.8.0 when i installed mynode version 0.02.02.

any suggestions? is there a way to upgrade LND separately or do i have to setup the vm again


[mynode_logs.tar.gz](https://github.com/mynodebtc/mynode/files/4576548/mynode_logs.tar.gz)

**Comment by webdiverblue** [comment]
Update:

still after update to mynode version 0.2.05 the lnd version is still 0.8.0-beta...

**Comment by webdiverblue** [comment]
After i updated to version 0.2.07 the LND Version is now 0.10.0-beta abd everything works fine.
I close this Issue.
thank u for
