### ISSUE TITLE
Proposal: make heavier use of tags for issues and PRs

### ISSUE THREAD

**Issue by thunderbiscuit** [mynodebtc/mynode#308]
That's it. Just thinking of how this project can scale and continue to attract contributors, and I think labels help in doing that. 

Also of note is that GitLab has a feature where you can subscribe to specific labels only, and I think GitHub is working on implementing that as well.

**Comment by abhiShandy** [comment]
Taylor has started using release tags, and occasionally labels issues/PRs. Perhaps if he gives limited privilege to one of us, we can do it for the project.

**Comment by tehelsper** [comment]
Closing since I do use tags now. Other requests can be added in a new issue.
