### ISSUE TITLE
Upgrade may have not completed

### ISSUE THREAD

**Issue by st4cks4ts** [mynodebtc/mynode#316]
I’ve tried to retry the upgrade and continue to upgrade to the latest versions but still get the following error.
![449C149F-B85D-4E67-B486-7E77C7259545](https://user-images.githubusercontent.com/64940868/81248914-b2956880-8fda-11ea-9c82-d3f077065c80.jpeg)

**Comment by tehelsper** [comment]
Is anything not working as expected? Can you email the upgrade log to admin@mynodebtc.com?

**Comment by st4cks4ts** [comment]
Everything works as normal just the flag. Unfortunately clicking show upgrade log button doesn’t work. Another way to find that file?

**Comment by KeysBTC** [comment]
Same issue on latest upgrade.

**Comment by st4cks4ts** [comment]
Same issue with most recent upgrade

**Comment by tehelsper** [comment]
Can you try opening the Linux Terminal and running:

sudo /usr/bin/mynode_post_upgrade.sh

And see how it fails.

**Comment by st4cks4ts** [comment]
`+ set -e
+ date
Thu 14 May 13:45:44 CDT 2020
+ /usr/bin/mynode_stop_critical_services.sh
Stopping myNode services...
Dojo is already stopped.
+ rm -rf /var/log/alternatives.log /var/log/auth.log /var/log/auth.log.1 /var/log/auth.log.2 /var/log/bitcoind.log /var/log/bitcoind.log.1 /var/log/boot.log /var/log/btmp /var/log/daemon.log /var/log/daemon.log.1 /var/log/debug /var/log/debug.1 /var/log/dpkg.log /var/log/electrs.log /var/log/electrs.log.1 /var/log/electrs.log.2 /var/log/fail2ban.log /var/log/flask /var/log/kern.log /var/log/kern.log.1 /var/log/kern.log.2 /var/log/lastlog /var/log/lnd_admin.log /var/log/lnd_admin.log.1 /var/log/lnd_backup.log /var/log/lnd_backup.log.1 /var/log/lndconnect.log /var/log/lndhub.log /var/log/lndhub.log.1 /var/log/lndhub.log.2 /var/log/lnd.log /var/log/lnd.log.1 /var/log/lnd.log.2 /var/log/log2ram.log /var/log/loopd.log /var/log/loopd.log.1 /var/log/messages /var/log/messages.1 /var/log/messages.2 /var/log/mynode_docker_images.log /var/log/mynode_docker_images.log.1 /var/log/mynode.log /var/log/mynode.log.1 /var/log/mynode_quicksync.log /var/log/mynode_quicksync.log.1 /var/log/mynode_quicksync.log.2 /var/log/openvpn.log /var/log/openvpn-status.log /var/log/private /var/log/rtl.log /var/log/rtl.log.1 /var/log/syslog /var/log/syslog.1 /var/log/ufw.log /var/log/unlock_lnd.log /var/log/unlock_lnd.log.1 /var/log/user.log /var/log/user.log.1 /var/log/wtmp /var/log/www.log /var/log/www.log.1 /var/log/www.log.2
+ dpkg --configure -a
dpkg: dependency problems prevent configuration of openjdk-11-jre:armhf:
 openjdk-11-jre:armhf depends on openjdk-11-jre-headless (= 11.0.7+10-3~deb10u1); however:
  Package openjdk-11-jre-headless:armhf is not installed.

dpkg: error processing package openjdk-11-jre:armhf (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openjdk-11-jre:armhf`

**Comment by tehelsper** [comment]
Thanks. It definitely looks like your upgrade failed and is not confused. You have a couple options.
#1 
sudo apt-get install openjdk-11-jre-headless
sudo /usr/bin/mynode_post_upgrade.sh
(check for new error)

#2 
Re-flash your SD card with the latest version from the website and re-upgrade. No blockchain or lnd data will be lost.

**Comment by st4cks4ts** [comment]
Thanks Taylor. Option 2 was able to fix things.

**Comment by tehelsper** [comment]
Great!
