### ISSUE TITLE
Version 2.05 - new install : Cannot create LND wallet

### ISSUE THREAD

**Issue by davterra** [mynodebtc/mynode#317]
As discussed with @tehelsper on the premium Telegram channel, I've been trying to figure out why, after going from "Community" to "Premium" and then upgrading to 2.05, I was not able to create a LND wallet. No matter what I did or how long I waited, an attempt to create a wallet led to a red-letter message saying "Try again later". An attempt to restore an old wallet resulted in an error message.

I'm running mynode on Virtualbox. I did a complete wipe. Deleted old vm, imported 1.7 .ova, copied over chain data from existing node and fired it up. Same result as before. The message in red letters telling me to "try later". 

Since Vbox allows me to save snapshots of current machine state that I can restore, I decided to do just that. I took a snapshot of my fresh install of 2.05, checked out the 1.96 release  from git, and did a manual downgrade. And just like that, as Forrest Gump would say, everything works. I can create a LND wallet, and everything else looks good.

Rather than create a new wallet now, I'm going to save this working version in another snapshot and then upgrade sequentially from 1.96 to 2.05 to see if I can isolate where things break down in the lightning implemtation.

I don't know if my problem is specific to VBox users or not. I'm guessing it is, or there would be more instances of this problem in the Telegram channel.

Again, I am happy to discuss on Telegram channel or in PM.

**Comment by webdiverblue** [comment]
Hey davterra,

what shows your lnd status? 
what is your lnd version?

`#sudo systemctl status lnd`

**Comment by davterra** [comment]
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-05-08 13:40:42 CDT; 1h 2min ago
  Process: 2365 ExecStartPre=/usr/bin/pre_lnd.sh (code=exited, status=0/SUCCESS)
  Process: 2376 ExecStartPre=/usr/bin/wait_on_bitcoin.sh (code=exited, status=0/SUCCESS)
  Process: 2853 ExecStartPost=/bin/echo abc > /mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/poke_login (code=exited, status=0/SUCCESS)
 Main PID: 2852 (lnd)
    Tasks: 13 (limit: 4689)
   Memory: 5.4M
   CGroup: /system.slice/lnd.service
           └─2852 /usr/local/bin/lnd --caches.channel-cache-size=35000 --ignore-historical-gossip-filters

May 08 13:40:49 mynode lnd[2852]: 2020-05-08 13:40:49.499 [INF] LTND: Version: 0.9.0-beta commit=v0.9.0-beta, build=production, logging=default
May 08 13:40:49 mynode lnd[2852]: 2020-05-08 13:40:49.499 [INF] LTND: Active chain: Bitcoin (network=mainnet)
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.034 [INF] CHDB: Checking for schema update: latest_version=12, db_version=11
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.034 [INF] CHDB: Performing database schema migration
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.034 [INF] CHDB: Applying migration #12
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.035 [INF] CHDB: Migrating invoice bodies to TLV, adding payment addresses and feature vectors.
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.035 [INF] CHDB: Migration to TLV invoice bodies, payment address, and features complete!
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.308 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.342 [INF] RPCS: password gRPC proxy started at 0.0.0.0:10080
May 08 13:40:50 mynode lnd[2852]: 2020-05-08 13:40:50.342 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock`

**Comment by davterra** [comment]
UPDATE:
After upgrading (manually) from 1.96 to 2.00 to 2.04 to 2.05, all instances worked properly.
No idea what caused the initial problem, but could well have been my fault.
I am going to continue to update manually, as I really prefer to see what's happening in real time.
I'm closing this issue and thank those who tried to help here, and on Telegram.
