### ISSUE TITLE
Internal Server Error message entering into Settings

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#32]
I receive this message if i enter into settings:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

myNode is working correctly, and i have that problem only entering into Setting page.

Some info:

Disk Usage 23%
CPU 21.2%
RAM 31.1%
Temperature 40°

myNode v0.1.60

**Comment by tehelsper** [comment]
I'm 99% sure I know what this is. I'm pretty sure a QuickSync client has a weird character in the name and displaying it causes an exception.

Can you run "sudo tail -n 200 /var/log/flask" if you have access to the Linux terminal?

**Comment by Amiga500** [comment]
Yes.. it's related with ASCII..

![IMG_20191030_034939](https://user-images.githubusercontent.com/16525337/67825126-9c0cd280-fac8-11e9-9aa9-50f0154dac24.jpg)

**Comment by fellowworldcitizen** [comment]
Same issue here on fresh PI 3 install. Any way to get around this? I need to disable quicksync. How can I access the settings via terminal?
