### ISSUE TITLE
Dojo connection issues ("Unauthorized" ...sometimes "Bad Request")

### ISSUE THREAD

**Issue by xFvl** [mynodebtc/mynode#320]
Anyone else have issues running Dojo? I'm getting what seem to be connection errors related to permissions. See below - API, PushTX, and Orchestrator all read "Unauthorized".

If I run Whirlpool, I'm unable to successfully log in to the desktop client ("technical error") when connected to Dojo. I've reinstalled, rebooted, looked at the mynode_docker_image logs... Any ideas? Thanks!

v0.2.05 on a raspi4

![Screenshot_2020-05-13 myNode Dojo](https://user-images.githubusercontent.com/29760774/81843874-1c45d300-9503-11ea-9714-2a59b6bb85d1.png)

<img width="261" alt="Screen Shot" src="https://user-images.githubusercontent.com/29760774/81843815-046e4f00-9503-11ea-974e-ed5779fbfde7.png">

https://[internal ip]:8899 renders:
<img width="819" alt="screenshot" src="https://user-images.githubusercontent.com/29760774/82104488-fc154000-96cb-11ea-899c-734f23e103e6.png">

**Comment by tehelsper** [comment]
@xFvl Can I ask what you did to close this issue? It may be helpful for others.

The number of Bad Request / Unauthorized errors has been decreasing, but it appears a few people still run into the issue.

**Comment by xFvl** [comment]
Eventually after restarting TOR, Dojo, and Whirlpool several times, and probably luck, it seemed to start working properly. I was finally able to get Whirlpool to connect, and the Dojo tabs all were green. Rescanned xpubs, zpubs, etc. in Dojo and Samourai wallet began populating UTXOs and txs.

However, this was short lived as I'm running into it again. The problem seems to crop up intermittently, which is really difficult to debug.

**Comment by tehelsper** [comment]
How much RAM does your raspi4 have?

**Comment by xFvl** [comment]
2 GB

**Comment by xFvl** [comment]
RAM usage does seem high:

`Welcome to myNode!
Linux myNode 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

System load:   3.15 2.53 2.12  	Up time:       2 days		
Memory usage:  73 % of 1988MB 	Zram usage:    95 % of 999Mb
Usage of /:    42% of 15G    	storage/:      74% of 916G`

`$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1988        1441         242          10         305         541
Swap:           999         947          52`

**Comment by 3cola** [comment]
I am assuming that you are using the package zram-tools, from your message above...
You could try to add more compressed memory via zram:
edit /etc/default/zramswap -> ALLOCATION=2048
and you can change some stuffs in /etc/sysctl.conf to optimize your rpi for zram:
vm.vfs_cache_pressure=500
vm.swappiness=100
vm.dirty_background_ratio=1
vm.dirty_ratio=50

and reboot...

Is it helping ?

**Comment by Jacksper13** [comment]
@tehelsper Dojo has been updated at least twice since mynode v0.2.05 fixing major connectivity issues - I'd close

**Comment by tehelsper** [comment]
Closing - 4GB is pretty much required now for apps like Dojo, Mempool, etc...
