### ISSUE TITLE
Can't disable Tor

### ISSUE THREAD

**Issue by ottosch** [mynodebtc/mynode#326]
I'm running version 0.2.06 community edition.
I want to disable Tor. This is what I did:

1- Edited bitcoin.conf and commented Tor lines. Added onlynet=ipv4 and onlynet=ipv6. Restarted, and as was still connecting to Tor nodes,
2- In settings, I disabled "Bitcoin and Lightning Tor". Restarted. Still connecting to Tor nodes.

Then someone told me in the Telegram group that I shouldn't edit bitcoin.conf manually.
3- So, I reset my bitcoin.conf and restarted. Still connecting to Tor nodes.

4- Went to settings, enabled again.
5- Disabled again.

I still am connecting to a mix of regular and Tor nodes. How can I disable Tor?

I see this note in settings: "If you have customized your Bitcoin or LND config, this setting has no effect". Maybe after step 1 I've permanently marked my node as customised?

**Comment by tehelsper** [comment]
Is this still present in v0.2.11?

**Comment by ottosch** [comment]
Yes.
I have just upgraded and it's the same.

Tor is marked as disabled in settings, but in the Bitcoin status page, my local Bitcoin address is a Tor one and about half of the connections are from Tor nodes.

**Comment by AngelicInsight** [comment]
I'm also experiencing this on v0.2.13. Unable to disable Tor. My bitcoin.conf is default.

**Comment by tehelsper** [comment]
Make sure you are not using a custom config. Can you check on the settings page to see if you are using a custom config?

**Comment by AngelicInsight** [comment]
I just verified. The settings page doesn't show any indication of a custom config on bitcoin or lnd. Also, I reset both and rebooted to confirm. Tor is still active even with the toggle turned off.

**Comment by bkiac** [comment]
Same for me on 0.2.21

**Comment by MacDefender** [comment]
With 0.2.25 the same here. Disabled tor but its still running (checked with top) and I still get onion URIs generated instead of IPv4 ones.

**Comment by tehelsper** [comment]
Tor is always enabled - disabling tor from the settings page just means Bitcoin and LND do not use it to connect to their networks.

**Comment by Jacksper13** [comment]
@tehelsper sounds like there was a misunderstanding in what "disabling tor" means - if you plan on hiding the onion URIs when tor is disabled to prevent future misunderstandings leave open, if you consider this incident is resolved close.
