### ISSUE TITLE
Dojo is stuck at "installing..."

### ISSUE THREAD

**Issue by Furunodo** [mynodebtc/mynode#329]
Dojo is stuck at "installing..."
<img width="178" alt="image" src="https://user-images.githubusercontent.com/52054596/83496896-a2758980-a4b1-11ea-8070-e1dbe42f1366.png">

This is already after I tried to install it again:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/52054596/83497030-cb961a00-a4b1-11ea-8a6f-0df495ff715a.png">

What can I try next?

This is version 0.2.00. I know there's a newer version and I will probably pay for Premium but I first want to know that things will kinda work.

**Comment by Jacksper13** [comment]
@tehelsper Dojo updated multiple times since mynove v0.2.00 - suggested close

**Comment by tehelsper** [comment]
Docker app installation has been dramatically improved.
