### ISSUE TITLE
Remap Mempool Viewer links to use local Explorer

### ISSUE THREAD

**Issue by sixside** [mynodebtc/mynode#336]
When using Mempool Viewer, and you search for a transaction, it would be nice if the tx hash link was changed to link to the local explorer, instead of the external Blockstream explorer. 

So instead of:

href="https://www.blockstream.info/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16"

It would link to:

href="http://mynode.local:3002/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16

Just replacing 'https://www.blockstream.info' with 'http://mynode.local:3002' (or http://[LOCAL IP ADDRESS]:3002 if appropriate).

**Comment by Jacksper13** [comment]
@tehelsper this is already resolved (prolly since mempool v2), clicking any tx in mempool viewer redirects to a local address - suggested close

**Comment by tehelsper** [comment]
Resolved in latest mempool version. It has a local explorer.
