### ISSUE TITLE
Web interface issue: Empty reply from server

### ISSUE THREAD

**Issue by Furunodo** [mynodebtc/mynode#339]
I can ssh onto the box, but the web interface stopped working. Bitcoind and others seem to be working fine.

    curl -k https://mynode.local/
    curl: (52) Empty reply from server

![image](https://user-images.githubusercontent.com/52054596/85402816-3cca6980-b554-11ea-9e20-29d0d3ec2aa3.png)

**Comment by tehelsper** [comment]
Does a reboot make the web UI work again?

What was done prior to the web UI not working? It appears you are using HTTPS. Can you try HTTP?

**Comment by Furunodo** [comment]
Don't remember the details, I switched off the box.

Reboot didn't work.

http didn't work.

I may boot it again but I guess it makes more sense to do that with a newer version of myNode?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pgsdesign** [comment]
I'm having a similar issue with my brand new unit, but I can't get to it at all - so "no server found" error. I see it getting the IP from my dhcp server, I can ping it, I added an "A" dns record to name it locally and I can ping that,  I didn't know what account to use to SSH in, but I can see it going to mynodebtc.com:443 every 10 minutes (824452 bytes a day worth of data), ipify.org:443 (6239 of data a day), and seeip.org:443 (2919 bytes a day). I've tried rebooting and using every version of the URL possible with http, https, just the IP, using the dns record I added to hit it, etc. I can't get it to show up. Can you share how you SSH in so I can try that as well?

**Comment by tehelsper** [comment]
You can ping the IP address, but the web browser is not responding? You should be able to ssh and get access to the terminal with a command like this:

ssh admin@DEVICE_IP_ADDRESS

If you have not yet accessed the device, you have to start with HTTP and not HTTPS for access since HTTPS doesn't work until the drive has been attached, formatted, and setup.

**Comment by pgsdesign** [comment]
I attached the hard drive and turned it on. Could it be that I need to turn it on without the drive attached first and then attach the drive after I connect? Could that be the thing I screwed up?

I’ve attached some screen shots consolidated into one picture showing the DHCP address it’s getting, checked the MAC address to make sure it was the Raspberry Pi, successful pings from both Mac and PC, a timeout on the SSH attempt from the Mac. I tried SSH via Putty on the PC with the same result. I also have a couple shots from my firewall showing it's doing some stuff so it’s alive in some sense.

I’m up there again Monday if you have some next things to try.

Thanks!!
![MyNodeTroubleshooting](https://user-images.githubusercontent.com/86155271/122656596-e82edf80-d110-11eb-802f-60144b6e7480.jpg)

**Comment by pgsdesign** [comment]
I attached the hard drive and turned it on. Could it be that I need to turn it on without the drive attached first and then attach the drive after I connect? Could that be the thing I screwed up?

I’ve attached some screen shots consolidated into one picture showing the DHCP address it’s getting, checked the MAC address to make sure it was the Raspberry Pi, successful pings from both Mac and PC, a timeout on the SSH attempt from the Mac. I tried SSH via Putty on the PC with the same result. I also have a couple shots from my firewall showing it's doing some stuff so it’s alive in some sense.

I’m up there again Monday if you have some next things to try.

Thanks!!

Jeff

**Comment by tehelsper** [comment]
That's really unusual. Do you happen to have a VNP running on your device that could be preventing certain types of network connections from working?

My only other idea is that the SD card is bad or has been corrupted, but only enough to prevent network from working properly. The more typical signs if that is the case are the device totally can't boot or tor refuses to work (not the case here).

Instructions to re-flash the SD card are available here. I would give that a try if you can to see if it helps.
https://mynodebtc.com/download

**Comment by pgsdesign** [comment]
Sounds like a plan, I’ll report back either way. I'll check with my Firewall guy (super geek type) as to whether something else is at play on the network.

Thanks so much,
Jeff

**Comment by rpsalmon** [comment]
Hello - 
I am having a similar issue. I was able to use the web interface at http://mynode.local/ and began the syncing process but now I can not get a response. I don't want to restart the pi as it looks like it is working. Just no web interface. Similarly no response when using http://mynode.ipaddress and my unit is brand new as well.

Was it a network issue? 

> I'm having a similar issue with my brand new unit, but I can't get to it at all - so "no server found" error. I see it getting the IP from my dhcp server, I can ping it, I added an "A" dns record to name it locally and I can ping that, I didn't know what account to use to SSH in, but I can see it going to mynodebtc.com:443 every 10 minutes (824452 bytes a day worth of data), ipify.org:443 (6239 of data a day), and seeip.org:443 (2919 bytes a day). I've tried rebooting and using every version of the URL possible with http, https, just the IP, using the dns record I added to hit it, etc. I can't get it to show up. Can you share how you SSH in so I can try that as well?

**Comment by pgsdesign** [comment]
I had to re-flash the card and it worked fine after that. It’s been running ever since. 

Hope this helps!  
Jeff

**Comment by rpsalmon** [comment]
Thanks for the response - I did some more research and it appears my trouble was USB port I was using for the ssd. I am limited to usb 2 because of "poor driver support" on usb 3. Switched it over and it is back syncing. 🤞🏾

**Comment by tehelsper** [comment]
@rpsalmon Good to hear. I'm going to close this issue now since its so old. New issues can be opened up if this re-appears.
