### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rhst1** [mynodebtc/mynode#34]
When attempting to upgrade from the home page or when trying to get to the Settings page an Internal Server Error shows up with the message: 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Amiga500** [comment]
Which version are you using?

**Comment by rhst1** [comment]
Will try and let you know

**Comment by rhst1** [comment]
After restart was able to access settings and have started upgrade process

**Comment by Amiga500** [comment]
Good. With v0.1.61 you shouldn't have this bug anymore

**Comment by rhst1** [comment]
Home page:

 

Starting...

Launching myNode services...

**Comment by rhst1** [comment]
After myNode restarted, I was able to access settings and initiated the upgrade, but after the server restarted, it was still at 1.59

 

I initiated the upgrade (again) – will let you know results

 

From: rhstone@wakarusariver.com <rhstone@wakarusariver.com> 
Sent: Wednesday, October 30, 2019 1:47 PM
To: 'mynodebtc/mynode' <reply@reply.github.com>
Subject: RE: [mynodebtc/mynode] Internal Server Error (#34)

 

Home page:

 

Starting...

Launching myNode services...

**Comment by Amiga500** [comment]
Happened to me too.. try again ;)

**Comment by rhst1** [comment]
Still stuck at 1.59

 

Here is a screenshot showing that an upgrade is available, but not listing the version:

 



 

Clicking See Changes shows the improvements in versions 1.60 and 1.61, but myNode still won’t upgrade from the settings page

**Comment by Amiga500** [comment]
mmmhhhh.. try later again

**Comment by rhst1** [comment]
Maybe we should close this issue, since it has been resolved and add a new issue regarding the failure to upgrade?

**Comment by Amiga500** [comment]
Sure
