### ISSUE TITLE
Using Bitcoin Data from Existing Node

### ISSUE THREAD

**Issue by salenjak** [mynodebtc/mynode#344]
Hi,

I am trying to copy data from existing node according to steps from: https://www.mynodebtc.com/guide/using_bitcoin_data_from_existing_node

I get "Permission denied" message when try to copy blocks with next command:
sudo scp -r admin@192.168.1.5:/mnt/hdd/mynode/bitcoin/blocks /mnt/hdd/mynode/bitcoin/

This is copied from PuTTY:
admin@myNode:~ $ sudo /usr/bin/mynode_stop_critical_services.sh
[sudo] password for admin:
Stopping myNode services...
/usr/bin/mynode_stop_critical_services.sh: line 23: /opt/mynode/dojo/docker/my-dojo/dojo.sh: No such file or directory
admin@myNode:~ $ sudo rm -rf /mnt/hdd/mynode/bitcoin/blocks
admin@myNode:~ $ sudo rm -rf /mnt/hdd/mynode/bitcoin/chainstate
admin@myNode:~ $ sudo rm -rf /mnt/hdd/mynode/bitcoin/indexes
admin@myNode:~ $ sudo chown -R admin:admin /mnt/hdd/mynode/bitcoin/
admin@myNode:~ $ sudo scp -r admin@192.168.1.5:/mnt/hdd/mynode/bitcoin/blocks /mnt/hdd/mynode/bitcoin/
The authenticity of host '192.168.1.5 (192.168.1.5)' can't be established.
ECDSA key fingerprint is SHA256:1/Y/UgipxyknHUDX6mfV93xKh/tj/pxCeFpoyAFC+2o.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.5' (ECDSA) to the list of known hosts.
admin@192.168.1.5's password:
scp: /mnt/hdd/mynode/bitcoin/blocks: Permission denied

Any idea?

**Comment by user411** [comment]
Does the device you're connecting to definitely have the path "/mnt/hdd/mynode/bitcoin/blocks" extant and is it assessible by the user "admin"? You may need to modify the command for your specific setup.

I copied data from my existing node today and found it easier to do the scp from the existing node. So I 

$ cd ~/bitcoin/.bitcoin
$ scp -r blocks admin@mynode.local:/mnt/hdd/mynode/bitcoin/blocks
$ scp -r chainstate admin@mynode.local:/mnt/hdd/mynode/bitcoin/chainstate
$ scp -r indexes admin@mynode.local:/mnt/hdd/mynode/bitcoin/indexes

and then continue on with the default instructions from the mynode machine.

Hope this helps.

**Comment by salenjak** [comment]
Hi user411,

Thanks for the reply.

I was building a node for my friend. As I didn't know how to solve the issue decided to synchronise of the blockchain from scratch. 

Hope your advice will help someone next time.

I am closing now this issue.
