### ISSUE TITLE
Electrum Wallet client 4.0 does not sync with old electrs version.

### ISSUE THREAD

**Issue by beeforbacon** [mynodebtc/mynode#345]
mynode currently uses (electrs) electrum  rust server 0.7.0 which is over one year old. They are already at 0.8.5. After upgrading to Electrum Wallet 4.0, the wallet client no longer syncs with the local server through tor, and is very spotty when connected through localhost:50002.

**Comment by Genesius** [comment]
I confirm Electrum Wallet 4.0 cannot connect to Electrum server on Mynode.

**Comment by tehelsper** [comment]
This issue was resolved in the latest release - v0.2.11.
