### ISSUE TITLE
Failure to upgrade

### ISSUE THREAD

**Issue by rhst1** [mynodebtc/mynode#35]
After resolving an Internal Server Error, we now have a new problem: failure to upgrade.

On the home page and on the settings page myNode says an upgrade is available, but on the settings page only the current version (1.59) is shown. The latest version is blank. Clicking the See Changes button does show the improvements brought about in versions 1.60 and 1.61

Clicking the Upgrade button seems to initiate the upgrade process as expected, but after trying it twice, we find the upgrade failed - remaining at 1.59

**Comment by rhst1** [comment]
Upgrade was finally successful. Not sure why, but rebooting the router may have helped - am closing the issue

**Comment by tehelsper** [comment]
Yeah, this failure tends to be a network hiccup. It basically means the
latest version info could not be grabbed from the internet.
