### ISSUE TITLE
Issues after upgrade from v0.1.8 to v0.2.11

### ISSUE THREAD

**Issue by lordgivemestrength** [mynodebtc/mynode#352]
I recently upgraded a flawlessly working v0.1.8 MyNode, as I was looking forward to utilising loops to balance my lightning channels.

First I went to v0.2.10 and although the MyNode version was correct, LND and RTL were still old version 0.9 and 0.6.2Beta respectively.

Upgraded MyNode to v0.2.11 to see if that works, and it came up with an error on electrum server, and all other applications at the old builds.

I have reset Electrum, and that is currently syncing again. the question is therefore, can I instal / download LND v0.10 and RTL v0.7.x separately to give me the functionality I need?

Being a total tech noob to this, I have tried to instal BTC0.20.0, LND 0.10.3 and RTL separately via the code in this github, but although it starts running, I see multiple permission denied messages for BTC, LND and RTL.

Hoping someone here can give some pointers.
Thanks in advance.

**Comment by tehelsper** [comment]
I would recommend re-flashing the SD card if you has issues when making a jump that large. Or re-attempt the upgrade.

**Comment by lordgivemestrength** [comment]
Reattempted the upgrade several times, and it always ends with RTL being in an error state unless I re-instal that application from settings menu. 

I even tried installing LND 0.10.3 separately but think I stored it in wrong location ( total noob lol. )

I will do the flash of SD card over the weekend.
Question though - the latest one on github is 0.2.07 so does that mean I flash that image and then upgrade again via the normal upgrade process?

**Comment by tehelsper** [comment]
Yeah, that's right.
