### ISSUE TITLE
Stalled setup - Looking for drive, Repairing drive, Launching Services...

### ISSUE THREAD

**Issue by dwabz** [mynodebtc/mynode#353]
Hi, I am attempting to set up my own node using a Raspberry Pi 4b, WD Blue 1TB SSD SATA ext drive, Orico drive enclosure (SATA to USB 3.0) and a premium subscription. 
My first attempt at setting this up worked well, it formatted the drive and it started to sync. I left it running and went to bed at 223 of /167,500. Woke up 6hrs later to find an error message - looking for a drive. Tried several resets and each time the system cycles through Repairing the drive, then 'Launching MyNode services and finally back to Looking for the drive. 
I've just bought a new SATA-USB3.0 cable just in case drive connectivity is responsible but - got the same result. 
I'm not sure what to do. Really keen to get the node running but superbly frustrated and the mo.

**Comment by tehelsper** [comment]
Try using the recommended SATA -> USB adapter from mynodebtc.com/download and see if that improves things. Some USB -> SATA adapters do not work well with Raspberry Pi devices.

**Comment by dwabz** [comment]
Thanks. I might try that. 24hrs on and it is still syncing - 457,500/639,000
Is it normal to take this long??

**Comment by tehelsper** [comment]
Yes, that is actually quite fast. Depending on internet speed, tor connection, etc... it can take 2-5 days with an SSD.

**Comment by tehelsper** [comment]
Did your issue resolve?

**Comment by dwabz** [comment]
Hi  Taylor,

The issue has  not recurred and the initial sync is still ongoing

Currently 637.2k/639.5k so it should be complete in a few hours 😊

Thx again for your help

D
