### ISSUE TITLE
ROCKPro64 : myNode Premium

### ISSUE THREAD

**Issue by khny258** [mynodebtc/mynode#354]
I encountered a bug on myNode Premium with ROCKPro64. The myNode Premium doesn't see the the latest version 0.2.11 - I had to manually install it and now the screen looks like this:
![Annotation 2020-07-14 084910](https://user-images.githubusercontent.com/55590940/87427686-2b064000-c5af-11ea-84cb-cde15f790baa.jpg)

**Comment by tehelsper** [comment]
Can you try running these commands:

torify curl http://www.mynodebtc.com/device/latest_version
curl http://www.mynodebtc.com/device/latest_version

I'm not sure how that could fail unless torify did not work.

**Comment by khny258** [comment]
![Annotation 2020-07-15 134038](https://user-images.githubusercontent.com/55590940/87577361-ca573000-c6a0-11ea-8b68-685550593b24.jpg)
yeah, looks like torify didn't work

**Comment by tehelsper** [comment]
OK, that makes sense.

Can you run:

apt-get -y install torsocks

And then re-run the torify command to see if it was installed properly?

**Comment by khny258** [comment]
ok that worked. thanks!
