### ISSUE TITLE
LND won't progress past 'Launching...' - RPi4

### ISSUE THREAD

**Issue by asperks** [mynodebtc/mynode#356]
My LND won't start.  The other day, I powered down the Pi to replace the heat sink in the device.  It was running at 48c, and since the replacement it's running at about 42c.

But now, the LND status screen is stuck on 'Launching'.  I've re-installed LND twice, and still a day after the re-installs, LND never progresses beyond 'Launching'.  During the last re-install, I made sure that the device was upgraded to the latest version (0.2.11)

I'm about to try the re-install a third time.  But don't hold much hope.  I've created a channel.backup file, but what other steps might I take to get LND to run?

**Comment by asperks** [comment]
I've just gone to the linux terminal and typed lncli, and it tells me that it is at this version:

```
admin@myNode:~ $ lncli
NAME:
   lncli - control plane for your Lightning Network Daemon (lnd)

USAGE:
   lncli [global options] command [command options] [arguments...]
   
VERSION:
   0.9.2-beta commit=v0.9.2-beta
```

That's not right.  It should be at 0.10.2, yes?  So it looks like the LND install isn't working.

**Comment by asperks** [comment]
Does anyone know how to force update LND in the mynodebtc node from the command line?

**Comment by tehelsper** [comment]
It should be 10.3. Are you having any other issues? I would re-flash the SD card and re-upgrade to v0.2.11.

**Comment by asperks** [comment]
Pretty straightforward to do that, sure, but then I lose all of my onion connections.  I'm happy to upgrade at the command prompt if there are any guides?  Will report on progress so that i can be recorded as a step-by-step process.  If it all goes pear-shaped I just re-image.  Are there any internal scripts that allow one to upgrade the LND instance by the command prompt?

I looked over the raspiblitz documentation, and I can see where it might be possible.  The question I really have is whether the RPC username that blitz uses that connects the bitcoin daemon to the LND instance is the.  As username of 'bitcoin' is used.

Is there any information you could provide that details this so that I might try it myself?  Like I said, I don't mind upgrading LND from the terminal.  Just want to make sure the authentication details will work.

**Comment by asperks** [comment]
This is the guide I'd want to use...

https://stadicus.github.io/RaspiBolt/raspibolt_faq.html#how-to-upgrade-lnd

**Comment by tehelsper** [comment]
Yeah, the commands would be identical to the commands for upgrading lnd in the /usr/bin/mynode_post_upgrade.sh script. Look for the lnd section - and that script is run as root.

However, that is also exactly what the re-install does. You could re-install lnd one more time and then look for the log under /home/admin/upgrade_logs/ and look for the most recent lnd reinstall log.

**Comment by asperks** [comment]
There isn't any /home/admin/upgrade_logs.  There's a /home/admin/reinstall_logs directory.

In that directory, there's a file called reinstall_lnd.txt

'''
+ source /usr/share/mynode/mynode_config.sh
++ IS_ARMBIAN=0
++ IS_ROCK64=0
++ IS_ROCKPRO64=0
++ IS_RASPI=0
++ IS_RASPI3=0
++ IS_RASPI4=0
++ IS_X86=0
++ DEVICE_TYPE=unknown
+++ tr -d '\0'
++ MODEL='Raspberry Pi 4 Model B Rev 1.1'
++ grep amd64
++ uname -a
++ true
++ [[ Raspberry Pi 4 Model B Rev 1.1 == *\R\o\c\k\6\4* ]]
++ [[ Raspberry Pi 4 Model B Rev 1.1 == *\R\o\c\k\P\r\o\6\4* ]]
++ [[ Raspberry Pi 4 Model B Rev 1.1 == *\R\a\s\p\b\e\r\r\y\ \P\i\ \3* ]]
++ [[ Raspberry Pi 4 Model B Rev 1.1 == *\R\a\s\p\b\e\r\r\y\ \P\i\ \4* ]]
++ IS_RASPI=1
++ IS_RASPI4=1
++ '[' 0 -eq 1 ']'
++ '[' 1 -eq 1 ']'
++ DEVICE_TYPE=raspi4
+++ free --giga
+++ awk '{print $2}'
+++ grep Mem
++ TOTAL_RAM_GB=4
+++ mynode-get-device-serial
++ SERIAL_NUM=10000000f8583d1d
++ MYNODE_DIR=/mnt/hdd/mynode
++ VPN_BACKUP_DIR=/mnt/hdd/mynode/vpn
++ QUICKSYNC_DIR=/mnt/hdd/mynode/quicksync
++ QUICKSYNC_CONFIG_DIR=/mnt/hdd/mynode/.config/transmission
++ QUICKSYNC_TORRENT_URL=https://mynodebtc.com/device/blockchain.tar.gz.torrent
++ QUICKSYNC_TORRENT_BETA_URL=https://mynodebtc.com/device/blockchain_beta.tar.gz.torrent
++ QUICKSYNC_UPLOAD_RATE_FILE=/mnt/hdd/mynode/settings/quicksync_upload_rate
++ QUICKSYNC_BACKGROUND_DOWNLOAD_RATE_FILE=/mnt/hdd/mynode/settings/quicksync_background_download_rate
++ LATEST_VERSION_URL=http://www.mynodebtc.com/device/latest_version
++ LATEST_BETA_VERSION_URL=http://www.mynodebtc.com/device/latest_beta_version
++ UPLOADER_FILE=/mnt/hdd/mynode/settings/uploader
++ UPGRADE_ERROR_FILE=/mnt/hdd/mynode/settings/upgrade_error
++ LND_BACKUP_FOLDER=/home/bitcoin/lnd_backup/
++ LND_TLS_CERT_FILE=/mnt/hdd/mynode/lnd/tls.cert
++ LND_WALLET_FILE=/mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/wallet.db
++ LND_CHANNEL_FILE=/mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/channel.backup
++ LND_CHANNEL_FILE_BACKUP=/home/bitcoin/lnd_backup/channel.backup
++ LND_ADMIN_MACAROON_FILE=/mnt/hdd/mynode/lnd/data/chain/bitcoin/mainnet/admin.macaroon
++ PRODUCT_KEY_FILE=/home/bitcoin/.mynode/.product_key
++ ELECTRS_ENABLED_FILE=/mnt/hdd/mynode/.mynode_electrs_enabled
++ LNDHUB_ENABLED_FILE=/mnt/hdd/mynode/.mynode_lndhub_enabled
++ BTCRPCEXPLORER_ENABLED_FILE=/mnt/hdd/mynode/.mynode_btcrpceplorer_enabled
++ VPN_ENABLED_FILE=/mnt/hdd/mynode/.mynode_vpn_enabled
++ MEMPOOLSPACE_ENABLED_FILE=/mnt/hdd/mynode/.mynode_mempoolspace_enabled
++ BTCPAYSERVER_ENABLED_FILE=/mnt/hdd/mynode/.mynode_btcpayserver_enabled
++ BITCOIN_SYNCED_FILE=/mnt/hdd/mynode/.mynode_bitcoind_synced
++ QUICKSYNC_COMPLETE_FILE=/mnt/hdd/mynode/quicksync/.quicksync_complete
++ IS_PREMIUM=0
++ PRODUCT_KEY=not_found
++ '[' -f /home/bitcoin/.mynode/.product_key ']'
++ UPGRADE_DOWNLOAD_URL='http://www.mynodebtc.com/device_api/download_latest_standard.php?type=raspi4&product_key=not_found&ser$
++ UPGRADE_DOWNLOAD_SIGNATURE_URL=http://www.mynodebtc.com/device/hashes/mynode_release_latest_raspi4.sha256
++ UPGRADE_BETA_DOWNLOAD_URL='http://www.mynodebtc.com/device_api/download_latest_standard.php?beta=1&type=raspi4&product_key=n$
++ UPGRADE_BETA_DOWNLOAD_SIGNATURE_URL=http://www.mynodebtc.com/device/hashes/mynode_release_latest_beta_raspi4.sha256
++ UPGRADE_PUBKEY_URL=https://raw.githubusercontent.com/mynodebtc/pubkey/master/mynode_release.pub
++ '[' -f /usr/share/mynode/mynode_config_raspi.sh ']'
++ source /usr/share/mynode/mynode_config_raspi.sh
++ '[' -f /usr/share/mynode/mynode_config_debian.sh ']'
+ '[' 1 -ne 1 ']'
+ APP=lnd
+ /usr/bin/mynode_stop_critical_services.sh
Stopping myNode services...
Dojo is already stopped.
+ '[' lnd = bitcoin ']'
+ '[' lnd = lnd ']'
+ rm -f /home/bitcoin/.mynode/.lnd_url
+ for i in {1..3}
+ /bin/bash /usr/bin/mynode_post_upgrade.sh
/usr/bin/mynode_reinstall_app.sh: line 81: /home/admin/upgrade_logs/reinstall_app_lnd_post_1.txt: No such file or directory
+ RC=1
+ '[' 1 -eq 0 ']'
+ sleep 10s
+ for i in {1..3}
+ /bin/bash /usr/bin/mynode_post_upgrade.sh
/usr/bin/mynode_reinstall_app.sh: line 81: /home/admin/upgrade_logs/reinstall_app_lnd_post_2.txt: No such file or directory
+ RC=1
+ '[' 1 -eq 0 ']'
++ PRODUCT_KEY=not_found
++ '[' -f /home/bitcoin/.mynode/.product_key ']'
++ UPGRADE_DOWNLOAD_URL='http://www.mynodebtc.com/device_api/download_latest_standard.php?type=raspi4&product_key=not_found&ser$
++ UPGRADE_DOWNLOAD_SIGNATURE_URL=http://www.mynodebtc.com/device/hashes/mynode_release_latest_raspi4.sha256
++ UPGRADE_BETA_DOWNLOAD_URL='http://www.mynodebtc.com/device_api/download_latest_standard.php?beta=1&type=raspi4&product_key=n$
++ UPGRADE_BETA_DOWNLOAD_SIGNATURE_URL=http://www.mynodebtc.com/device/hashes/mynode_release_latest_beta_raspi4.sha256
++ UPGRADE_PUBKEY_URL=https://raw.githubusercontent.com/mynodebtc/pubkey/master/mynode_release.pub
++ '[' -f /usr/share/mynode/mynode_config_raspi.sh ']'
++ source /usr/share/mynode/mynode_config_raspi.sh
++ '[' -f /usr/share/mynode/mynode_config_debian.sh ']'
+ '[' 1 -ne 1 ']'
+ APP=lnd
+ /usr/bin/mynode_stop_critical_services.sh
Stopping myNode services...
Dojo is already stopped.
+ '[' lnd = bitcoin ']'
+ '[' lnd = lnd ']'
+ rm -f /home/bitcoin/.mynode/.lnd_url
+ for i in {1..3}
+ /bin/bash /usr/bin/mynode_post_upgrade.sh
/usr/bin/mynode_reinstall_app.sh: line 81: /home/admin/upgrade_logs/reinstall_app_lnd_post_1.txt: No such file or directory
+ RC=1
+ '[' 1 -eq 0 ']'
+ sleep 10s
+ for i in {1..3}
+ /bin/bash /usr/bin/mynode_post_upgrade.sh
/usr/bin/mynode_reinstall_app.sh: line 81: /home/admin/upgrade_logs/reinstall_app_lnd_post_2.txt: No such file or directory
+ RC=1
+ '[' 1 -eq 0 ']'
'''

**Comment by asperks** [comment]
Any suggestions?

**Comment by asperks** [comment]
So it got further after creating that folder.  The log now exists in the folder after I've done a re-install.  I started it last night and now when I come back it says 'Opening DB' in the LND status.  

These are the last lines of the log file:

```
+ cp -f /usr/share/mynode/thub_config.yaml /mnt/hdd/mynode/thunderhub/thub_config.yaml
+ chown -R bitcoin:bitcoin /mnt/hdd/mynode/thunderhub
+ echo https://github.com/apotdevin/thunderhub/archive/v0.8.8.tar.gz
+ LNDCONNECTARCH=lndconnect-linux-armv7
+ '[' 0 = 1 ']'
+ LNDCONNECT_UPGRADE_URL=https://github.com/LN-Zap/lndconnect/releases/download/v0.2.0/lndconnect-linux-armv7-v0.2.0.tar.gz
+ LNDCONNECT_UPGRADE_URL_FILE=/home/bitcoin/.mynode/.lndconnect_url
+ CURRENT=
+ '[' -f /home/bitcoin/.mynode/.lndconnect_url ']'
++ cat /home/bitcoin/.mynode/.lndconnect_url
+ CURRENT=https://github.com/LN-Zap/lndconnect/releases/download/v0.2.0/lndconnect-linux-armv7-v0.2.0.tar.gz
+ '[' https://github.com/LN-Zap/lndconnect/releases/download/v0.2.0/lndconnect-linux-armv7-v0.2.0.tar.gz '!=' https://github.co$
+ '[' '!' -f /usr/bin/ngrok ']'
+ rm -f /usr/local/bin/tor
++ tor --version
+ TOR_VERSION='Tor version 0.4.2.7.'
+ [[ Tor version 0.4.2.7. != *\T\o\r\ \v\e\r\s\i\o\n\ \0\.\4* ]]
+ '[' 0 = 1 ']'
+ rm -f /etc/update-motd.d/10-armbian-header
+ rm -f /etc/update-motd.d/30-armbian-sysinfo
+ rm -f /etc/update-motd.d/35-armbian-tips
+ rm -f /etc/update-motd.d/40-armbian-updates
+ rm -f /etc/update-motd.d/41-armbian-config
+ rm -f /etc/update-motd.d/98-armbian-autoreboot-warn
+ apt-get clean
+ systemctl enable docker
+ systemctl enable bitcoind
+ systemctl enable lnd
+ systemctl enable firewall
+ systemctl enable invalid_block_check
+ systemctl enable usb_driver_check
+ systemctl enable https
+ systemctl enable docker_images
+ systemctl enable glances
Synchronizing state of glances.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable glances
+ systemctl enable webssh2
+ systemctl enable tor
Synchronizing state of tor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tor
+ systemctl enable loopd
+ systemctl enable rotate_logs
+ systemctl enable corsproxy_btcrpc
Created symlink /etc/systemd/system/multi-user.target.wants/corsproxy_btcrpc.service → /etc/systemd/system/corsproxy_btcrpc.ser$
+ systemctl disable hitch
Synchronizing state of hitch.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable hitch
+ systemctl disable mongodb
+ systemctl disable lnd_admin
Failed to disable unit: Unit file lnd_admin.service does not exist.
+ true
+ systemctl disable dhcpcd
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable dhcpcd
+ systemctl daemon-reload
+ sync
```
I'll wait for a few hours and see it that resolves it.

**Comment by tehelsper** [comment]
Thanks for the log! The issue will be fixed in the next release. The folders were not all made properly for a re-install if an upgrade folder had never been made before.

Now, you can check the lnd log from the status page to see why lnd won't start.

**Comment by asperks** [comment]
Looks like this issue is closed out and will be resolved in the next release.  LND is giving a different message now (DB Loading...) and still hangs, but I'll raise that as another issue.
