### ISSUE TITLE
Electrs cpu runs at 95-100% on raspberry pi 4

### ISSUE THREAD

**Issue by ahabel23** [mynodebtc/mynode#357]
Electrs uses high CPU when a wallet is open on the client side (windows). When the wallet is closed CPU use drops. I tried a wallet that has approximately 200 transactions and also one that has 2 transactions, both have the issue.  I deleted and rebuilt the electrs data but had the same issue.  Brought this up with @romanz and he suggested I open an issue here.

RaspPi 4 (4gb RAM)
Electrum 4.0.2 (had issue with 3.8 as well)
Mynode premium 0.2.11

**Comment by Transisto** [comment]
Same thing, CPU always 100% when pushing data to an electrum client.
at the rate of about 5 address/second

**Comment by tehelsper** [comment]
I'm not really sure what I can do. myNode uses an unmodified version of electrs.

**Comment by tehelsper** [comment]
I can reproduce this issue though. When having a wallet open, it definitely uses one core at 100% on my RP4.

**Comment by ahabel23** [comment]
It's also difficult to interact with as Electrum goes to "Synchronizing (0/1)" and is extremely slow to come back. The strange thing is, I don't think I had this problem originally. For now, I am going to attempt to Mynode as a VM in virtualbox to see if I can get better performance but it would be nice to come to some kind resolution.

**Comment by tehelsper** [comment]
I've never noticed that. I can get wallets with a number of transactions (<50) to sync in seconds using myNode on a Raspberry Pi 4.

**Comment by romanz** [comment]
Thanks for reporting this issue!
I am using Prometheus to report various performance-related metrics in electrs, inculding the duration for lookup operations and Electrum RPCs:
https://github.com/romanz/electrs/blob/9c0d69af6cfa7e3a826c216c5bca18aeb774bc8b/src/query.rs#L224-L230
https://github.com/romanz/electrs/blob/9c0d69af6cfa7e3a826c216c5bca18aeb774bc8b/src/rpc.rs#L545-L548

Would it be possible to collect and share those metrics (e.g. using [Prometheus](https://github.com/romanz/electrs/blob/master/doc/usage.md#monitoring)/Grafana) for the Raspberry Pi platform?
The following graphs can be useful for understanding the performance bottlenecks:
http://localhost:9090/graph?g0.range_input=1h&g0.stacked=1&g0.expr=rate(electrs_electrum_rpc_sum%5B1m%5D)&g0.tab=0
http://localhost:9090/graph?g0.range_input=1h&g0.stacked=1&g0.expr=rate(electrs_electrum_rpc_count%5B1m%5D)&g0.tab=0
http://localhost:9090/graph?g0.range_input=1h&g0.stacked=1&g0.expr=rate(electrs_query_duration_sum%5B1m%5D)&g0.tab=0
http://localhost:9090/graph?g0.range_input=1h&g0.stacked=1&g0.expr=rate(electrs_query_duration_count%5B1m%5D)&g0.tab=0

**Comment by romanz** [comment]
BTW, could you please share the specifications of the storage device you are using for the Bitcoin blockchain & electrs index?

**Comment by ahabel23** [comment]
The drive I'm using is a Seagate STGX1000400. It runs at 5400rpm. 
Here's the graphs you requested.
![1](https://user-images.githubusercontent.com/40004389/87970912-bab16000-ca81-11ea-844b-166f98360c8a.JPG)
![2](https://user-images.githubusercontent.com/40004389/87970917-bdac5080-ca81-11ea-857a-86375b253232.JPG)
![3](https://user-images.githubusercontent.com/40004389/87970920-bedd7d80-ca81-11ea-8b85-3666eeab5ad8.JPG)
![4](https://user-images.githubusercontent.com/40004389/87970926-c0a74100-ca81-11ea-99c7-6e227f1b8706.JPG)

**Comment by romanz** [comment]
How many addresses are tracked by the server (generating the graphs above)?

It seems that most of the time is consumed by (re-)computing the confirmed status of wallet addresses:
https://user-images.githubusercontent.com/40004389/87970920-bedd7d80-ca81-11ea-8b85-3666eeab5ad8.JPG

As a work-around, you can try to decrease the polling interval by setting `--wait-duration-secs` to higher value (the default is 5 seconds).

We should allow caching of `confirmed_status` invocations in case the blockchain didn't change (no new blocks or re-orgs):
https://github.com/romanz/electrs/blob/9c0d69af6cfa7e3a826c216c5bca18aeb774bc8b/src/query.rs#L301

**Comment by romanz** [comment]
We can use something similar to #185 or #186 to optimize the performance for this use-case.

**Comment by Transisto** [comment]
![electrs](https://user-images.githubusercontent.com/388716/88341756-2c044380-cd0c-11ea-825c-944dd9be67e2.gif)
20X speed with mynode beta_07-22-20_1595475780

**Comment by Transisto** [comment]
![electrs2](https://user-images.githubusercontent.com/388716/88343212-e4cb8200-cd0e-11ea-817a-4fd696ef659a.gif)
Electrs doesn't stop even when wallet isn't syncing. 5x speed, 5min in 1min

**Comment by tehelsper** [comment]
@Transisto Is that better or worse than v0.2.11 for you? The only change was to increase the bitcoind poll time from 5s to 15s.

The behavior in your second comment I believe is understandable. Electrs will still run in an attempt to find new TXs and process blocks as they come in. On my Raspi 4 with a smaller wallet, I saw electrs run at one CPU for about ~5s, then drop to 0 for ~10s every 15s.

**Comment by Transisto** [comment]
Same but I'm not 100% sure the beta version installed properly so these
results might be meaningless.

**Comment by ahabel23** [comment]
I updated to the latest version that has "--wait-duration-secs 15" and have much better performance. I consider this closed. Thanks all.
