### ISSUE TITLE
[Feature] Add show logs button under every apps info page.

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#358]
List of apps with it's own page that could show a ![image](https://user-images.githubusercontent.com/388716/87748143-1c907200-c7c3-11ea-9e37-225be8f4f70f.png) button.

Bitcoind
LND 
LNDHub 
electrs
Dojo
Tor

**Comment by Jacksper13** [comment]
@tehelsper "Show log" already shown in Status page for each app - @Transisto do you consider this resolved or are you requesting this button shows in the Applications tab? If resolved I'd close

**Comment by Transisto** [comment]
> @tehelsper "Show log" already shown in Status page for each app - @Transisto do you consider this resolved or are you requesting this button shows in the Applications tab? If resolved I'd close

Yes, most of these app info page have a lot of spare room on their pages.

![image](https://user-images.githubusercontent.com/388716/116903665-b4543500-ac0a-11eb-8087-b2132baa73c1.png)
example

**Comment by tehelsper** [comment]
Not sure I'm following - the status page has a list of apps and a button to show the log.

**Comment by Transisto** [comment]
For example, The name of the electrum page is called "Electrum Server Status"

I'd like to see a button to see the logs there instead of going to a separate status page and looking for electrum there.

Seems like it could easily apply to every app that has an "Info" page.

**Comment by tehelsper** [comment]
Oh yeah, I wanted to keep the info pages free from low-level details and logs and stuff since it should "just work". Only if a user is curious or has an issue, should they need the log, so they are on a separate page dedicated to that level of detail.

**Comment by Transisto** [comment]
Your call.
