### ISSUE TITLE
BTCPay Server "update" button doesn't update

### ISSUE THREAD

**Issue by maltokyo** [mynodebtc/mynode#361]
Latest BTCPay server docker version is: `btcpayserver/btcpayserver:1.0.5.3` but myNode has only `btcpayserver/btcpayserver:1.0.4.4`

When I press "update" button, nothing happens in the background, and no update is made even after hours of waiting.  On top of this, the standard upgrade script/command `btcpay-update.sh` provided with BTCPay server is not available in mynode, so I can not find any way to trigger the upgrade on the command line either...

This button, does nothing:
![image](https://user-images.githubusercontent.com/1388507/87809737-27e3ac00-c85c-11ea-9e9d-d2e3bd9c1733.png)

**Comment by tehelsper** [comment]
This is expected. BTC Pay Server upgrades are managed as part of the myNode upgrade process.

**Comment by maltokyo** [comment]
ok, I guess mentioning in docs or suppressing the update button would be good!
