### ISSUE TITLE
LNbits and Specter red when activated

### ISSUE THREAD

**Issue by ChuckinBits** [mynodebtc/mynode#362]
For whatever reason LNbits and Specter doesn't work for me.
I have premium. Running all apps and services except beta apps. I'm on my local network, quicksync is disabled, running v0.2.11, tried restarting myNode a couple of times with LNbits off and with it on/red.  Not sure where Specter logs are located but here are the LNbits errors: 
Jul 15 11:01:23 myNode systemd[1]: Failed to start LNBits.
Jul 15 11:01:23 myNode systemd[1]: lnbits.service: Failed with result 'exit-code'.
Jul 15 11:01:23 myNode systemd[1]: lnbits.service: Control process exited, code=exited, status=200/CHDIR
Jul 15 11:01:23 myNode systemd[21722]: lnbits.service: Failed at step CHDIR spawning /usr/bin/is_not_shutting_down.sh: No such file or directory
Jul 15 11:01:23 myNode systemd[21722]: lnbits.service: Changing to the requested working directory failed: No such file or directory
Jul 15 11:01:23 myNode systemd[1]: Starting LNBits...

**Comment by tehelsper** [comment]
Since the error is chdir, it likely means the app install failed. Try re-installing those apps via the settings page.

**Comment by ChuckinBits** [comment]
I reinstalled LNbits through the settings page and now its giving me different errors. Both LNbits and Specter still not working.
LNbits logs:
Jul 17 19:32:02 myNode systemd[1]: Failed to start LNBits.
Jul 17 19:32:02 myNode systemd[1]: lnbits.service: Failed with result 'exit-code'.
Jul 17 19:32:02 myNode systemd[1]: lnbits.service: Control process exited, code=exited, status=1/FAILURE
Jul 17 19:32:02 myNode lnbits[7324]: ModuleNotFoundError: No module named 'jinja2'
Jul 17 19:32:02 myNode lnbits[7324]:     from jinja2 import escape
Jul 17 19:32:02 myNode lnbits[7324]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
Jul 17 19:32:02 myNode lnbits[7324]:     from flask.cli import main
Jul 17 19:32:02 myNode lnbits[7324]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/bin/flask", line 5, in <module>
Jul 17 19:32:02 myNode lnbits[7324]: Traceback (most recent call last):
Jul 17 19:32:01 myNode lnbits[7324]: Loading .env environment variables…
...

**Comment by tehelsper** [comment]
Can you log in via SSH and send me the reinstall log for lnbits in the ~/upgrade_logs/ folder?

**Comment by ChuckinBits** [comment]
[reinstall_app_lnbits_post_1.txt](https://github.com/mynodebtc/mynode/files/4941104/reinstall_app_lnbits_post_1.txt)

**Comment by tehelsper** [comment]
You might want to try the re-install again. It triggered A LOT of apps to update and the log just stopped in the middle of installing lnbits.

**Comment by ChuckinBits** [comment]
Ok, I tried reinstalling LNbits again and this time it was successful. LNbits, Specter, and everything else is working. Thank you for your help.
