### ISSUE TITLE
mynode runs normally and still writes "Looking for drive"

### ISSUE THREAD

**Issue by honza23CZ** [mynodebtc/mynode#364]
Hi,

I have a problem with the SSD, I have the impression that the device does not see it

HHD is m.2 SSD---1TB

under win 10 it works normally-I see him

I have no problem buying a license-ut it must work first

Thank you very much for your help

I bought this device

SSD
https://www.aliexpress.com/item/4000295959010.html?spm=a2g0s.9042311.0.0.26714c4duvJZz8
Box
https://www.aliexpress.com/item/4000713179678.html?spm=a2g0s.9042311.0.0.26714c4duvJZz8

**Comment by davterra** [comment]
Your link descibes an internal hard drive. I'm curious about what kind of setup you are using to run mynode. Since you're trying to access an internal hard drive I can only assume that you're using a laptop or desktop computer, and are using the Virtualbox
version of mynode?

**Comment by honza23CZ** [comment]
Hi,

problem solved

I use an external drive according to the links above, under Pi4

the problem was with the external box for SSD m.2

the problem is that they don't have drivers installed, so it doesn't work with all external boxes

with this external boxen for SSD m.2 works:

https://www.alza.cz/i-tec-mysafe-m-2-nvme-drive-metal-external-case-10gbps-d5560573.htm
