### ISSUE TITLE
Error Creating Wallet when restoring from seed

### ISSUE THREAD

**Issue by bucko13** [mynodebtc/mynode#367]
I've been trying to recover a lightning wallet through the UI but only getting failures. There's an error message after submission in the UI: "Error Creating Wallet". There are no obvious errors I can see in the console. The only thing is a 302 for the `POST /lnd/create_wallet_with_seed`, but I'm guessing this is to be expected. The only other error is `Error: You must pass a 'userId' or 'anonymousId' key` but this doesn't seem related as it's in the console on the home page too.

I've tried without a channel backup and with a backup file from Zap. Creating a new wallet from scratch seemed to work without any problem. I checked the number of words, and it's 24 as requested/expected. I tried with commas and I also tried space-separated and new line separated, all with the same result. 

Version: 0.2.12
Browser: Chrome and Safari (same issue on both)
Device Type | raspi4
Device RAM | 2 GB

**Comment by tehelsper** [comment]
The expectation is space separated words. I cannot seem to reproduce this.

Can you try to create a new wallet (only get the words, then cancel). And then try to restore the wallet using those words?

**Comment by bucko13** [comment]
Yep, so that worked. It's odd though because the original list has the right count and I double-checked that all words are valid, from the BIP39 dictionary. The list that is failing is from another wallet (created with a raspiblitz actually). Would that have something to do with it? Is there some kind of error correction on the list that would invalidate a list not following the same standard or is the mynode wallet using a different list completely? 

I did also try with the list given when I created a new one as suggested but switched some of the words with others from the BIP dictionary and got the same error

**Comment by tehelsper** [comment]
Those words are passed directly to and from lnd. I'm not sure why a seed from raspiblitz would not work - I thought it was generated the same way.

**Comment by bucko13** [comment]
Ok, I'll look into it more. Maybe try generating the wallets with other tools, including lncli, and see if any errors are returned.

**Comment by bucko13** [comment]
I think this is related to a couple things. One is that LND uses a different wallet mnemonic standard than BIP39 called [AEZEED](https://coldbit.com/what-types-of-mnemonic-seeds-are-used-in-bitcoin/) (reference PR [here](https://github.com/lightningnetwork/lnd/pull/719)) This is why some changes in the list will cause an error, it's also why trying to verify the seed (including one generated directly in mynode) will fail normal BIP39 validators (I tried with bcoin and bip39.js, both of which use BIP39), I'm guessing because the checksum generation is different. 

The other thing that's probably going on is that raspiblitz prompts for a wallet seed passphrase which encrypts the seed. I think this should be a relatively quick fix to support by adding another field for a passphrase to the restore window and send that to lnd. A quick search through the raspiblitz code and it looks like their "Password D" (lnd seed password) is used for the AEZEED passphrase, which is what's missing from the recovery step (see [here](https://github.com/rootzoll/raspiblitz/blob/8d6dad1b9895853d900f68b725144ec96f99da95/home.admin/config.scripts/lnd.initwallet.py#L118)).

**Comment by tehelsper** [comment]
Correct, it is definitely different than a BIP39 seed phrase.

Yeah, if you used a seed password you probably cant load the wallet via the myNode UI. You could probably manually import it though via the lnd CLI.

**Comment by bucko13** [comment]
Ok, I'll give that a shot. Is there any issue around the wallet password (not the seed password but what lnd expects for unlocking)?

**Comment by bucko13** [comment]
So the seed is accepted when I do it via the cli. I did get an error though trying to include the channel.backup file that i thought was a little weird. 

```
[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
```
I tried a second time without the channel backup and it worked. I used the mynode login I created for the wallet password and it seemed to be ok. Then I changed the alias via the UI and after restarting the status in the UI seems to be stuck on "Logging in..."

**Comment by tehelsper** [comment]
What is the status now? Did you pick a wallet password? I forgot, but you probably have to set that to the same as the contents of the .lndpw file which is used to store the random password that unlocks the wallet automatically.

Find it by using:
sudo cat /mnt/hdd/mynode/settings/.lndpw

**Comment by bucko13** [comment]
Ah ok. Yeah that’d probably be it then. It’s still trying to log in. Any idea why it didn’t work with the channel backup?

**Comment by bucko13** [comment]
Nevermind. It worked with the right wallet password. So wallet password did it. Just need to wait for it to sync now :)

**Comment by tehelsper** [comment]
Good! No, sorry, I don't know why. I believe you can retry the scb import once the wallet is up and running via the lnd cli.

**Comment by bucko13** [comment]
How long do you expect for the lightning status to be "waiting" after a successful import? It's been almost 24 hours now on mine. Checking the status in the cli, `lncli getinfo`, returns the block height at the current latest block.

**Comment by bucko13** [comment]
nvm, took about a day and a half but it's all running now. Guess I was just expecting a little more feedback from the UI and was too lazy to dig in with the shell.

To recap for anyone else that runs into this issue: 
- If you're trying to restore an lnd wallet/node from another system, currently you likely need to do this via the CLI (`ssh admin@192.168.1.xxx` or whatever the IP of your mynode is). 

- You'll need to know the seed password and if you have a `channels.backup` file, that should be `scp`'d to your mynode. 

- You'll also need the randomly generated wallet password that mynode creates by running: `sudo cat /mnt/hdd/mynode/settings/.lndpw`

- In the cli, run `lncli create -multi_file=./channels.backup` (substitute `./channels.backup` with the path to your backup file). You'll be prompted for your seed phrase if you're restoring, the wallet password, and the seed password. Wallet password is from mynode, seed password you should have from your seed backup. 

- Seems to take 1-2 days for the lightning UI to go from `waiting` to done on a raspi v4.
