### ISSUE TITLE
Next.js collects anonymous telemetry regarding usage

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#368]
I observed that Next.js (dependency of ThunderHub) shared this info

`
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
`

IMO myNode should opt out of telemetry by default.

Adding `npx next telemetry disable` just after building Thunderhub should do the trick.

**Comment by tehelsper** [comment]
Thanks for letting me know! Added for next release.

**Comment by abhiShandy** [comment]
Cool! I'm closing this issue.

However, the way the post-upgrade script is structured, the fix (in commit f185694) will not execute if the latest thunderhub is already installed. We should think about a better way to make such patches without forcing a reinstall, possibly by restructuring the post-upgrade script.

**Comment by tehelsper** [comment]
I agree it will not solve existing installs, but I decided not to worry about those.

Thunderhub is currently upgrading frequently and I will likely push an update soon that would include the settings update. If it was not going to get updated, I would have included additional logic to handle updating existing installs.
