### ISSUE TITLE
FEATURE: add Samourai Dojo and Whirlpool

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#37]
Another project that will be add in future

**Comment by Amiga500** [comment]
https://github.com/BTCxZelko is working on it

**Comment by sapientsaxonsaboo** [comment]
Hi,

Is Dojo still in the process of being added? I can see Whirlpool has been added. 

-- DLL

**Comment by Amiga500** [comment]
Yes, if you come into our Telegram channel, you can have more news from devs https://t.me/mynode_btc

**Comment by Amiga500** [comment]
Whirlpool integrated months ago, Dojo just arrived on last unofficial build (beta)
