### ISSUE TITLE
Issue while upgrading to 0.2.13

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#371]
Repro steps:
1. mynode 0.2.12 running on VirtualBox version 
2. Upgrade to latest version

While booting - error : "symbol 'grub_calloc' not found

Steps taken to fix the issue:
Got back mynode running from backup image on version 0.2.11
Upgraded to version 0.2.13

On boot got same error....

**Comment by tehelsper** [comment]
It looks like a bad version of grub was pushed to the debian repos. It has been bad problem for many linux users around the world since yesterday.

https://askubuntu.com/questions/1263125/how-to-fix-a-grub-boot-error-symbol-grub-calloc-not-found

You can recover this way:

First, boot into a linux live cd or recovery cd. For example, the debian 10.4.0 netinstall cd, and launch recovery mode. There may be easier options.
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/

Then, run these commands:

sudo grub-install /dev/sda
sudo grub-update
sudo reboot

**Comment by imacfan** [comment]
Great, this worked

**Comment by linkinparkrulz** [comment]
> It looks like a bad version of grub was pushed to the debian repos. It has been bad problem for many linux users around the world since yesterday.
> https://askubuntu.com/questions/1263125/how-to-fix-a-grub-boot-error-symbol-grub-calloc-not-found
> You can recover this way:
> First, boot into a linux live cd or recovery cd. For example, the debian 10.4.0 netinstall cd, and launch recovery mode. There may be easier options.
> https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/
> Then, run these commands:
> sudo grub-install /dev/sda
> sudo grub-update
> sudo reboot

How do I go about this with a virtualbox implementation?

**Comment by tehelsper** [comment]
You can add a virtual CD to the VM under the settings menus in virtualbox. The ISO file you download is basically the same thing as a bootable physical CD.

**Comment by linkinparkrulz** [comment]
> You can add a virtual CD to the VM under the settings menus in virtualbox. The ISO file you download is basically the same thing as a bootable physical CD.

Okay sounds good! Only option that sounds reasonable is rescue mode. I was able to get to a shell, but it doesn't recognize 'sudo'

**Comment by linkinparkrulz** [comment]
It seems like I could fix the issue, myNode is starting up again. I downloaded a boot repair disk and told the VM to boot from there. I applied the recommended settings, restarted the VM and everything seems normal now. This is the repair disk:
https://sourceforge.net/p/boot-repair-cd/home/Home/

This advice from the telegram chat solved the issue for me.

**Comment by RolfHodl** [comment]
Same Problem on the 0.2.14 - just had a backup and could restore the 0.2.13 - can this be fixed in 0.2.15 maybe?

**Comment by Satsurday** [comment]
I got the exact same issue. I'm on my 4th or 5th reinstall of the upgrade. It's been like 3 days of trying to upgrade now. Once the upgrade screen is done, it says it's attempting launch mynode and then just never proceeds. I can go into the status/settings page and see that the upgrade failed and have the option to restart the upgrade all over again and repeat the loop. 

Anyone know if there's a better solution than to randomly stumble upon a successful upgrade?
