### ISSUE TITLE
Add link to https://jlopp.github.io/bitcoin-core-config-generator/ in mynode.local/bitcoind/config

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#372]
Add link to https://jlopp.github.io/bitcoin-core-config-generator/ in http://mynode.local/bitcoind/config

**Comment by tehelsper** [comment]
I don't really want to encourage custom configs, since it prevents future myNode updates from using a new config.

**Comment by Transisto** [comment]
I get it, 99% of those are mostly experimental and risk breaking things.
