### ISSUE TITLE
Specter: forces mynode to logout

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#373]
Every time I use Specter by clicking its button on "mynode.local" home page. It forces "mynode" to logout..
I have to re-authenticate to get back to mynode.local homepage.

I am using my node on VirtualBox

**Comment by tehelsper** [comment]
Thanks! This should be resolved in the next version. Specter and mynode were using cookie IDs with the same name, which caused conflicts.

**Comment by abhiShandy** [comment]
I am facing a similar issue. `/mnt/hdd/mynode/bitcoin/.cookie` is missing for some reason.

**Comment by tehelsper** [comment]
@abhiShandy That cookie file is different from the web cookie that controls logins. However, if the .cookie files does not exist other apps may have issues. Check your bitcoin log at startup to see if it is getting created or skipped and make sure "rpcpassword" is not listed in your bitcoin config if you customized it.

**Comment by abhiShandy** [comment]
I never changed the bitcoin configuration, so it's still a mystery why cookie creation was skipped. 

By adding the rpcuser and rpcpassword, I figured that my wallet database and few blocks were corrupt. It is probably due to the loose cable when I was moving the node without shutting it down. I am reindexing the blockchain.

**Comment by Jacksper13** [comment]
@tehelsper per your comment above this should be resolved - @imacfan can you confirm? @abhiShandy you still having the issue? Specter and mynode have had multiple updates since Aug 2020, I would close this issue

**Comment by imacfan** [comment]
Yes .. it is resolved > @tehelsper per your comment above this should be resolved - @imacfan can you confirm? @abhiShandy you still having the issue? Specter and mynode have had multiple updates since Aug 2020, I would close this issue

**Comment by abhiShandy** [comment]
I don't face this issue anymore

**Comment by tehelsper** [comment]
Thanks for responding! I closed it.
