### ISSUE TITLE
Dojo: CPU utilisation is very high

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#374]
1. On virtual box with 2vCPU and 5 GB RAM
2. With Dojo Enabled CPU utilisation remains between 85-90%, when other tasks are not running.
3. After I disable Dojo CPU utilisations falls back to 3-4%
4. I have tried this multiple times , it seems Dojo utilises too much CPU capacity 

Please confirm, if this is known issue or not. Or there is something else that might be causing this issue of high CPU utilisation

**Comment by tehelsper** [comment]
I have not noticed this. When Dojo is enabled, can you open glances or run "htop" in the Linux terminal to determine which process is using most of the CPU?

**Comment by imacfan** [comment]
Strange , "htop" shows quite low usage as well. On the home page UI it was higher for some time, now it seems resolved as well
