### ISSUE TITLE
myNode VM grub_calloc not found grub rescue. Updated to latest resale, now I can't boot. 

### ISSUE THREAD

**Issue by corbimos** [mynodebtc/mynode#377]
I'm running myNode trough Oracle VM on Windows 10. Just updated and now the machine wont boot.

Error: symbol 'grub_calloc' not found.
entering rescue mode...
grub rescue> ls
(hd0) (hd0,msdos5) (hdo,msdos1) (hd1)

the only fix i found googling says to set the boot drive and run insmod normal, but that just gives me the grub_calloc not found error again. 

Anyone else run into this and fix it?

Can I install the VM again but keep my blockchain and other data?

Any help is appreciated.

**Comment by tehelsper** [comment]
See this issue for a resolution. It has been closed, but still has useful info.

https://github.com/mynodebtc/mynode/issues/371
