### ISSUE TITLE
False upgrade warning

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#38]
I entered into settings and it appear the button upgrade even if the upgrade doesn't exists ( i don't see any new tag into github). No version number of latest version and blank windows about recent changes.

![error](https://user-images.githubusercontent.com/16525337/68042490-5112db00-fcd3-11e9-8e08-1ad596ee4b4b.jpg)

**Comment by tehelsper** [comment]
Fix coming in 0.1.62

**Comment by Amiga500** [comment]
no more appeared
