### ISSUE TITLE
Lightning Wallet Generates INVALID BIP39 Mnemonic Seed

### ISSUE THREAD

**Issue by salenjak** [mynodebtc/mynode#380]
Hi,

First, I want to mention that I have performed a next text: deleting of Lightning Wallet with some on-chain balance and then restoring it with BIP39 Mnemonic Seed generated by MyNode. This works OK if you restore it via MyNode LND, but none of the other wallets( tried with Electrum desktop version, Samourai Wallet) doesn't load the right wallet.

There is some incompatibility problem with the way that Mynode generates BIP39 Mnemonic.

For example this is screenshot of http://mynode.local/lnd/create_wallet   
page (don't worry, I didn't created a wallet with seed from screenshot):
![mynode-create-seed](https://user-images.githubusercontent.com/61781250/89269832-bf0d7980-d63a-11ea-9417-31121eb144ed.png)

And when I test the BIP39 Mnemonic generated by MyNode on https://iancoleman.io/bip39/ page it gives Invalid mnemonic warning.
![invalid-mnemonic](https://user-images.githubusercontent.com/61781250/89269878-cfbdef80-d63a-11ea-8747-2840c3b976a4.png)

I belive that this is something that needs to be fixed because You can't pull on-chain BTC from Mynode to external wallet if your Mynode stops to work.
Also, if you already have some on-chain BTC on external wallet, and want to restore it in Mynode LND, MyNode gives errors that it can't restore a wallet with those IP39 Mnemonic.

**Comment by tehelsper** [comment]
Not a bug. LND uses Aezeed for its seed phrase.

If you make a new wallet, you can transfer funds to a newly generated address. It it NOT recommended to store large amount of funds on your myNode device. Think of it like cash in a wallet and not funds in a savings account.

https://github.com/lightningnetwork/lnd/tree/master/aezeed
