### ISSUE TITLE
Machine hanging after initializing install of Dojo

### ISSUE THREAD

**Issue by gaetawoo** [mynodebtc/mynode#386]
myNode 0.2.13 on VM
I clicked Install on Dojo, and after beginning, the myNode started a reboot, but it was stalled in the reboot:
![image](https://user-images.githubusercontent.com/5017089/89746575-803b5180-da88-11ea-8e08-92e5e829fe60.png)
It is stuck at the "A stop job is running for Advanced key-value store (4min 34s / no limit). Seems like there should rightly be a limit on this or it'll never automatically reboot. I'll have to go into the	VM itself and force a power cycle.

**Comment by tehelsper** [comment]
What did you execute to see that output? That appears to be the redis service. Did it ever reboot?

**Comment by gaetawoo** [comment]
All I did was click on Install for Dojo, then on the VM that myNode is running on, myNode installation process initiated a reboot and that is displayed in the VM. No it never rebooted. I had to manually restart it.

**Comment by tehelsper** [comment]
Is it reproducible if you initiate another reboot?

**Comment by gaetawoo** [comment]
I can try but it's not likely. This happens rarely and I haven't seen a pattern

**Comment by tehelsper** [comment]
How long did you wait? It likely would have rebooted eventually. Some services have built-in timeouts of 10-15 minutes if they are not stopping.

**Comment by gaetawoo** [comment]
Next time I see it I'll wait 15 minutes. I figured it wouldn't shut down since it said no limit

**Comment by Jacksper13** [comment]
@tehelsper Dojo and mynode have been updated several times since mynode v0.2.13, suggested close
