### ISSUE TITLE
Feature suggestion, Disable optional services on first launch when 2gb hardware is detected.

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#389]
I'd start with only bitcoind and the few near zero ram usage app enabled if less than 3gb is detected

**Comment by abhiShandy** [comment]
That's a nice idea.

On my rock64 with 2GB ram, the top three apps by memory usage are
- bitcoin: 554 MB
- electrs: 118 MB
- lnd: 75 M
- total ~750MB

I would recommend to include these three in the **minimalist** version and save the rest for full version.

**Comment by tehelsper** [comment]
This has already been implemented for all hardware. Bitcoin is the only service that runs by default. What am I missing?

Netdata and lnd also run as well, but netdata can be disabled on the settings page and can be helpful for watching resource usage regarding bitcoin sync. Lnd is enabled as well, but does not start until bitcoin is synced and basically uses zero resources until a wallet is created.

**Comment by abhiShandy** [comment]
I think he meant to suggest hiding other heavy apps (like btcpay server, whirlpool) if the RAM is not large enough

**Comment by tehelsper** [comment]
Ah, that could be the case. Yeah, I've thought about that some, but I didn't want to make that choice for people. For example, whirlpool may work, but running Dojo and Mempoolspace would be impossible. Either one at a time may run OK, just slowly.

I decided to start shipping and recommending all devices be 4GB+ in March and decided not to limit it in software.

In fact, I do a lot of my testing on a RP4 with only 2GB RAM and it works really well. However, I don't run Dojo or Mempool on that device.

**Comment by Jacksper13** [comment]
@tehelsper I understand this is resolved? Unless you plan on graying out options or planting alert messages saying "You do not have enough RAM to enable this app, enable at your own risk" or similar, I suggest this issue is closed

**Comment by tehelsper** [comment]
Closing - very few people use 2GB anymore and a feature to scale bitcoin memory based on RAM usage was added to help as well.
