### ISSUE TITLE
Unable to sweep all founds with RTL - "decoded address is of unknown format"

### ISSUE THREAD

**Issue by webdiverblue** [mynodebtc/mynode#390]
![Screenshot from 2020-08-11 21-36-27](https://user-images.githubusercontent.com/64732472/89941421-e8b63a00-dc12-11ea-9360-09674b34752b.png)

Hi,

i would like to send all founds onchain from one mynode to an other mynode via RTL "sweep all" function
but it doesn't matter weather i use adress type P2SH (NP2WKH) or Bech32 (P2WKH) generated by RTL on the new mynode
the response is always:

"decoded address is of unknown format"

Is that an known error?

**Comment by tehelsper** [comment]
You would probably get a better response filing this over at https://github.com/Ride-The-Lightning/RTL
