### ISSUE TITLE
Issue upgrading to 0.2.14

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#394]
When I upgrade to most recent version. Mynode starts upgrading then after reboot stuck at 

"site can't be reached. 
localhost refused to connect"

Rebooted again and still the same issue. 

![IMG_2977](https://user-images.githubusercontent.com/54225190/90329129-92a11800-dfbf-11ea-9a9d-0039e8149c99.jpg)

**Comment by abhiShandy** [comment]
Were you upgrading from CLI or GUI? If CLI, did you see any error message?

**Comment by imacfan** [comment]
> Were you upgrading from CLI or GUI? If CLI, did you see any error message?

I was upgrading from GUI.. now got the backup VDI  file for VirtualBox(i created as backup before upgrading)..replaced the stuck one with backup VDI
Started VM from VirtualBox again
Disabled force HTTS in settings GUI
running the upgrade again, its been > 2 hours and still showing "Upgrading screen". Anyway to check if it is still in progress?

**Comment by abhiShandy** [comment]
Close that update window, and check the home page every 10 minutes.

**Comment by imacfan** [comment]
> Close that update window, and check the home page every 10 minutes.

Seems not upgrading: 
**It appears a recent upgrade may not have fully completed.**

This is what I got in upgrade logs:

===========================================================
=== Upgrade Attempt #1
===========================================================


/usr/share/mynode/mynode_config.sh: line 12: /proc/device-tree/model: No such file or directory
Linux mynode 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
+ set -e
+ date
Sun 16 Aug 2020 02:53:24 AM CDT
+ /usr/bin/mynode_stop_critical_services.sh
Stopping myNode services...
Warning: The unit file, source configuration file or drop-ins of glances.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of lndhub.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of netdata.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of rtl.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of webssh2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of dojo.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of btc_rpc_explorer.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of specter.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of thunderhub.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Dojo is already stopped.
Warning: The unit file, source configuration file or drop-ins of electrs.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of loopd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of lnd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of quicksync.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of bitcoind.service changed on disk. Run 'systemctl daemon-reload' to reload units.
+ rm -rf /var/log/alternatives.log /var/log/apt /var/log/auth.log /var/log/auth.log.1 /var/log/auth.log.2 /var/log/bitcoind.log /var/log/bitcoind.log.1 /var/log/bitcoind.log.2 /var/log/boot.log /var/log/btmp /var/log/btmp.1 /var/log/caravan.log /var/log/caravan.log.1 /var/log/caravan.log.2 /var/log/daemon.log /var/log/daemon.log.1 /var/log/daemon.log.2 /var/log/debug /var/log/debug.1 /var/log/debug.2 /var/log/dpkg.log /var/log/dpkg.log.1 /var/log/electrs.log /var/log/electrs.log.1 /var/log/electrs.log.2 /var/log/fail2ban.log /var/log/fail2ban.log.1 /var/log/fail2ban.log.1.gz-2020081608.backup /var/log/fail2ban.log.3.gz /var/log/fail2ban.log.4.gz /var/log/flask /var/log/flask.1 /var/log/flask.2 /var/log/kern.log /var/log/kern.log.1 /var/log/kern.log.2 /var/log/lastlog /var/log/lightdm /var/log/lnd_backup.log /var/log/lnd_backup.log.1 /var/log/lnd_backup.log.2 /var/log/lndconnect.log /var/log/lndhub.log /var/log/lnd.log /var/log/lnd.log.1 /var/log/lnd.log.2 /var/log/loopd.log /var/log/loopd.log.1 /var/log/loopd.log.2 /var/log/messages /var/log/messages.1 /var/log/messages.2 /var/log/mynode_docker_images.log /var/log/mynode_docker_images.log.1 /var/log/mynode_docker_images.log.2 /var/log/mynode.log /var/log/mynode.log.1 /var/log/mynode.log.2 /var/log/mynode_quicksync.log /var/log/mynode_quicksync.log.1 /var/log/mynode_quicksync.log.2 /var/log/openvpn.log /var/log/openvpn.log.1 /var/log/openvpn.log.2.gz /var/log/openvpn.log.3.gz /var/log/openvpn-status.log /var/log/private /var/log/rtl.log /var/log/rtl.log.1 /var/log/rtl.log.2 /var/log/syslog /var/log/syslog.1 /var/log/syslog.2 /var/log/ufw.log /var/log/ufw.log.1 /var/log/ufw.log.1.gz-2020081608.backup /var/log/ufw.log.3.gz /var/log/ufw.log.4.gz /var/log/unlock_lnd.log /var/log/unlock_lnd.log.1 /var/log/unlock_lnd.log.2 /var/log/user.log /var/log/user.log.1 /var/log/user.log.2 /var/log/wtmp /var/log/www.log /var/log/www.log.1 /var/log/www.log.2 /var/log/Xorg.0.log /var/log/Xorg.0.log.old
+ mkdir -p /var/log/nginx
+ TORIFY=
+ '[' -f /mnt/hdd/mynode/settings/torify_apt_get ']'
+ systemctl stop https
Warning: The unit file, source configuration file or drop-ins of https.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Info

**Comment by imacfan** [comment]
Tried 2 - 3 times. Seems upgraded now.

**Comment by RolfHodl** [comment]
Got the same issue as by upgrading from 0.2.12-to 0.2.13 like now with 0.2.13-0.2.14 like in here https://github.com/mynodebtc/mynode/issues/371

**Comment by Bosch-0** [comment]
Same issue from 0.2.13 to 0.2.14

**Comment by tehelsper** [comment]
Going to v0.2.14 was a big update and upgrades are marked as failed and stop if any single command fails at any point. It might takes a couple tries to reinstall or you can wait for the next SD card image.

I just made a new Rock64 image.

Sorry for the inconvenience.

**Comment by Satsurday** [comment]
I got the exact same issue as OP. I'm on my 4th or 5th reinstall of the upgrade. It's been like 3 days of trying to upgrade now. Once the upgrade screen is done, it says it's attempting launch mynode and then just never proceeds. I can go into the status/settings page and see that the upgrade failed and have the option to restart the upgrade all over again and repeat the loop. I get the same error Upgrade Attempt summary above.

Anyone know if there's a better solution than to randomly stumble upon a successful upgrade?

**Comment by abhiShandy** [comment]
Try upgrading manually from SSH terminal, like the community edition.

**Comment by tehelsper** [comment]
@Satsurday What does the myNode Startup Log show?

**Comment by ethhodler** [comment]
Same issue here. I'm working with the virtual version and after the upgrade the vm keeps showing this error code at startup:
error: symbol 'grub_calloc' not found. Entering rescue mode...

**Comment by tehelsper** [comment]
@btchodler Your issue is https://github.com/mynodebtc/mynode/issues/371 and can be solved.

For others, try upgrading when using HTTP and not HTTPS. The conversion from gunicorn to nginx may be interfering with the upgrade process.

**Comment by Satsurday** [comment]
i tried to re-flash and upgrade. No luck. Still the same error.
any other suggestions? 

=== Upgrade Attempt #1
===========================================================


+ set -e
+ date
Thu 20 Aug 19:03:28 CDT 2020
+ /usr/bin/mynode_stop_critical_services.sh
Stopping myNode services...
Warning: The unit file, source configuration file or drop-ins of glances.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of rtl.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of webssh2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of btc_rpc_explorer.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of thunderhub.service changed on disk. Run 'systemctl daemon-reload' to reload units.
/usr/bin/mynode_stop_critical_services.sh: line 27: /opt/mynode/dojo/docker/my-dojo/dojo.sh: No such file or directory
Warning: The unit file, source configuration file or drop-ins of electrs.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of loopd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of lnd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of quicksync.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Warning: The unit file, source configuration file or drop-ins of bitcoind.service changed on disk. Run 'systemctl daemon-reload' to reload units.
+ rm -rf /var/log/alternatives.log /var/log/apt /var/log/auth.log /var/log/auth.log.1 /var/log/auth.log.2 /var/log/bitcoind.log /var/log/bitcoind.log.1 /var/log/boot.log /var/log/bootstrap.log /var/log/btmp /var/log/btmp.1 /var/log/daemon.log /var/log/daemon.log.1 /var/log/daemon.log.2 /var/log/debug /var/log/debug.1 /var/log/debug.2 /var/log/dpkg.log /var/log/dpkg.log.1 /var/log/dpkg.log.2.gz /var/log/electrs.log /var/log/electrs.log.1 /var/log/fail2ban.log /var/log/fail2ban.log.1 /var/log/faillog /var/log/flask /var/log/fontconfig.log /var/log/gunicorn /var/log/kern.log /var/log/kern.log.1 /var/log/kern.log.2 /var/log/lastlog /var/log/lnd_backup.log /var/log/lnd_backup.log.1 /var/log/lndconnect.log /var/log/lnd.log /var/log/lnd.log.1 /var/log/log2ram.log /var/log/loopd.log /var/log/loopd.log.1 /var/log/messages /var/log/messages.1 /var/log/messages.2 /var/log/mynode_docker_images.log /var/log/mynode_docker_images.log.1 /var/log/mynode.log /var/log/mynode.log.1 /var/log/mynode_quicksync.log /var/log/mynode_quicksync.log.1 /var/log/private /var/log/redis /var/log/rtl.log /var/log/rtl.log.1 /var/log/syslog /var/log/syslog.1 /var/log/syslog.2 /var/log/sysstat /var/log/tor /var/log/ufw.log /var/log/unlock_lnd.log /var/log/unlock_lnd.log.1 /var/log/user.log /var/log/user.log.1 /var/log/user.log.2 /var/log/wtmp /var/log/www.log /var/log/www.log.1
+ mkdir -p /var/log/nginx
+ TORIFY=
+ '[' -f /mnt/hdd/mynode/settings/torify_apt_get ']'
+ TORIFY=torify
+ systemctl stop https
Warning: The unit file, source configuration file or drop-ins of https.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by tehelsper** [comment]
@Satsurday See above comment. Did you use HTTP or HTTPS? Have you tried via the Linux terminal?

**Comment by Satsurday** [comment]
If I used HTTPS i encounter the web browser image "site can't be reached". If I used HTTP, I can log in, it'll say its "Launching" mynode. Never actually launches. I check settings and status and its still failed. I don't have linux. I use windows. Should I follow this: https://www.reddit.com/r/mynodebtc/comments/e4jscx/faq_how_to_update_mynode_community_edition/

**Comment by imacfan** [comment]
> For anyone having trouble with the VM, I did make a new image for v0.2.14 so you won't have to upgrade near as far.
> 
> http://mynodebtc.com/download

Seems some issue with ova file... missing second disk? On first boot it keeps formatting drive

**Comment by Satsurday** [comment]
Problem solved gents. No idea how. Now on to 0.2.15. Wish me luck.

**Comment by tehelsper** [comment]
@imacfan That is a display bug. You need to add a 2nd drive that it can use for storage. The formatting message is false and its not actually doing anything.

@Satsurday Good to hear!

**Comment by imacfan** [comment]
> @imacfan That is a display bug. You need to add a 2nd drive that it can use for storage. The formatting message is false and its not actually doing anything.
> 
> @Satsurday Good to hear!
Stuck here .. nothing seems to be happening. Had to create VDI file in VirtualBox and attached it. Still same screen. This was not the case with the earlier OVA file
![image](https://user-images.githubusercontent.com/54225190/91122407-e5618a80-e6b7-11ea-91a6-c683204e00a1.png)

**Comment by RolfHodl** [comment]
> For anyone having trouble with the VM, I did make a new image for v0.2.14 so you won't have to upgrade near as far.
> 
> http://mynodebtc.com/download

Is this version now compatible with VMware esxi?

**Comment by tehelsper** [comment]
Try the latest OVA file if you are having issues. It automatically includes a data drive now.

**Comment by Jacksper13** [comment]
Close issue since there's a 0.2.21 image available to download now?

**Comment by Jacksper13** [comment]
@tehelsper I'd close this - resolved 16 versions ago
