### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by auldsyababua** [mynodebtc/mynode#396]
Hi all, 

Firefox is still flagging this mynode.local as unsecure. 

Wondering if Firefox is wrong or if there is actually an issue here:

<img width="420" alt="Screen Shot 2020-08-17 at 7 53 27 PM" src="https://user-images.githubusercontent.com/18078607/90465170-a9309780-e0c3-11ea-8776-a9db73406874.png">
<img width="422" alt="Screen Shot 2020-08-17 at 7 54 51 PM" src="https://user-images.githubusercontent.com/18078607/90465173-a9c92e00-e0c3-11ea-8175-33010bfbdb0f.png">

**Comment by tehelsper** [comment]
Browsers will almost always flag self signed certificates as insecure. Self-signed certs are still more secure than HTTP.

**Comment by auldsyababua** [comment]
thanks
