### ISSUE TITLE
Bitcoin has experienced an error

### ISSUE THREAD

**Issue by auldsyababua** [mynodebtc/mynode#399]
Im seeing this issue after trying to set up whirlpool

I was told that i needed to connect a drive to my node. So i disconnected everything to try and remount, then i got this: "Bitcoin has experienced an error. Please check the logs."

I checked the logs and i am happy to share them here but don't know if the logs would expose any information i wouldn't want public.

Please advise.

**Comment by tehelsper** [comment]
That typically means that the bitcoin blockchain data was corrupt. You may need to reset your blockchain data or re-index via the options on the settings page.

**Comment by outpoints** [comment]
How did you fix this? @auldsyababua

**Comment by auldsyababua** [comment]
It seems this error message does not mean much and your node should continue to work as normal. I just rebooted the raspi, and waited for it to fetch the missing blocks. After that, I got the error again, but just exited it and everything seems to be working ok now.

**Comment by tehelsper** [comment]
Well, bitcoind will automatically restart after a while and try again. I _could_ eventually resolve itself, but that is rare, which is why it is so important to look at the bitcoind log and see what is going on.
