### ISSUE TITLE
New v2.14 VBox .ova does not include disk2/mynode00002.vmdk

### ISSUE THREAD

**Issue by davterra** [mynodebtc/mynode#402]
The title pretty much says it all. Someone complained in the Premium TG group about this, so I downloaded and imported it and can replicate his result. No disk 2 file.

**Comment by tehelsper** [comment]
That was intentional so users can add their own disk 2 with the size they want so it fits on their drive. However, it is an issue that the status screen says formatting, when in reality it is not formatting anything.

For example, a user may want to use a 750GB drive because they know they will not use electrum server or they may want to add a 2TB drive to really future-proof their storage needs.

**Comment by davterra** [comment]
> That was intentional so users can add their own disk 2 with the size they want so it fits on their drive. However, it is an issue that the status screen says formatting, when in reality it is not formatting anything until a 2nd drive is added.
> 
> For example, a user may want to use a 750GB drive because they know they will not use electrum server or they may want to add a 2TB drive to really future-proof their storage needs.

Oh, OK...so I can take any drive I choose and just attach it...using any name I choose?

**Comment by tehelsper** [comment]
Yeah, well with a VM you would typically create a virtual drive with any name and size you like and you can "store" that drive on whatever physical drive you prefer.

**Comment by imacfan** [comment]
> Yeah, well with a VM you would typically create a virtual drive with any name and size you like and you can "store" that drive on whatever physical drive you prefer.

Attached new VDI in VirtualBox... don't see any movement. 

Through command line I tried navigate to mynode "Got no such file or directory"
cd: /hdd/mnt/mynode: No such file or directory

Are there any other steps which I am missing after attaching the drive?

**Comment by imacfan** [comment]
> > Yeah, well with a VM you would typically create a virtual drive with any name and size you like and you can "store" that drive on whatever physical drive you prefer.
> 
> Attached new VDI in VirtualBox... don't see any movement.
> 
> Through command line I tried navigate to mynode "Got no such file or directory"
> cd: /hdd/mnt/mynode: No such file or directory
> 
> Are there any other steps which I am missing after attaching the drive?

Ignore for now.. seems after 2-3 reboots and clicking "Format"..it seems to be working. I see growing size of the attached drive

**Comment by davterra** [comment]
> Yeah, well with a VM you would typically create a virtual drive with any name and size you like and you can "store" that drive on whatever physical drive you prefer.

Oh sure. I understand. I like this change. Will try to build out Virtualbox docs in the new repo and include this, ASAP.
I'll close this issue.
Thank you.

**Comment by gaetawoo** [comment]
@davterra did you get a chance to update the document somewhere about this? I just tried to run a new VM with this version and had no idea this what the reason Drive Formatting seemed to do nothing. Bad ux. (Not your fault of course)

**Comment by tehelsper** [comment]
The "formatting" UI issue has been resolved if you update to the latest version. New VM images have not been been made yet.

**Comment by gaetawoo** [comment]
In what way has it been fixed? It would still require one to add a new vdi to the VM right?

**Comment by tehelsper** [comment]
The "formatting" issue was resolved - it would properly say "looking for drive".

However, requiring users to add their own drive for better flexibility seemed to confuse a number of people, so I've made a new image that automatically includes a 1TB drive.
