### ISSUE TITLE
Upgrade froze and left unfinished

### ISSUE THREAD

**Issue by PeterSurda** [mynodebtc/mynode#411]
**Describe the bug**
I upgraded from 0.2.11 to 0.2.15. Something caused apt to freeze and the system was then left in an unfinished state, which required me to clean up manually. There was no indication of a problem shown in the web interface. However my electrum client stopped connecting and I only spotted it a couple of days later. I had to replace the redis.service file (the debian one for the mynode one), and `apt install nginx` (and remove some excessive files from default nginx installation). Now it seems to work ok.

It may be that for some reason during the upgrade the redis.service file wasn't replaced, and then `systemctl redis restart` froze and prevented the upgrade from finishing. 

**Expected behavior**
Either there should be some sort of error report, or it should resolve things automatically.

**Desktop (please complete the following information):**
 - current firefox

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version: 0.2.15 (previously 0.2.11)

**Additional context**
Not sure what else may be broken. I only noticed redis (that was stalling) and nginx (no TLS proxy).

**Comment by AllienWorks** [comment]
I'm on Raspi4 as well, upgrading from 0.2.06 to 0.2.16 manually and yes, even for me the upgrade got stuck at
```
Setting up redis-server (5:5.0.3-4+deb10u2) ...
```
during the system update.

**Comment by tehelsper** [comment]
Should be fixed in the latest release. Try re-trying the upgrade now that the redis service file should be overridden.

**Comment by AllienWorks** [comment]
> Should be fixed in the latest release. Try re-trying the upgrade now that the redis service file should be overridden.

I'm running into the same issue in 0.2.16. Just tried 2× since I last commented.

**Comment by tehelsper** [comment]
Did that happen during an "apt-get upgrade"? If you run "sudo apt list --installed | grep redis" what version does it show currently?

I am running the version you listed, so there must have been an upgrade at some point.

Another option - try running:

sudo apt-mark hold redis-server

That should prevent it from upgrading which may avoid the lockup.

**Comment by Jacksper13** [comment]
@tehelsper updated image for download - suggested close

**Comment by tehelsper** [comment]
Updates to redis-server are now also held back and don't auto-update.
