### ISSUE TITLE
update manually from 2.15 to 2.16

### ISSUE THREAD

**Issue by kilocrypto1** [mynodebtc/mynode#414]
I try to update version 2.15 to 2.16 but everytime i get this error from putty
![image](https://user-images.githubusercontent.com/70512698/92971838-7d65bf00-f481-11ea-9b3f-28196a245ee7.png)

i tried it several times now...I have no programma or command line skill at all so i don't know what to do... 

It keeps giving this message at the when it comes to the TOR part..
![image](https://user-images.githubusercontent.com/70512698/92971973-b7cf5c00-f481-11ea-8efa-e9b85db63b9e.png)

How can i fix this issue and can i still use mynode or did "the half updating" changed things in mynode?

Many thanks!

**Comment by tehelsper** [comment]
What is not working? Running that command will reboot your device which will cause the SSH session to drop.

**Comment by kilocrypto1** [comment]
When i try to update to 2.16  putty disconnects and the install stops as shown in the screenshot... So i can not update to 2.16...

because i can not give any more command and nothing happens

**Comment by tehelsper** [comment]
Let's take a step back.

- What command did you execute?
- What behavior do you expect?
- What version are you currently running (reported on status or settings page)?
- What function or service is not working properly?

That script is expected to reboot the device as shown in the image. The "sync" command is the last command before the device reboots.

**Comment by kilocrypto1** [comment]
I use the walkthrough that is on the mynode.com website.  
I use putty so i put in the following commands:

**Comment by tehelsper** [comment]
Please log in and check the version that you are currently running. That looks like everything worked fine.

**Comment by kilocrypto1** [comment]
still 2.15

**Comment by tehelsper** [comment]
Interesting. I would try to re-flash the SD card with the latest v0.2.16 image.

**Comment by kilocrypto1** [comment]
i tried to update to the new 2.17. but got the same error....putty server gave the same error... so putty network closed the network connection.... and i still am on 2.15..... what do i need to do to reflash the SD card.... Can i take it out of the raspi? or do i need to turn the rapsi off first? and to i lose any thing ( lightning channel balances? or other thing) when i do that?

many thanx

**Comment by tehelsper** [comment]
Yeah, turn off the raspi, take the sd card out, and flash with the 0.2.16 image. Nothing will be lost but your password goes back to bolt.

**Comment by Jacksper13** [comment]
Image 0.2.21 available, close issue?

**Comment by Jacksper13** [comment]
@tehelsper new image for download - I'd close
