### ISSUE TITLE
some backup enhancements

### ISSUE THREAD

**Issue by haukehess** [mynodebtc/mynode#42]
1. The file channel.backup is kept on the harddisk only. I would prefer it to be copied to the local sd card from time to time. Or somewhere else (network mounted disk?) optional. This would prevent fund loss on disk failure (and I had some of them before using raspi4, maybe this is over but I'm only a few days in).

2. there are some very good resources on the topic: recovering with seed+backup.channel, and even on recovering off-chain funds with electrum. I received the following via instagram: 

The on-chain funds are on a default BIP84 derivation path (m/84'/0'/0'/x/y)
The aezeed you can decode with my tool:

https://guggero.github.io/cryptography-toolkit/#!/aezeed

There‘s an offline version that you can use on an offline computer for mainnet seeds
 Ah, and the derivation path depends on the address type. 84 is for bech32, 49 is for nested segwit addresses

Maybe this could make it into the "guides" section of mynodebtc.com in some form, so 
others won't rely on telegram and socialising skills (that might go mute when hardware failure just happened and serious fund loss is on the users mind)

**Comment by tehelsper** [comment]
Your first request is already done. ;-)

There is a service that runs and checks to see when the file changes and copies it to the SD card. The file is located at /home/bitcoin/lnd_backup/channel.backup and is the file that is downloaded when you download it via the link in the GUI.

Yeah, that would be a good guide, but luckily no one has needed it yet and there are other resources.

**Comment by tehelsper** [comment]
Added GUI option to restore seed + SCB.
