### ISSUE TITLE
LND GUI stuck on "waiting" for 24+hr

### ISSUE THREAD

**Issue by mgalenb** [mynodebtc/mynode#420]
**Describe the bug**
The LND indicator on the home page seems to be stuck on waiting (has been for 24+hrs). Note i modified the mynode code a bit so i could install on a hardkernel odroid hc2. bitcoin starts up and syncs fine. did txindex=1 fine. lnd starts up and the logs seem to indicate it is synced.

**Expected behavior**
I have created a wallet seed phrase but cant do anything past that. All other lightning apps are also in the waiting mode.

**Screenshots**
Here is the home screen:
![Screen Shot 2020-09-29 at 12 27 52 PM](https://user-images.githubusercontent.com/6004917/94606381-3a606580-024f-11eb-8c8f-0a7bf69aa3e1.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 85

**MyNode hardware (please complete the following information):**
 - Device: Hardkernel Odroid HC2 (XU4)
 - Version 2.16

**Additional context**
As noted earlier i modified the setup_service.sh script a bit so i could install on odroid HC2 (ARM architeture). repo at https://github.com/mgalenb/mynode.git

Both the LND and bitcoin logs seem to indicate everything is fine

LND log:
-- Logs begin at Tue 2020-09-29 01:10:31 PDT, end at Tue 2020-09-29 12:23:26 PDT. --
Sep 29 12:23:19 myNode lnd[4751]: 2020-09-29 12:23:19.756 [INF] DISC: Broadcasting 66 new announcements in 7 sub batches
Sep 29 12:23:11 myNode lnd[4751]: 2020-09-29 12:23:11.152 [INF] CRTR: Processed channels=0 updates=16 nodes=9 in last 59.999573998s
Sep 29 12:22:11 myNode lnd[4751]: 2020-09-29 12:22:11.152 [INF] CRTR: Processed channels=0 updates=41 nodes=0 in last 59.999643383s
Sep 29 12:21:49 myNode lnd[4751]: 2020-09-29 12:21:49.756 [INF] DISC: Broadcasting 64 new announcements in 7 sub batches
Sep 29 12:21:11 myNode lnd[4751]: 2020-09-29 12:21:11.152 [INF] CRTR: Processed channels=0 updates=60 nodes=4 in last 59.999485268s
Sep 29 12:20:19 myNode lnd[4751]: 2020-09-29 12:20:19.756 [INF] DISC: Broadcasting 57 new announcements in 6 sub batches
...

**Comment by jscoltock** [comment]
Was this ever resolved?  I'm having the same issue.

**Comment by tehelsper** [comment]
Try these steps:
- Upgrade to latest revision
- Check the lnd log on the status page

Stuck at "logging in" can be due to several issues - corruption, network issues, etc...

**Comment by btcb0b** [comment]
I get this error in LND, it's running:

Jun 27 19:25:28 myNode lnd[10646]: 2021-06-27 19:25:28.632 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access

I SSH'd and tried lncli unlock and got this after inputting the password:

Input wallet password:
[lncli] rpc error: code = Unknown desc = invalid passphrase for master public key

This is the start of my lnd hub log file:

- Logs begin at Sun 2021-06-27 15:35:28 CDT, end at Sun 2021-06-27 19:26:53 CDT. --
Jun 27 19:26:40 myNode systemd[1]: lndhub.service: Failed with result 'exit-code'.
Jun 27 19:26:40 myNode systemd[1]: lndhub.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 27 19:26:40 myNode lndhub[26245]: npm ERR!     /home/bitcoin/.npm/_logs/2021-06-28T00_26_40_304Z-debug.log
Jun 27 19:26:40 myNode lndhub[26245]: npm ERR! A complete log of this run can be found in:
Jun 27 19:26:40 myNode lndhub[26245]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 27 19:26:40 myNode lndhub[26245]: npm ERR! Failed at the lndhub@1.3.5 start script.

Any ideas on this? I've done a reboot and a complete shutdown

**Comment by tehelsper** [comment]
LND Hub is different than LND and it won't load until LND does. What does your Lightning log show?

**Comment by btcb0b** [comment]
I got on Telegram and found the pinned tweet, went to Twitter and added the line to the config at the end, then got advice to add it in the Applications Option section and now it's running fine.

All 14 of my channels show inactive though, stopped my heart when I saw zero balance in my channels, I guess they'll all come back online eventually?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tehelsper** [comment]
Closing this issue. New issue causes same symptoms and is resolved.

**Comment by btcb0b** [comment]
Hi Taylor,

I moved and plugged in my node to the router in place at the house. I logged into the router and found the range of IP addresses it uses and used Angry IP to scan the range - I tried each of the live IP addresses (with https, that is correct?)

I'm unable to find the login for my node- do you have any suggestions on what to try?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tehelsper** [comment]
Try starting with this guide and feel free to log a support ticket for more info.

https://mynodebtc.github.io/troubleshooting/device-not-booting.html

https://mynodebtc.com/support

**Comment by btcb0b** [comment]
Thanks! I tried a million things except turning it off and turning it on again. I'm able to login now

Cheers,

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
