### ISSUE TITLE
Tweaks to UI presented on twitter

### ISSUE THREAD

**Issue by pedromvpg** [mynodebtc/mynode#422]
Proposing a couple of tweaks to the restyling presented on twitter.
https://twitter.com/mynodebtc/status/1310802886981570561/photo/1

- Button alignment on white tiles
- Padding
- Table styling
- Gutter width

![Comparison](https://user-images.githubusercontent.com/807505/94944893-e603f280-04a7-11eb-9788-61de89203ed6.png)
![Changes](https://user-images.githubusercontent.com/807505/94945121-31b69c00-04a8-11eb-88c4-d0f7e2a19a8f.png)

**Comment by Amiga500** [comment]
Very good!

**Comment by Amiga500** [comment]
I add another thing i found. It miss a space into Lightning page. On Bitcoin Core is ok.

![11111](https://user-images.githubusercontent.com/16525337/94988923-1e233800-0571-11eb-9e2e-e85b9b5a3372.jpg)
![22222](https://user-images.githubusercontent.com/16525337/94988924-1fecfb80-0571-11eb-9122-d8f814549fcb.jpg)

**Comment by tehelsper** [comment]
Thanks. I think I've got the alignment fixed. I purposefully kept the buttons in place because I want to use the empty space for future enhancements.... Bitcoin button to show recent blocks, LN button to pop up deposit address, etc...

**Comment by Bosch-0** [comment]
Very nice!
