### ISSUE TITLE
it is not possible to disable quicksync, instead it starts from scratch

### ISSUE THREAD

**Issue by morrishanson** [mynodebtc/mynode#426]
I have a question regarding your great mynode software, which i am running on a raspberry pi 4.
i have downloaded the complete Quicksync Pre Validated Blockchain and after some time for syncing the rest, everything seemed to run, cause i got into the dashboard. The Bitcoin Sync was green and Running.
Then i pushed the button disable quicksync, cause i saw that recommendation in a youtube video. However, this took me some minutes and after the reboot quicksync was still enabled and the downloading process of the torrent started from scratch... 0,00%
i have no idea what happened here, but in the settings the option i had was again "Disable Quicksync".. then i tried it a second time with the same effect, waited some minutes and after the reboot the quicksync process was enabled and started at 0,00%

so i think there may be a bug in the actual release of myNode..

What should i do now?
Are the prevalidated files still on the hdd..?
how can i check that. 

i have also validated the complete blockchain with bitcoin core, so is there a possibility to transfer the files to the mynode hdd? if yes, in which directory and are there any command line tips to make that possilbe.

best wishes and i hope to hear from you soon.

**Comment by tehelsper** [comment]
Which version were you running? This issue should be resolved now.

**Comment by SatoshiNakamotogmx** [comment]
Will that work for the  1.0

**Comment by Jacksper13** [comment]
@morrishanson can you confirm this was resolved? Thanks!
