### ISSUE TITLE
Stop the LND while doing backup

### ISSUE THREAD

**Issue by jansiebert1** [mynodebtc/mynode#427]
When I did static channel backup of my lightning node I was not able to stop the lnd
'lncli stop' didn't do anything
and 'sudo systemctl stop lnd.service' stopped the service but it started it again after a minute.

There should be a way to make a back-up and stop the lightning node since the channel state can change between you make the back-up and, for example, upgrade your node or do some other potentially dangerous thing.

**Comment by jansiebert1** [comment]
From this (https://wiki.ion.radar.tech/tutorials/troubleshooting/static-channel-backups), I understand one does not have to maintain the latest channel state because the static channel backup package will attempt to notify remote peers to force close their channel. This will prevent users from accidentally broadcasting an old state and allow them to safely close out and receive their local balance.

**Comment by tehelsper** [comment]
To get the SCB file, you can download it via the UI on the LND or settings page. There is no need to stop LND.
