### ISSUE TITLE
Feature req - Ubuntu Mate 19.10 arm img for Blockstream satellite 

### ISSUE THREAD

**Issue by dawiepoolman** [mynodebtc/mynode#43]
as per title
That would be uber awesome

**Comment by tehelsper** [comment]
I'm not sure how this would tie into the existing myNode software. I could possible add the blockstream satellite CLI tool.

**Comment by tehelsper** [comment]
Aged out - satellite additions are still tentative

**Comment by U17R** [comment]
what is the status on using blockstream sat with mynodebtc ? possible or future?
