### ISSUE TITLE
Unable to open mempool

### ISSUE THREAD

**Issue by gongyj0948** [mynodebtc/mynode#431]
**Describe the bug**
When I open mempool, it can't load (see screenshot below). Always indicate **Offline**. 

So, I went to mempool's Github, enter the following commend in my node's CLI:
```
docker pull mempool/mempool:v1.0
docker create -p 80:80 -e BITCOIN_NODE_HOST=192.168.1.102 -e BITCOIN_NODE_USER=foo -e BITCOIN_NODE_PASS=bar --name mempool mempool/mempool:v1.0
docker start mempool
```
Then, here's what I got:
![Screen Shot 2020-10-21 at 10 55 43 AM](https://user-images.githubusercontent.com/29460794/96737817-15619d00-138c-11eb-9383-071318bb1cd0.png)

**Expected behavior**
Mempool is opened.

**Screenshots**
![Screen Shot 2020-10-21 at 10 46 59 AM](https://user-images.githubusercontent.com/29460794/96736653-cff0a000-138a-11eb-9df0-e02e0537b0ce.png)

**Desktop (please complete the following information):**
 - Browser [brave]
 - Version [1.15.75]

**MyNode hardware (please complete the following information):**
 - Device: [Raspi4]
 - Version [0.2.17]

**Additional context**

**Comment by Amiga500** [comment]
and I have this:
admin@myNode:~ $ docker start mempool
Error response from daemon: No such container: mempool
Error: failed to start containers: mempool
admin@myNode:~ $

on 0.2.17 Raspi4 google chrome

**Comment by calligrl** [comment]
I get the exact same thing, and it looks just the same as gongyj0948's screenshot.

myNode version: 0.2.17 in a VM.

I disabled and re-enabled mempool with no difference in behaviour.

There is no option to re-install mempool.

Mempool Staus: Running - Running Containers: 

Log:

-- Logs begin at Thu 2020-10-29 14:57:44 CDT, end at Thu 2020-10-29 15:39:37 CDT. --
Oct 29 15:39:25 mynode mempoolspace[31003]: Fetching block tx 45 of 2922
Oct 29 15:39:25 mynode mempoolspace[31003]: Fetching block tx 44 of 2922
Oct 29 15:39:18 mynode mempoolspace[31003]: Fetching block tx 43 of 2922
Oct 29 15:39:13 mynode mempoolspace[31003]: Fetching block tx 42 of 2922
Oct 29 15:39:10 mynode mempoolspace[31003]: Fetching block tx 41 of 2922
Oct 29 15:39:10 mynode mempoolspace[31003]: Fetching block tx 40 of 2922
Oct 29 15:39:10 mynode mempoolspace[31003]: Fetching block tx 39 of 2922
Oct 29 15:39:10 mynode mempoolspace[31003]: Fetching block tx 38 of 2922
Oct 29 15:39:09 mynode mempoolspace[31003]: Fetching block tx 37 of 2922
Oct 29 15:39:09 mynode mempoolspace[31003]: Fetching block tx 36 of 2922
Oct 29 15:39:01 mynode mempoolspace[31003]: Fetching block tx 35 of 2922
Oct 29 15:39:01 mynode mempoolspace[31003]: Fetching block tx 34 of 2922
Oct 29 15:39:01 mynode mempoolspace[31003]: Fetching block tx 33 of 2922
Oct 29 15:38:58 mynode mempoolspace[31003]: Fetching block tx 32 of 2922
Oct 29 15:38:58 mynode mempoolspace[31003]: Fetching block tx 31 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 30 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 29 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 28 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 27 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 26 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 25 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 24 of 2922
Oct 29 15:38:57 mynode mempoolspace[31003]: Fetching block tx 23 of 2922
Oct 29 15:38:54 mynode mempoolspace[31003]: Fetching block tx 22 of 2922
Oct 29 15:38:54 mynode mempoolspace[31003]: Fetching block tx 21 of 2922
Oct 29 15:38:54 mynode mempoolspace[31003]: Fetching block tx 20 of 2922
Oct 29 15:38:54 mynode mempoolspace[31003]: Fetching block tx 19 of 2922
Oct 29 15:38:54 mynode mempoolspace[31003]: Fetching block tx 18 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 17 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 16 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 15 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 14 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 13 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 12 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 11 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 10 of 2922
Oct 29 15:38:51 mynode mempoolspace[31003]: Fetching block tx 9 of 2922
Oct 29 15:38:45 mynode mempoolspace[31003]: Fetching block tx 8 of 2922
Oct 29 15:38:45 mynode mempoolspace[31003]: Fetching block tx 7 of 2922
Oct 29 15:38:45 mynode mempoolspace[31003]: Fetching block tx 6 of 2922
Oct 29 15:38:45 mynode mempoolspace[31003]: Fetching block tx 5 of 2922
Oct 29 15:38:45 mynode mempoolspace[31003]: Fetching block tx 4 of 2922
Oct 29 15:38:45 mynode mempoolspace[31003]: Fetching block tx 3 of 2922
Oct 29 15:38:44 mynode mempoolspace[31003]: Fetching block tx 2 of 2922
Oct 29 15:38:44 mynode mempoolspace[31003]: Fetching block tx 1 of 2922
Oct 29 15:38:29 mynode mempoolspace[31003]: }
Oct 29 15:38:29 mynode mempoolspace[31003]:   code: -32602
Oct 29 15:38:29 mynode mempoolspace[31003]:     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Oct 29 15:38:29 mynode mempoolspace[31003]:     at endReadableNT (_stream_readable.js:1185:12)
Oct 29 15:38:29 mynode mempoolspace[31003]:     at IncomingMessage.emit (events.js:228:7)
Oct 29 15:38:29 mynode mempoolspace[31003]:     at IncomingMessage.<anonymous> (/mempool.space/backend/node_modules/bitcoin/lib/jsonrpc.js:110:17)
Oct 29 15:38:29 mynode mempoolspace[31003]: getRawMempool error. Error: Invalid params, response status code: 500
Oct 29 15:38:29 mynode mempoolspace[31003]: Updating mempool
Oct 29 15:38:29 mynode mempoolspace[31003]: }
Oct 29 15:38:29 mynode mempoolspace[31003]:   code: -32602
Oct 29 15:38:29 mynode mempoolspace[31003]:     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Oct 29 15:38:29 mynode mempoolspace[31003]:     at endReadableNT (_stream_readable.js:1185:12)
Oct 29 15:38:29 mynode mempoolspace[31003]:     at IncomingMessage.emit (events.js:228:7)
Oct 29 15:38:29 mynode mempoolspace[31003]:     at IncomingMessage.<anonymous> (/mempool.space/backend/node_modules/bitcoin/lib/jsonrpc.js:110:17)
Oct 29 15:38:29 mynode mempoolspace[31003]: Error getMempoolInfo Error: Invalid params, response status code: 500
Oct 29 15:38:29 mynode mempoolspace[31003]: }

Then it repeats this part quite a lot:

}
Oct 29 15:38:29 mynode mempoolspace[31003]:   code: -32602
Oct 29 15:38:29 mynode mempoolspace[31003]:     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Oct 29 15:38:29 mynode mempoolspace[31003]:     at endReadableNT (_stream_readable.js:1185:12)
Oct 29 15:38:29 mynode mempoolspace[31003]:     at IncomingMessage.emit (events.js:228:7)
Oct 29 15:38:29 mynode mempoolspace[31003]:     at IncomingMessage.<anonymous> (/mempool.space/backend/node_modules/bitcoin/lib/jsonrpc.js:110:17)
Oct 29 15:38:29 mynode mempoolspace[31003]: Error getMempoolInfo Error: Invalid params, response status code: 500
Oct 29 15:38:29 mynode mempoolspace[31003]: }

**Comment by tehelsper** [comment]
How much RAM do you have? I have started seeing a similar issue on my RP4 with 2GB. I didn't see the exception, but I get repeated "Fetching block tx" messages. I'm running version 1.0.1 though.

Maybe @wiz has an idea?

**Comment by wiz** [comment]
I'm not sure about the v1 code since it's quite old, but considering you're all suddenly having issues when the mempool got larger I would assume it's running out of RAM somehow. It might be some specific RAM limit with the way mynode configures Docker?

**Comment by wiz** [comment]
From the logs it looks like the JSONRPC API is returning 500 - did Bitcoin Core crash?

**Comment by tehelsper** [comment]
I would also guess RAM, but mine is not crashing and mempool seems to be keeping up with blocks just fine. It just always says "offline" in the web ui.

```
Mempool updated in 2.246 seconds
Running statistics
Fetching block tx 982 of 2376
Fetching block tx 983 of 2376
New block found (#654715)! 2373 of 2376 found in mempool. 2 not found.
Updating mempool
Calculated fee for transaction 1
Calculated fee for transaction 2
Calculated fee for transaction 3
Calculated fee for transaction 4
Calculated fee for transaction 5
Calculated fee for transaction 6
Calculated fee for transaction 7
Calculated fee for transaction 8
Calculated fee for transaction 9
Calculated fee for transaction 10
Calculated fee for transaction 11
Calculated fee for transaction 12
Calculated fee for transaction 13
Calculated fee for transaction 14
Calculated fee for transaction 15
Calculated fee for transaction 16
Calculated fee for transaction 17
Calculated fee for transaction 18
Calculated fee for transaction 19
Calculated fee for transaction 20
Calculated fee for transaction 21
Calculated fee for transaction 22
Calculated fee for transaction 23
Calculated fee for transaction 24
Calculated fee for transaction 25
Calculated fee for transaction 26
Calculated fee for transaction 27
Calculated fee for transaction 28
Calculated fee for transaction 29
Calculated fee for transaction 30
Calculated fee for transaction 31
Calculated fee for transaction 32
Calculated fee for transaction 33
Calculated fee for transaction 34
Calculated fee for transaction 35
Mempool updated in 7.141 seconds
Updating mempool
Calculated fee for transaction 1 / 58
Calculated fee for transaction 2 / 58
```

**Comment by wiz** [comment]
At first glance of those logs, it appears that mempool is getting HTTP 500 from Bitcoin Core, so looks like mempool not loading is a symptom of Bitcoin Core issues

**Comment by tehelsper** [comment]
I probably wasn't clean - mine it not working, but I do not see the exceptions from the 500 error. I do see "X not found" messages, but that should not be an issue from what I can tell. It looks like that just means TXs were seen that were not in the local mempool.

**Comment by wiz** [comment]
> It looks like that just means TXs were seen that were not in the local mempool.

Yeah that's normal and unrelated to the issue, it just means a miner mined some TX that weren't in your mempool. I found a public v1 instance which seems to be running fine so I assume this is MyNode related https://bitma.tk/

**Comment by calligrl** [comment]
> How much RAM do you have? I have started seeing a similar issue on my RP4 with 2GB. I didn't see the exception, but I get repeated "Fetching block tx" messages. I'm running version 1.0.1 though.
> 
> Maybe @wiz has an idea?

myNode is running in the VM on a device with 8 GB RAM; 5.5 GB given over to the myNode VM.

**Comment by calligrl** [comment]
> From the logs it looks like the JSONRPC API is returning 500 - did Bitcoin Core crash?

No, Bitcoin Core didn't crash.

**Comment by tehelsper** [comment]
@wiz, I really don't think this is myNode related. Bitcoin core is finding blocks just fine and others services are running. Mempool even looks fine according to its logs, but it just won't show blocks in the UI. Any ideas?

**Comment by wiz** [comment]
Okay let me spin up a v1 instance today and try it

**Comment by gongyj0948** [comment]
> How much RAM do you have? I have started seeing a similar issue on my RP4 with 2GB. I didn't see the exception, but I get repeated "Fetching block tx" messages. I'm running version 1.0.1 though.
> 
> Maybe @wiz has an idea?

I have 4GB RAM

**Comment by calligrl** [comment]
Just in case there's any significance to it, here's a sample of the log when I looked just now. It still shows 'Offline' when viewing the mempool page.

-- Logs begin at Fri 2020-10-30 14:01:54 CDT, end at Fri 2020-10-30 14:39:56 CDT. --
Oct 30 14:39:53 mynode mempoolspace[26332]: Fetching block tx 630 of 2884
Oct 30 14:39:52 mynode mempoolspace[26332]: Fetching block tx 629 of 2884
Oct 30 14:39:51 mynode mempoolspace[26332]: Fetching block tx 628 of 2884
Oct 30 14:39:48 mynode mempoolspace[26332]: Fetching block tx 627 of 2884
Oct 30 14:39:47 mynode mempoolspace[26332]: Fetching block tx 626 of 2884
Oct 30 14:39:46 mynode mempoolspace[26332]: Fetching block tx 625 of 2884
Oct 30 14:39:45 mynode mempoolspace[26332]: Fetching block tx 624 of 2884
Oct 30 14:39:45 mynode mempoolspace[26332]: Fetching block tx 623 of 2884
Oct 30 14:39:43 mynode mempoolspace[26332]: Fetching block tx 622 of 2884
Oct 30 14:39:30 mynode mempoolspace[26332]: Fetching block tx 621 of 2884
Oct 30 14:39:02 mynode mempoolspace[26332]: Statistics cache created
Oct 30 14:39:00 mynode mempoolspace[26332]: Fetching block tx 620 of 2884
Oct 30 14:38:57 mynode mempoolspace[26332]: Fetching block tx 619 of 2884
Oct 30 14:38:56 mynode mempoolspace[26332]: Fetching block tx 618 of 2884
Oct 30 14:38:56 mynode mempoolspace[26332]: Fetching block tx 617 of 2884
Oct 30 14:38:56 mynode mempoolspace[26332]: Fetching block tx 616 of 2884
Oct 30 14:38:54 mynode mempoolspace[26332]: Fetching block tx 615 of 2884
Oct 30 14:38:48 mynode mempoolspace[26332]: Fetching block tx 614 of 2884
Oct 30 14:38:43 mynode mempoolspace[26332]: Fetching block tx 613 of 2884
Oct 30 14:38:40 mynode mempoolspace[26332]: Fetching block tx 612 of 2884
Oct 30 14:38:36 mynode mempoolspace[26332]: Fetching block tx 611 of 2884
Oct 30 14:38:33 mynode mempoolspace[26332]: Fetching block tx 610 of 2884
Oct 30 14:38:33 mynode mempoolspace[26332]: Fetching block tx 609 of 2884
Oct 30 14:38:31 mynode mempoolspace[26332]: Fetching block tx 608 of 2884
Oct 30 14:38:29 mynode mempoolspace[26332]: Fetching block tx 607 of 2884
Oct 30 14:38:25 mynode mempoolspace[26332]: Fetching block tx 606 of 2884
Oct 30 14:38:18 mynode mempoolspace[26332]: Fetching block tx 605 of 2884
Oct 30 14:38:15 mynode mempoolspace[26332]: Fetching block tx 604 of 2884
Oct 30 14:38:10 mynode mempoolspace[26332]: Fetching block tx 603 of 2884
Oct 30 14:37:51 mynode mempoolspace[26332]: Fetching block tx 602 of 2884
Oct 30 14:37:48 mynode mempoolspace[26332]: Fetching block tx 601 of 2884
Oct 30 14:37:47 mynode mempoolspace[26332]: Fetching block tx 600 of 2884
Oct 30 14:37:46 mynode mempoolspace[26332]: Fetching block tx 599 of 2884
Oct 30 14:37:46 mynode mempoolspace[26332]: Fetching block tx 598 of 2884
Oct 30 14:37:42 mynode mempoolspace[26332]: Fetching block tx 597 of 2884
Oct 30 14:37:41 mynode mempoolspace[26332]: Fetching block tx 596 of 2884
Oct 30 14:37:36 mynode mempoolspace[26332]: Fetching block tx 595 of 2884
Oct 30 14:37:32 mynode mempoolspace[26332]: Fetching block tx 594 of 2884

The difference from the first log is: there is none of this (below) in the log this time:

}
Oct 29 15:38:29 mynode mempoolspace[31003]: code: -32602
Oct 29 15:38:29 mynode mempoolspace[31003]: at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Oct 29 15:38:29 mynode mempoolspace[31003]: at endReadableNT (_stream_readable.js:1185:12)
Oct 29 15:38:29 mynode mempoolspace[31003]: at IncomingMessage.emit (events.js:228:7)
Oct 29 15:38:29 mynode mempoolspace[31003]: at IncomingMessage. (/mempool.space/backend/node_modules/bitcoin/lib/jsonrpc.js:110:17)
Oct 29 15:38:29 mynode mempoolspace[31003]: Error getMempoolInfo Error: Invalid params, response status code: 500
Oct 29 15:38:29 mynode mempoolspace[31003]: }

**Comment by Jacksper13** [comment]
@tehelsper got resolved with mempool v2 - suggested close

**Comment by tehelsper** [comment]
This is definitely resolved - there was a proxy issue with the websocket that was fixed.
