### ISSUE TITLE
Lightning Pool integration

### ISSUE THREAD

**Issue by AbelLykens** [mynodebtc/mynode#433]
**Is your content request related to a problem? Please describe.**
Lightning Pool by Lightning Labs allows node operators to buy and sell liquidity. I feel this will become an essential service for operators, allowing for quickly bootstrapping a new node, and making money selling liquidity.

**Describe the solution you'd like**
I'd like the option to:
* Open Lightning Pool accounts. It will (de default) use the liquidity from the node
* Allow to request liquidity (eg: enter a buy order)
* Allow to offer liquidity (eg: enter an ask order)

**Additional context**
Lightning Pool has a complete API. 
Wiki: https://lightningwiki.net/index.php/Lightning_Pool
Orders: https://twitter.com/LightningPool

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by liftedkilt** [comment]
Here's how raspiblitz is adding it:

https://github.com/rootzoll/raspiblitz/pull/1739

**Comment by AbelLykens** [comment]
It would be necessary to:

- Install poold daemon
- Create some UI, which would talk over API to poold

Or wait for RTL to integrate?

**Comment by tehelsper** [comment]
Poold is coming in the next release. I am waiting on the various wallet apps to support it from a UI perspective, but the pool commands should work just fine via the Linux terminal.

**Comment by tehelsper** [comment]
Pool was added.
