### ISSUE TITLE
multiple entries in /etc/resolv.conf

### ISSUE THREAD

**Issue by pysiak** [mynodebtc/mynode#444]
**Describe the bug**
/etc/resolv.conf seems to be duplicating DNS entries

**Expected behavior**
Should not touch resolv.conf

**Screenshots**
Screenshot attached.
![image](https://user-images.githubusercontent.com/2396137/101260482-943e4980-3730-11eb-8615-8cb068ca175a.png)

**Desktop (please complete the following information):**

**MyNode hardware (please complete the following information):**
 - Device: raspi4
 - Version: not sure when it happened, but I'm on 0.2.19

**Additional context**
I do upgrades myself using instructions.

**Comment by tehelsper** [comment]
Resolved in latest release - no more extra DNS entries.
