### ISSUE TITLE
Payment Request: "Pay Invoice" button doesn't generate invoice

### ISSUE THREAD

**Issue by ArbenKarb** [mynodebtc/mynode#448]
Describe the bug
"Pay Invoice" button from payment request doesn't generate invoice

To Reproduce the bug

    Create Payment request
    Specify payment request details
    save
    view
    hit "Pay Invoice" button

Expected behavior
Should generate invoice with QR code as it does when clicking "pay" on the payment request page:
image
image

Your BTCPay Environment (please complete the following information):

    Btcpayserver v1.0.6.2
    self hosted (mynode on raspi)

already reported in:
https://github.com/btcpayserver/btcpayserver/issues/2147

**Comment by tehelsper** [comment]
Was this working in previous versions of BTC Pay Server on myNode?

**Comment by ArbenKarb** [comment]
No

**Comment by ArbenKarb** [comment]
Must be due to some network issue. Closing for now
