### ISSUE TITLE
Button or option to reset BtcPayServer Admin email and password

### ISSUE THREAD

**Issue by manakill** [mynodebtc/mynode#450]
Button or option to reset BtcPayServer Admin email and password since the current method outlined by BtcPayServer(https://docs.btcpayserver.org/FAQ/FAQ-ServerSettings/) doesn't seem to work with how it's set up in MyNode. An easy to use option for MyNode admin to use would be very helpful to restore admin access to BtcPayServer

**Comment by tehelsper** [comment]
Have you tried to re-install btcpayserver? I believe that would work now.

**Comment by manakill** [comment]
> 
> 
> Have you tried to re-install btcpayserver? I believe that would work now.

I'm saving that as a last ditch effort as I believe I had some small amount of coin in there from when I was setting it up and getting familiar with things

**Comment by tehelsper** [comment]
IIRC, BTCPayServer never stores money locally - it would all be in either your lightning wallet or the bitcoin wallet you provided the xpub for.

Technically, you can probably just remove the single docker volume used for btcpayserver config storage and reboot. That may reset it.

**Comment by manakill** [comment]
I was wondering about that, I see the 3 utxo's in RTL wallet and suspected they were the same ones I had in BTCPayServer. Awesome, I can just reinstall BTCPayServer, and should be back in business.

**Comment by Jacksper13** [comment]
@tehelsper sounds like this was resolved? Close issue?
