### ISSUE TITLE
update download links on mynodebtc.com/download

### ISSUE THREAD

**Issue by binarygeek** [mynodebtc/mynode#451]
**Describe the bug**
No bug, other than https://mynodebtc.com/download does not have the latest downloads linked. References 0.2.16 when latest is 0.2.20.

**Expected behavior**
Would prefer if I'm starting out to start out with the latest version instead of starting off outdated

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version: 0.2.16

**Additional context**
N/A

**Comment by jaroslavmraz** [comment]
It will be nice if you can add torrent for downloads becouse you have so slow download link.

**Comment by tehelsper** [comment]
Full images are much more time consuming to create, so new full images are not made for each  minor release. However, the latest RP4 image has been updated to v0.2.24.
