### ISSUE TITLE
LNDhub QR code for TOR. (tor support added in bluewallet) (200k sat bounty)

### ISSUE THREAD

**Issue by godSaysHODL** [mynodebtc/mynode#452]
Bluewallet is adding Tor support in their next release. https://github.com/BlueWallet/BlueWallet/pull/2295 

I would like suggest adding an info page to the LNDhub service box on myNode. This info page should have a QR code for connecting lndhub to your TOR onion address.

QR code generation should follow the format

http://mynodeonionaddress.onion:3000

Bluewallet also already has scan to import function on their network settings page, so this will flow nicely. Thanks

There is a 100k sat bounty to the person who implements this feature. dm godsaysHODL on twitter to claim once feature is in mynodeBTC release. Thanks for all you guys do!

**Comment by tehelsper** [comment]
Should this use HTTPS instead of HTTP?

The URL is already listed on the tor page - it would just need a QR code.

**Comment by godSaysHODL** [comment]
> Should this use HTTPS instead of HTTP?
> 
> The URL is already listed on the tor page - it would just need a QR code.

in my testing on TOR browser, http:// is actually secure due as long as your using onion protocol. And using https:// gets a bad request, even when trying the special 3001 port designated by mynode. 

Also, the apk for testing has been updated in the bluewallet repository with a working implementation for testing. Works great with this test QR I made for my node.

![image](https://user-images.githubusercontent.com/14336691/104061398-59a35300-51ad-11eb-84fa-744349672a45.png)

**Comment by godSaysHODL** [comment]
Good news! Bluewallet team has added a deeplinking feature to scanning the QR codes for connecting to your own node. QRs built with this format will be scannable from the main menu, without ever opening up a settings page

so you can download bluewallet, scan QR to connect to the node, confirm, and create your wallet without ever entering the settings menu

the new QR format is as such

LNDhub QR:
bluewallet:setlndhuburl?url=http%3A%2F%2Fg45wix2qhsxtoz2k675ikmlt5ypmcoz4nyhy44teku7amb7vqoh7jyyd.onion%3A3000

Electrum QR:
bluewallet:setelectrumserver?server=v7gtzf7nua6hdmb2wtqaqioqmesdb4xrlly4zwr7bvayxv2bpg665pqd.onion%3A50001%3At

I'm upping the bounty for this QR creating feature from you guys to 200k sats. Would really like to see this coexist when Bluewallet Tor update goes public soon 💯

**Comment by tehelsper** [comment]
Hmm... I'm actually seeing better pairing success with HTTP - not sure why.

I added BlueWallet pairing options on the Pair Wallet page in this commit. Tor should be ready, but not shown yet.

https://github.com/mynodebtc/mynode/commit/cd65818a7204aa3098c6d299e9202f34829ff543

**Comment by godSaysHODL** [comment]
> Hmm... I'm actually seeing better pairing success with HTTP - not sure why.
> 
> I added BlueWallet pairing options on the Pair Wallet page in this commit. Tor should be ready, but not shown yet.
> 
> [cd65818](https://github.com/mynodebtc/mynode/commit/cd65818a7204aa3098c6d299e9202f34829ff543)

Suhweet. Throw a 200k sat invoice at me to claim the bounty. 

BTW have you been getting lndhub failures from a "bandwidth exhausted" error? It's been happening to me since the lndhub update to 1.3

**Comment by godSaysHODL** [comment]
I believe I owe yall 200,000 sats

Thanks for everything yall are doing!

**Comment by tehelsper** [comment]
Thank you! I don't really want to take it myself, but I'd like to start a bounty pool for things like this to help improve the project via software and documentation updates. 

Here's a payment request:
LNBC2M1PSFC6SKPP55JUT6DCT3QAT5RS3G62A0P57FWWRG8ZZMF223DUL9SY78TMZ8MEQDQ2XGCRQVPSXQCQZPGXQRRSSSP5P99Q7HWP27S9RW5WYKYMGYA7WAHSEH90A0EJC3U4WWJ4MHZJ5V0S9QY9QSQH6Q22Z4XYEERN33Q922LVY5K59ZDGF80K4H9L3XM95FLMRT5J2SZ3WUKLAVE6R5JTSHDJCXEEW4LZ0AE7Y35NGPA4NPM5RM05J4DJUCQLY8GAT

I'll contribute at least another 200k sats and set up a bounty list over the next week or two.

**Comment by godSaysHODL** [comment]
Paid!! And yes, that'd be awesome. I'll be looking forward to seeing what your bounty pool funds and donating more 🧡🔥

**Comment by tehelsper** [comment]
Thank you!

**Comment by thmsmullee** [comment]
How can I connect lnhub with my Bluewallet ? (no Umbrel, no mynode, just plain debian)
There is the .env file with the line    LND_REST_ENDPOINT=127.0.0.1:8080  
Ther is BlueWallet with TOR enabled. Which connection-string should I use under "Lighning Settings" ?
THANKS

**Comment by tehelsper** [comment]
Try logging a support ticket or asking around in the community chats. We don't have a guide yet, but it should work fine with BlueWallet running on a phone and LNDHub running on myNode. We don't support custom installs on top of Debian.

**Comment by woodyjon** [comment]
I also cannot get it to work (on a mynode). I searched for guide or for anyone who successfully did it and explains it, but did not find any.

**Comment by tehelsper** [comment]
Is tor enabled within BlueWallet? I am able to connect after scanning the QR code, but the tor connection can be very flakey.

![Screenshot_20220822-215438](https://user-images.githubusercontent.com/5722611/186059562-a1a077d2-bb41-409a-a700-20784a28320d.png)
