### ISSUE TITLE
Add sphinx-relay

### ISSUE THREAD

**Issue by benflap** [mynodebtc/mynode#453]
[Sphinx chat](https://sphinx.chat/) is a lightning messaging app. To set it up on my own node I need to install [sphinx-relay](https://github.com/stakwork/sphinx-relay). I would like to see **sphinx-relay** added to mynode.

**Comment by Transisto** [comment]
While I'm a big fan of Sphinx relay, it seems like something that should be disabled by default.

**Comment by benflap** [comment]
Yes, I agree. I just want a one-click install.

**Comment by bitcoincoredotbin** [comment]
I 2nd this, would love Sphinx integrated. I'm having issues trying to manually install it on my own mynode. 

I know a few people who went with Umbrel for the Shpinx integration specifically.

**Comment by Transisto** [comment]
Added in last update.
