### ISSUE TITLE
Unable to upgrade LND

### ISSUE THREAD

**Issue by justinmoon** [mynodebtc/mynode#457]
**Describe the bug**
I'm currently running LND version `0.11.0`. I want to upgrade in order to use `poold` which requires `0.11.1`. I twice click this "upgrade" button, mynode restarts after a while, but `0.11.1` still not installed. (side note: it's weird this says LND is "not installed" because it's running with a few open channels).

![image](https://user-images.githubusercontent.com/4335621/103984513-e79b2180-514c-11eb-8761-9497c955c0ab.png)

**Expected behavior**
0.11.1 will be installed

**Desktop (please complete the following information):**
 - Firefox
 - Version 84.0.1
 - Linux

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version 0.2.21

**Comment by tehelsper** [comment]
Can you check the files under ~/upgrade_logs/ for one that relates to reinstalling lnd? If you want to send it to me I'll take a look - I'm not sure how this did not get upgraded.

For another workaround, you can also re-flash your SD card with the latest release.

**Comment by tehelsper** [comment]
Is this still an issue? LND should be at v0.12.0 now.

**Comment by Jacksper13** [comment]
@tehelsper new image for download should have updated LND version, this was on v0.2.21. I'd close the issue.
