### ISSUE TITLE
Mempool doesn't work over HTTPS

### ISSUE THREAD

**Issue by xxi000000** [mynodebtc/mynode#460]
**Describe the bug**
When "Force HTTPS" is enabled for myNode, accessing Mempool attempts to load via https://mynode.local:4081/. The Mempool UI is displayed, but it says "Offline" and "Loading blocks..." indefinitely.

The developer console displays the following error:

> WebSocket connection to 'wss://mynode.local:4081/ws' failed: Error during WebSocket handshake: Unexpected response code: 404

Mempool works fine when accessed over HTTP via http://mynode.local:4080/.

**Expected behavior**
I expect Mempool to work when "Force HTTPS" is enabled for myNode.

**Screenshots**
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/76971517/104451246-43abde80-556f-11eb-9edb-63b42fa1e789.png">

**Desktop (please complete the following information):**
 - Browser: Chrome, Firefox
 - Version: Latest

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version: 0.2.21

**Additional context**
Not sure if this is related to https://github.com/mynodebtc/mynode/issues/431, but my gut says no, hence this new issue.

**Comment by tehelsper** [comment]
Thanks for the info! I was able to track it down. The websocket had an issue running on HTTPS - it will be fixed in the next release with an updated NGINX config for mempool.

https://github.com/mynodebtc/mynode/commit/78c4e2296a6c0d2ba792f1afdfbed3488ec98271
