### ISSUE TITLE
Dojo stuck installing - Docker Failed... retrying later

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#464]
**Describe the bug**
Dojo stays "Installing" forever in the main view and Docker Image Build status fails after step 6/36, status stays at "Failed, retrying later" forever. 

**Expected behavior**
Docker image install without failing

**Screenshots**
![image](https://user-images.githubusercontent.com/63911988/105628430-27485580-5e3d-11eb-8ae8-eb07432fb17a.png)

**MyNode hardware (please complete the following information):**
- MyNode v0.2.22
- Raspi 4, 4Gb, 1Tb SSD

**Additional context**
Triggered after upgrade from previous version with Dojo disabled, then enabling it on v0.2.22
Several instances on the issue on the telegram channels, resolved by user @DnDave as follows:

The problem is in the file "/opt/mynode/mempoolspace/Dockerfile"
It uses "FROM alpine:latest"
Change that into "FROM node:14.15-alpine"
The next thing is, that this file will get overwritten during the boot process (after restart of mynode).
In order to prevent this, I have commented out a few lines in the startup scriptL
sudo nano /usr/bin/mynode_docker_images.sh
![image](https://user-images.githubusercontent.com/63911988/105628548-d84ef000-5e3d-11eb-8d09-9731b811c340.png)

After you have changed these 2 files:
(/opt/mynode/mempoolspace/Dockerfile)
(/usr/bin/mynode_docker_images.sh)
reboot the system
If all goes well, it will build the mempool image.
And after that the Dojo image.

**Comment by tehelsper** [comment]
Should be resolved next release. myNode replaces alpine:latest with the last alpine release 3.12.3 which doesn't have the install issue.

Also, further docker containers will continue to be created if one fails.

**Comment by Jacksper13** [comment]
Closing, resolved on release 0.2.23
