### ISSUE TITLE
Canonical way of dealing with endless "Installing..."

### ISSUE THREAD

**Issue by StevenBlack** [mynodebtc/mynode#465]
**What is the canonical way of dealing with app installation failures?**

**Describe the bug**
Basically new MyNode One 0.2.22 running on a 4Gb RasbPi provided by MyNode.

Stuck in this state for several days, including reboots.

<img width="721" alt="2021-01-25_11-14-56" src="https://user-images.githubusercontent.com/80144/105733122-2bd54280-5eff-11eb-8e25-44b73db3ae72.png">

This started with a failed attempt to install Dojo with an endless `installing...` period.  After reading code I find [this in `dojo.py`](https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/var/www/mynode/dojo.py#L20-L24) leading to [this in `device_info.py`](https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/var/www/mynode/device_info.py#L806-L807) and manually deleted `/tmp/installing_docker_images` and, thereafter, I just abandoned the idea of running Dojo on MyNode.

A few days later I tried installing Mempool and it has an endless  `installing...`  mode **and** of course Dojo (which I didn't touch and should be off) is also endlessly `installing...` as well.

**Expected behavior**
I expect installations to work and, if not, I expect a way to abort and return state to normal/uninstalled.  At present, it looks like my OEM-provided MyNode is just, hosed.

**Desktop (please complete the following information):**
 - Browser **ALL**
 - Version 0.2.22

**MyNode hardware (please complete the following information):**
 - Device: **Raspi4 OEM**
 - Version [e.g. 0.2.22]

**Additional context**
* There does not appear to be any way to restore state when an installation fails.
* Umbrel, which I also possess, works perfectly in all aspects of this.

**Comment by tehelsper** [comment]
A new alpine docker container released ~10 days ago is breaking mempool installation. A myNode fix was added last night to hot-patch mempool to fix the installation. It will be included next release. The failure was preventing further process on any docker container installation.

Also, one container failing install should no longer prevent subsequent containers from being built.

Changes:
https://github.com/mynodebtc/mynode/commit/b2d6e30fe714b7f96607af149e69aff052a7c431

**Comment by StevenBlack** [comment]
Thanks Taylor @tehelsper.  I'll apply the fix manually, and let you know.

**Comment by Jacksper13** [comment]
> Thanks Taylor @tehelsper. I'll apply the fix manually, and let you know.

Check temporary solution on issue #464
