### ISSUE TITLE
Different font size on mobile (chrome)

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#47]
I see different font size into settings page on mobile chrome like image below:
![1](https://user-images.githubusercontent.com/16525337/68541119-ebda7c00-039b-11ea-8ae6-d9ce2302fcd1.jpg)
![2](https://user-images.githubusercontent.com/16525337/68541121-eed56c80-039b-11ea-89e1-988a1799bfb9.png)
![3](https://user-images.githubusercontent.com/16525337/68541123-f137c680-039b-11ea-9d17-b5513b95c904.png)

**Comment by abhiShandy** [comment]
I plan to make the pages responsive to fit mobile screens better.

**Comment by Amiga500** [comment]
I think that Taylor will be happy for it! :)

**Comment by tehelsper** [comment]
Aging out - reopen is still problematic
