### ISSUE TITLE
node can't be used with a UPnP router - port 1900 blocked by ufw

### ISSUE THREAD

**Issue by MacDefender** [mynodebtc/mynode#473]
The lightning service can't be used with a UPnP router as the node itself (version 0.2.25 on Raspi4) blocks response messages from the router on port 1900

Incoming responses from the gateway with source port 1900 should be allowed or at least there should be an easy way to allow this manually without having to use ssh as many users might have problems with this.

Adding the corresponding firewall rule will fix the lnd service hanging in a restart loop:
sudo ufw allow proto udp from MY_GATEWAY_ROUTER_IP port 1900 to any comment 'allow UPnP discovery response'

**Comment by tehelsper** [comment]
How did you determine it was blocking the response? Port 1900 should be open by the following firewall rule that gets added at startup.

ufw allow 1900  comment 'allow SSDP for UPnP discovery'

**Comment by MacDefender** [comment]
I've watched the logs with `tail -f /var/log/syslog` and noticed that ufw there is reporting it blocked the answer from the router. When I look at the current rules with `iptables --list ` I already noticed that a rule was there and active:

> target     prot opt source               destination
> ACCEPT     udp  --  anywhere             anywhere             udp dpt:1900

But with this rule in effect ufw still reported that it blocked an incoming packet from my router port 1900. After I added my rule that explicitly allowed incoming packets from udp port 1900 the block message was gone and it worked:
> target     prot opt source               destination
> ACCEPT     udp  --  192.168.10.1         anywhere             udp spt:1900

I guess this may be due to UDP being stateless and no auto return is allowed for the outgoing request. So if the incoming reply can't be mapped to the outgoing request as its not TCP the router will block it at no packets with source port 1900 are allowed back in.

**Comment by tehelsper** [comment]
Ah, the difference is source vs dest port I think. The existing rule allows dest 1900 but it looks like it may have source port 1900 to some other dest port.

**Comment by tehelsper** [comment]
Could you try these rules and see if they work for you?

ufw allow from 10.0.0.0/8 port 1900 to any      comment 'allow UPnP from router'
ufw allow from 192.168.0.0/16 port 1900 to any  comment 'allow UPnP from router'
ufw allow from 172.16.0.0/12 port 1900 to any   comment 'allow UPnP from router'

I don't know the router IP, so this would all 1900 from local networks.

**Comment by tehelsper** [comment]
https://github.com/mynodebtc/mynode/commit/aca5806b401093ea609675d7359f8a7717ef8a4d

Update for next release.

**Comment by MacDefender** [comment]
These rules works fine for me. I've deleted my own rule and added those and after a reboot everything works as expected. This rule could be limited to UDP as UPnP is using UDP and there is no need to open this port on TCP but it won't hurt much as there is no server listening on TCP 1900 so it wouldn't change anything.

**Comment by tehelsper** [comment]
New rules added in v0.2.27.
