### ISSUE TITLE
Show app installation logs

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#474]
An option to show the installation logs for when individual apps are getting installed or upgraded from the "Applications" section would be great. There's currently no way of determining progress, pretty much like upgrades were before 0.2.21 - a similar solution would be appreciated!

![image](https://user-images.githubusercontent.com/63911988/107875487-80495d80-6ec0-11eb-92db-6391964eea6e.png)

Screenshot is from upgrading Thunderhub individually to latest version, after upgrading myNode to 0.2.26

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Good idea! Updated for next release.

https://github.com/mynodebtc/mynode/commit/016dd4ac1254685a044d1a6666705b8a48efefa2

**Comment by Jacksper13** [comment]
Sweet!
