### ISSUE TITLE
CK Bunker default password is "bolt" instead of user-defined

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#476]
CK Bunker won't open unless you type in the password "bolt". I would assume the intended functionality was to have the password be the user's actual password!

Found by user (at)Rope93 on the Telegram chat

Tested on raspi4, 4Gb, v0.2.26

Alternatively, add an "Info" button and explain this is the case in the instructions, explaining it can later be changed under "Bunker Setup"

![image](https://user-images.githubusercontent.com/63911988/107932879-548cad00-6f7e-11eb-9103-615bd1c22f1d.png)

**Comment by tehelsper** [comment]
See the system notes: https://github.com/mynodebtc/mynode/blob/master/SYSTEM_NOTES.md

That was by design since CKBunker does not hash the password yet, which means a plaintext copy lives on the filesystem. Eventually, if they hash the password, I would like to bring them back in sync.

**Comment by Jacksper13** [comment]
Fair!
