### ISSUE TITLE
[Suggestion] Add date to Settings ➡️ Change Log: add version date

### ISSUE THREAD

**Issue by StevenBlack** [mynodebtc/mynode#477]
A nice touch to consider; a good value signal.

Under Settings ➡️ Change Log we see the list of enhancements (good!) but no signal about when.  How old are these versions?  What's the pace of releases, the pace of improvements and innovation?  Adds context to upgrade decisions.

All these things would reflect well, given current pace.

![2021-02-17_12-47-17](https://user-images.githubusercontent.com/80144/108245917-d582aa80-711e-11eb-9ce3-8b0bd150fbb5.jpg)

**Comment by StevenBlack** [comment]
**Specific Context**: I just upgraded, and mempool.space is showing a red light. Reboot didn't resolve.

So at this juncture, if I know that v 0.0.26 is very recent, and that's context for deciding whether to file a support ticket.

**Comment by StevenBlack** [comment]
**Alternately**: a link at the top of the changes, pointing to https://github.com/mynodebtc/mynode/tags, accomplishes the same thing.

**Comment by tylr-r** [comment]
Agreed, I find ["keep a changelog"](https://keepachangelog.com) to be a good format if looking for suggestions moving forward.

**Comment by tehelsper** [comment]
Good idea, and I like that format. I've got some magic built in to get the delta between two versions so I can't switch right away, but will think about it moving forward.

Next release will start listing the date as the first item under each version.

**Comment by tehelsper** [comment]
Added.
