### ISSUE TITLE
Add testnet toggle

### ISSUE THREAD

**Issue by cd2357** [mynodebtc/mynode#479]
Please add a simple way to allow myNode to alternate between running on mainnet or on testnet.

This could be either
* a documentation section on how to do it manually in the configs
* a flag or an option set in a myNode config file
* a UI toggle that alternates between testnet and mainnet

This toggle would ideally switch all myNode apps and modules between testnet and mainnet. However if its not trivial to achieve this for some of them, they could also just be disabled when myNode is switched to testnet.

This feature would be great for myNode adoption, because it would allow newbies to basically try out Bitcoin and Lightning without risking to lose funds in case they make a mistake.

---

Something similar was already suggested in #157 (albeit in a different context). A relevant comment from there is:

> When I uncomment 'testnet=1' in Bitcoin.conf I get: "Bitcoin has experienced an error. Please check the logs."

_Originally posted by @elDaz2 in https://github.com/mynodebtc/mynode/issues/157#issuecomment-617569229_

**Comment by tehelsper** [comment]
Added in latest release!
