### ISSUE TITLE
File /etc/resolv.conf keeps growing

### ISSUE THREAD

**Issue by as-schug** [mynodebtc/mynode#482]
File /etc/resolv.conf keeps growing
Every time the system boots, it puts content about DNS, but dont clear previous content. So the file /etc/resolv.conf keeps growing

The version installed is 	0.2.27

**Comment by tehelsper** [comment]
Thanks for the heads up. I added a fix for next release.

**Comment by tehelsper** [comment]
https://github.com/mynodebtc/mynode/commit/0ca94f9b634a699a2742c220cdc529c25e0a910a
