### ISSUE TITLE
How to use joininbox?

### ISSUE THREAD

**Issue by Transisto** [mynodebtc/mynode#486]
An icon + terminal GUI box would be great

https://github.com/openoms/joininbox

**Comment by tehelsper** [comment]
It's in the plans, short instructions are:

1. Log into Terminal (SSH preferable)
2. Run "sudo mynode-joininbox"

**Comment by tehelsper** [comment]
Link added for next release:
https://github.com/mynodebtc/mynode/commit/52aafe57772473f6c6b6b18e2bb6717528768d38

**Comment by imacfan** [comment]
> It's in the plans, short instructions are:
> 
> 1. Log into Terminal (SSH preferable)
> 2. Run "sudo mynode-joininbox"

done that - now I was trying to run Joinmarket-QT. I get below instructions:
Instructions to open the JoinMarket-QT GUI on the desktop
_************************************************************************************


Use the following line in a new desktop terminal to connect:

ssh -X joinmarket@c2:ac:e4:d5:26:d6 joinmarket-clientserver/jmvenv/bin/python joinmarket-clientserver/scripts/joinmarket-qt.py

Use the PASSWORD_B (rpcpassword in the bitcoin.conf) to open the JoinMarket-QT GUI


************************************************************************************_

I replaced "c2:ac:e4:d5:26:d6" with my node IP address. 
It is asking for password. 
I provided RPCpassword.
Got - permission denied error. Whats the password for joinmarket? I don't remember setting it.

**Comment by tehelsper** [comment]
Hmmm... the way I have it setup, I'm not sure that is currently possibly. The joinmarket user is only available internally on the device and not via SSH.

The password you are being prompted for is the joinmarket user (not Bitcoin's RPC) and that user is not available that way.

**Comment by imacfan** [comment]
Ok. So it means I cannot run Joinmarket-QT remotely (via terminal) connecting to myNode running on Raspberry pi? 

Only way to use Joinmarket remotely is via command line interface. 

Thanks !


> Hmmm... the way I have it setup, I'm not sure that is currently possibly. The joinmarket user is only available internally on the device and not via SSH.
> 
> 
> 
> The password you are being prompted for is the joinmarket user (not Bitcoin's RPC) and that user is not available that way.
