### ISSUE TITLE
Two target drives found. Is myNode drive missing?

### ISSUE THREAD

**Issue by ratacibernetica** [mynodebtc/mynode#487]
**Describe the bug**
After logging in for the first time (and all subsequent  attempts), I see the following message every time:
"Two target drives found. Is myNode drive missing?"

I'm booting from a 16GB USB flash drive instead of the SD card. 
Another USB external drive (2 TB) is there to handle the heavy stuff.

**Expected behavior**
Don't boot into the clone tool if I didn't told it to.

**Screenshots**
<img width="758" alt="image" src="https://user-images.githubusercontent.com/1541791/110278583-7ee1f100-7fa5-11eb-81bb-97033e73de8d.png">

**Desktop (please complete the following information):**
 - Browser Chrome/ Safari
 - Version: latest

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version  0.2.24

**Additional context**
Looking at that part of the code (clone_tool.py) looks like it's detecting 2 unmounted external drives. 
I do have 2 USB drives, but that's it, and one of them is mounted as the main system (booting from it). 
Not sure why I keep hitting the clone tool if I didn't even request it. 

Tried formatting the drive off the settings menu.
Tried factory reset.

**Comment by tehelsper** [comment]
Try upgrading to the most recent release, that should get you started. I have not tested using a USB as the drive for the OS, but it should work (except for the clone tool).

Previously, the clone tool would auto-start if it saw two USB drives.

Alternatively, you could move to an SD card.

**Comment by tehelsper** [comment]
Fix added.
