### ISSUE TITLE
FEATURE: Wifi Enable/Disable on settings

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#49]
I was thinking about a Wifi Enable/Disable on settings (with field of SSID / password) if can be a interesting feature for who wants to use a node far from eth cables and don't want/know how to modify configuration files. 

It could be a good idea to add this feature on settings?

**Comment by tehelsper** [comment]
This is probably fine. I do want to avoid configuring specific IP address / DHCP /  DNS / Routes etc.... since that gets to be a lot, but wifi toggle + SSID / password could be good.

We need to make sure that it's only shown on devices / platforms that have wifi.

**Comment by KallerTobias** [comment]
Actually I see a big advantage in using wired connection only. Wifi is a potential point of weakness, a attacker doesn't have to enter your building to access the device. Off course Wifi would be very comfortable, but you don't need acces to the device, so just place it near by a router and everything is finde ...
Just my two cents ...

**Comment by Perpiolo** [comment]
I am having troubles trying to make wifi work. Is there any advancement on this?

Need to say, I have no idea of Linux....

Congrats for the work guys, thanks!

**Comment by tehelsper** [comment]
Not supporting wifi for now.
