### ISSUE TITLE
Unable to Upgrade a Raspberry Pi 3 Node

### ISSUE THREAD

**Issue by dolan2mp** [mynodebtc/mynode#492]
Hey Everyone,

Had an old Raspberry Pi 3 laying around and decided to turn it into a a node and I'm running into some issues trying to upgrade. Current version: 0.1.51

I'm following the instructions laid out in the official mynode instructions, and I keep getting a 404 error when I run "sudo mynode-local-upgrade [dev pc ip address]"

The error is as follows:

```
HTTP request sent, awaiting response... [IP] - - [16/Mar/2021 20:10:02] code 404, message File not found
[IP] - - [16/Mar/2021 20:10:02] "GET /mynode_rootfs_raspi3.tar.gz HTTP/1.1" 404 -
404 File not found
2021-03-16 20:10:02 ERROR 404: File not found.
```

When I run "make rootfs" only the following root file systems are created:

```
admin@myNode:~/mynode $ make rootfs
Creating root file system for raspi4
Creating root file system for rock64
Creating root file system for rockpro64
Creating root file system for debian
Done!

```
This is making me think there's no way for me to upgrade since my hardware is a raspi3 which isn't listed.

I'm not very well versed with ssh, linux, or git so navigating all of this is pretty confusing. Is it still possible to upgrade a raspi3, or are they now a legacy hardware that can't be upgraded?

If I can't upgrade, any ideas how to get my lightning wallet running? Every time I go to the wallet, the status says "waiting" and I heard that likely meant I needed an upgrade.

**Comment by Jacksper13** [comment]
Rpi3s are no longer supported, see Step 1 in here: [https://mynodebtc.com/download](https://mynodebtc.com/download)

**Comment by dolan2mp** [comment]
> Rpi3s are no longer supported, see Step 1 in here: https://mynodebtc.com/download

Thank you for your reply. I noticed this earlier when I was doing some research.

It looks like they're not recommended, but should still work (slowly). Is there a way to get the lightning network running on this on a Rpi3?

**Comment by Jacksper13** [comment]
No clue, sorry...=S

**Comment by tehelsper** [comment]
They will likely be so slow you will get frustrated. I have not tested on a RP3 in probably a year and A LOT of stuff has been added since then. Apps may crash due to lack of RAM.

However, you can add raspi3 to the list in the "make_rootfs.sh" file and you will get past your file not found error.

**Comment by dolan2mp** [comment]
> They will likely be so slow you will get frustrated. I have not tested on a RP3 in probably a year and A LOT of stuff has been added since then. Apps may crash due to lack of RAM.
> 
> However, you can add raspi3 to the list in the "make_rootfs.sh" file and you will get past your file not found error.

That all makes sense. Thank you for clarifying here. 

I've been contemplating just getting an 4, but want to see if I can make this work first. 

I appreciate your insight.
