### ISSUE TITLE
Wider upgrade log?

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#493]
When upgrading and showing the log, there's a lot of "blank" space on the sides of the log, yet the log cuts some of the text and you need to use the bottom bar to slide right and see the full text. 

![image](https://user-images.githubusercontent.com/63911988/111613096-73c96500-87de-11eb-83dc-7cde2f366808.png)

It'd be great if the log box was a little wider and showed all/most lines fully, 90% of the text that is cut fits within an extra half an inch or so

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Yeah, I was torn on that. Since most lines are short, I did not like the look of putting everything way over to the left either. I couldn't think of any great UI solutions, so I just stuck with this.

**Comment by Jacksper13** [comment]
Gotcha. Maybe leave the left margin where it where it is and make it wider on the right side only? That should leave the short lines (most of the upgrade) centered, and any long line would show up, even if it wasn't perfectly symmetric for long lines?

**Comment by tehelsper** [comment]
Yeah, I might just go widen it a couple hundred pixels since it's optional to look at anyway and it would be impossible to get it centered.

**Comment by Jacksper13** [comment]
Resolved in 66fbfedc26e4e4ee4d73d3f51eae16c839f38308
