### ISSUE TITLE
Enhance Whirlpool instructions

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#494]
Whirlpool instructions request download of GUI 10.2, but latest is currently on 10.3

![image](https://user-images.githubusercontent.com/63911988/111759123-91113880-889d-11eb-86fd-a4fe13266fb6.png)

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by Jacksper13** [comment]
Would also update the part where it says "use the raw IP address", adding something like "use the raw IP address, that should look something like https://192.168.XXX.XXX:8899". Had a friend the other day that got stuck here for an hour cause he couldn't figure this out haha

**Comment by Jacksper13** [comment]
Or rather, since you can pull the local IP address fill the XXX parts out with the user's actual local address, and in the parenthesis parts type "alternatively, try https://192.168.filledout.filledout:8899"

![image](https://user-images.githubusercontent.com/63911988/111760491-10533c00-889f-11eb-837a-0e2c8dc6c66a.png)

**Comment by tehelsper** [comment]
Yeah, I can definitely do that. Thanks for the feedback.

**Comment by Jacksper13** [comment]
Resolved in a91010ade7bae18fde1a5271dcfb918c714cd594
