### ISSUE TITLE
Update lightning dropdown text color for dark mode

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#495]
Maybe change the text color to white in the lightning dropdown for dark mode? It's kinda hard to read the details in black letter on a dark gray background

![image](https://user-images.githubusercontent.com/63911988/111761221-f403cf00-889f-11eb-8a5c-187d883747fb.png)

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Sorry about that. Forgot to verify the last CSS changes in dark mode before update. Fix has just been committed.

https://github.com/mynodebtc/mynode/commit/ba0194e75be8b930a2790c001f62df0e0d70155a
