### ISSUE TITLE
Simple step-by-step tutorial/guide for mynode's specter , please?

### ISSUE THREAD

**Issue by TheTotalConnector** [mynodebtc/mynode#496]
I want to re-create my saved specter-wallets (json files etc.) into mynode's specter, but really need a simple step-by-step guidance or tutorial with some necessary command lines, which I am not in command of (non-technical user). 

I formatted my drive via settings, rebooted, re-started, re-synced etc. & upgraded to latest version. Now everything seems to be working smoothly again- hope it stays this way. 
(Stepan of specter helped me to get a pruned version of Bitcoin core + specter app up and running, but it is not fully re-synced...and actually only suitable for small amounts of bitcoin). 

Now that mynode works again, I want to return to mynode and re-create / re-store our specter wallets and be connected to my fullnode , mynode.

I would appreciate an easy to follow tutorial or guide, how I can enter the necessary command lines. These are the instructions by Talor, who helped me a lot during my issues. 
Keyvan Davani [TheKeyvanDavaniConnection] #Bitcoin Podcast, [19.03.21 05:20]
[Forwarded from Taylor Helsper]
So, I'm not 100% sure how Specter works, but the files structure looks very logical and well-designed. Everything looks like a json file so backup may be as easy as replacing all contents under the specter data folder and restarting the specter service.

[Forwarded from Taylor Helsper]
"I can't go through the details now, but in general:
- Connect via SSH to myNode
- Erase files under /mnt/hdd/mynode/specter/
- Copy backed up files to /mnt/hdd/mynode/specter/
- Reboot

[Forwarded from Taylor Helsper]
After copy step, also:

[Forwarded from Taylor Helsper]
sudo chown -R bitcoin:bitcoin /mnt/hdd/mynode/specter/"

I would also need to know the specific settings, configurations, etc. for specter in mynode (General, bitcoin path,  HWI, etc.),and I can only do these steps outside my local network. I can login and access mynode via Tor-browser. 

Any help appreciated. Thanks.
Keyvan

**Is your content request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I need ip2tor for btcpayserver

**Describe the solution you'd like**

**Additional context**

- [ ] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
This may be best as a feature request for Specter. It may be possible to do externally by copying and pasting files, but it would be best if Specter could make the backup and re-import it via the user interface. Any external solution would just be guessing at putting the files in the right places and hoping it works.

Otherwise, it would really require tinkering and get it to work which is hard to write a guide for.

**Comment by tehelsper** [comment]
Actually, it already is a feature of Specter. Can you try this?

![image](https://user-images.githubusercontent.com/5722611/112733528-86464b80-8f0e-11eb-985a-445190143653.png)
