### ISSUE TITLE
Sphinx Chat Relay Over Tor

### ISSUE THREAD

**Issue by gogomickey** [mynodebtc/mynode#497]
Please add Tor support for the Sphinx Chat Relay.   Especially for those who operate remote nodes.  Umbrel supports it and I dont want myNode to fall behind in features.

**Comment by tehelsper** [comment]
Good idea. I'll look into adding it. Do you know if they support tor and local IP, or tor-only? The sphinx config seems very limiting as to how connections are setup.

**Comment by gogomickey** [comment]
Umbrel?  I'm not sure.  I'll look into it.  You are right though the connection setup for Sphinx is limited.  It's not ideal if you are forced to choose between tor or local ip.  Thanks for all the hard work.

**Comment by gogomickey** [comment]
Thanks for getting the relay to run over tor.  It works but I don't think it is quite stable.  I seem to stop receiving messages after a while.  A reboot of the node fixes
It but only temporarily.  Are you having similar problems?

**Comment by tehelsper** [comment]
Did you re-pair your chat app? It only works over tor if you delete the Sphinx database and re-pair unfortunately.

No, I haven't noticed any issues. Does restarting the sphinx app help? The only issue I saw was when my sphinx channel went inactive for a bit.

**Comment by ZsZolee** [comment]
I deleted the app on my phone, but now I can't reconnect to it on the newest mynode version. How can I switch back to localhost only? I don't want to loose my tribes.

**Comment by gogomickey** [comment]
Yea.  I did delete the relay database and re-pair.  It is definitely working over tor but it just seems like it goes long periods without relaying any messages unless you "kick it".  Reboot node or reinstall app on iOS and recover from keys.  I never lose connection with my lightning node-according to the app (green lightning bolt). It may just be the result of Sphinx still ironing out details.

**Comment by benflap** [comment]
> Did you re-pair your chat app? It only works over tor if you delete the Sphinx database and re-pair unfortunately.

You don't need to delete the Sphinx database to connect to `sphinx-relay` over tor. You just need to go to *Profile* > *Advanced* and change the *Server URL* to the onion address.

**Comment by ZsZolee** [comment]
> > Did you re-pair your chat app? It only works over tor if you delete the Sphinx database and re-pair unfortunately.
> 
> You don't need to delete the Sphinx database to connect to `sphinx-relay` over tor. You just need to go to _Profile_ > _Advanced_ and change the _Server URL_ to the onion address.

And what's the solution if you deleted the app from your phone? I don't want to delete the data because I will lose my tribes.

**Comment by benflap** [comment]
The way I understand it is the connection string is only useful for the first connection. After the first connection the sphinx app gets a private key that is used from that point forward. So unless you exported your keys you won't be able to access your database. 

If you have an iOS device sphinx might have saved your key in keychain. Otherwise, I believe you're out of luck.

See [this comment](https://github.com/stakwork/sphinx-relay/issues/154#issuecomment-779103988)

**Comment by ZsZolee** [comment]
I just don't understand why isn't this information shown anywhere in the app or on the relay node? Can't believe that the app was made like that without any option to generate a new string. This is so dumb because it could happen anything with a phone and then you are fucked. I wrote to the devs hope they will upgrade soon the relay software to be able to generate a new string.

**Comment by tehelsper** [comment]
> I just don't understand why isn't this information shown anywhere in the app or on the relay node? Can't believe that the app was made like that without any option to generate a new string. This is so dumb because it could happen anything with a phone and then you are fucked. I wrote to the devs hope they will upgrade soon the relay software to be able to generate a new string.

Completely agree. The fact that pairing is stateful seems like a big problem. I don't understand why the relay can't generate a key that can be used multiple times in case a client device is reset, lost, stolen, broken, etc...

**Comment by RhinoAK** [comment]
> Did you re-pair your chat app? It only works over tor if you delete the Sphinx database and re-pair unfortunately.
> 
> No, I haven't noticed any issues. Does restarting the sphinx app help? The only issue I saw was when my sphinx channel went inactive for a bit.

I was experiencing the same issue, but when your team updated the Sphinx Relay in your last node update, the current version appears and the connection to both iOS and Android over Tor to work flawlessly. Thanks

**Comment by Jacksper13** [comment]
@tehelsper sounds like this was resolved? Close?
