### ISSUE TITLE
Tor issue after pulling latest commits

### ISSUE THREAD

**Issue by RR82** [mynodebtc/mynode#499]
**Describe the bug**
After pulling the latest commits, from tag 0.2.28 to https://github.com/mynodebtc/mynode/commit/97afc3f2ca4090cb62de7d08b094596101a3a47b
there is a flood of Tor errors in the Bitcoin log:
```connect() to 127.0.0.1:9050 failed after select(): Connection refused (111)```

**MyNode hardware (please complete the following information):**
RockPRO64

**Additional context**
May be an issue with the Tor backup commit, the permissions for the directory /var/lib/tor were incorrect (2755 instead of 2700).
Executing:
```sudo chmod 2700 /var/lib/tor```
then reverting the Tor backup commit, and restarting solved the issue. 

After fixing, I haven't tried re-implementing the Tor backup commit.

**Comment by tehelsper** [comment]
Thanks for letting me know. I tried reproducing and was not able to, even on my RockPro64. Checking the permissions on all devices seemed fine.

If you re-upgrade, could you let me know if it happens again and if just modifying the permissions fixes the issue?

Also, the tor log may be helpful as well in case it offers any other insight into what was going on.

**Comment by tehelsper** [comment]
I was able to reproduce it and resolve. Permissions on that folder could get changed from debian-tor accidentally.
