### ISSUE TITLE
Tor failure leading to failing bitcoin and/or lightning

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#50]
Sometimes resetting Tor from the settings page solves the issue.

**Comment by rico2095** [comment]
I am having the same issues now for a few days, have tried resetting tor and rebooting but no luck.
Was working excellent until then

**Comment by tril0byte** [comment]
If you are having this issue, see if it was for the same reason as me
- lnd requires Tor to start
- Tor requires an accurate clock to start
- myNode uses systemd-timesyncd to set the clock
- systemd-timesyncd is configured with DNS names for its NTP servers
- DNS requires /etc/resolv.conf to contain a valid nameserver line
- resolv.conf is created by the startup script, see issue #133 
- If any of these are blocking your node, fix them and reboot

**Comment by tril0byte** [comment]
There's multiple issues going on here. The first issue is the clock is always wrong on the Pi 4 on boot. There is no Real Time Clock saved on the hardware, so Pi depends on a network time server. I believe some script is writing to systemd-timesyncd.service unit file which causes systemd to refuse to start the unit:

admin@myNode:/mnt/hdd/mynode/bitcoin $ sudo systemctl start systemd-timesyncd
**Warning: The unit file, source configuration file or drop-ins of systemd-timesyncd.service changed on disk. Run 'systemctl daemon-reload' to reload units.**

To work around this every time my Pi boots MyNode:
sudo systemctl daemon-reload
sudo systemctl start systemd-timesyncd

After this point, it seems Tor, then LND both may need manual restarts... or I'm not waiting long enough. I wasn't able to find what writes to the systemd timesyncd unit file as the text timesyncd doesn't occur in /usr/bin - possibly a batch copy.

**Comment by tehelsper** [comment]
Tor is not on a much newer version. Closing.
