### ISSUE TITLE
Unable to access GUI after v0.2.29 update

### ISSUE THREAD

**Issue by khny258** [mynodebtc/mynode#501]
Hi Taylor, I'm a myNode premium user. I tried to upgrade myNode on my rockpro64 last night and I haven't been able to access the GUI ever since. When I ping the local IP, it shows myNode up and running. What should I do?

**Comment by johandegrieck** [comment]
Same here, I'm premium user, pushed the upgrade button yesterday, but didn't reach GUI afterwards.. I can also successfully ping my MyNode... What can I do see my beloved homescreen on http://mynode.local again?

**Comment by wksantiago** [comment]
I have the same problem since this morning after the upgrade.

**Comment by richardwhatever** [comment]
Same

**Comment by wksantiago** [comment]
> A new dependency was added for QRCode generation last release. If it did not install properly, the web UI may not start.
> 
> Accessing the Linux Terminal: https://mynodebtc.com/guide/debug_access_linux_terminal
> 
> Try running this via SSH:
> 
> `sudo /usr/bin/mynode_post_upgrade.sh`
> 
> That will kick it to re-install any dependencies. The specific issue could be fixed by this though:
> 
> `sudo pip2 install qrcode image`

Try running this via SSH:

sudo /usr/bin/mynode_post_upgrade.sh

How long does this command runs for?

**Comment by tehelsper** [comment]
Yeah, that script is the heart of each upgrade and can take anywhere from 5min to ~1hr depending on what needs to be installed.

You may need to reboot after the script finishes. It will set the device in an "upgrading" state, but does not trigger a reboot.

**Comment by wksantiago** [comment]
Indeed exactly what happened thanks

**Comment by khny258** [comment]
My myNode is back. Thanks @tehelsper!!

**Comment by richardwhatever** [comment]
Worked for me too.

**Comment by johandegrieck** [comment]
Yup, resolved!
