### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by Jonesy760** [mynodebtc/mynode#502]
I have an NGINX server already running on my network. I know that its not possible to have two NGINX servers on a network without some other things but I was wondering if there is a way prior to booting mynode that I can edit the NGINX file to proxy to my current NGINX server so that i can get mynode to work on the network. 

If i have the wrong plan please correct me if im wrong, im not an expert, just a hobbyist looking to get mynode working with my current nginx server or if there is another way please send me ur ideas.

**Comment by tehelsper** [comment]
There shouldn't be a problem. NGINX runs completely internal to myNode, so nothing else on your network should care.

**Comment by Jonesy760** [comment]
ah okay thank you. am I able to ask more questions here or should I find another place to ask them? @tehelsper

**Comment by tehelsper** [comment]
Try Telegram or the other options listen on mynodebtc.com/support. I'll close this issue.
