### ISSUE TITLE
Clone Error after finish

### ISSUE THREAD

**Issue by MyNameIsOka** [mynodebtc/mynode#505]
**Describe the bug**
After the cloning tool finishes, I get the error `Clone failed: Command 'e2fsck -y -f /dev/sda1' returned non-zero exit status 8`.
I am cloning from a 1 TB HDD to a 1 TB SSD.

**Expected behavior**
The copying process should finish correctly.

**Screenshots**
![photo_2021-04-06 07 14 15](https://user-images.githubusercontent.com/18796117/113633414-e1fb9c00-96a7-11eb-8c57-c9e1ea64d90a.jpeg)

**Desktop:**
Every browser shows the same.
OS Big Sur

**MyNode hardware:**
 - Device: Raspi4
 - Version 0.2.29

**Comment by tehelsper** [comment]
Does this occur after the clone seems to complete? You could try just attaching the new drive - it may have succeeded enough to start working.

**Comment by MyNameIsOka** [comment]
Yes, after the clone completes, this check is apparently done.
I tried rebooting with only the new drive attached and it recognized the drive as a completely new drive and wanted to format it again.

**Comment by tehelsper** [comment]
Interesting. With the new drive only attached you could try running these commands via the Linux Terminal.

sudo e2fsck -y -f /dev/sda1
sudo resize2fs /dev/sda1
sudo reboot

I'm assuming the drive is labeled sda1. Those are the only two remaining steps. Are you sure the new SSD is larger and the clone occurred in the proper direction? Sometimes 1TB can be smaller than another drive's 1TB size?

**Comment by MyNameIsOka** [comment]
Thanks, I will try that.

Well, both drives are 1 TB, and the old drive only uses ~550 GB. 

Yeah, the cloning was in the right direction.

> Sometimes 1TB can be smaller than another drive's 1TB size?

What can I do in that case?

**Comment by tehelsper** [comment]
I'm not 100% sure, but if it cloned in the proper direction and succeeded it's probably not a concern. If you re-attach both drives, the clone tool should show the sizes.

**Comment by MyNameIsOka** [comment]
I tried what you described and when I did `sudo e2fsck -y -f /dev/sda1` I got the message
![image](https://user-images.githubusercontent.com/18796117/113843082-43b62600-97ce-11eb-96b0-4b2c23d8db9e.png)
I tried the 2 suggestions but that resulted in the same error.

I tried it with /dev/sda and got a similar error, however at the bottom it said:
`Found a gpt partition table in /dev/sda`
I tried it with /dev/sda because I noticed that in the beginning when starting the cloning process, the SSD actually shows /dev/sda:
![cloning1](https://user-images.githubusercontent.com/18796117/113844521-86c4c900-97cf-11eb-80e7-f81fd24f6f65.png)

Do you have any other idea how to proceed from here?
Thanks a lot for your support!

**Comment by tehelsper** [comment]
That makes me think the cloning itself may have failed. You could always keep the device in this state and manually run the clone command (hacky, but any errors may be more visible).

CAUTION - VERIFY THIS COMMAND OR IT MAY ERASE DATA
sudo dd bs=64K if=/dev/sdb of=/dev/sda conv=sync,noerror

Then, you may need to run the following two commands from above as well. That is pretty much the heart of the clone tool.

**Comment by MyNameIsOka** [comment]
Can I manually run the clone command while mynodeBTC is running?
I only have a MacOS machine which doesn't recognize the file system of the external HDD.

I looked for the currently running HDD in myNode by doing SSH into it. Running `mount` gave me quite a lot of results:
![image](https://user-images.githubusercontent.com/18796117/113974501-ff339480-9878-11eb-9487-da32d1e0f42f.png)

It seems that the currently running HDD is registered as /dev/sda1, right?

So your previous command would become:
`sudo dd bs=64K if=/dev/sda1 of=/dev/sda conv=sync,noerror` (have to verify what device ID the SSD would have)

**Comment by tehelsper** [comment]
No, you would run it while the clone tool is open, but not doing anything at the choice prompt where it shows two drives. That would be a state where neither drive is mounted and in-use.

Also, the clone would be between the two block devices (sda and sdb) - they can change which is which drive. Cloning from sda to sda1 would likely corrupt the drive.

**Comment by MyNameIsOka** [comment]
Thank you for your support! The manual cloning process worked.
I didn't do it while the clone tool was open, but manually stopped all mynode services.
The SSD is now correctly cloned and running smoothely.

Thanks again!
