### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#51]
- [x] don't show other QS options when it's disabled
- [x] example commands on bitcoin-cli page
- [x] temperature on remote login

**Comment by Amiga500** [comment]
I was thinking if it wouldn't be better to center the buttons into the settings page (but not the lowest one like "Check for the update" and "Open Glances")

**Comment by abhiShandy** [comment]
Centering the buttons would be very useful for mobile design, and they would look good if they span the entire width.

IMO these things should be part of the UI revamp in the near future when we use Bootstrap (or something else) to make the entire web-app responsive (and more modern).

**Comment by tehelsper** [comment]
I like the center / full width on mobile, but I do like the left -> right flow on desktop browsers.

**Comment by tehelsper** [comment]
I don't think I understand temp on remote login. Can you explain?

**Comment by abhiShandy** [comment]
![Screen Shot 2019-11-12 at 9 22 33 PM](https://user-images.githubusercontent.com/6998593/68727592-d67b7280-0592-11ea-8085-04c2e721e38a.png)

Show temperature on the shell after login, just like memory usage.
