### ISSUE TITLE
Unable to create and start systemd service

### ISSUE THREAD

**Issue by Prabhudevaraju** [mynodebtc/mynode#510]
**Describe the bug**

I'm trying to create a systemd service to call a python program which displays BTC price and block info on screen. 
when I run the python script manually, it works. But tried to create as service and start, it is not working.

 sudo systemctl start lcd.service

Service file info.
-------------------------------------
[Unit]
Description=lcd
After=multi-user.target

[Service]
WorkingDirectory=/home/admin/TBM/TBMLCD-v0.2/MyNodeLCDV2_0_4/
Type=simple
ExecStart=/usr/bin/python3 /home/admin/TBM/TBMLCD-v0.2/MyNodeLCDV2_0_4/MyNodeLCD.py
User=admin
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=lcd
Restart=always

[Install]
WantedBy=multi-user.target

--------------------------------------

**Expected behavior**
systemd service should run python script when mynode boots.

**Screenshots**

**Desktop (please complete the following information):**

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version 0.2.24

**Additional context**
Am I missing anything while starting the service ?

**Comment by tehelsper** [comment]
You likely don't have the dependencies available when being run via systemd. You can also enable is to run automatically via:
systemctl enable lcd

Check the log  of the new service using this:
journalctl -f -u lcd

That should show you the errors the script is running into.

**Comment by Prabhudevaraju** [comment]
Hi Taylor,

Managed to enable the service but when I tried to start the service, it get stuck.  and the log is empty. 
wondering what could be the reason. 

admin@myNode:/etc/systemd/system $ systemctl enable lcd
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-unit-files ===
Authentication is required to manage system service or unit files.
Authenticating as: admin
Password:
==== AUTHENTICATION COMPLETE ===
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: admin
Password:
==== AUTHENTICATION COMPLETE ===
admin@myNode:/etc/systemd/system $ systemctl start lcd
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'lcd.service'.
Authenticating as: admin
Password:
==== AUTHENTICATION COMPLETE ===



admin@myNode:/etc/systemd/system $ journalctl -f -u lcd.service
-- Logs begin at Tue 2021-04-13 13:17:04 CDT. --

**Comment by Prabhudevaraju** [comment]
used rc.local to call the python program.
