### ISSUE TITLE
Mempool App error after upgrade to 0.2.30

### ISSUE THREAD

**Issue by gogomickey** [mynodebtc/mynode#515]
Raspberry pi 4

After upgrading to newest firmware version my mempool app no longer works.  I have tried upgrading manually again, reinstalling the app, etc with no success.  Any ideas how to resolve this?

**Comment by gogomickey** [comment]
From my mempool logs.  Any ideas?

Apr 22 16:06:40 myNode systemd[1]: Failed to start Mempool.
Apr 22 16:06:40 myNode systemd[1]: mempool.service: Failed with result 'exit-code'.
Apr 22 16:06:40 myNode systemd[1]: mempool.service: Control process exited, code=killed, status=15/TERM
Apr 22 16:06:40 myNode systemd[1]: mempool.service: Start-post operation timed out. Stopping.
Apr 22 16:06:31 myNode mempool[31562]: + sleep 10s
Apr 22 16:06:31 myNode mempool[31562]: Waiting to initialize mempool DB...
Apr 22 16:06:31 myNode mempool[31562]: + echo 'Waiting to initialize mempool DB...'
Apr 22 16:06:31 myNode mempool[31562]: + '[' false == true ']'
Apr 22 16:06:31 myNode mempool[31562]: + isRunning=false
Apr 22 16:06:31 myNode mempool[31562]: ++ docker inspect '--format={{.State.Running}}' mempool_db_1
Apr 22 16:06:31 myNode mempool[31562]: + '[' 1 ']'
Apr 22 16:06:21 myNode mempool[31562]: + sleep 10s
Apr 22 16:06:21 myNode mempool[31562]: Waiting to initialize mempool DB...
Apr 22 16:06:21 myNode mempool[31562]: + echo 'Waiting to initialize mempool DB...'
Apr 22 16:06:21 myNode mempool[31562]: + '[' false == true ']'
Apr 22 16:06:21 myNode mempool[31562]: + isRunning=false
Apr 22 16:06:21 myNode mempool[31562]: ++ docker inspect '--format={{.State.Running}}' mempool_db_1
Apr 22 16:06:21 myNode mempool[31562]: + '[' 1 ']'
Apr 22 16:06:11 myNode mempool[31562]: + sleep 10s
Apr 22 16:06:11 myNode mempool[31562]: Waiting to initialize mempool DB...
Apr 22 16:06:11 myNode mempool[31562]: + echo 'Waiting to initialize mempool DB...'
Apr 22 16:06:11 myNode mempool[31562]: + '[' false == true ']'
Apr 22 16:06:11 myNode mempool[31562]: + isRunning=false
Apr 22 16:06:11 myNode mempool[31562]: ++ docker inspect '--format={{.State.Running}}' mempool_db_1

**Comment by tehelsper** [comment]
After re-install, what does the docker image log show on the status page?

Also, can you run:

sudo systemctl status mempoolspace
sudo systemctl status mempool
docker ps

**Comment by gogomickey** [comment]
I ended up restarting docker and mempool space was operational again.

**Comment by Jacksper13** [comment]
@gogomickey is it resolved? If you don't have the issue on v0.2.31 - can the issue be closed?

Thanks!

**Comment by tehelsper** [comment]
Sounds resolved. Closing. Re-open if not.
