### ISSUE TITLE
LND - enabled watchtower, then switched off - doesn't start again

### ISSUE THREAD

**Issue by atom686** [mynodebtc/mynode#518]
Accidentally I've enabled "Watchtower" toggle in Lightning wallet settings. Lightning wallet interface changed to a different one, with lot less fields. Then I switched watchtower toggle off, but Lightning wallet interface remained the same. Tried to restart the node, Lightning gets stuck at "Opening DB"

Mynode 2.30, Raspi4

**Comment by atom686** [comment]
![2021-04-22 18 31 29](https://user-images.githubusercontent.com/70887271/115751005-08ecea00-a399-11eb-89c4-fbf551efb163.jpg)
It's stuck on this screen

**Comment by atom686** [comment]
<img width="782" alt="Screen Shot 2021-04-22 at 18 33 01" src="https://user-images.githubusercontent.com/70887271/115751254-4c475880-a399-11eb-8505-b79323a5c1e0.png">
stuck on this screen

**Comment by atom686** [comment]
40 minutes later resolved by itself. 
Don't switch Watchtower toggle on if you don't want to get grey hairs

**Comment by tehelsper** [comment]
Did you happen to grab the log from LND while it was opening DB? It would show what is was doing during that time. Every time I have toggled it, it went very fast. I'm not sure what it could have been doing.
