### ISSUE TITLE
Improve initial setup UX

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#52]
1. Show all stages (completed, current, next) during setup, quicksync, reboot, etc
2. Option to show verbose details
3. Option to interrupt the process

**Comment by tehelsper** [comment]
I'd like to see this focused on upgrades first. I am pretty sure I have seen a handful of upgrades that don't fully finish before the reboot for some reason. Being able to see detailed info during this process would be helpful.

**Comment by abhiShandy** [comment]
I agree, one click upgrade is interrupted if an impatient user reloads the page.

**Comment by tehelsper** [comment]
Closing - refreshes now will not interrupt upgrade.
