### ISSUE TITLE
Text out of place when not in full screen 

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#520]
When not in full screen mode (screenshots below taken when browser is moved to half screen) some of the menus overlap each other and text gets out of their designated box. Definitely not a priority, just FYI

![image](https://user-images.githubusercontent.com/63911988/116528591-4cd17900-a8dc-11eb-88f5-6761986d85c7.png)

![image](https://user-images.githubusercontent.com/63911988/116528792-83a78f00-a8dc-11eb-949f-9b5cfdba05e1.png)

![image](https://user-images.githubusercontent.com/63911988/116531762-cdde3f80-a8df-11eb-9d6b-804ea2048c94.png)

Mynode v0.2.30

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Yeah, I know about this to some extent. Min screen width needs to be at least ~1200px. Most phones can emulate that relatively well and it basically is found on all modern monitors.

**Comment by Jacksper13** [comment]
Gotcha - no pending action items then? If you wanna look into it I'll leave the issue open, If you consider there's not much that can be done in this regard I'll close it.

Thanks!

**Comment by tehelsper** [comment]
No plans to do anything soon and, if anything, Id' prioritize supporting using the full screen better over getting small screens to work perfectly. Neither are high priority at the moment though.

**Comment by Jacksper13** [comment]
Sounds good!
