### ISSUE TITLE
Unable to login to the new Lighning Terminal that was added in the 0.2.30 update

### ISSUE THREAD

**Issue by Z-and** [mynodebtc/mynode#523]
I noticed this was added but first thing it does is ask for a password. Both my lightning wallet password and default "bolt" password didn't work. How are we supposed to access this? Is there another default password? 

Thanks

**Comment by tehelsper** [comment]
Yes, there is another password. The password used by Lightning Terminal is (unfortunately) stored in plaintext on the device, so I cannot re-use your existing password without compromising security. To prevent password re-use and increase security, myNode randomly generates a password for use by Lightning Terminal.

To find the password, go to the main Lightning page and then click on the "Show Password" button for Terminal.

**Comment by Jacksper13** [comment]
@Z-and if you hit "Wallet" in the Lightning area in the main page, you can see it in there (see below) - let us know if it worked and if so, please close the issue! =)

![image](https://user-images.githubusercontent.com/63911988/116862056-75bb7c00-ac04-11eb-8344-ff8546486080.png)

**Comment by Z-and** [comment]
Great thank you, all set!
