### ISSUE TITLE
Typo in Bitcoin version in release notes

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#525]
On v0.2.31 Bitcoin release says 0.2.21 instead of v0.21.1. Reported by @Max21000000 on TG

![image](https://user-images.githubusercontent.com/63911988/116920520-0456ea00-ac53-11eb-9c44-09e0ceee023c.png)

**Comment by tehelsper** [comment]
Ugh. Typo that got copied / pasted in several places. Fixed now.
