### ISSUE TITLE
Reset bitcoin config

### ISSUE THREAD

**Issue by as-schug** [mynodebtc/mynode#528]
If I reset the bitcoin config, it uses wrong values.

Based on total amount of memory, 8Gb in my case, maxmempool should be 500 and dbcache should be 2500.
Instead, it is dbcache=500 and maxmempol=50.

It is determining this values if the total amount of memory could not be determined or the variable $TOTAL_RAM_GB is not initialized.

Desktop
 - Brave Browse
 - Version 1.23.75

MyNode hardware
 - Device: RASPI4 8 GB Memory
 - Version 0.2.31

**Comment by tehelsper** [comment]
If you reboot the device and check the config again, does it still use the incorrect values? Or is it only after resetting the config?

**Comment by as-schug** [comment]
It got those values after mynode upgrade to version 0.2.31. So I tried to reset config, but that values were the same.

**Comment by tehelsper** [comment]
You're right, I was able to reproduce the bug. The config gen script will now be run before each instance of Bitcoin restarting which caused the TOTAL_GB_RAM variable to be unset, causing it to use default values. Fix is in for next release.

**Comment by as-schug** [comment]
Fixed
