### ISSUE TITLE
Donation system improvement and proposal to encourage donations in the community edition

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#529]
![image](https://user-images.githubusercontent.com/63911988/117166875-1063b880-adc7-11eb-8853-ac5ea8edab51.png)

In the community edition, putting an xpub generating bc1 addresses instead of having a static address would be helpful for 2 reasons:

1) No one knows how much has been donated so far
2) Uniquely identifying each payment would allow to reward donations. For example, you could make it so that if someone donates 75% of the cost of the premium in BTC they could automatically get a premium license

The main concern is how to track unique payments (to give away community upgrade rewards) _**without tracking users**_ - no one should be able to trace funds back to a single user.

Ideas for the unique bc1 address generation without tracking users:
- Randomly generate a number between 1 and 2^256 every **first time** mynode is initialized and use that random number as the derivation path to calculate the bc1 address from the xpub
     - Pros: Allows for _highly likely_ unique bc1 addresses to be generated (or at least same likeliness of generating a seed phrase from zero and finding out it already has funds), that can be saved locally in plaintext and "remembered" in that unique machine
     - Cons: You would have to hard code the xpub in the code, that kind of beats objective 1), even though it does shield you a bit. It would still be not-straight forward for the average mynode user to track all the funds sent to that xpub (need to track all derivation paths) - in any case, better than current situation.
- Make a call home every **first time** mynode is initialized (only if the call is done through TOR to make it impossible to identify any IP), keep the xpub and counter on your side and just provide a unique bc1 address to each call to be placed in the donation field. Note that this would only be acceptable if the communication is done through TOR. If a secure connection can't be established you can always default back to a generic bc1 address and opt out of the rewards - current scenario.

Two ideas on how to apply the reward:
 - One time payment: you have your unique bc1 address, you make a payment for, say, 75% of the cost (should update $/BTC ratio on a daily basis or so) of the premium, you get an automatic upgrade (something like the code showing up when you hit the donation goal, and automatically applying it)
 - Allow for stacked up payments: If you pay half of it now, it will stay there (a nice GUI helps, something like "X/Y for license upgrade!") and you can donate more whenever you want to, until you hit the goal over time (no one else has that bc1 address after all)
    - What happens when the price goes up or down and you donated X/Y?
        - I would keep _Y_ variable and get it adjusted every day/week, so even if you donate $25 today, if BTC goes up x3, the day it hits $75 you'll get the upgrade. This would encourage people to donate, even if it's just a bit, and reward long time "community" users.
        
Not a typical feature request, but I guess an idea to keep in the back burner to encourage donations in BTC.

MyNode v0.2.31

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Cool ideas, but I'm not really looking for profit out of the donations. I keep thinking I'm going to donate it to a hot project at some point, but there's only like $100 in there and haven't decided who to send it to.

I like the idea of encouraging donations - I think it would be really cool to setup something like this + lnd donations to go directly to the projects included within myNode. For example, a user that really likes RTL and Electrs could install an update to the app and donate $2 or something.

Do paynyms help the identity issue? I'm not very familiar with them, but they seemed to help solve a similar problem from what I remember.

**Comment by Jacksper13** [comment]
Oh that would be dope! Maybe contact the creators of each app and ask them for a Nym to put it by each application in the applications section?

**Comment by Jacksper13** [comment]
Anyway, I liked your position on this, no need to keep this open
