### ISSUE TITLE
mynode_upgrade.sh is crashing without completing the update

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#533]
**Describe the bug**
Attempting to upgrade from 0.2.30 to 0.2.31 has failed with the following log contents:

```
++ cat /opt/upgrade/out/rootfs_raspi4/usr/share/mynode/version
+ VERSION=0.2.31
+ '[' 0 = 1 ']'
+ cp -rf /opt/upgrade/out/rootfs_raspi4/etc /opt/upgrade/out/rootfs_raspi4/home /opt/upgrade/out/rootfs_raspi4/lib /opt/upgrade/out/rootfs_raspi4/opt /opt/upgrade/out/rootfs_raspi4/usr /opt/upgrade/out/rootfs_raspi4/var /
+ 'CE_TYPE}/*' /
/usr/bin/mynode_upgrade.sh: line 58: CE_TYPE}/*: No such file or directory
/usr/bin/mynode_upgrade.sh: line 59: syntax error near unexpected token `fi'
/usr/bin/mynode_upgrade.sh: line 59: `fi'
```
This failure results in the system believing it has upgraded and it displays 0.2.31 which it hasn't upgraded to.

**Expected behavior**
That the upgrade completes successfully.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version 0.2.30

**Additional context**
I have removed the torify commands from mynode_upgrade.sh 

Nothing else to add, except to note that the system is partially updated (via the cp above) but the post-upgrade doesn't run for the apps.

Also, no idea where the `'CE_TYPE}/*' /` comes from, the `${DEVICE_TYPE}` is properly expanded in the cp command and executed.

**Comment by tehelsper** [comment]
Ah yeah, making changes to this file is VERY sensitive. Because the extraction of the tarball overwrites the file, the script can fail because the file has changed while it is being executed.

I actually just added a semi-fix recently. When launching mynode_upgrade.sh from the web UI, it will try again if the first fails since the first failure may be caused by this script being updated.

**Comment by HamishMacEwan** [comment]
Thanks for clarifying that…

Seems I'm left with an upgrade that fails because I change the script, or one that fails because Tor is slow and unreliable.  I've left some error messages in a different issue.

Meanwhile, what runs before mynode_upgrade.sh?  If I knew that I could probably finish the upgrade by... if not by hand, by using a script that begins where the overwritten one fails...

**Comment by tehelsper** [comment]
If you run "df -h" you can check to see if the drive is actually out of space or if the complaint is due to the ramlog filling up and causing updates to fail. That was a problem about a year ago, but seems mostly resolved now.
