### ISSUE TITLE
GUI for "Uninstall" button under Applications on v0.2.32 dark mode seems off

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#534]
The uninstall button in dark mode for v0.2.32 seems off... The main issue being that the text "uninstall" can barely be read. A higher contrast between text and background color would be appreciated! Maybe a darker red?

![image](https://user-images.githubusercontent.com/63911988/118243922-4841be80-b49f-11eb-8f2f-c8cd7242ef8f.png)

Mynode v0.2.32

**Comment by tehelsper** [comment]
Ah, missed that. Fixed in https://github.com/mynodebtc/mynode/commit/f01b96cb994ed9d077a660456545fec2b15bcafc
