### ISSUE TITLE
Transparent vs opaque background in the applications, status and settings pages

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#535]
In the main screen all menus are opaque and are on top of the background, but in the status, settings or applications pages tables have transparent backgrounds that make elements hard to read with some of the background pictures (happens for both, laser eyes and moon).

This transparency/opaqueness is also inconsistent across dark and light modes, see below. In any case, I would argue a solid background for the text would make everything easier to read. It'd also feel cleaner.

![image](https://user-images.githubusercontent.com/63911988/118250140-6eb72800-b4a6-11eb-97b5-6700b15cd6c4.png)
![image](https://user-images.githubusercontent.com/63911988/118250328-a32ae400-b4a6-11eb-8301-fba0ff5a9026.png)
![image](https://user-images.githubusercontent.com/63911988/118250234-87274280-b4a6-11eb-91ab-84e76e277012.png)
![image](https://user-images.githubusercontent.com/63911988/118250298-99a17c00-b4a6-11eb-8623-90568f81daba.png)
![image](https://user-images.githubusercontent.com/63911988/118250444-c786c080-b4a6-11eb-87ac-058c4ed93a0e.png)

Mynode v 0.2.32

**Comment by Jacksper13** [comment]
The same applies to upgrade/install logs

![image](https://user-images.githubusercontent.com/63911988/118261634-1edf5d80-b4b4-11eb-8796-05e6eb415bba.png)

**Comment by tehelsper** [comment]
If you can, can you let me know what you think after the changes in https://github.com/mynodebtc/mynode/commit/f01b96cb994ed9d077a660456545fec2b15bcafc

I think it looks cleaner now.

**Comment by Jacksper13** [comment]
Looking good!
