### ISSUE TITLE
mynode_startup.sh fails on btcpayserver setup

### ISSUE THREAD

**Issue by RR82** [mynodebtc/mynode#537]
**Describe the bug**
mynode_startup.sh fails on btcpayserver setup

**Expected behavior**
successful startup

**Screenshots**
shows up in the mynode status page, mynode startup status as 'error' and the log indicates the error due to trying to cp a non-existent file

**MyNode hardware (please complete the following information):**
 - Device: RockPRO64
 - Version 0.2.32

**Additional context**
see comment on commit 3f50a811213e58f9616f6bdad10329a2a8540f60 for a potential fix

I am not sure if I need to comment on the commit and submit a new issue, so let me know if this is redundant information.

**Comment by tehelsper** [comment]
Can you try upgrading to v0.2.33? It has a fix that should prevent this issue.

**Comment by RR82** [comment]
Yes, fixed in v0.2.33, thanks!
