### ISSUE TITLE
Can't upgrade: mynode-local-upgrade timing out

### ISSUE THREAD

**Issue by bucko13** [mynodebtc/mynode#539]
**Describe the bug**
After getting the server running on the dev machine with the latest tagged release, I try and run the upgrade command on the mynode. Unfortunately it just hangs and eventually times out.

It cycles through this on an endless loop:

```
--2021-06-09 21:45:35--  http://192.169.1.39:8000/mynode_rootfs_raspi4.tar.gz
Connecting to 192.169.1.39:8000...
```

**Expected behavior**
According to [the docs](This will download your locally generated artifact and install it on your device
Your device will automatically reboot to ensure updates take effect):

> This will download your locally generated artifact and install it on your device
Your device will automatically reboot to ensure updates take effect

**Desktop (please complete the following information):**
N/a. Running this on a macos 

**MyNode hardware (please complete the following information):**
-  Raspi4
 - Version 0.2.19

**Additional context**
I can confirm the file server is running on my local machine as I can access it at the correct port from other machines. It's just the mynode that seems to be timing out.

**Comment by tehelsper** [comment]
Have you started the file server and run "make rootfs" or "make rootfs_auto" to make the local upgrade file?

**Comment by bucko13** [comment]
Yes, the file server is running and as I mentioned I can even access it from other devices on the LAN. I'd also ran `make rootfs` but not `make rootfs_auto` (only the first one is in the README). But the `auto` version just spits out an endless loop of `./make_rootfs_auto.sh: line 16: entr: command not found` anyway. Accessing the file server I can even see the different tarballed upgrade files.

**Comment by tehelsper** [comment]
Yeah, only one is needed. Can the device ping the 192.169.1.39 address? I'm not sure how it could be unable to connection unless it was on a different network.

**Comment by bucko13** [comment]
Hmmm, yeah ok so pinging says it's unreachable. But it is on the same network. I'm SSH'd in via a locally assigned IP, I can access mynode.local, I can even ping the IP of the mynode device from the dev machine, just not vice versa. Are there any settings on the device that would be blocking outgoing connections like that? I also rebooted the device in case there was some errant setting that needed to be reset.

**Comment by tehelsper** [comment]
Can it ping anything else, like 8.8.8.8 or google.com? Does anything else seems broken?

You try "sudo ufw disable" to see if its the firewall, but I'm not sure how that would be causing this issue.

**Comment by bucko13** [comment]
It can ping 8.8.8.8 and everything else seems normal. The bitcoin node is running and lightning is working as well. I do have sphinx setup on the machine which hasn't been reachable (and was actually what prompted me to try and upgrade), but that's the only thing out of the ordinary. ran `sudo ufw disable` on the device and still nothing.

Is there anything about the raspi being on ethernet and the dev machine being on wifi that could be causing issues?

**Comment by bucko13** [comment]
So, I was able to get this working by using a demo user on my device. Same IP just much less running, so there's clearly something on my device blocking incoming connections. It's strange because I could ping the device from the problem user from other devices on the LAN, but for some reason the mynode couldn't. I even made sure all firewalls, etc. were shutdown. Anyway, for anyone else running into the same thing, try and run the upgrade server from another device or as blank of a setup as possible.
