### ISSUE TITLE
Loop "server.proto" error

### ISSUE THREAD

**Issue by MWDJ** [mynodebtc/mynode#540]
After upgrade to 0.2.34, running loop in console results in the following error:

admin@myNode:~ $ loop monitor
2021/06/09 21:59:07 WARNING: proto: file "server.proto" has a name conflict over looprpc.FAILURE_REASON_TIMEOUT
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/06/09 21:59:07 WARNING: proto: file "server.proto" has a name conflict over looprpc.FAILURE_REASON_NONE
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/06/09 21:59:07 WARNING: proto: file "server.proto" has a name conflict over looprpc.UNKNOWN
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/06/09 21:59:07 WARNING: proto: file "server.proto" has a name conflict over looprpc.SUCCESS
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/06/09 21:59:07 WARNING: proto: file "server.proto" has a name conflict over looprpc.HTLC_PUBLISHED
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/06/09 21:59:07 WARNING: proto: file "server.proto" has a name conflict over looprpc.INITIATED
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

Note: offchain cost may report as 0 after loopd restart during swap
 
[Rest of loop command executes as expected]

**Expected behavior**
Loop should run normally and not threaten to panic!

**MyNode hardware:**
 - Device: Raspi4B premium
 - Version 0.2.34

-MWDJ

**Comment by tehelsper** [comment]
Should be resolved in the next loop release according to ln devs.

**Comment by MWDJ** [comment]
Warnings are no longer displayed with loop 14.1 after upgrading mynode to 0.2.36.
