### ISSUE TITLE
Lightning Core Service hanging at "Logging in..."

### ISSUE THREAD

**Issue by cd2357** [mynodebtc/mynode#542]
**Describe the bug**
After a restart, in the UI the Lightning Core Service block says "Logging in..." and remains stuck at that.

Logging in via ssh and running `lncli getinfo` I get

```
[lncli] Wallet is encrypted. Please unlock using 'lncli unlock', or set password
using 'lncli create' if this is the first time starting lnd.
```

FYI: This is not the first time starting `lnd`.

After running `lncli unlock` and putting in the password, it unlocks and works as expected.

**Expected behavior**
The UI should give more useful tips instead of "Logging in..." like "Please run `lncli unlock`" or similar

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version: 0.2.34

**Comment by tehelsper** [comment]
Can you check the LND log from the status page? This typically means an issue has occurred and more information will be available from the log.

**Comment by cd2357** [comment]
Here is the log after a restart:

```
-- Logs begin at Sun 2021-06-13 10:29:11 CEST, end at Sun 2021-06-13 10:46:09 CEST. --
Jun 13 10:31:00 myNode lnd[4168]: 2021-06-13 10:31:00.017 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
Jun 13 10:31:00 myNode lnd[4168]: 2021-06-13 10:31:00.016 [INF] RPCS: Password gRPC proxy started at 0.0.0.0:10080
Jun 13 10:31:00 myNode lnd[4168]: 2021-06-13 10:31:00.012 [INF] RPCS: Password RPC server listening on 0.0.0.0:10009
Jun 13 10:31:00 myNode lnd[4168]: 2021-06-13 10:31:00.006 [INF] LTND: Database now open (time_to_open=9.972378442s)!
Jun 13 10:31:00 myNode lnd[4168]: 2021-06-13 10:31:00.004 [INF] CHDB: Checking for schema update: latest_version=20, db_version=20
Jun 13 10:30:50 myNode lnd[4168]: 2021-06-13 10:30:50.034 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
Jun 13 10:30:50 myNode lnd[4168]: 2021-06-13 10:30:50.034 [INF] LTND: Opening the main database, this might take a few minutes...
Jun 13 10:30:50 myNode lnd[4168]: 2021-06-13 10:30:50.033 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jun 13 10:30:50 myNode lnd[4168]: 2021-06-13 10:30:50.033 [INF] LTND: Version: 0.12.1-beta commit=v0.12.1-beta, build=production, logging=default, debuglevel=info
Jun 13 10:30:50 myNode lnd[4168]: Automatically obtained bitcoind's RPC credentials
Jun 13 10:30:50 myNode lnd[4168]: Attempting automatic RPC configuration to bitcoind
Jun 13 10:30:48 myNode systemd[1]: Started LND Lightning Daemon.
Jun 13 10:30:47 myNode lnd[4120]: Not shutting down!
Jun 13 10:30:47 myNode lnd[4120]: Checking if device is shutting down...
Jun 13 10:30:47 myNode systemd[1]: Starting LND Lightning Daemon...
```

**Comment by cd2357** [comment]
I tried reinstalling LND under Manage Applications, but on restart it still ends up in the same state.

**Comment by tehelsper** [comment]
Can you try running this to make sure the unlock service is running?

sudo systemctl status lnd_unlock.service

Also, are there are more messages after that if you wait a while?

Finally, can you run:

sudo mynode-lnd-unlock

Does that unlock the service?

**Comment by cd2357** [comment]
Found the problem.

I somehow had the wrong password in `/mnt/hdd/mynode/settings/.lndpw`. I changed it to the correct one, now LND properly starts after a reboot.

Thanks for the help.
