### ISSUE TITLE
Bitcoin.conf RPC security

### ISSUE THREAD

**Issue by flacogozo** [mynodebtc/mynode#543]
**Describe the bug**
Bitcoin.conf is not setup using proper RFC-1918    https://datatracker.ietf.org/doc/html/rfc1918
Existing setup:
rpcallowip=10.0.0.0/8
rpcallowip=172.0.0.0/8
rpcallowip=192.0.0.0/8

**Expected behavior**
It should be setup to only allow:   
     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)

**Comment by flacogozo** [comment]
Sorry.  Reporting in security

**Comment by tehelsper** [comment]
Which version are you on? I think this may have been resolved although there is some bitcoin.conf cleanup to be done between various device types.

**Comment by flacogozo** [comment]
I installed this week using the OVA.    Under "status" the version is:    0.2.16

**Comment by flacogozo** [comment]
Hi, I just upgraded and the conf file looks good.
