### ISSUE TITLE
bitcoin.conf private IP address space subnets.

### ISSUE THREAD

**Issue by flugelhodl** [mynodebtc/mynode#545]
The default mynode bitcoin.conf seems to have the following lines:

```
rpcallowip=172.0.0.0/8
rpcallowip=192.0.0.0/8
```
and
```
whitelist=bloomfilter@172.0.0.0/8
whitelist=bloomfilter@192.0.0.0/8
```

What these chosen subnets imply is that we're allowing only private address space access to RPC, and 'bloomfilter' which is fair.

However the ranges are too broad and encroach on publicly routable IP address space. Please see the below reference URL:

https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses

```
rpcallowip=172.16.0.0/12
rpcallowip=192.168.0.0/16
```
and
```
whitelist=bloomfilter@172.16.0.0/12
whitelist=bloomfilter@192.168.0.0/16
```

I understand that realistically this isn't a problem, since the node will be behind a NAT firewall, but still. 

Thanks for taking the time to read my issue, and I hope I've not missed something obivous with this, just trying to assist :).

**Comment by flugelhodl** [comment]
I've just searched the code and seen the defaults are correct here, so not sure why my node is resetting to these wrong values :S. Just a leftover old config?

**Comment by tehelsper** [comment]
Yeah, probably left over old config or still on an old version. If you customized your config it makes it "stick" and further myNode updates are not applied. Recent versions should be using the correct subnets.

**Comment by flugelhodl** [comment]
I reset my node's config and it's now got correct values.

I'll close this now and show myself the door :). Sorry for wasting your time.
