### ISSUE TITLE
Lightning DB won't open after v2.36

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#546]
After successfully upgrading to v2.36, LND gets stuck in opening database, it goes back and forth between opening DB and DB open...

![image](https://user-images.githubusercontent.com/63911988/123283808-04b18a00-d50c-11eb-9f66-4993089ebef7.png)
![image](https://user-images.githubusercontent.com/63911988/123284047-3a567300-d50c-11eb-9013-4f54716edcc1.png)

Lightning Terminal status gets stuck constantly repeating:
Jun 24 10:41:01 myNode lit[13745]: 2021-06-24 10:41:01.906 [WRN] GRPC: grpc: addrConn.createTransport failed to connect to {localhost:10009   0 }. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused". Reconnecting...

LND status is red with:
Jun 24 10:44:07 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jun 24 10:44:07 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 10:44:07 myNode lnd[17742]: error reading password from file /mnt/hdd/mynode/settings/.lndpw: open /mnt/hdd/mynode/settings/.lndpw: permission denied
Jun 24 10:44:07 myNode lnd[17742]: 2021-06-24 10:44:07.028 [INF] LTND: Shutdown complete

LNDHub status is red with:
Jun 24 10:45:55 myNode systemd[1]: lndhub.service: Failed with result 'exit-code'.
Jun 24 10:45:55 myNode systemd[1]: lndhub.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR!     /home/bitcoin/.npm/_logs/2021-06-24T08_45_55_610Z-debug.log
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! A complete log of this run can be found in:
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! Failed at the lndhub@1.3.5 start script.
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR!
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! Exit status 3
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! lndhub@1.3.5 start: `babel-node index.js`
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! errno 3
Jun 24 10:45:55 myNode lndhub[18801]: npm ERR! code ELIFECYCLE

On Rpi4 4Gb 32bit

**Comment by Jacksper13** [comment]
Tried reinstalling LND, no progress

**Comment by Jacksper13** [comment]
After some hours in loop, Lightning Terminal Status changed to


Jun 24 14:21:52 myNode systemd[1]: lit.service: Failed with result 'exit-code'.
Jun 24 14:21:52 myNode systemd[1]: lit.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 14:21:52 myNode lit[15229]: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Jun 24 14:21:52 myNode lit[15229]: 2021-06-24 14:21:52.200 [INF] SGNL: Gracefully shutting down.
Jun 24 14:21:52 myNode lit[15229]: 2021-06-24 14:21:52.200 [INF] SGNL: Shutting down...
Jun 24 14:21:52 myNode lit[15229]: 2021-06-24 14:21:52.200 [INF] SGNL: Received shutdown request.
Jun 24 14:21:52 myNode lit[15229]: 2021-06-24 14:21:52.200 [ERR] LITD: Could not start subservers: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Jun 24 14:21:51 myNode lit[15229]: 2021-06-24 14:21:51.948 [WRN] GRPC: grpc: addrConn.createTransport failed to connect to {localhost:10009   0 }. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused". Reconnecting...

**Comment by xxi000000** [comment]
Mine was stuck on "Waiting" after the upgrade. Not sure if it's related to the issue you're seeing, but a reboot fixed it for me.

**Comment by tehelsper** [comment]
That error message makes me think the permissions on your lnd password file are preventing lnd from reading it directly (previously it was a different script which then entered the password).

Can you run this command and share the results:

sudo ls -ls /mnt/hdd/mynode/settings/.lndpw

This may resolve the issue:

sudo chown bitcoin:bitcoin /mnt/hdd/mynode/settings/.lndpw

**Comment by Jacksper13** [comment]
![image](https://user-images.githubusercontent.com/63911988/123384775-155a1280-d595-11eb-82e3-1dd07895e86b.png)

@xxi000000 rebooted a couple of times, same issue.

Running sudo chown bitcoin:bitcoin /mnt/hdd/mynode/settings/.lndpw did however fix it. Thank you!

**Comment by tehelsper** [comment]
Thanks. For some reason, you lnd password file was owned by the root user and the bitcoin user running lnd could not read the file. I can add some code to explicitly prevent that from occurring again.
