### ISSUE TITLE
Previously uninstalled BTCPay Server re-installed after upgrade

### ISSUE THREAD

**Issue by xxi000000** [mynodebtc/mynode#547]
**Describe the bug**
After upgrading myNode, BTCPay Server shows up as installed even though it was previously uninstalled before the upgrade.

**Expected behavior**
None of the other apps I had previously uninstalled appear as installed after upgrading, and I'd expect the same behavior with BTCPay Server.

**Screenshots**
<img width="863" alt="image" src="https://user-images.githubusercontent.com/76971517/123331210-fdd74700-d50c-11eb-8670-a9d01c78dd1d.png">

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 89.0.1

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version: 0.2.36

**Additional context**
N/A

**Comment by tehelsper** [comment]
I tracked down the issue and it will be resolved in the next release. You will have to uninstall the app after upgrading for it to stick.

**Comment by tehelsper** [comment]
https://github.com/mynodebtc/mynode/commit/ddb4d30adadd17a7cc5d1250dcbbe554b7694e6f

**Comment by xxi000000** [comment]
Thank you!
