### ISSUE TITLE
Lightning Terminal error

### ISSUE THREAD

**Issue by craxis** [mynodebtc/mynode#549]
**Describe the bug**
The Lightning Terminal fails to start, it shows an 'error' on the status page, screenshot below. Log with failure info from Lightning Terminal is also below.

![image](https://user-images.githubusercontent.com/33916749/123816295-32f4e800-d8c5-11eb-9bfb-bf9a10368e6e.png)

Jun 29 09:19:47 myNode systemd[1]: lit.service: Failed with result 'exit-code'.
Jun 29 09:19:47 myNode systemd[1]: lit.service: Main process exited, code=exited, status=1/FAILURE
Jun 29 09:19:47 myNode lit[18236]: error starting lnd gRPC proxy server: could not dial remote loop: could not read loop TLS cert /mnt/hdd/mynode/loop/mainnet/tls.cert: open /mnt/hdd/mynode/loop/mainnet/tls.cert: no such file or directory
Jun 29 09:19:47 myNode lit[18236]: 2021-06-29 09:19:47.896 [INF] LITD: Dialing lnd gRPC server at localhost:10009
Jun 29 09:19:47 myNode systemd[1]: Started Lightning Terminal.
Jun 29 09:19:47 myNode lit[18211]: [lncli] rpc error: code = Unknown desc = the RPC server is in the process of starting up, but not yet ready to accept calls
Jun 29 09:19:47 myNode lit[18211]: Checking if LND is synced...
Jun 29 09:19:47 myNode lit[18209]: + exit 0
Jun 29 09:19:47 myNode lit[18209]: }
Jun 29 09:19:47 myNode lit[18209]:   "warnings": ""
Jun 29 09:19:47 myNode lit[18209]:   },
Jun 29 09:19:47 myNode lit[18209]:     }
Jun 29 09:19:47 myNode lit[18209]:       "active": false
Jun 29 09:19:47 myNode lit[18209]:       },
Jun 29 09:19:47 myNode lit[18209]:         "min_activation_height": 709632
Jun 29 09:19:47 myNode lit[18209]:         "since": 687456,
Jun 29 09:19:47 myNode lit[18209]:         "timeout": 1628640000,
Jun 29 09:19:47 myNode lit[18209]:         "start_time": 1619222400,
Jun 29 09:19:47 myNode lit[18209]:         "status": "locked_in",
Jun 29 09:19:47 myNode lit[18209]:       "bip9": {
Jun 29 09:19:47 myNode lit[18209]:       "type": "bip9",
Jun 29 09:19:47 myNode lit[18209]:     "taproot": {
Jun 29 09:19:47 myNode lit[18209]:     },
Jun 29 09:19:47 myNode lit[18209]:       "height": 481824
Jun 29 09:19:47 myNode lit[18209]:       "active": true,
Jun 29 09:19:47 myNode lit[18209]:       "type": "buried",
Jun 29 09:19:47 myNode lit[18209]:     "segwit": {
Jun 29 09:19:47 myNode lit[18209]:     },
Jun 29 09:19:47 myNode lit[18209]:       "height": 419328
Jun 29 09:19:47 myNode lit[18209]:       "active": true,
Jun 29 09:19:47 myNode lit[18209]:       "type": "buried",
Jun 29 09:19:47 myNode lit[18209]:     "csv": {
Jun 29 09:19:47 myNode lit[18209]:     },
Jun 29 09:19:47 myNode lit[18209]:       "height": 388381
Jun 29 09:19:47 myNode lit[18209]:       "active": true,
Jun 29 09:19:47 myNode lit[18209]:       "type": "buried",
Jun 29 09:19:47 myNode lit[18209]:     "bip65": {
Jun 29 09:19:47 myNode lit[18209]:     },
Jun 29 09:19:47 myNode lit[18209]:       "height": 363725
Jun 29 09:19:47 myNode lit[18209]:       "active": true,
Jun 29 09:19:47 myNode lit[18209]:       "type": "buried",
Jun 29 09:19:47 myNode lit[18209]:     "bip66": {
Jun 29 09:19:47 myNode lit[18209]:     },
Jun 29 09:19:47 myNode lit[18209]:       "height": 227931
Jun 29 09:19:47 myNode lit[18209]:       "active": true,
Jun 29 09:19:47 myNode lit[18209]:       "type": "buried",
Jun 29 09:19:47 myNode lit[18209]:     "bip34": {
Jun 29 09:19:47 myNode lit[18209]:   "softforks": {
Jun 29 09:19:47 myNode lit[18209]:   "pruned": false,
Jun 29 09:19:47 myNode lit[18209]:   "size_on_disk": 400143258440,
Jun 29 09:19:47 myNode lit[18209]:   "chainwork": "00000000000000000000000000000000000000001f1a6424a6ddffdb2e9d2127",
Jun 29 09:19:47 myNode lit[18209]:   "initialblockdownload": false,
Jun 29 09:19:47 myNode lit[18209]:   "verificationprogress": 0.9999992845672721,
Jun 29 09:19:47 myNode lit[18209]:   "mediantime": 1624967665,
Jun 29 09:19:47 myNode lit[18209]:   "difficulty": 19932791027262.74,
Jun 29 09:19:47 myNode lit[18209]:   "bestblockhash": "000000000000000000026fcec6cc3dc38557b8a956cac662fef00ad6ec974f80",
Jun 29 09:19:47 myNode lit[18209]:   "headers": 689134,
Jun 29 09:19:47 myNode lit[18209]:   "blocks": 689134,
Jun 29 09:19:47 myNode lit[18209]:   "chain": "main",
Jun 29 09:19:47 myNode lit[18209]: {
Jun 29 09:19:47 myNode lit[18209]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Jun 29 09:19:47 myNode lit[18209]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Jun 29 09:19:47 myNode lit[18209]: Checking if Bitcoin is synced...
Jun 29 09:19:47 myNode lit[18209]: + echo 'Checking if Bitcoin is synced...'
Jun 29 09:19:47 myNode lit[18209]: + set -e
Jun 29 09:19:47 myNode lit[18208]: Not shutting down!
Jun 29 09:19:47 myNode lit[18208]: Checking if device is shutting down...
Jun 29 09:19:47 myNode systemd[1]: Starting Lightning Terminal...

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 89.0.2

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version 0.2.37

**Additional context**
I have stop/started/rebooted several times, no effect.  I have reinstalled Lightning Terminal and LND, did not resolve the issue.

**Comment by tehelsper** [comment]
What does the log for loop show? The error appears to indicated this file does not exist: /mnt/hdd/mynode/loop/mainnet/tls.cert

Can you check to see if that file is there?

**Comment by craxis** [comment]
> 
> 
> What does the log for loop show? The error appears to indicated this file does not exist: /mnt/hdd/mynode/loop/mainnet/tls.cert
> 
> Can you check to see if that file is there?

Loop is running, status is green, and its log has no entries.
![image](https://user-images.githubusercontent.com/33916749/124294727-055aa980-db26-11eb-831d-3064185fadeb.png)


I checked that directory, and there are no files in that directory. Should those cert files be there as part of the setup or cert generating process?

**Comment by tehelsper** [comment]
Yeah, loop should be creating those certificates. That's very unusual. Can you try a reboot and check the loop log after? Logs are only kept for a certain period of time until they are forgotten.

**Comment by craxis** [comment]
Ok, rebooted, Loop status is green, running, but here is the log:

-- Logs begin at Fri 2021-07-02 19:32:19 CDT, end at Fri 2021-07-02 19:36:22 CDT. --
Jul 02 19:34:01 myNode loop[3717]: 2021-07-02 19:34:01.710 [INF] LNDC: Waiting for lnd to unlock
Jul 02 19:34:01 myNode loop[3717]: 2021-07-02 19:34:01.702 [INF] LNDC: Connected to lnd
Jul 02 19:34:01 myNode loop[3717]: 2021-07-02 19:34:01.699 [INF] LNDC: Creating lnd connection to localhost:10009
Jul 02 19:34:01 myNode loop[3717]: 2021-07-02 19:34:01.697 [INF] LOOPD: Version: 0.14.1-beta commit=
Jul 02 19:33:59 myNode systemd[1]: Started loop.
Jul 02 19:33:59 myNode loop[3555]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Jul 02 19:33:58 myNode loop[3555]: Checking if LND is synced...
Jul 02 19:33:58 myNode systemd[1]: Starting loop...

Looks like the connection is being refused, which I assume is why the certs aren't being created.

**Comment by craxis** [comment]
I found the issue. UPnP was disabled on my router, once enabled, these errors went away and Lightning Terminal is now running as expected.
