### ISSUE TITLE
Unable to access lightning wallet after upgrading to 0.2.37?

### ISSUE THREAD

**Issue by Z-and** [mynodebtc/mynode#550]
Ever since I upgraded to 0.2.37 I have been unable to access my lightning wallet. I went to the logs for LND and it shows that the wallet is unlocked (see logs below)

```
Jul 02 16:24:00 myNode lnd[4037]: 2021-07-02 16:24:00.355 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: wallet locked, unlock it to enable full RPC access
Jul 02 16:24:00 myNode lnd[4037]: 2021-07-02 16:24:00.355 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
Jul 02 16:24:00 myNode lnd[4037]: 2021-07-02 16:24:00.355 [ERR] RPCS: [/lnrpc.Lightning/SubscribeInvoices]: wallet locked, unlock it to enable full RPC access
Jul 02 16:23:58 myNode lnd[4037]: 2021-07-02 16:23:58.666 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
Jul 02 16:23:56 myNode lnd[4037]: 2021-07-02 16:23:56.663 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access

```
I ssh'd in and tried unlocking the wallet manually but get the following error (even though I'm typing in the correct password)

`[lncli] rpc error: code = Unknown desc = invalid passphrase for master public key`

Any help would be greatly appreciated...

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version 1.26.67

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version 0.2.37

**Comment by tehelsper** [comment]
Do you have a custom LND config? If so, try resetting that or add the following line:

wallet-unlock-password-file=/mnt/hdd/mynode/settings/.lndpw

See this twitter thread:
https://twitter.com/mynodebtc/status/1409255172967219214

**Comment by Z-and** [comment]
> Do you have a custom LND config? If so, try resetting that or add the following line:
> 
> wallet-unlock-password-file=/mnt/hdd/mynode/settings/.lndpw
> 
> See this twitter thread:
> https://twitter.com/mynodebtc/status/1409255172967219214

That did the trick, thank you!
