### ISSUE TITLE
Minor cosmetic enhancement for Reset Docker button under Settings

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#552]
Increase gap between Reset Docker button and text to match other options under settings.

myNode v0.2.38

![image](https://user-images.githubusercontent.com/63911988/126153664-de03ddb5-7e3d-40f4-b648-2614ca77730f.png)

- [X] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Missing some CSS. Fixed for next release. Thanks.

https://github.com/mynodebtc/mynode/commit/90be0ffbf77dc376cda7f32ba203809142156cc7

**Comment by Jacksper13** [comment]
No prob
