### ISSUE TITLE
Router Problem related to myNode, Blue Wallet and iPhone iOs 14

### ISSUE THREAD

**Issue by gemarti** [mynodebtc/mynode#555]
I am running MyNode (latest version)and my Blue wallet on iOS 14 is connected to it. Every time I get on the network myNode is on with my iPhone my router starts misbehaving and cuts off internet to other family members. What type of network activity is Blue Wallet performing when it connects to myNode? Is there a solution to this problem? 

This is the Community Ed. As I am evaluating.

**Comment by tehelsper** [comment]
I'm not sure how communication between your iPhone and myNode+LNDHub would cause router issues. If you disable LNDHub or kill the app on your phone, are you seeing the same issues?

What type of router do you have?

**Comment by gemarti** [comment]
I am connected to a Spectrum (TWC) supplied ARRIS router. 
When I started getting complaints about connectivity as a test I turned WIFI off on my iPhone and everyone was happy. 
I haven't responded because I am waiting for an opportunity to disable LNDHub to see what happens in the household; it's a intermittent problem and I thought it was maybe a bandwidth issue. 
I am responding now just to keep this thread open for a little longer; this may not be an issue with myNode and if so I apologize. 

Thank you in advance for your assistance.

**Comment by gemarti** [comment]
I am going to close this because I believe my issue was resolved. 
On my router I was using google name servers; I reverted back to using my ISP's name servers and I have not had any further complaints concerning network access since doing so. Have a nice day.
