### ISSUE TITLE
Specter upgrade issue with v0.2.39

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#557]
**Describe the bug**
I upgraded mynode , from 2.38 to 2.39, but specter app was not upgraded to 1.5.1. 
I tried uninstall and reinstall but app do not work anymore. See screenshots 

**Expected behavior**
Sepcter upgrade to 1.5.1
**Screenshots**

<img width="572" alt="image" src="https://user-images.githubusercontent.com/54225190/129536896-02162ce6-90b5-42fd-b3b8-7ca199327df4.png">

--------

<img width="995" alt="image" src="https://user-images.githubusercontent.com/54225190/129536979-f57767b0-aa16-4dcc-98d1-706a65f1caa8.png">

**Desktop (please complete the following information):**
 - Browser [ safari]
 - Version 14.1.2

**MyNode hardware (please complete the following information):**
 - Device: [Raspi4, ]
 - Version []

**Additional context**
Error log:

Starting Specter...
Aug 16 22:01:07 myNode systemd[1]: Stopped Specter.
Aug 16 22:01:07 myNode systemd[1]: specter.service: Scheduled restart job, restart counter is at 1665.
Aug 16 22:01:07 myNode systemd[1]: specter.service: Service RestartSec=30s expired, scheduling restart.
Aug 16 22:00:37 myNode systemd[1]: Failed to start Specter.
Aug 16 22:00:37 myNode systemd[1]: specter.service: Failed with result 'exit-code'.
Aug 16 22:00:37 myNode systemd[1]: specter.service: Control process exited, code=exited, status=200/CHDIR
Aug 16 22:00:37 myNode systemd[14783]: specter.service: Failed at step CHDIR spawning /usr/bin/is_not_shutting_down.sh: No such file or directory
Aug 16 22:00:37 myNode systemd[14783]: specter.service: Changing to the requested working directory failed: No such file or directory
Aug 16 22:00:37 myNode systemd[1]: Starting Specter...
Aug 16 22:00:37 myNode systemd[1]: Stopped Specter.

**Comment by sudo-a9** [comment]
I am experiencing the same thing with Specter.  Nothing would make it work.  Reinstalls, upgrades, nothing.

I am also experiencing the same issue with Whirlpool (did not upgrade).  Thunderhub (did not upgrade, reinstalled and now red).  RTL wouldn't work in Thunderhub's absence.

We need a fix for this ASAP.

**Comment by tehelsper** [comment]
Can you send the upgrade log to the support email or share the specific failure message here (not whole log)? It looks like the upgrade had an issue and isn't finding Specter.

**Comment by tehelsper** [comment]
Looks like Pool changed the naming and functionality of some of their release files regarding checking signatures. That is causing the upgrade script to fail. A fix added in v0.2.40 that should help.

**Comment by imacfan** [comment]
> Looks like Pool changed the naming and functionality of some of their release files regarding checking signatures. That is causing the upgrade script to fail. A fix added in v0.2.40 that should help.

Specter is now fixed with upgrade to 0.2.40. Dojo, mempool and ThuderHub are still having issues. I will see if re-installing , restart helps or not

**Comment by imacfan** [comment]
Dojo , mempool fixed after re-install. But nothing makes ThuderHub work again

**Comment by imacfan** [comment]
I am getting Same error with ThunderHub > mempool

**Comment by sudo-a9** [comment]
> 
> 
> I am getting Same error with ThunderHub > mempool

As am I.

**Comment by tehelsper** [comment]
There is a Thunderhub fix (downgrade) in the latest beta.

**Comment by imacfan** [comment]
Ok. Installing beta now to check > There is a Thunderhub fix (downgrade) in the latest beta.

**Comment by imacfan** [comment]
> There is a Thunderhub fix (downgrade) in the latest beta.

Installed beta. Now still same error when I click thunder hub. Should I uninstall and install again ?

**Comment by imacfan** [comment]
Works now. Issue can be closed.
