### ISSUE TITLE
Upgrading node.js as part of the img for full bos features

### ISSUE THREAD

**Issue by xCaCO3** [mynodebtc/mynode#560]
**Is your content request related to a problem? Please describe.**
bos telegram sync doesn't work with node.js < 12

**Describe the solution you'd like**
Any plans to incorporate with image a newer version?

**Comment by tehelsper** [comment]
I'd like to, but the risk is moderate and it requires all node apps to be re-installed. It's the same reason I can't upgrade Thunderhub past ~12.17.

**Comment by tehelsper** [comment]
To clarify, it's in the plan, it will just take some time and planning. It will be a very big upgrade. I'm actually running nodejs v14 on one of my nodes and it runs very well.

**Comment by xCaCO3** [comment]
Thank you Taylor, sounds like a plan!
