### ISSUE TITLE
64 bit upgrade

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#563]
**Describe the bug**
I am currently running 32 bit version of mynode.
I want to upgrade to the beta version 64 bit.

What are the steps of doing so without losing existing data (bitcoin, lightning)?

thanks!

**Comment by tehelsper** [comment]
Upgrading from 32-bit to 64 bit has not been well tested. The biggest issue is with the docker containers that have been saved that are 32 bit and don't seem to run well. Bitcoin and LND data should be fine though. You could also make an image of the drive first in case anything were to happen.

The steps would be simple though.
- Re-flash SD card with 64 bit OS
- Boot with new OS and check app status (mempool, dojo, btc pay server... may have issues)
- Re-install any problem apps or reset docker to resolve issues

Let me know how it goes if you try.

**Comment by imacfan** [comment]
Flashed a new SD card with 64bit version. 

Attached a new cloned drive. 
Stuck at login screen. Doesn't recognise old password. Not taking the default password "bolt"

**Comment by imacfan** [comment]
Nevermind .. default password started working after trying login via terminal.

**Comment by imacfan** [comment]
Seems stuck at Lightning. 
It's showing "waiting" with red dot. Nothing is moving it. 

Any ideas , what could be the issue

**Comment by imacfan** [comment]
this is the log:

/home/bitcoin/.lnd/lnd.conf:24: unknown option: wallet-unlock-password-file
Aug 30 08:25:13 myNode systemd[1]: Started LND Lightning Daemon.

**Comment by tehelsper** [comment]
Try upgrading to the latest version. The config file from previous upgrades was stored on the external drive and assumes lnd is on version 13.1+.

**Comment by imacfan** [comment]
Yes , already upgraded from 2.34 to 2.41. Same issue. 

I also tried manual unlock using - lncli unlock command. Doesn't work

**Comment by tehelsper** [comment]
Are there any other logs or errors regarding the login? Login should happen automatically based on the line your referenced earlier. Had you customized your lnd config?

**Comment by imacfan** [comment]
No , I haven't customised. Just commented to the unlock line in config to check manual unlock. 

May be I need to try again. I am back to old 32bit version. So need to reclone the drive again as latest state might have changed.

**Comment by tehelsper** [comment]
OK, going back to 32-bit went smoothly?

**Comment by imacfan** [comment]
Yes , I had those sitting as is. Both SD and SSD drive. Just plugged them back in and it worked. 

I was experimenting on cloned SSD drive (cloned using Balena)

**Comment by imacfan** [comment]
I tried again, this time red dot is gone. Latest version of LND. log is below, stuck at "waiting":

Aug 31 02:52:10 myNode lnd[6503]: Attempting automatic RPC configuration to bitcoind
Aug 31 02:52:10 myNode lnd[6503]: Automatically obtained bitcoind's RPC credentials
Aug 31 02:52:10 myNode lnd[6503]: 2021-08-31 02:52:10.623 [INF] LTND: Version: 0.13.1-beta commit=v0.13.1-beta, build=production, logging=default, debuglevel=info
Aug 31 02:52:10 myNode lnd[6503]: 2021-08-31 02:52:10.626 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Aug 31 02:52:10 myNode lnd[6503]: 2021-08-31 02:52:10.771 [INF] RPCS: RPC server listening on 0.0.0.0:10009
Aug 31 02:52:10 myNode lnd[6503]: 2021-08-31 02:52:10.782 [INF] RPCS: gRPC proxy started at 0.0.0.0:10080
Aug 31 02:52:10 myNode lnd[6503]: 2021-08-31 02:52:10.783 [INF] LTND: Opening the main database, this might take a few minutes...
Aug 31 02:52:10 myNode lnd[6503]: 2021-08-31 02:52:10.783 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
Aug 31 02:52:12 myNode lnd[6503]: 2021-08-31 02:52:12.101 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 31 02:52:12 myNode lnd[6503]: 2021-08-31 02:52:12.192 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 31 02:52:12 myNode lnd[6503]: 2021-08-31 02:52:12.351 [ERR] RPCS: [/lnrpc.Lightning/NewAddress]: waiting to start, RPC services not available
Aug 31 02:52:12 myNode lnd[6503]: 2021-08-31 02:52:12.391 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available

**Comment by imacfan** [comment]
Any other way to move the lightning without losing opened channels?

**Comment by tehelsper** [comment]
Not that I know of. Those errors are expected while LND is in its state prior to login. Are there any other errors in the log later on? Nothing in that log explains why it isn't starting up properly.

For example, here's my log when I restart LND:

Sep 05 18:47:03 myNode lnd[6331]: 2021-09-05 18:47:03.304 [INF] LNWL: Done catching up block hashes
Sep 05 18:47:03 myNode lnd[6331]: 2021-09-05 18:47:03.303 [INF] LNWL: Catching up block hashes to height 699222, this might take a while
Sep 05 18:47:03 myNode lnd[6331]: 2021-09-05 18:47:03.291 [INF] LNWL: Started rescan from block 00000000000000000004af9f87d3c48cf7b4b7ef7a047f10b1049bcb56e95ba6 (height 699222) for 252 addresses
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.111 [INF] LTND: Waiting for chain backend to finish sync, start_height=699222
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.086 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.086 [INF] LTND: Channel backup proxy channel notifier starting
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.030 [INF] HSWC: Trimming open circuits for chan_id=676031:1979:1, start_htlc_id=396
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.027 [INF] HSWC: Payment circuits loaded: num_pending=1, num_open=0
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.026 [INF] HSWC: Restoring in-memory circuit state from disk
Sep 05 18:47:02 myNode lnd[6331]: 2021-09-05 18:47:02.001 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=true)! NOTE: Ensure the backend node is proxying over Tor as well
Sep 05 18:47:01 myNode lnd[6331]: 2021-09-05 18:47:01.996 [INF] CHRE: LightningWallet opened
Sep 05 18:47:01 myNode lnd[6331]: 2021-09-05 18:47:01.987 [INF] LNWL: The wallet has been unlocked without a time limit
Sep 05 18:47:01 myNode lnd[6331]: 2021-09-05 18:47:01.082 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: the RPC server is in the process of starting up, but not yet ready to accept calls
Sep 05 18:46:59 myNode lnd[6331]: 2021-09-05 18:46:59.601 [ERR] RPCS: [/lnrpc.Lightning/SubscribeInvoices]: the RPC server is in the process of starting up, but not yet ready to accept calls
Sep 05 18:46:59 myNode lnd[6331]: 2021-09-05 18:46:59.077 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: the RPC server is in the process of starting up, but not yet ready to accept calls
Sep 05 18:46:58 myNode lnd[6331]: 2021-09-05 18:46:58.886 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
Sep 05 18:46:58 myNode lnd[6331]: 2021-09-05 18:46:58.886 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
Sep 05 18:46:58 myNode lnd[6331]: 2021-09-05 18:46:58.886 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
Sep 05 18:46:58 myNode lnd[6331]: 2021-09-05 18:46:58.844 [INF] CHRE: Primary chain is set to: bitcoin
Sep 05 18:46:58 myNode lnd[6331]: 2021-09-05 18:46:58.633 [INF] LNWL: Opened wallet
Sep 05 18:46:57 myNode lnd[6331]: 2021-09-05 18:46:57.071 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
Sep 05 18:46:55 myNode lnd[6331]: 2021-09-05 18:46:55.393 [INF] LTND: Attempting automatic wallet unlock with password provided in file
Sep 05 18:46:55 myNode lnd[6331]: 2021-09-05 18:46:55.392 [INF] LTND: Database now open (time_to_open=5.48732046s)!
Sep 05 18:46:55 myNode lnd[6331]: 2021-09-05 18:46:55.392 [INF] CHDB: Checking for schema update: latest_version=22, db_version=22
Sep 05 18:46:55 myNode lnd[6331]: 2021-09-05 18:46:55.065 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Sep 05 18:46:54 myNode lnd[6331]: 2021-09-05 18:46:54.541 [ERR] RPCS: [/lnrpc.Lightning/SubscribeInvoices]: waiting to start, RPC services not available
Sep 05 18:46:53 myNode lnd[6331]: 2021-09-05 18:46:53.061 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Sep 05 18:46:51 myNode lnd[6331]: 2021-09-05 18:46:51.055 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Sep 05 18:46:49 myNode lnd[6331]: 2021-09-05 18:46:49.905 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
Sep 05 18:46:49 myNode lnd[6331]: 2021-09-05 18:46:49.904 [INF] LTND: Opening the main database, this might take a few minutes...
Sep 05 18:46:49 myNode lnd[6331]: 2021-09-05 18:46:49.899 [INF] RPCS: gRPC proxy started at 0.0.0.0:10080
Sep 05 18:46:49 myNode lnd[6331]: 2021-09-05 18:46:49.890 [INF] RPCS: RPC server listening on 0.0.0.0:10009
Sep 05 18:46:49 myNode lnd[6331]: 2021-09-05 18:46:49.862 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Sep 05 18:46:49 myNode lnd[6331]: 2021-09-05 18:46:49.861 [INF] LTND: Version: 0.13.1-beta commit=v0.13.1-beta, build=production, logging=default, debuglevel=info
Sep 05 18:46:49 myNode lnd[6331]: Automatically obtained bitcoind's RPC credentials
Sep 05 18:46:49 myNode lnd[6331]: Attempting automatic RPC configuration to bitcoind

**Comment by bloodir** [comment]
I have updated from 32 bit to 64 without any issue. Flashed new SDcard with 64 bit, updated to latest version and everything works fine. Make sure that the update actually took place as previously I had an error during the update, yet myNode version was showing latest, but lnd was still 0.12.1. That way you would keep getting unlock error.

**Comment by imacfan** [comment]
Finally worked for me as well !

**Comment by tehelsper** [comment]
Good to hear! I plan on making new 32 and 64 bit images for the next release or two after some relatively large updates and that should make updating to 64 bit easier.

**Comment by raymonddurk** [comment]
Would that be an easy upgrade path for anyone on a 32 bit version as in a one click upgrade.

**Comment by quarreller** [comment]
Are there any new informations about how to updating from 32 bit version to 64 bit in a easy way?
Thank you

**Comment by tehelsper** [comment]
@quarreller I don't plan on ever supporting 32->64 as a one click upgrade. It would be very difficult and likely cause issues.

However, you can pretty easily re-flash your SD card with a 64-bit image. All data from the external drive will remain.

**Comment by quarreller** [comment]
@tehelsper
first excuse my english...
I did it and at the end it works... here my feedback for all..

Flashing sd card with 64 bit version-no problem
Starting myNode-ok-and syncing 6 blocks...done
Standard theme and passwort is active
Bitcoin-Lightning (shows my sats had no channels open)-RTL-electrum server-btc explorer is running!!

LND  Hub i had to enable again(for my blue wallet)
Mempool was hanging on installing for 20 minutes and i uninstall that app-reinstalled and working
Dont know why Dojo was hanging on installing(was not installed on 32 bit version)...so i uninstalled that app...

At the end i did a reboot-and it seems everything i had enabled on the 32bit version is working now on the 64bit

**Comment by MWDJ** [comment]
I upgraded successfully to 64bit from 32bit with an SD card swap following myNode shutdown (using reference v0.2.48 from https://www.mynodebtc.com/download)... All previous channels remained open and available!  
Be sure to keep your storage drive connected (per the site upgrade instructions). Device registration was automatically applied for premium updates.

My experience was similar to comments in this post @quarreller @imacfan. 
Firefox browser did not permit use of default password (initially); although SSH was working. I switched to an alternate chrome based browser (edge) to use the GUI (with default password) to reconfigure myNode settings.  I also had to select "uninstall" for Mempool and Dojo and one other application (showing installing) to remove the red status.  Additionally, SSH terminal will not remember any cached commands after the swap (not a significant concern).

After changing IP address from the command line and installing mempool (causing a reboot), Bitcoin, LND, RTL and other applications are working with all prior channels connected and running.  Upgrades to latest myNode release can be applied from the GUI normally.

Note: This 64-bit migration resolved periodic LND crashing issues that appeared to have been contributed from 2GB+ channel.db and other large databases that occurred under 32-bit myNode.  Much more stable now!

**Comment by tehelsper** [comment]
Good to hear! The issue with Mempool and Dojo should be resolved if you were running the most recent version before and after. Docker has issues with the upgrade without clearing the data which *should* automatically happen if the device detects an upgrade. If that didn't work, there may still be an issue there.
