### ISSUE TITLE
RPi4 mynode hangs/disconnects/crashes from network

### ISSUE THREAD

**Issue by alfredovilla01** [mynodebtc/mynode#566]
After a few days, sometimes even less than 24 hrs, the RPi just hangs and can no longer be found on the network. The router doesn't recognize the IP anymore, as if it was dropped (I have a specific addressed assigned to the RPi via the router). My only recourse is to power cycle the RPi.  It then all comes back up and goes to the assigned internal address (it's wired in). I can't SSh in when it crashes for obvious reasons to see what has gone wrong.

I understand this may not be mynode related, and maybe is only related to my internal network.  Having said that, I believe mynode should be able to recover from a network crash (or when my IPS gives me a new lease) and when it comes back online, it can continue working... as all other devices do. Another thought is that perhaps the RPi SD card maybe is corrupt of get overloaded?  Or maybe I don't have enough memory?  or?

I'm not an expert, but I don't see anything obvious in the log files I was able to check out after a reboot from a crash.

myNode (Linux 5.10.52-v7l+ 32bit)
Raspi4 - 2GB edition, w 32GB SD card (PNY)
Current Version | 0.2.41 |  
External SSD 750GM (Micron) via USB

**Comment by tehelsper** [comment]
Hey, thanks for the info. The device should be able to handle network outages and my guess is that it is not network related.

I noticed your device has 2GB of RAM, which is likely the culprit. The behavior you are seeing is typical once the device tries to start running too many applications - they all start to become unresponsive.

How many apps do you have enabled? I would first try disabling some apps to see if that improves the uptime. However, my real recommendation is to upgrade to a 4GB or 8GB Raspberry Pi device.

**Comment by alfredovilla01** [comment]
Thanks for the advise.  I was afraid that maybe the RAM was the issue.  I have disabled ELECTRUM server.  Now I am running at 60-64% MEM.  It use to be around 70-72% with a constant "warning".  Hopefully this will do it and will let you know.   Otherwise... I'll probably get me 4GB RPi version.  Looking at GLANCES, I get the following summaries:

CPU	8.9%
user:	5.3%
system:	1.8%
idle:	91%
nice:	1.6%
irq:	0%
iowait:	0.1%
steal:	0%
ctx_sw:	3272
inter:	1900
sw_int:	625

MEM	61.2%
total:	1.88G
used:	1.1G
free:	746M
active:	458M
inactive:	1.27G
buffers:	20.3M
cached:	738M

SWAP	2.8%
total:	2.00G
used:	58.0M
free:	1.94G
LOAD	4-core
1 min:	0.53
5 min:	0.58
15 min:	0.93

CONTAINERS 5 (served by Docker 20.10.8)
Name
nodejs
db
tor
webssh2
nginx

No warning or critical alert detected

TASKS 192 (513 thr), 1 run, 138 slp, 0 oth

FILE SYS	Used	Total
/ (/dev/root)	8.66G	29.1G
_/hdd.log (/dev/root)	8.66G	29.1G
/mnt/hdd (/dev/sda1)	501G	687G

SENSORS
cpu_thermal 1	C	58
