### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by 0bs72** [mynodebtc/mynode#571]
**Describe the bug**
Not too sure if this is a bug or not.

**Expected behavior**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**MyNode hardware (please complete the following information):**
 - Device: VM
 - Version 22.0.0

**Additional context**
Up until V22.0.0 I've never seen the Electrum Server listed as a Peer. Now I'm seeing...
```
ID |        IP       | Version | TX (MB) | RX (MB) | Ping (ms)
15 | 127.0.0.1:33296 | electrs | 2152.68 |  14.04  | 11710
```
To my mind, this looks as if Electrum is routing out and back, via the TOR Network, rather than simply connecting directly via the LAN or Localhost, given the Ping time.

**Comment by tehelsper** [comment]
This isn't a bug. The latest version of electrum server connects to bitcoind as a peer to download blocks rather than using JSON RPC. I believe this type of connection is more efficient for transferring data.

**Comment by 0bs72** [comment]
> This isn't a bug. The latest version of electrum server connects to bitcoind as a peer to download blocks rather than using JSON RPC. I believe this type of connection is more efficient for transferring data.

My thanks to you for the quick reply and information.
I'd appreciate your view on the Ping time that I'm see? That number seems VERY high to me.

**Comment by tehelsper** [comment]
Yeah, that is high for normal ping, but I'm not sure if electrs prioritizes responding right away. As long as the connection is up and it appears to be working fine, I don't think it's anything to worry about. Especially since Bitcoin doesn't need data from electrs.
