### ISSUE TITLE
Copy function of password error

### ISSUE THREAD

**Issue by OnThisHill** [mynodebtc/mynode#579]
**Describe the bug**
When copying code to access lightning terminal, a space character is added before and after the code on the clipboard. This causes copy paste password to fail when trying to access the terminal.

**Expected behavior**
Password to be copied correctly.

**Desktop (please complete the following information):**
 - Browser [e.g. firefox
 - Version [latest stable 

**MyNode hardware (please complete the following information):**
 - Device: [Raspi4]
 - Version [0.2.43]

**Comment by tehelsper** [comment]
Yeah, depending on the browser the copy text can easily pick up extra space on the left hand side. I'll look into adding a "copy" button to avoid confusion.

**Comment by tehelsper** [comment]
Copy button added in last release.
