### ISSUE TITLE
Glances and Netdata issues with installed myNode from scratch

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#58]
Installed myNode from scratch on new sdcard (v0.1.63) rpi4
configured wifi ssid and password through raspi-config and enabled with "ifconfig wlan0 up"
upgraded to v0.1.66

ISSUES:
1 - on settings: Public IP error (resolved using a STATIC IP)
2 - http://mynode.local:61208/ error connection glances (even with 192.168.1.100:61208)
3 - http://mynode.local:19999/ error connection netdata (even with 192.168.1.100:19999)
4 - even if i force HTTPS (with button on top right) connection remain in HTTP

**Comment by Amiga500** [comment]
i have put static ip and now issue number 1 is resolved.. but glances and netdata don't load yet

**Comment by Amiga500** [comment]
tried to connect on another linux machine to raspberry pi.. same issue with glances and netdata and with https that, even pressed the button on top right in the main page to force https, it didn't work.

**Comment by Amiga500** [comment]
"sudo /usr/bin/mynode_post_upgrade.sh" ongoing.. is installing a lot of stuff.. probably will resolve

**Comment by abhiShandy** [comment]
check `systemctl status glances` and `systemctl status netdata`

**Comment by Amiga500** [comment]
Thanks. I resolved using these commands..

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo /usr/bin/mynode_post_upgrade.sh

now into welcome login i see
IP:            172.18.0.1 192.168.1.100

my local ip is the second one

**Comment by abhiShandy** [comment]
Glad it worked!
Did you attempt upgrading the freshly installed image using the settings page or remote login?

**Comment by Amiga500** [comment]
Yeah! I upgrade with ssh on remote login

**Comment by tehelsper** [comment]
Yeah, the other IP is docker. I need to look into that. It looks like docker may not always successfully install the first time. I'm looking into it.

**Comment by Amiga500** [comment]
First time i launched the script post upgrade it blocked and i forcely close. It was about after the pgp sign of Laolu.. So related to lnd.
