### ISSUE TITLE
LND stops with error lnd[12800]: error: Server response: Work queue depth exceeded

### ISSUE THREAD

**Issue by tukac** [mynodebtc/mynode#590]
**Describe the bug**
After reboot LND works ok for some time, a day or so. Then it locks the wallet with error lnd[12800]: error: Server response: Work queue depth exceeded.

Unlocking the wallet without new reboot results in several failed LND starting attempts, then LND locks again. It is impossible to start LND without reboot.

Default Bitcoin config has set rpcworkqueue=32 and I haven't changed it.

I am not increasing this limit but will try to figure out what app is exhausting RPC connections. I have disabled Dojo as first suspect. Dojo was enabled but I was not using it. Dojo is now disabled and LND is working without reboot. I will wait for couple of days to see if error re-appears or if disabling Dojo has permanently solved the issue.

However, raising rpcworkqueue to 64 might be needed for Dojo to not cause LND to stop.
 
**Desktop (please complete the following information):**
 - myNode 0.2.44
 - bitcoin 0.22.0
 - LND v0.13.3-beta
 - Dojo v1.12.0

**MyNode hardware (please complete the following information):**
 - RPi4B 8Gb, SSD

**Comment by tehelsper** [comment]
Thanks for logging this. Let me know if you find out which app is causing the connections. I've seen this issue before, but it hasn't happened recently. I wonder if a new app update increased the poll rate.

What other apps are enabled?

**Comment by tukac** [comment]
This issue surfaced after latest upgrade. Enabled are apps:
RPC explorer - latest
Electrum server - 0.9.0
LND - latest
LND connect - latest
Lightning terminal - 0.5.1
Loop - latest
Pool - latest
RTL - latest

Dojo was latest and is disabled now. So far issue didn't resurfaced.

**Comment by tukac** [comment]
Week has passed and node is working fine. Dojo is still disabled.

I will enable Dojo to see if issue re-appears.

**Comment by tukac** [comment]
LND stopped working after Dojo was enabled. Same as on the beginning.

Dojo is definitely the cause. I am surprised more people are not reporting this.

I will upgrade to latest 0.2.45 to see if issue remains.

**Comment by tukac** [comment]
I have upgraded from 0.2.44 to 0.2.45. LND worked fine at first. However, after half a day or so same "Work queue depth exceeded" error re-appeared.

Without rebooting I disabled Dojo and immediately LND started working fine.

All this experimentation was with default Bitcoin config set as rpcworkqueue=32.

**Comment by tukac** [comment]
I have flashed SD card to 0.2.48 and this issue disappeared. Maybe upgrade process had something to do with it...
I am closing this issue. Working setup:

Dojo v1.12.1
Electrs v0.9.3
LND v0.14.1
