### ISSUE TITLE
Warden 

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#591]
**Describe the bug**
I see option to install Warden. I did install it, but can't see it on the UI.. How to access it after installing?

Thanks

**Comment by tehelsper** [comment]
Where are you seeing that? I had it partially added at one point, but it wasn't complete. It should not be appearing in any install list until it's complete.

**Comment by imacfan** [comment]
> Where are you seeing that? I had it partially added at one point, but it wasn't complete. It should not be appearing in any install list until it's complete.

Ok. 
I saw it in the drop down 
![image](https://user-images.githubusercontent.com/54225190/139614735-dc31cd63-b764-4152-8181-4d95a2b2efc1.jpeg)

**Comment by tehelsper** [comment]
Ah, thanks. Will be fixed next release.

https://github.com/mynodebtc/mynode/commit/99ef45b78a0f0086b3b308b7cfccaf4b0df18f4b
