### ISSUE TITLE
UPGRADE FAILED! Hash did not match!

### ISSUE THREAD

**Issue by wksantiago** [mynodebtc/mynode#594]
Getting 
+ exit 1
+ echo 'UPGRADE FAILED! Hash did not match!'
...
on upgrade to v0.2.45 from v0.2.44

**Comment by tehelsper** [comment]
This is almost 100% the same as https://github.com/mynodebtc/mynode/issues/592

Try the following commands and then things should act normally.

```
sudo wget https://raw.githubusercontent.com/mynodebtc/mynode/master/rootfs/standard/etc/tor/torrc -O /etc/tor/torrc
sudo systemctl restart tor@default.service
```

or

```
sudo wget https://raw.githubusercontent.com/mynodebtc/mynode/master/rootfs/standard/etc/tor/torrc -O /etc/tor/torrc
sudo mynode-reboot
```

**Comment by wksantiago** [comment]
Perfect problem solved thanks

**Comment by tehelsper** [comment]
Sorry for the trouble. For others referencing this, the same root issue can happen after upgrading to v0.2.44 after Oct. 31 and before Nov. 3, when v0.2.45 was released. The issue can appear as:

- Bitcoin not syncing
- LND not starting properly
- Upgrade failing

**Comment by tehelsper** [comment]
Issue is caused by tor getting update in the package repo to a version that rejected the myNode torrc config file.
