### ISSUE TITLE
Crowdfunding app "awaiting payment" pop up is not working #527

### ISSUE THREAD

**Issue by as-schug** [mynodebtc/mynode#595]
According to https://github.com/btcpayserver/btcpayserver/issues/527,
using SSL, does not show pop up "awaiting payment" windows.
I inserted mannualy to https_btcpayserver.conf nginx file
----
.
.
.
    location / {
        proxy_pass http://127.0.0.1:49392;

#add this
        **proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;**
#end

        include /etc/nginx/mynode/mynode_ssl_proxy_params.conf;
    }
.
.
.
---

We´d apreciatte if it could be handled by  mynode scripts

**Comment by tehelsper** [comment]
Thanks, added in https://github.com/mynodebtc/mynode/commit/8423ae6a76fe1845322f3d55c89d574881daaa1c
