### ISSUE TITLE
Initial Bitcoin Sync issue

### ISSUE THREAD

**Issue by lordgivemestrength** [mynodebtc/mynode#597]
**Describe the bug**
My node ( before upgrading from v0.2.43 ) showed a bitcoin error. I didn't look too deep, the node has been working fine for over a year.

I went to transfer funds to myself and realised sync had stopped on bitcoin 0.21.1
Decided to upgrade the node anyway, so moved to version 0.2.45.

Issue remained, so decided to resync the chain.
Now I seem to be stuck at block height 387415 and has been for hours.

Also, there was an alert I noticed for "full disk space" but it isn't. I cleared the alert, no change. Still not continuing with sync.

**Expected behavior**
I expected a resync function to clear issue and resync the chain.

**Screenshots**

<img width="628" alt="Screenshot 2021-11-16 at 22 49 27" src="https://user-images.githubusercontent.com/60814779/142078799-04d6658e-c02d-4029-b638-d20e997c6977.png">

<img width="552" alt="Screenshot 2021-11-16 at 22 50 55" src="https://user-images.githubusercontent.com/60814779/142078900-1130f4e7-000c-4f54-8744-cb1b5f253dc7.png">

**Desktop (please complete the following information):**

Chrome, v95.0.4638.69

**MyNode hardware (please complete the following information):**
 - Device: [e.g. Raspi3, Raspi4, Rock64, VM]
 - Version [e.g. 0.2.15]

Raspberry Pi4, 4g, 32g flash card, and 1TB HDD. 

**Additional context**

The only other issues I sometimes had was where electrum would error, and I had to wipe the data within electrum and have it reindex. This has happened perhaps twice in over a year ( not recently either. )

**Comment by tehelsper** [comment]
You may need to upgrade to an SSD. Your drive is showing as being very small now, but do you happen to remember if QuickSync was enabled? QuickSync + the current blockchain size is getting very close to filling up a 1TB drive. SSDs don't need QuickSync, so they have a lot of space available.

I'm guessing the drive got full and so the chain got corrupted causing the Bitcoin error. After upgrading and clearing the chain, the space is now available and it didn't use QS since it's entirely disabled by default in recent versions.

**Comment by lordgivemestrength** [comment]
Yes, QS was enabled. 
Disk space indicates low at 12% though at the moment, and still the initial sync is frozen at block 387415.

I've just disabled QS now. Lets see what happens.

Question - if I upgrade to an SSD, is just a hot swap?
Will my channels be preserved?

**Comment by tehelsper** [comment]
You can shutdown and attach the new drive, but that would not migrate data.

There is a built in clone tool to help migrate data.

https://mynodebtc.github.io/advanced/clone-tool.html

**Comment by lordgivemestrength** [comment]
Resolved now. I wiped bitcoin info again, and re-synced chain. ( Quick sync used and still worked OK )
