### ISSUE TITLE
Is it possible to generate a new .onion address for a single app?

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#601]
I have revealed an app .onion address and would like to change to a new .onion address, but **NOT** change all the others.

This is probably not common enough to become part of the Web UI, but there many be a CLI solution that can be used.

I removed the `/var/lib/tor/mynode_app` and rebooted, but this simply regenerated the existing `hostname`

- [✅ ] Mark this if you searched the existing list of open/closed issue and did not find anything similar

PS. Flagged this as a Feature request because it's not a bug.

**Comment by tehelsper** [comment]
Backups of the tor folders are made so if someone needs to re-flash their SD card, they will get the same tor addresses.

To change a single tor address, try deleting the folder your did as well as the backup, like:

`rm -rf /var/lib/tor/mynode_app`
and
`rm -rf /mnt/hdd/mynode/tor_backup/mynode_app`

**Comment by HamishMacEwan** [comment]
Thanks Taylor, the wonderful resilience of myNode sometimes makes it a difficult task to kill something for resurrection!

Following your advice and a reboot (is there something more elegant that would work?) the app has a new .onion address.

**Comment by tehelsper** [comment]
Glad it worked! Restarting the tor service would likely have worked as well to make the new addresses - `systemctl restart tor@default`, but that could possibly cause bitcoind and lnd to disconnect. I'm not sure how well they handle tor being restarted underneath them. I always just reboot after making tor changes.
