### ISSUE TITLE
Startup local script to custom partition mounting

### ISSUE THREAD

**Issue by as-schug** [mynodebtc/mynode#602]
I made a custom script to mount my hdd partition, called **/usr/local/bin/mynode_startup_local.sh**

I call it before mounting hdd while loop at **/usr/bin/mynode_startup.sh**

Here is the code, just before **while [ ! -f /mnt/hdd/.mynode ]**

**# Custom user initialization script, if present
if [ -x /usr/local/bin/mynode_startup_local.sh ]; then
    /usr/local/bin/mynode_startup_local.sh
fi**

![image](https://user-images.githubusercontent.com/67750682/144324976-afa7f957-7372-45d3-8b49-61bd2b2db1bf.png)

This custom script I have to put it again at the startup main script every time I upgrade mynode.
It would be great if you code it to the new releases of **/usr/bin/mynode_startup.sh**

Thank you for your appreciation

**Comment by tehelsper** [comment]
Can I ask what your custom script is doing? Is it also mounting the drive or just running prior to mounting the drive?

Perhaps it could help others.

**Comment by as-schug** [comment]
> Can I ask what your custom script is doing? Is it also mounting the drive or just running prior to mounting the drive?
> 
> Perhaps it could help others.

it it also mounting.
In geneal fact, downloads from my local server a script that has the key for raw harddisk.
It downloads that script to a memory mouted fs like /run/user/0, so the script never touch hard disks.
Also the origin script is not touching hard disks. This file is kept safe with gpg
I´ve been using this method for about 1 year.

If mynode(s) box is stollen, all my funds are safe for sure
The key for that encryption is a xpriv key, derivated from a path of my seed like "m/somecustomnumber'/othercustomnumber'

It is recomended that skip all fs checks, so it does not check or try to check a encrypted hard disk.

Here is the script. Some var names are in Brazilian portuguese.



=========================================
/usr/local/bin/mynode_startup_local.sh
=========================================
#!/bin/bash

RAIZ=/run/user/0
INICIALIZADOR=$RAIZ/monta.mynode002.cmd

touch /home/bitcoin/.mynode/skip_fsck

while [ true ]; do

   rsync --port 915 192.168.0.250::INIT/monta.mynode002.cmd $RAIZ/ -avP --inplace

  if [ -f $INICIALIZADOR ]; then
     chmod 755 $INICIALIZADOR
     $INICIALIZADOR
     shred $INICIALIZADOR
     if [ -f /mnt/hdd/.mynode ]; then
         break
     fi
   fi
  sleep 5;
done

exit 0

=====================================
And here is the downloaded final script
=====================================
#! /bin/sh

KEY=xprv9u5my5mMWQcB9zZ7m2Dj8D79jpv9G6QNhtBd2vSKzjSqzgzscHe1bmMgwXf3fUh6KKmwynKyusTaycwrHE6ikxSR7AweSCybHz5eo84GHeF

cryptsetup remove MEUNODE
echo -n $KEY | cryptsetup create MEUNODE /dev/sda --cipher aes-cbc-plain64 --hash sha512 --offset 96

mount /dev/mapper/MEUNODE /mnt/hdd 

exit 0

=========================================================

I hope it inspires others to have more ideas..

Thank you

**Comment by tehelsper** [comment]
Added ability for hook scripts. This should work for you and I added a couple other hook points as well. Let me know if you need anything else.

https://github.com/mynodebtc/mynode/commit/4fec2216543c66209efe706a03f68a66f478aeba

**Comment by as-schug** [comment]
> Added ability for hook scripts. This should work for you and I added a couple other hook points as well. Let me know if you need anything else.
> 
> [4fec221](https://github.com/mynodebtc/mynode/commit/4fec2216543c66209efe706a03f68a66f478aeba)

Perfect... Thank you!!!
