### ISSUE TITLE
PyBLOCK new version

### ISSUE THREAD

**Issue by curly60e** [mynodebtc/mynode#603]
Improvements:

The package structure was changed.
Improved installation with PYPI in just one command (pip3 install pybitblock)
This let you execute it in every part of the system typing "pyblock"
Updating it changed: pip3 install pybitblock -U

Problems:

When you install Pyblock with pip3, all config files will create in the folder you execute it.
For nodes like MyNode it will make this an issue.

Solutions:

MyNode could use just the information located in the pybitblock folder and continue using MyNode execution format like nothing happened.
![imagen](https://user-images.githubusercontent.com/55191248/144708955-ef6563db-28aa-4cc0-9aee-e66feeda0729.png)

**Comment by tehelsper** [comment]
I'm not sure if I'm following. I already added a command to help with some of this: `mynode-pyblock` which helps manage folder location. Does that help? It can be run from anywhere.

**Comment by curly60e** [comment]
I know and it was a great work, I was clarifying the new version to take into account for future MyNode updates and so you do not run into any dilemma. 

As I said all Pyblock's files are inside pybitblock.  :)
