### ISSUE TITLE
SD Card nearly full — what are some sensible actions to take

### ISSUE THREAD

**Issue by StevenBlack** [mynodebtc/mynode#609]
Hi Taylor @tehelsper the MyNode web UI informs me that my SD card is nearly full (96% full).

First I want to say, it's great to see this warning. It shows care and attention to detail.

I plan on getting a bigger SD card (it's 16Gb presently) but, until then, are there any files on the SD card I can zap?  I'm thinking log files, previous version upgrade bundles, that sort of thing.

I can probably figure this out, trial and error to a large degree, but do you know offhand what's lilely voluminous and expendable on the SD card?

**Comment by tehelsper** [comment]
Thanks, I appreciate it. Here are a few tips:

1. To find specific large files and apps, you can try these commands and it will show usages.
    `sudo du -h -d1 /opt/mynode/` - show app sizes
    `sudo du -h -d1 /home/` - see if any user account is especially large
    `sudo du -h -d1 /root/.cargo/` - check if old rust toolchains are taking space
    `sudo du -h -d1 /home/admin/.cargo/` - check if old rust toolchains are taking space
2. Uninstall any unused apps. Large ones are typically RTL, Thunderhub, Caravan, and JoinMarket.
3. Clear npm cache `sudo -u bitcoin npm cache clean --force`
4. Try removing old / extra Rust versions.
5. Re-flash the same SD card and it will cleanup any remnants. 16GB still pretty easily fits everything, but old files can build up over time, especially if doing manual upgrades or any other development.
6. The obvious one, re-flash an image onto a larger SD card.

**Comment by StevenBlack** [comment]
Awesome Taylor @tehelsper thank you.

**Comment by StevenBlack** [comment]
Excellent Taylor @tehelsper.

* `sudo -u bitcoin npm cache clean --force` moved the needle from `96% of 15G` to `89% of 15G`.  That cleared about a gig of disk space. It made the warning go away. Buys enough time for a new 32Gb micro sd card to arrive.

Here are some of the others; I won't act on these, but it's nice to know these are an option.

```
admin@myNode:~ $ sudo du -h -d1 /opt/mynode/
123M	/opt/mynode/LndHub
126M	/opt/mynode/jm_backup
1.6M	/opt/mynode/mempoolspace
8.0K	/opt/mynode/webssh2
118M	/opt/mynode/corsproxy
320M	/opt/mynode/wardenterminal
4.0K	/opt/mynode/docker
127M	/opt/mynode/joinmarket-clientserver
562M	/opt/mynode/caravan
20K	/opt/mynode/btcpayserver
56M	/opt/mynode/whirlpool
334M	/opt/mynode/sphinxrelay
55M	/opt/mynode/ckbunker
61M	/opt/mynode/lnbits
720M	/opt/mynode/RTL
240K	/opt/mynode/custom
384K	/opt/mynode/netdata
824M	/opt/mynode/thunderhub
100M	/opt/mynode/specter
69M	/opt/mynode/btc-rpc-explorer
3.6G	/opt/mynode/
```

```
admin@myNode:~ $ sudo du -h -d1 /root/.cargo/
[sudo] password for admin:
13M	/root/.cargo/bin
254M	/root/.cargo/registry
266M	/root/.cargo/
```

```
admin@myNode:~ $ sudo du -h -d1 /home/admin/.cargo/
11M	/home/admin/.cargo/bin
11M	/home/admin/.cargo/
```

I think this is a nice reference for anyone who needs to create slack on the micro sd card in the future.

Thanks again Taylor!

**Comment by tehelsper** [comment]
No problem! Also, for the large apps and Rust toolchains, it's best not to delete them manually. Use the Application page within myNode to uninstall the app and it will clean up the space better. Otherwise, there's a risk of the app just re-installing itself later or causing other issues.

For the Rust toolchains, most users probably won't ever need to touch it (only devs). But if you do, use the "rustup" commands to manage. The device itself should really only keep a single one, if necessary, but they can be large. Example, run "rustup toolchain list" as the admin and root user to list the specific toolchains.

**Comment by woodyjon** [comment]
> Thanks, I appreciate it. Here are a few tips:
> 
> 1. To find specific large files and apps, you can try these commands and it will show usages.
>    `sudo du -h -d1 /opt/mynode/` - show app sizes
>    `sudo du -h -d1 /home/` - see if any user account is especially large
>    `sudo du -h -d1 /root/.cargo/` - check if old rust toolchains are taking space
>    `sudo du -h -d1 /home/admin/.cargo/` - check if old rust toolchains are taking space
> 2. Uninstall any unused apps. Large ones are typically RTL, Thunderhub, Caravan, and JoinMarket.
> 3. Clear npm cache `sudo -u bitcoin npm cache clean --force`
> 4. Try removing old / extra Rust versions.
> 5. Re-flash the same SD card and it will cleanup any remnants. 16GB still pretty easily fits everything, but old files can build up over time, especially if doing manual upgrades or any other development.
> 6. The obvious one, re-flash an image onto a larger SD card.

Hello.
I had the same message. I re-flashed an image onto a larger SD card. But when I launch my mynode with the new sd card, the master password was reset to "bolt", it seems all the settings were not kept. And the lightning does not seem to start. Do you know if we need to take specific step for moving to a new SD card?
Thanks.

**Comment by tehelsper** [comment]
Yes, that's expected and is how you reset your password if you forget it. Some apps may need to be re-installed but most settings should remain.

**Comment by woodyjon** [comment]
> Yes, that's expected and is how you reset your password if you forget it. Some apps may need to be re-installed but most settings should remain.

Waiting for more hours, my lightning node is back where it should be. So everything is fine. Thanks a lot.
