### ISSUE TITLE
Lightning: trouble creating wallet

### ISSUE THREAD

**Issue by MMBTTF** [mynodebtc/mynode#616]
**Describe the bug**
When I try to create a Lightning wallet, I generate the phrase, save the words down, and then I get an error: Error Creating Wallet!

**Expected behavior**
New Lightning wallet would be created.

**Screenshots**
![Screen Shot 2022-01-16 at 9 07 11 PM](https://user-images.githubusercontent.com/97867664/149711338-5cce8628-c1dc-4494-a06b-b035b8aff6f5.png)

If helpful, here is my LND config code [with a few redactions for this post]:

# lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
maxpendingchannels=5
alias=mynodebtc.com [myNode]
color=#68F442

# Tor-only by default
listen=localhost

acceptortimeout=30s

rpclisten=[REDACTED FOR THIS GITHUB POST]
restlisten=[REDACTED FOR THIS GITHUB POST]

tlsextraip=[REDACTED FOR THIS GITHUB POST]
tlsextradomain=mynode.local

debuglevel=info
#debuglevel=debug

# This line needs to be uncommented if you have a lnd wallet and commented if you do not
wallet-unlock-password-file=/mnt/hdd/mynode/settings/.lndpw
wallet-unlock-allow-create=true

ignore-historical-gossip-filters=true
accept-keysend=true
accept-amp=true
caches.channel-cache-size=35000

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
bitcoin.mainnet=1
bitcoin.testnet=0

bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=[REDACTED FOR THIS GITHUB POST]

[autopilot]
#autopilot.active=1
#autopilot.maxchannels=5
#autopilot.allocation=0.6

[bolt]
db.bolt.auto-compact=true

[routing]
routing.strictgraphpruning=true
[Application Options]
nat=false

[Tor]
tor.active=true
tor.v3=true
tor.streamisolation=true

[Application Options]
tlsextradomain=[REDACTED FOR THIS GITHUB POST].onion

**Desktop (please complete the following information):**
 - Browser [safari]
 - Version [15.2]

**MyNode hardware (please complete the following information):**
 - Device: [Raspi4]
 - Version [e.g. 0.2.50]

**Additional context**
No additional context, other than I'm not sure why this isn't working.  Base/core function of the MyNode.  Should be simple.

**Comment by tehelsper** [comment]
Do you happen to have a custom LND config? What LND version is reported on the home screen?

**Comment by MMBTTF** [comment]
LND is v0.14.1-beta
Lightning (at top right of myNode home page) says v0.13.1

I am not trying to run a custom LND config.  I did run Lightning-EDIT CONFIG-Reset Config, but it didn't help.

I'm wondering if my Lightning app isn't connecting with the internet, possibly due to a Tor or settings issue.  But I'm otherwise at a loss.
![Screen Shot 2022-01-18 at 6 04 07 AM](https://user-images.githubusercontent.com/97867664/149952250-918b9437-09c6-4d5b-8f66-1aa95bae5061.png)
![Screen Shot 2022-01-18 at 6 07 02 AM](https://user-images.githubusercontent.com/97867664/149952567-795e636c-be79-49cd-96d2-e0fc7ac23cfc.png)

**Comment by tehelsper** [comment]
Yeah, for some reason LND is not updating when the upgrade script is running. Can you check the upgrade log from the settings page after attempting a lnd re-install?

Other options:
- Try reinstalling the latest full upgrade via the settings page
- Check upgrade log for errors
- Re-flash SD card with latest version and re-upgrade

**Comment by tehelsper** [comment]
It could be a bad SD card or some other issue early in the upgrade process preventing apps from properly updating.

**Comment by MMBTTF** [comment]
Looks like its failing.  Any idea how to fix based on this log?
![image](https://user-images.githubusercontent.com/97867664/150160705-33bbe9f6-0ec1-4123-a3e8-9c2d47b1e4ff.png)

**Comment by tehelsper** [comment]
Have you tried re-installing via a Reinstall Latest Version on the settings page? It appears like your python version is old, which is preventing lnd manage from installing, causing it to fail early.

**Comment by MMBTTF** [comment]
I tried reinstalling the most recent LND version several times.  Is there a way to update Python first?

**Comment by MMBTTF** [comment]
> a

You mentioned an SD card.  Where is that supposed to be plugged in?

**Comment by tehelsper** [comment]
> Have you tried re-installing via a Reinstall Latest Version on the settings page?

Did you try this? It should detect the old python version.

It's the small card that's plugged in on the bottom on the Raspberry Pi board.

**Comment by MMBTTF** [comment]
Tried reinstalling LND a few times.  Keeps getting stuck with errors.

If I need to replace the card, is it as simple as buying a new card and swapping the one that's there?  Do you have a card recommendation?

**Comment by tehelsper** [comment]
I don't think I'm being clear - there should be a single button literally named "Install Latest Version" on the settings page. It may help.

See:
https://mynodebtc.github.io/troubleshooting/device-did-not-upgrade.html#re-attempt-the-upgrade

**Comment by tehelsper** [comment]
It may also show a different error and that log can be seen also on the settings page with the show upgrade log button at the top.

**Comment by MMBTTF** [comment]
When I try to update the LND, I get this in the log:

+ printf '\n\n\n'
##################################################
+ printf '##################################################\n'
Post upgrade script failed attempt 3. Retrying.  
+ printf 'Post upgrade script failed attempt 3. Retrying.  \n'
##################################################
+ printf '##################################################\n'

**Comment by tehelsper** [comment]
Yeah, it's going to fail because of the lndmanage + python3 error. Did you try the button "Install Latest Version" on the settings page? It's the only button that may help without re-flashing the SD card.

**Comment by MMBTTF** [comment]
I'm running through the "Install Latest Version" in the Developer section.  Will report back.

**Comment by MMBTTF** [comment]
Looks like that worked.  We can close this ticket out.  Thanks!
