### ISSUE TITLE
RTL failing to install/start after upgrade

### ISSUE THREAD

**Issue by brh28** [mynodebtc/mynode#617]
RTL failing to start after upgrading MyNode version (+ enabling other apps including Sphinx and Thunderhub). I've tried upgrading/reinstalling RTL via GUI but that appears to be failing based on the screenshot below.

**Expected behavior**
RTL should be installed on the latest version and be accesable via GUI.

**Info**
`Jan 18 17:35:07 myNode systemd[1]: rtl.service: Failed with result 'exit-code'.
Jan 18 17:35:07 myNode systemd[1]: rtl.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 17:35:07 myNode rtl[11499]:     at internal/main/run_main_module.js:21:11
Jan 18 17:35:07 myNode rtl[11499]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Jan 18 17:35:07 myNode rtl[11499]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Jan 18 17:35:07 myNode rtl[11499]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Jan 18 17:35:07 myNode rtl[11499]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Jan 18 17:35:07 myNode rtl[11499]:     at Module._compile (internal/modules/cjs/loader.js:760:23)
Jan 18 17:35:07 myNode rtl[11499]: SyntaxError: Unexpected identifier
Jan 18 17:35:07 myNode rtl[11499]:        ^^^^
Jan 18 17:35:07 myNode rtl[11499]: import http from 'http';
Jan 18 17:35:07 myNode rtl[11499]: /opt/mynode/RTL/rtl.js:1`

[
![rtl](https://user-images.githubusercontent.com/31115595/150037195-78e40ac3-80ce-451a-ab07-229b147c4feb.png)
](url)

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version: 0.2.50
- RTL: "not installed"

*Thunderhub is also failing. Based on the logs provided below, it doesn't appear related, but I'm providing just in case they are:
`npm ERR! Failed at the thunderhub@0.12.31 start script.
Jan 18 17:47:02 myNode thunderhub[16175]: npm ERR!
Jan 18 17:47:02 myNode thunderhub[16175]: npm ERR! Exit status 1
Jan 18 17:47:02 myNode thunderhub[16175]: npm ERR! thunderhub@0.12.31 start: `next start "-p" "3030"`
Jan 18 17:47:02 myNode thunderhub[16175]: npm ERR! errno 1
Jan 18 17:47:02 myNode thunderhub[16175]: npm ERR! code ELIFECYCLE
Jan 18 17:47:02 myNode thunderhub[16175]:     at Object.loadConfig [as default] (/opt/mynode/thunderhub/node_modules/next/dist/server/config.js:399:74)
Jan 18 17:47:02 myNode thunderhub[16175]: Error: Not supported`

**Comment by tehelsper** [comment]
Can you attempt to re-install RTL via the application page and share the latest upgrade log from the settings page (minus and sensitive data)? That will show any install errors.

**Comment by tehelsper** [comment]
You should also be able to see the entire log from the settings page. The myNode UI allows browsing the log files.

One interesting thing is that your node (nodejs) version appears old, which could explain it. It should be something like v14.18.3.

A few options:
- From settings page try to re-install the latest version
- If that doesn't work, check log, possible try again
- Re-flash SD card with latest from mynodebtc.com/download and re-upgrade to v0.2.50

**Comment by brh28** [comment]
Upgraded NodeJs, which fixed my ThunderHub issue, but I'm still seeing an "import http" error in the RTL logs. But as long as I have a working wallet application, I'll hold off on re-flashing and good to consider this resolved from my end.

Appreciate the help! @tehelsper

**Comment by tehelsper** [comment]
Good to hear. Sometimes, if an upgrade fails due to network issues or some other random reason, any issues can be resolved by re-attempting the full version upgrade via the settings page "Reinstall Latest Version". Doing that may help as well and can't cause any further issues. The script is intended to be able to be executed multiple times in case any issues occur.
