### ISSUE TITLE
BTCPay breaking after adding LTC or doge as currency

### ISSUE THREAD

**Issue by second2falcon** [mynodebtc/mynode#621]
I tried adding LTC and DOGE as currency to BTCPay but that somehow bricked docker.

I expected after a reboot of my node.

**MyNode hardware (please complete the following information):**
 - Device: Debian AMD PC
 - Version 0.2.50

**Comment by tehelsper** [comment]
Never tried using LTC or DOGE and they aren't supported, but Docker should not have gotten hosed. Any specific error messages?

**Comment by second2falcon** [comment]
I have now reset my node, but if I recall correctly it said in the docket logs (even after reboots) starting docker services, then all the docker containers running and then stopping docker service. Something like that.

**Comment by second2falcon** [comment]
> Never tried using LTC or DOGE and they aren't supported, but Docker should not have gotten hosed. Any specific error messages?

Do you know if BTCPay is pre compiled or how btcpay server is installed? I know that if you just download the docker container, you can use **export** to set other currencies.

**Comment by tehelsper** [comment]
Latest release has a new install method. You could customize the exports prior to installing by editing the files.
