### ISSUE TITLE
LN stuck on "Waiting..."

### ISSUE THREAD

**Issue by ChristopherMarie** [mynodebtc/mynode#624]
LN suddenly stopped functioning properly. 
I flashed a new SD card and swapped it from the old one.
Also resetted the LND Config to default.

Renamed macaroon using:
cd ./.lnd/data/chain/bitcoin
mv mainnet mainnet-OLD

Currently looks like this
![image](https://user-images.githubusercontent.com/98503158/151281518-a8d027ad-78fe-4026-8a3a-46ac415d07ef.png)
![image](https://user-images.githubusercontent.com/98503158/151281678-ae830321-fa68-444d-9a9d-c06aaaa47e4d.png)

Using Raspi4 4gb

Snapshot of logs
![image](https://user-images.githubusercontent.com/98503158/151281864-f2340298-b69f-41ad-9319-354756b5f770.png)

**Comment by tehelsper** [comment]
What was happening before you moved the folder? Your channel DB is quite large. Did you re-flash with a 64 bit image?

**Comment by ChristopherMarie** [comment]
Not sure what you mean by moving the folder.

I dloaded using this:
![image](https://user-images.githubusercontent.com/98503158/151294688-93f8a9a6-c06e-4786-ab61-2ee76e08a420.png)

Not sure if I as previously using legacy.

here is the log
[lnd.log](https://github.com/mynodebtc/mynode/files/7947725/lnd.log)

here is some of the log using lncli getinfo:

    "synced_to_chain": false,
    "synced_to_graph": false,
    "testnet": false,
    "chains": [
        {
            "chain": "bitcoin",
            "network": "mainnet"
        }
    ],
    "uris": [
    ],
    "features": {
        "0": {
            "name": "data-loss-protect",
            "is_required": true,
            "is_known": true
        },
        "5": {
            "name": "upfront-shutdown-script",
            "is_required": false,
            "is_known": true
        },
        "7": {
            "name": "gossip-queries",
            "is_required": false,
            "is_known": true
        },
        "9": {
            "name": "tlv-onion",
            "is_required": false,
            "is_known": true
        },
        "12": {
            "name": "static-remote-key",
            "is_required": true,
            "is_known": true
        },
        "14": {
            "name": "payment-addr",
            "is_required": true,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        },
        "23": {
            "name": "anchors-zero-fee-htlc-tx",
            "is_required": false,
            "is_known": true
        },
        "30": {
            "name": "amp",
            "is_required": true,
            "is_known": true
        },
        "31": {
            "name": "amp",
            "is_required": false,
            "is_known": true
        },
        "45": {
            "name": "explicit-commitment-type",
            "is_required": false,
            "is_known": true
        },
        "2023": {
            "name": "script-enforced-lease",
            "is_required": false,
            "is_known": true
        }
    }
}

**Comment by tukac** [comment]
This issue is very similar to  #619 ...

**Comment by ChristopherMarie** [comment]
should i merge my issue with #619?
what should I do from here?

**Comment by ChristopherMarie** [comment]
> Did you re-flash with a 64 bit image?

Running on myNode (Linux 5.10.63-v8+ 64bit)

**Comment by tehelsper** [comment]
In your LND log, did you tell LND to restart or reboot your device during that time? I noticed a few times it indicated LND was going to restart.

Can you check the CPU and RAM use of LND via htop or something while it's running? It may be getting killed for using too much RAM if it's going off in the weeds.

**Comment by tehelsper** [comment]
I was wondering why you moved this folder:

cd ./.lnd/data/chain/bitcoin
mv mainnet mainnet-OLD

**Comment by ChristopherMarie** [comment]
Here is a new set of logs:
[lnd.log](https://github.com/mynodebtc/mynode/files/7962652/lnd.log)

i was recommended to use this to create a new macaroon directory after reboot:
cd ./.lnd/data/chain/bitcoin
mv mainnet mainnet-OLD

should I undo this? if so how?

RAM is currently at 73.9%. IIRC it was not like this before even when LN was not working.
![image](https://user-images.githubusercontent.com/98503158/151640332-9c189dce-06c6-427a-bf50-547546ecaa77.png)

Is this what you mean by htop?
![image](https://user-images.githubusercontent.com/98503158/151640463-10e279cd-e9d4-4612-878e-bcb43b2d5103.png)

**Comment by ChristopherMarie** [comment]
I have just upgraded, and now showing this:

![image](https://user-images.githubusercontent.com/98503158/151651873-68dd778c-5b6f-4931-b7c3-7d127ba42405.png)
![image](https://user-images.githubusercontent.com/98503158/151651904-078338fd-fcce-4e1e-a3e2-d0c240bd9a7b.png)

Glances is showing this:
![image](https://user-images.githubusercontent.com/98503158/151651882-be94bf9a-3a03-481d-8605-fa505379aabd.png)

**Comment by ChristopherMarie** [comment]
Latest logs
[lnd.log](https://github.com/mynodebtc/mynode/files/7963251/lnd.log)

**Comment by ChristopherMarie** [comment]
should i just do a factory reset on myNode or would that not make a difference?

**Comment by tehelsper** [comment]
It may help. I'd expect a SD card re-flash would help the most, but you said you'd tried that so it may not do much again. Glances looks fine - no extreme CPU usage or running out of RAM.

Does the disk usage and other info still show 0 / ...? That can indicate a problem if it stays that way.

**Comment by ChristopherMarie** [comment]
how do i go about channel backup and restoring?
Will doing a factory reset eventually lead to all the channels closing?

**Comment by tehelsper** [comment]
Manually closing any channels ahead of time would be beneficial. This guide may help. Restoring this way will close channels.

https://mynodebtc.github.io/lightning/restore.html

**Comment by ChristopherMarie** [comment]
is there a way of restoring without having to close all the channels? Or is this how LN work?
I have backup files channel.backup and channel-all.bak I think one of them might be from RTL. Will both work?

What would happen if I did not use the Channel Backup File?
![image](https://user-images.githubusercontent.com/98503158/152106907-83d357c3-eebb-4446-8b3d-d81793d41b4e.png)

**Comment by tukac** [comment]
Channel backup will force-close all your channels. There is no way around, this is how channels work.

channel.backup is created by LND itself. You created it via myNode web probably.
channel-all.bak is created by RTL interface. I never used it but I guess you can only use it inside RTL.

You should use newer backup. If they are created at the same time try channel.backup first.

However, before full restore I would first try flashing 32bit SD card with latest image. Maybe this issue is related to switching from 32bit to 64bit architecture. If so, going back to 32bit may be beneficial.

**Comment by ChristopherMarie** [comment]
Won't 32bit have issues as the channel db is quite large (980m)? #619 also noticed seeing it at 980m as well. Wondering if this is the limitations of 32bit.

**Comment by tehelsper** [comment]
I've read at 1GB 32-bit starts having issues, but I have not had it get that large myself. Use the channel.backup downloaded from myNode and make sure it's up to date as tukac recommended. The RTL backup only works within myNode.

**Comment by tukac** [comment]
I've switched to 64bit at around 950Mb.1024Mb seems to be the limit for 32bit.

If you decide to try 32bit image post here if any progress.

**Comment by ChristopherMarie** [comment]
I did a factory reset. this is what it currently looks like:
Is it still incomplete?

![image](https://user-images.githubusercontent.com/98503158/153684820-8722b766-88bb-4c92-bf97-990981e9d383.png)
![image](https://user-images.githubusercontent.com/98503158/153684754-cd42789c-a1c1-4cb2-b908-f82043123d99.png)

**Comment by tukac** [comment]
It looks fine but there is no sats in your wallet, you need to use seed from previous wallet to restore old wallet.
This seem no longer software issue, use Telegram channel for faster responses.

**Comment by ChristopherMarie** [comment]
i did use the previous seed. URI is the same except after @, where it is a different TOR address.

**Comment by tehelsper** [comment]
Maybe the seed recovery failed / didn't initiate or the peers are offline. You can check the status via CLI.

`lncli getrecoveryinfo`

**Comment by ChristopherMarie** [comment]
Showing this. What do I need to do from here?
![image](https://user-images.githubusercontent.com/98503158/153729673-a6f0a16f-bd40-4868-b7c5-3aebd180e44d.png)

**Comment by tehelsper** [comment]
Did you attach the SCB file when re-making your wallet?

**Comment by ChristopherMarie** [comment]
the channel.backup file? if so, yes.

**Comment by ChristopherMarie** [comment]
It does show 2 onchain recent transactions from a while ago, and that is it.

![image](https://user-images.githubusercontent.com/98503158/153734931-d82dcb09-99c6-490b-a969-538f951477b7.png)

**Comment by ChristopherMarie** [comment]
I did a full rescan using reset-wallet-transactions=true. It is now displaying an onchain balance, however there are zero channels/balances. On 1ML/Amboss there are still channels open. It seems the channel.backup file did not work, or was not executed. How can I get this to work properly?

**Comment by tukac** [comment]
channel.backup will force close all channels. You will not see them open in RTL. Funds will be returned to on-chain wallet.

Force closing a channel can take from a day up to a couple of weeks, so be patient.

**Comment by ChristopherMarie** [comment]
is there a way to check whether the channel.backup process is running?

**Comment by tehelsper** [comment]
I believe the previous command was a way to check that - `lncli getrecoveryinfo`

If you use lncli to get detailed channel info, do you see any that are pending close?

**Comment by ChristopherMarie** [comment]
This is what it is returning

![image](https://user-images.githubusercontent.com/98503158/154175932-ae582536-9566-40ba-987c-fdfe18db4dec.png)

**Comment by tukac** [comment]
Try `lncli listchannels` and `lncli getinfo`.

How did you initiate force closing? Coupe of useful links from googling "lnd restoring channel.backup":
https://docs.lightning.engineering/lightning-network-tools/lnd/disaster-recovery
https://www.youtube.com/watch?v=o9j9-9CbRj0

**Comment by ChristopherMarie** [comment]
I asked a node to force close our channel from their end. The other node received their side of the funds, however I do not see my side in my onchain wallet. I did a rescan, and it still did not appear. What can I do to retrieve it, or make it appear on my myNode?

**Comment by tehelsper** [comment]
It can take weeks for a force-close to show up in the wallet. And only then, it will show up if lnd is running properly, which it may not be. I'm thinking it may be in a restart loop or was before re-making, but it doesn't look like it did the auto-recovery via SCB for some reason.

This may help:
https://mynodebtc.github.io/lightning/restore.html#manual-recovery

**Comment by ChristopherMarie** [comment]
i saved the channel.backup file in   /home/admin as i kept getting permission denied elsewhere.
I then ran this code:  lncli restorechanbackup --multi_file=/home/admin/channel.backup
It has closed most of the channels. There are some remaining. 
I am starting to see balances coming on chain, but I do not see the funds from the channel from my prev msg.

What should I do about the remainder? Most of them are online, and I had channels with them well before I saved the SCB.

**Comment by tehelsper** [comment]
Permission denied? There's a button to download the most recent copy on the Lightning and Settings page.

I'd just wait. I'm not sure which SCB you used, so it may not be closing all channels.

**Comment by ChristopherMarie** [comment]
I meant I transferred the channel.backup file using scp from my PC to mynode. I got permission denied trying to save it to /home/bitcoin/lnd_backup/ so I chose /home/admin/ instead.

The SCB I am using is the one I downloaded from mynode before I did the factory reset.

**Comment by tehelsper** [comment]
OK, gotcha, that makes sense.
