### ISSUE TITLE
Option to enable peer bloom filters

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#627]
To add mynode as a peer to Bisq, it should have "peerbloomfilters=1" defined in the config file, acording to their documentation here: https://bisq.wiki/Connecting_to_your_own_Bitcoin_node.

Could this be added as a toggle switch, the same way activating BIP158 is currently set up?

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
I'm not familiar with all the issues, but I think there are some concerns with bloomfilters when exposed online. If I understand correctly, the current setup should allow peerbloomfilters for local connections. Would that work for your setup?

If so, could you try verifying this is in your config and that a Bisq connection works?

# Enable Bloom filters
whitelist=bloomfilter@127.0.0.1
whitelist=bloomfilter@10.0.0.0/8
whitelist=bloomfilter@172.16.0.0/12
whitelist=bloomfilter@192.168.0.0/16

**Comment by raymonddurk** [comment]
I have Bloom filters enabled with the above and it works just fine with Bisq.

**Comment by tehelsper** [comment]
You may want to start here. I think it just opens up a possible DDoS vector where someone could slow down your node with a huge amount of complex requests.

**Comment by Jacksper13** [comment]
Hmm, I see... How about adding the toggle and a warning when enabled? It's just that manually changing the config the file to add my specific Bisq client it's non-standard messes with upgrades, and it'd be great to have an "official"/"standard" way of adding this and keeping the upgrades smooth. Thanks!

**Comment by tehelsper** [comment]
I'll add a toggle w/ warning.

**Comment by Jacksper13** [comment]
Awesome, thank you! Closed with 16d78404d2189d1d3feebad8df6c33908fc11f3b
