### ISSUE TITLE
Thoughts about the current UI

### ISSUE THREAD

**Issue by soyjavi** [mynodebtc/mynode#63]
:fist_oncoming: 

First, congratulations on the project. I think it is very important for this ecosystem create more alternatives for each individual to have their own node.

I would like to open this thread to think about the possible improvements that I think the project should have regarding UI / UX.

I think it would be very important to get away from the *ServerSideRendering* pattern and build something API oriented. In this way we could create a better and most UI/UX friendly frontend client. Also In this way we could create a good security policies for our API and give other developers the opportunity to create / improve different clients.

Imagine a client with:
 - push notifications (tx states, invoices...)
 - auto (hidden) updates...
 - great mobile UX

Thoughts??

**Comment by tehelsper** [comment]
Aging out. UI improvements are still possible
