### ISSUE TITLE
BtcPay server 502 Bad Gateway error after upgrade to 0.2.52

### ISSUE THREAD

**Issue by tukac** [mynodebtc/mynode#631]
After completing recent upgrade 0.2.52 BtcPay server v1.4.4 shows 502 Bad Gateway error.

On same network and same browser, another MyNode 0.2.48 BtcPay v1.3.6 server works fine.

Both are RPi 4B + SSD.

docker logs btcpayserver_btcpayserver_1

[btcpayserver docker log](https://github.com/mynodebtc/mynode/files/8056325/btcpayserver.docker.log)

**Comment by tukac** [comment]
I've noticed dotnet is very active. One core is 100% used by dotnet for an half hour now. I will disable BTCPay server to see if it stops.

**Comment by tehelsper** [comment]
Can you also run docker ps? The error is saying BTC Pay server can't start because something else is using the port.

**Comment by tukac** [comment]
Sure:
[docker ps.txt](https://github.com/mynodebtc/mynode/files/8056813/docker.ps.txt)

Dotnet is still running at 100% CPU after 3 hours. I will let it run some more.

**Comment by tehelsper** [comment]
OK, since the dotnet process is coming from the nbxplorer container, could you try getting those logs?

docker logs btcpayserver_nbxplorer_1

**Comment by tukac** [comment]
NBXplorer seem to require "whitelist=127.0.0.1" line in bitcoind config. After I have edited BtcPay server works ok!

[docker logs btcpayserver_nbxplorer_1.txt](https://github.com/mynodebtc/mynode/files/8059156/docker.logs.btcpayserver_nbxplorer_1.txt)

**Comment by tehelsper** [comment]
Did you happen to have a custom Bitcoin config? 127.0.0.1 should already be partially whitelisted. I'm not sure how this wouldn't cause it to break on all setups.

**Comment by tukac** [comment]
I have custom config, yes. I have previously whitelisted download@127.0.0.1 and bloomfilter@127.0.0.1. Same config since upgrade to 1.4.4 (from 1.3.6) resulted in BtcPay server 502 Bad Gateway error.

I have another node with virtually same config still running 1.3.6 fine. Something changed within BtcPay server.

**Comment by tehelsper** [comment]
Yeah, I think BTCPay must have required something new, but I'm not sure what else it could be since download and bloomfilter should have already been enabled.
