### ISSUE TITLE
Syncing Blockchain and Telegram support

### ISSUE THREAD

**Issue by cybercrypt13** [mynodebtc/mynode#633]
I have had mynode running for 2 weeks now syncing the blockchain and it is still doing so.  It has gotten up to 67xxxx of 72xxxx but appears to only sync if I am viewing the page.  No Idea what is going on.

On a side note, I attempted to joining the telegram group for help but keep getting kicked off of the group.  Have done this twice and both times before I could get finished typing I got kicked off.

Thanks,

**Comment by tehelsper** [comment]
That's not a terrible sync speed, but 7 days is closer to what I would expect. If your tor connection isn't great, it could be slowing things down. It can be disabled on the settings page.

For Telegram, does it ask you to answer a simple math question? Maybe try a different app, like desktop or tablet or upgrade your current one to see if it helps? I haven't heard of anyone else having issues.

**Comment by cybercrypt13** [comment]
yes, I missed the math problem.  I got that taken care of.  I also didn't realize it was syncing completely over tor so understand the speed issue.  I was thinking it was just over my connection which is very fast and was confused.  All good.

thanks,

**Comment by Jacksper13** [comment]
Close issue?
