### ISSUE TITLE
LND alias goes blank and /lnd/change_alias triggers Internal Server Error

### ISSUE THREAD

**Issue by richardsj** [mynodebtc/mynode#638]
**Describe the bug**
Using the web UI, LND -> click icon to change alias

OR edit /home/bitcoin/.lnd/lnd.conf and edit alias= to contain anything
OR service lnd stop ; edit /home/bitcoin/.lnd/lnd.conf ; service lnd start

**Expected behavior**
Node alias e.g. "MyNiftyNode" should be set in alias= and visible on RTL and Thunderhub

Instead RTL shows the first digits of the node ID hex and Thunderhub and 1ML.com do too

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version [e.g. 0.2.53]

**Comment by tehelsper** [comment]
Thanks for logging this. I can reproduce. I'll work on getting a fix out for the next release.

**Comment by tehelsper** [comment]
Fixed in latest release.
