### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by lucbran** [mynodebtc/mynode#641]
After latest upgrade, I can connect and login to mynode but page shows Internal Server Error..If you tried manual upgrade, please try again..
Have repeated same operation 4 times but same result.. What to do?
Thanks

**Comment by tehelsper** [comment]
Can you connect to the command line or jump to the status page by adding /status to the URL? Then check the www log to see the error details.

If command line, try this:

sudo journalctl -f -u www

**Comment by tehelsper** [comment]
To help fix, you can try this:

sudo /usr/bin/mynode_post_upgrade.sh

**Comment by ordoabcrypto** [comment]
I'm getting the same error after the update but it occurs when trying to change my LN node Alias. It won't change despite updating the config file, saving and rebooting (it actually got cleared and I can't set a new one).

`Internal Server Error.If you tried manual upgrade, please try again.` comes up each time I try from the GUI.

**Comment by tehelsper** [comment]
There was an issue changing the alias a few versions back. Try updating to the latest release.

**Comment by ordoabcrypto** [comment]
Am on latest release already (0.2.53). Reached out to support and was informed to try updating to beta. Will give that a shot tonight and report back.

**Comment by tehelsper** [comment]
Sorry, I was incorrect. The fix is only in the beta and not the latest release. It will be in the next update.

**Comment by tehelsper** [comment]
Fixed in latest release.
