### ISSUE TITLE
Electrum server crashes with invalid message

### ISSUE THREAD

**Issue by rossengeorgiev** [mynodebtc/mynode#646]
**Describe the bug**
Electrum syncs to about 40% and then crashes with the following log message

**Expected behavior**
To sync completely

**MyNode hardware (please complete the following information):**
 - Device: Desktop with Intel CPU on Debian
 - Version 0.2.53

**Additional context**

```
Mar 31 23:21:34 myNode systemd[1]: Stopped myNode Electrum Server.
Mar 31 23:21:34 myNode systemd[1]: electrs.service: Scheduled restart job, restart counter is at 506.
Mar 31 23:21:34 myNode systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Mar 31 23:20:34 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Mar 31 23:20:34 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Mar 31 23:20:34 myNode electrs[13514]:     2: receiving on an empty and disconnected channel
Mar 31 23:20:34 myNode electrs[13514]:     1: failed to get block 0000000000000000bb8d183e01646010c579424f6acdcbc605a1236c049921df
Mar 31 23:20:34 myNode electrs[13514]:     0: sync failed
Mar 31 23:20:34 myNode electrs[13514]: Caused by:
Mar 31 23:20:34 myNode electrs[13514]: Error: electrs failed
Mar 31 23:20:34 myNode electrs[13514]: [2022-03-31T20:20:34.060Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Mar 31 23:20:34 myNode electrs[13514]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 31 23:20:34 myNode electrs[13514]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 6693323263, max: 4000000 }', src/p2p.rs:211:62
```

**Comment by tehelsper** [comment]
I would guess that means corrupt data since the application overall does seem to run. Can you try this:

- Reset Electrum data via the settings page
- If that doesn't help, reset blockchain data and then reset the electrum data again

**Comment by rossengeorgiev** [comment]
Tried electrum reset, but still crashes with the same message. Tried to reindex, which I understand is only chain reindex, but that also got stuck abour 30-40% in. End up starting from scratch as I changed the hardware. Thanks

**Comment by tehelsper** [comment]
One other thought - it was likely a saved custom bitcoin config. If you had saved a config and aren't using the latest myNode default upload to electrum from bitcoin is limited to 1GB before it stops sending data.
