### ISSUE TITLE
BIP 157 Toggle causes reboot issue due to missing blockfilterindex

### ISSUE THREAD

**Issue by glencjones** [mynodebtc/mynode#650]
**Describe the bug**
On toggling bip 157 and pressing save mynode saves and restarts causing it to fail because the -blockfilterindex=1 has not been set too.

**Screenshots**
![image](https://user-images.githubusercontent.com/23737842/164759092-1a3f622b-8b31-4220-96b8-a70123e43c64.png)

 - Version: beta_04-13-22_1649911391

**MyNode hardware (please complete the following information):**
 - Device:Raspi4,

**Additional context**
possibly another toggle should be flipped at the same time, or both flags are placed in the config.
-peerblockfilters=1
-blockfilterindex-1

**Comment by tehelsper** [comment]
Thanks. You can also toggle BIP158 to get rid of that error. I should automatically set blockfilterindex=1 if BIP157 is enabled.

**Comment by glencjones** [comment]
Yep the problem happened because I did not read around the subject, hit save and I had no chance to recover.   So my fault, for being a noob I should have also read what would happen (i.e. Index rebuild).  I think for noobs it should automatically set the other toggle, with a warning of a restart.

**Comment by tehelsper** [comment]
Yeah, I hadn't realized they weren't both mutually exclusive. Next release will have it set so any dependencies are also set if 158 is enabled.

**Comment by tehelsper** [comment]
Included fix in latest release.
