### ISSUE TITLE
Channel.backup file Page Not Found

### ISSUE THREAD

**Issue by Fiach-Dubh** [mynodebtc/mynode#654]
**Describe the bug**
within localhost/settings i scroll down to the Lightning section and click "Download" under "DOWNLOAD CHANNEL BACKUP". It redirects me to "Page not found" "myNode 404" in the tab.

**Expected behavior**
A file of some kind to either save externally or locally.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser:  chromium
 - Version: 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.12 (64-bit)

**MyNode hardware (please complete the following information):**
 - Device: Laptop with OS on internal SSD and Data on internal HDD
 
**Additional context**
mynode version 0.2.54
2 channels are currently open, though they have not yet been used.

**Comment by tehelsper** [comment]
Can you run this and share the output.

sudo systemctl status lnd_backup

**Comment by Fiach-Dubh** [comment]
lnd_backup.service - Backup LND Channel File
   Loaded: loaded (/etc/systemd/system/lnd_backup.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-05-03 17:50:31 CDT; 12h ago
  Process: 15505 ExecStartPre=/usr/bin/is_not_shutting_down.sh (code=exited, status=0/SUCCESS)
  Process: 15506 ExecStartPre=/usr/bin/wait_on_bitcoin.sh (code=exited, status=0/SUCCESS)
  Process: 15508 ExecStartPre=/usr/bin/wait_on_lnd.sh (code=exited, status=0/SUCCESS)
 Main PID: 16190 (python3)
    Tasks: 1 (limit: 4915)
   Memory: 26.1M
   CGroup: /system.slice/lnd_backup.service
           └─16190 /usr/local/bin/python3 /usr/bin/mynode_backup_scb.py

May 04 06:45:14 myNode lndbackup[16190]:   Hash 1: dbea2875655334df1403f921fca1969c
May 04 06:45:14 myNode lndbackup[16190]:   Hash 2: REPLACE_FILE
May 04 06:45:14 myNode lndbackup[16190]: Error: [Errno 2] No such file or directory: '/home/bitcoin/lnd_backup/channel.backup'
May 04 06:45:14 myNode lndbackup[16190]: Drive mounted!
May 04 06:45:14 myNode lndbackup[16190]: Backing up SCB file...
May 04 06:46:14 myNode lndbackup[16190]: Drive mounted!
May 04 06:46:14 myNode lndbackup[16190]: Backing up SCB file...
May 04 06:46:14 myNode lndbackup[16190]:   Hash 1: dbea2875655334df1403f921fca1969c
May 04 06:46:14 myNode lndbackup[16190]:   Hash 2: REPLACE_FILE
May 04 06:46:14 myNode lndbackup[16190]: Error: [Errno 2] No such file or directory: '/home/bitcoin/lnd_backup/channel.backup'

**Comment by Fiach-Dubh** [comment]
I navigated to the bitcoin folder and did an "ls" checking for a lnd_backup folder. nothing showed up for the bitcoin folder when doing ls

**Comment by Fiach-Dubh** [comment]
I redid the sudo systemctl status lnd_backup after rebooting successfully and got:

● lnd_backup.service - Backup LND Channel File
   Loaded: loaded (/etc/systemd/system/lnd_backup.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-05-04 07:19:18 CDT; 11min ago
  Process: 10624 ExecStartPre=/usr/bin/is_not_shutting_down.sh (code=exited, status=0/SUCCESS)
  Process: 10625 ExecStartPre=/usr/bin/wait_on_bitcoin.sh (code=exited, status=0/SUCCESS)
  Process: 10627 ExecStartPre=/usr/bin/wait_on_lnd.sh (code=exited, status=0/SUCCESS)
 Main PID: 11236 (python3)
    Tasks: 1 (limit: 4915)
   Memory: 25.5M
   CGroup: /system.slice/lnd_backup.service
           └─11236 /usr/local/bin/python3 /usr/bin/mynode_backup_scb.py

May 04 07:29:19 myNode lndbackup[11236]: Drive mounted!
May 04 07:29:19 myNode lndbackup[11236]: Backing up SCB file...
May 04 07:29:19 myNode lndbackup[11236]:   Hash 1: 2c8b5dad8bacb0f7275bee396f450879
May 04 07:29:19 myNode lndbackup[11236]:   Hash 2: REPLACE_FILE
May 04 07:29:19 myNode lndbackup[11236]: Error: [Errno 13] Permission denied: '/home/bitcoin/lnd_backup/channel.backup'
May 04 07:30:19 myNode lndbackup[11236]: Drive mounted!
May 04 07:30:19 myNode lndbackup[11236]: Backing up SCB file...
May 04 07:30:19 myNode lndbackup[11236]:   Hash 1: 2c8b5dad8bacb0f7275bee396f450879
May 04 07:30:19 myNode lndbackup[11236]:   Hash 2: REPLACE_FILE
May 04 07:30:19 myNode lndbackup[11236]: Error: [Errno 13] Permission denied: '/home/bitcoin/lnd_backup/channel.backup'

**Comment by tehelsper** [comment]
OK, I think I know what's going on and it's a permissions issue. Can you try installing the latest beta from the bottom of the settings page? It would be version "beta_05-04-22_1651726662".

**Comment by Fiach-Dubh** [comment]
hmm, 

i just did cat channel.backup in terminal

looks, interesting

less special characters, so its not encrypted this time. but more < / ^ and caps locked characters

14 lines in length

sound about right?

**Comment by tehelsper** [comment]
I think it is encrypted by your seed phrase and it's stored in a binary format, so there's no way to look at it with a text editor. It's used when re-making a wallet.

**Comment by Fiach-Dubh** [comment]
thank you again!
