### ISSUE TITLE
LNDg Django backend login user/pass

### ISSUE THREAD

**Issue by tukac** [mynodebtc/mynode#655]
I have installed LNDg v1.0.5. I can't log in because Django login requires user/pass. What is it?

LNDg v1.0.5
MyNode 0.2.55

**Comment by tehelsper** [comment]
Should be admin / bolt as default

**Comment by tukac** [comment]
It is, thanks

**Comment by macaronish** [comment]
Is there a way to change the password for LNDg? It seems like changing the myNode password does not get applied to LNDg.
