### ISSUE TITLE
Bitcoin error.

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [mynodebtc/mynode#661]
**Describe the bug**
Shutdown: done
scheduler thread exit
Shutdown: In progress...
Error: Invalid or corrupt peers.dat (Checksum mismatch, data corrupted).

**Expected behavior**
Go to
cd /home/bitcoin/.bitcoin/
ls
sudo rm -rf peers.dat

Restart bitcoin.

**MyNode hardware (please complete the following information):**
 - Device: [VM]
 - VERSION 0.2.55

**Additional context**
If you have more archives like peers.xXXx, peers.XxxX, ..., delete too and restart bitcoin to fix.

**Comment by tehelsper** [comment]
Sounds like you resolved it. Deleting any corrupt files would resolve the issue. That is a bit unusual though - I've never seen the peers db be corrupted.
