### ISSUE TITLE
Not keeping up with sync

### ISSUE THREAD

**Issue by rico1881** [mynodebtc/mynode#663]
Keep getting this error on the status page as my node is struggling to keep with blocks and seems to be constantly syncing

Low MemoryYour device was running low on memory and a process has been restarted. You may want to disable some applications.[404366.596717] Out of memory: Killed process 29295 (node) total-vm:23480028kB, anon-rss:1523476kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:6596kB oom_score_adj:0
--

**Comment by tehelsper** [comment]
What type of device are you using? That message just means that your device is running out of RAM. You could also try increasing the amount of SWAP on the settings page, but that's not a great solution. Disabling some apps may be be your best path.

**Comment by rico1881** [comment]
im using rasp pi, since latest update seems to be ok just that electrum is not syncing now. everything else is working ok. 
getting the following :

-- Logs begin at Sun 2022-06-05 23:24:47 CDT, end at Tue 2022-06-07 23:26:24 CDT. --
Jun 07 23:26:05 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Jun 07 23:26:05 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 23:26:05 myNode electrs[12051]:     1: No such file or directory (os error 2)
Jun 07 23:26:05 myNode electrs[12051]:     0: failed to open bitcoind cookie file: /home/bitcoin/.bitcoin/.cookie
Jun 07 23:26:05 myNode electrs[12051]: Caused by:
Jun 07 23:26:05 myNode electrs[12051]: Error: electrs failed
Jun 07 23:26:05 myNode electrs[12051]: [2022-06-08T04:26:05.267Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Jun 07 23:26:05 myNode electrs[12051]: [2022-06-08T04:26:05.234Z INFO  electrs::chain] chain updated: tip=000000000000000000010856b86d2dc017781825d087c5d2cfa0e92396d56c3f, height=737382
Jun 07 23:26:00 myNode electrs[12051]: [2022-06-08T04:26:00.547Z INFO  electrs::chain] loading 737382 headers, tip=000000000000000000010856b86d2dc017781825d087c5d2cfa0e92396d56c3f
Jun 07 23:25:55 myNode electrs[12051]: [2022-06-08T04:25:55.761Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 148 SST files, 35.30922954 GB, 4.395412505 Grows
Jun 07 23:25:55 myNode electrs[12051]: [2022-06-08T04:25:55.670Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Jun 07 23:25:55 myNode electrs[12051]: [2022-06-08T04:25:55.670Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Jun 07 23:25:55 myNode electrs[12051]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Jun 07 23:25:55 myNode systemd[1]: Started myNode Electrum Server.

**Comment by tehelsper** [comment]
Can you check to see if this file exists?

sudo ls -lsa /home/bitcoin/.bitcoin/.cookie

**Comment by rico2095** [comment]
Where do I find this file ?

**Comment by tehelsper** [comment]
In the /home/bitcoin/.bitcoin/ folder. That was the Linux terminal command to see if it exists.

**Comment by rico2095** [comment]
Well I don’t think it exits


Many Thanks

Mark Richards

**Comment by rico1881** [comment]
any update on what to do ret next to solve issue? thanks

**Comment by tehelsper** [comment]
Did you check to see if it exists? If not, have you customized your bitcoin config file at all? For some reason, bitcoin must not be making the .cookie file. Can you share the output of the command above?

**Comment by rico2095** [comment]
I do remember adding rpc user and password a while ago, shall I remove this?

**Comment by rico2095** [comment]
Thanks Taylor that sorted it 👍

**Comment by rico1881** [comment]
Where do I look for this?

Many Thanks
Mark
________________________________
