### ISSUE TITLE
NGINX Bad Gateway After Update

### ISSUE THREAD

**Issue by a-pie** [mynodebtc/mynode#664]
I cannot access the node via the browser - I keep getting a NGINX Bad Gateway page.
I can still reach the node via SSH, and it shows up on my routers client list.

Multiple browsers have been tested, all get the following response - but only from the 'mynode.local' endpoint:
502 Bad Gateway
nginx/1.14.2

Every other endpoint is unreachable.

Here is the bottom of the log in the admin home ~/upgradelogx/upgrade_log_from_0.2.42_upgrade.txt (let me know if it is safe to paste more of it):

./out/rootfs_raspi4/var/www/mynode/static/jquery_ui/images/ui-icons_ffffff_256x240.png
./out/rootfs_raspi4/var/www/mynode/static/jquery_ui/images/ui-icons_555555_256x240.png
./out/rootfs_raspi4/var/www/mynode/static/jquery_ui/images/ui-icons_444444_256x240.png
++ cat /opt/upgrade/out/rootfs_raspi4/usr/share/mynode/version
+ VERSION=0.2.56
+ '[' 0 = 1 ']'
+ cp -rf /opt/upgrade/out/rootfs_raspi4/etc /opt/upgrade/out/rootfs_raspi4/home /opt/upgrade/out/rootfs_raspi4/lib /opt/upgrade/out/rootfs_raspi4/opt /opt/upgrade/out/rootfs_raspi4/usr /opt/upgrade/out/rootfs_raspi4/var /
+ e.log
/usr/bin/mynode_upgrade.sh: line 58: e.log: command not found
+ exit 1

**Comment by a-pie** [comment]
UNAME='Linux myNode 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux'

**Comment by tehelsper** [comment]
That's unusual. Two ideas:

- Re-run the upgrade by running "sudo /usr/bin/mynode_upgrade.sh"
- Re-flash the SD card with the latest image (brand new) from mynodebtc.com/download
