### ISSUE TITLE
Can't configure static IP address on Debian

### ISSUE THREAD

**Issue by tioneb22** [mynodebtc/mynode#676]
I would like to set a static IP address for myNode but the traditional method isn't working.
Typically on Debian we need to edit the **/etc/network/interfaces** and change this line:
>iface enp0s3 inet dhcp

to these lines:

> iface enp0s3 inet static
>         address 10.10.111.40
>         netmask 255.255.255.0
>         gateway 10.10.111.1

Reloading and restarting the networking service doesn't apply the config, I even tried rebooting the box from the WebUI's "Reboot Device" button.

I kept troubleshooting and noticed that the current interface being used for DHCP was different than the one specified in "/etc/network/interfaces". (I ran an "ip add" to find out). 
It was **ens33** instead of **enp0s3**.

I edited the /etc/network/interfaces file to match the ens33 interface instead and tried rebooting but it's still getting it's IP from DHCP.

How can I set a static IP address?

#
# EDIT / Update
#
Okay. So I decided to run a manual upgrade (According to https://www.reddit.com/r/mynodebtc/comments/e4jscx/faq_how_to_update_mynode_community_edition/).
After the upgrade completed the box rebooted and it lost network connectivity. It didn't grab an IP from DHCP and the static IP I had set was not configured either.
I consoled into the VM and checked the interface status (running "ip add") and it was down, no IP configured.

So what controls the IP address?!

**Comment by tehelsper** [comment]
It uses network manager. I would try creating a "host" (name may differ) in your DHCP server so it assigns the same IP address to the device based on its MAC address. That way it still get the DNS info, etc...

**Comment by tioneb22** [comment]
Okay. So theoretically I can configure a static IP via the `nmcli `command.
Will rebooting myNode overwrite my changes?

Setting a static IP should really be an option in the WebUI.

**Comment by tioneb22** [comment]
Alright, I was able configure a static IP address using nmcli, and I've confirmed that it persists a reboot.
The up/down part must be done through the local console, or you can just reboot the box for changes to take effect:

> sudo nmcli connection modify Wired\ connection\ 1 ifname ens33 ipv4.method manual ipv4.addresses X.X.X.X/24 gw4 X.X.X.X
> sudo nmcli connection reload
> sudo nmcli connection down Wired\ connection\ 1
> sudo nmcli connection up Wired\ connection\ 1
