### ISSUE TITLE
Web server down after manual upgrade

### ISSUE THREAD

**Issue by tioneb22** [mynodebtc/mynode#677]
I ran an upgrade manually (as per the reddit post here -> https://www.reddit.com/r/mynodebtc/comments/e4jscx/faq_how_to_update_mynode_community_edition/) and now myNode is no longer accessible via port 80, port 443 gives me a "502 Bad Gateway" error.

The upgrade had succeeded and my Putty session got disconnected when it had completed.

I'm trying to troubleshoot what went wrong and I'm running into an error when trying to run the Python web server manually.
I'm running it via:
`sudo python /var/www/mynode/mynode.py`
and I'm getting an error that says "NameError: name 'register_dynamic_app_flask_blueprints' is not defined"

Any help is greatly appreciated!

**Comment by tioneb22** [comment]
Okay, so I did some troubleshooting. The mynode.py script was complaining about not having a function called "register_dynamic_app_flask_blueprints". I search for this function across all python files in the /var/www/mynode directory and I didn't get any hits (other than the mynode.py of course). So I'm not sure what this is used for...

I commented this line out (line 111) from the mynode.py script and tried to run it again and....voila, it works!

It doesn't seem like the register_dynamic_app_flask_blueprints is used for anything? Can anyone correct me if I'm wrong?
I'll keep this commented out until there is a different resolution. I will keep this bug open for now.

**Comment by tehelsper** [comment]
Did you pull straight from master? You may want to try getting the code for the latest release. There are a lot of moving parts right now preparing for some large changes.

**Comment by tioneb22** [comment]
I'm not sure, I followed the pinned reddit post here: https://www.reddit.com/r/mynodebtc/comments/e4jscx/faq_how_to_update_mynode_community_edition/

I assume I got the most recent code, I run a "git pull" from the cloned repo and it tells me its the latest release.

**Comment by tehelsper** [comment]
You could try downloading the latest release tarball rather than the git steps.

Commands:
wget https://github.com/mynodebtc/mynode/archive/refs/tags/v0.2.57.tar.gz -o mynode.tar.gz
tar -xvf mynode.tar.gz

**Comment by tioneb22** [comment]
It's working now so I'll close this issue, but if it happens again I can try the tar ball.
