### ISSUE TITLE
Feature Request: LND Tor HyBrid Mode (TOR + ClearNet)

### ISSUE THREAD

**Issue by InsaneSplash** [mynodebtc/mynode#678]
I would like to ask if we can include the option to allow LND to run in a hybrid mode, ie make use of TOR and ClearNet at the same time. Currently, you can only run LND with TOR or without TOR. 

It is possible to edit the lnd config file to manually add and modify where required to get this implemented, but this provides warnings of future updates being ignored and would assist in allowing the system to function without any custom changes.

Add the option to enable/disable split connectivity
`tor.skip-proxy-for-clearnet-targets=true`
`tor.streamisolation=false`

Allow LND to listen on all IP's instead of only localhost without disabling TOR
`listen=0.0.0.0:9735`

Add the ability to specify an external IP if one has a static IP
`externalip=xxx.xxx.xxx.xxx:9735`
OR for Dynamic DNS hosts
`externalhosts=ln.example.com:9735`

Add the ability to enable NAT mode if myNode does not have a public static IP.
`nat=true`

Additional reference information found here - [https://lightningnetwork.plus/posts/137](https://lightningnetwork.plus/posts/137)

- [X] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
This is a cool idea. I'll add it to the list of future features.
