### ISSUE TITLE
Write Guide for Accessing GUI via Tor

### ISSUE THREAD

**Issue by tehelsper** [mynodebtc/mynode#68]

**Comment by abhiShandy** [comment]
I have made a guide to setup Tor browser and access web GUI on MacOS

[torSetupMacOS.zip](https://github.com/mynodebtc/mynode/files/3877152/torSetupMacOS.zip)

**Comment by tehelsper** [comment]
Thanks! But I'm aging this issue out since passwords are no longer needed and using the web GUIs link now provides access in the Tor Web Browser.
