### ISSUE TITLE
Poor performance using the PC Disk Image boot method

### ISSUE THREAD

**Issue by vicariousdrama** [mynodebtc/mynode#682]
**Describe the bug**
Using PC Disk Image v0.2.55 as bootable USB, bootup works from the USB and MyNode begins its sync process, but seems all disk I/O is running through the attached USB thumbdrive, hindering performance

**Expected behavior**
Disk I/O performance should be much faster off internal SSD.  

**Screenshots**

Here is a section of glances, showing a depiction of the file system.  Note that sda is the internal 1 TB SSD, and sdb is the attached, bootable USB thumbdrive (32 GB max)
![image](https://user-images.githubusercontent.com/88121568/180126581-644d626c-d5f2-45dd-9b84-629d80ae3cf0.png)

Here is a capture from atop showing sdb as the bottleneck.  The internal hard drive is hardly accessed, while swap is maxed out and the attached thumb drive is constantly busy.
![image](https://user-images.githubusercontent.com/88121568/180126727-7d2e82b3-c0d9-41af-b194-d8a86d6af6f8.png)

The swap is verified as being at /mnt/hdd/swapfile
![image](https://user-images.githubusercontent.com/88121568/180126902-f4209bd2-cfe8-46e5-8ec6-beea110029bd.png)

With exception to /mnt/hdd, every one of these filesystems is effectively under / which lives on the sdb2 (USB thumbdrive) device
![image](https://user-images.githubusercontent.com/88121568/180126964-f3f021f9-f748-4ca3-8676-71692cb49d30.png)

**Desktop (please complete the following information):**
 - not applicable

**MyNode hardware (please complete the following information):**
 - Device: ASUS Laptop circa 2015, i7 CPU, 16 GB RAM, 1 TB SSD storage
 - Version: v0.2.55 PC Disk Image, mynode_amd64_0-2-55_uefi.img.gz (amd64)

**Additional context**
Relatedly, should be able to install from the USB, and no longer need the USB thumbdrive for subsequent boots, but presumably that is a separate plan in the roadmap

**Comment by tehelsper** [comment]
This may be running as expected. Can you add more details on exactly what IO is on the USB that should be on the data drive (SSD)?

All OS data will be on the drive you flashed with myNode. The design is such that there are always two drives - one for the OS and one for the data. So, the USB will still be used. If you have secondary internal SSD you could always write the myNode image to that as well. However, using one SSD for the OS and data storage is not currently supported.

**Comment by vicariousdrama** [comment]
I don't know what specifically is running through the USB (the bootable OS image), but I know it has constant disk I/O because it has a red led that lights up to show disk activity for reads/writes and its just nonstop.

It should finishing synching over the next 4 hours and then I'll see if app performance is actually viable running all disk I/O through the usb.  

Ultimately though I'll need to redo this and use partitions on the disk to separate OS and data, unless the scripts can't support that due to forcefully using different block devices.  Really need a way to install to a single internal SSD and not require 2 separate devices.

**Comment by vicariousdrama** [comment]
This issue has been resolved through coordination in telegram group.  Ultimate cause was a poor performing USB flashdrive that was being used by OS.  Once a faster drive was acquired and had the disk image burned to it, the system came up noticeably faster (in about a minute, vs 10 minutes), disk activity was stable, with no CPU_IOWAITs and avio in atop showing sub millisecond access times

The culprit: Microcenter branded 32 GB USB 3.0 with internal labeling 511-180619191
Replaced with: Samsung USB 3.1 Flash Drive FIT Plus at 64 GB
