### ISSUE TITLE
Woes upgrading to 64bit: Electrs (Certs), WebSSH2 (not running), others

### ISSUE THREAD

**Issue by vicariousdrama** [mynodebtc/mynode#690]
**Describe the bug**
I'm not able to successfully run any applications apart from Bitcoin Core and Lightning after upgrading to 64bit version of mynode.  Previously this was running on 32bit and to upgrade I took a new microsd, flashed the 64bit and started up with it.

**Expected behavior**
Under 32bit I was able to run Bitcoin Core, LND, LNDHub, Dojo, Whirlpool, Electrs and Block Explorer

**MyNode hardware (please complete the following information):**
 - Device:  Raspi4 4GB
 - Version: 0.2.57
 - Hard Drive: 1TB SSD, 300GB free
 - SD Card: 32 GB, 22GB free

**Additional context**

After upgrade to 64bit, I am trying to diagnose errors running applications.  Seeing the following via journalctl -f

**Electrs**
* `Failed to start Proxy for Secure Electrs`.  _Occurs whether Electrum Server installed or not._
* mynode_gen_cert_electrs.sh complains about not being able to create regular file for the .crt, .key, and .pem due to permission denied 

The /home/bitcoin/.mynode/electrs is owned by root, old files by bitcoin, and the script is running as bitcoin, so its obviously not going to be able to write to the folder. Seemed to resolve by setting ownership of the respective folder/files to bitcoin
Prior to this I could not connect as the service wasn't up and listening.  Now however, I get an error when connecting with Sparrow as it says 'Certificate expired at Sun Aug 14 14:02:44 UTC 2022'.  Is there a way to force Electrs to recreate the certificate from within mynode or should I go ahead and do this manually?

**TLS Proxy**
* tls_proxy.service has many restarts.
* reports error: tls_proxy.service: Main process exited, code=exited, status=1/FAILURE.  Failed with result 'exit-code'.

I'm not sure if the above is affecting anything else yet, other then its Electrs on each restart

**Web SSH**
* webssh2.service was also restarting alot.  When this fails, it just has code=exited. Failed with result 'exit-code'.  
* on Manage Apps screen, web ssh has red dot
* occasional docker errors:  Unable to find webssh2:latest locally, and Not continuing with pull after error, requested access to the resource is denied. unauthorized: authentication required.

Linux Terminal for the Web SSH is not working as a result, but can SSH just fine normally.

**LND**
* Looking at glances, LND CPU usage is often high, over 100% and this node has no significant peers, channels, etc.
* logs show [ERR] RPCS: [/wtcclientrpc.WatchtowerClient/ListTowers]: watchtower client not active

**Other**
* /etc/systemd/system.conf:2: Invalid maximum tasks value 'unlimited', ignoring: Unknown error -22
* I get warning on status page : `Low Memory Your device was running low on memory and a process has been restarted. You may want to disable some applications. [76802.435495] Out of memory: Killed process 8896 (python3) total-vm:2790856kB, anon-rss:2053544kB, file-rss:8kB, shmem-rss:0kB, UID:1000 pgtables:5496kB oom_score_adj:0`
* DOCKER LOG: Aug 18 16:42:29 myNode dockerd[3491]: time="2022-08-18T16:42:29.681510011-05:00" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
* DOCKER LOG: Aug 18 16:42:29 myNode dockerd[3491]: time="2022-08-18T16:42:29.679988041-05:00" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"

Currently have only Bitcoin, LND running and trying to get Electrs established

**Comment by tehelsper** [comment]
Hey, just saw you had closed this. Did the issues go away?

A couple suggestions:
- First, just try a reboot which may help reset some of the apps and fix permission issues
- It could also be a bad flash of the image onto the SD card, re-flashing may help as well
- For the docker issues, there may have been an issue and some data can get lost. But, for example, Dojo should be able to re-sync after a 32->64 bit upgrade.
- For the electrum issues, the new image may change the device's IP address which can affect the certs due to the local IP change. Try resetting the electrum certs on the settings page.

**Comment by vicariousdrama** [comment]
I was able to resolve the issues by
1. Uninstall apps not being used, including those I intend to use
2. Install Electrs
3. Manually deleted the certificates for electrs on the microsd and external drive (I didn't know about the Settings page in the UI, but see that now)
4. After individual reboots for Electrs and WebSSH2, those working fine, then did one at a time for Dojo and Whirlpool

The certificates for Electrs were apparently expired a few days prior and I just didn't notice under 32bit as I hadn't done a tx recently.  Was clued in when I could connect with Sparrow doing non-ssl vs ssl and it bringing up the warning.
