### ISSUE TITLE
Issue: upgrade to 0.3.0

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#692]
**Describe the bug**
Upgraded to version 0.3.0 from earlier latest version.
After upgrade, node is stuck at looking for drive. See attached error log for node startup.
**Expected behavior**
running mynode
**Screenshots**

**Desktop (please complete the following information):**
 - Browser [Safari]

**MyNode hardware (please complete the following information):**
 - Device: [ Raspi4]
 - Version [0.3.0]

**Additional context**
Log : 

Logs begin at Tue 2022-08-23 08:53:57 CDT, end at Tue 2022-08-23 09:00:47 CDT. --
Aug 23 09:00:46 myNode systemd[1]: Failed to start myNode Startup.
Aug 23 09:00:46 myNode systemd[1]: mynode.service: Failed with result 'exit-code'.
Aug 23 09:00:46 myNode systemd[1]: mynode.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 09:00:46 myNode mynode[13761]: ModuleNotFoundError: No module named 'urllib3'
Aug 23 09:00:46 myNode mynode[13761]:     import urllib3
Aug 23 09:00:46 myNode mynode[13761]:   File "/usr/local/lib/python3.8/site-packages/requests/__init__.py", line 43, in 
Aug 23 09:00:46 myNode mynode[13761]:     import requests
Aug 23 09:00:46 myNode mynode[13761]:   File "/var/pynode/utilities.py", line 9, in 
Aug 23 09:00:46 myNode mynode[13761]:     from utilities import *
Aug 23 09:00:46 myNode mynode[13761]:   File "/usr/bin/mynode_usb_driver_check.py", line 8, in 
Aug 23 09:00:46 myNode mynode[13761]: Traceback (most recent call last):
Aug 23 09:00:45 myNode mynode[13761]: + /usr/local/bin/python3 /usr/bin/mynode_usb_driver_check.py
Aug 23 09:00:45 myNode mynode[13761]: + '[' '!' -s /home/bitcoin/.mynode/mynode_serial ']'
Aug 23 09:00:45 myNode mynode[13761]: + '[' '!' -f /home/bitcoin/.mynode/mynode_serial ']'
Aug 23 09:00:45 myNode mynode[13761]: + true
Aug 23 09:00:45 myNode mynode[13761]: umount: /mnt/hdd: not mounted.
Aug 23 09:00:45 myNode mynode[13761]: + umount /mnt/hdd
Aug 23 09:00:45 myNode mynode[13761]: + dphys-swapfile uninstall
Aug 23 09:00:45 myNode mynode[13761]: + dphys-swapfile swapoff
Aug 23 09:00:45 myNode mynode[13761]: + '[' 0 = 1 ']'
Aug 23 09:00:45 myNode mynode[13761]: + '[' -f /opt/mynode/custom/logo_dark_custom.png ']'
Aug 23 09:00:45 myNode mynode[13761]: + '[' -f /opt/mynode/custom/logo_custom.png ']'
Aug 23 09:00:45 myNode mynode[13761]: + echo /var/pynode
Aug 23 09:00:45 myNode mynode[13761]: + '[' -d /usr/local/lib/python3.8/site-packages ']'
Aug 23 09:00:45 myNode mynode[13761]: + echo /var/pynode
Aug 23 09:00:45 myNode mynode[13761]: + '[' -d /usr/local/lib/python3.7/site-packages ']'
Aug 23 09:00:45 myNode mynode[13761]: + echo /var/pynode
Aug 23 09:00:45 myNode mynode[13761]: + '[' -d /usr/local/lib/python2.7/dist-packages ']'
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /mnt/usb_extras
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /mnt/hdd
Aug 23 09:00:45 myNode mynode[13761]: + rm -rf /etc/motd
Aug 23 09:00:45 myNode mynode[13761]: + chown admin:admin /home/admin/.bitcoin/
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /etc/torrc.d
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /home/admin/.bitcoin/
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /home/bitcoin/.mynode/
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /var/run/tor
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /run/tor
Aug 23 09:00:45 myNode mynode[13761]: + '[' '!' -f /var/lib/mynode/.expanded_rootfs ']'
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /var/lib/mynode
Aug 23 09:00:45 myNode mynode[13761]: + chown -R admin:admin /home/admin/.config/
Aug 23 09:00:45 myNode mynode[13761]: + mkdir -p /home/admin/.config/
Aug 23 09:00:45 myNode mynode[13761]: + echo on
Aug 23 09:00:45 myNode mynode[13761]: + for dev in /sys/bus/usb/devices/*/power/control
Aug 23 09:00:45 myNode mynode[13761]: + echo on
Aug 23 09:00:45 myNode mynode[13761]: + for dev in /sys/bus/usb/devices/*/power/control
Aug 23 09:00:45 myNode mynode[13761]: + echo on
Aug 23 09:00:45 myNode mynode[13761]: + for dev in /sys/bus/usb/devices/*/power/control
Aug 23 09:00:45 myNode mynode[13761]: + echo on
Aug 23 09:00:45 myNode mynode[13761]: + for dev in /sys/bus/usb/devices/*/power/control
Aug 23 09:00:45 myNode mynode[13761]: + '[' -d /sys/bus/usb/devices/ ']'
Aug 23 09:00:45 myNode mynode[13761]: + '[' 0 = 1 ']'
Aug 23 09:00:45 myNode mynode[13761]: # Added at myNode startup
Aug 23 09:00:45 myNode mynode[13761]: + grep 'Added at myNode startup' /etc/resolv.conf
Aug 23 09:00:45 myNode mynode[13761]: + needDns=0

**Comment by tehelsper** [comment]
Interesting. That package hasn't changed in a long time. Can you try running these commands?

`pip3 list | grep urllib`

This may resolve the issue.

`sudo apt-get -y install python3-requests`

Or this

`sudo pip3 install urllib3`

**Comment by imacfan** [comment]
Did work even after installing. 

Had re flash older version. Then upgraded again to 0.3.0. 
Working now.
