### ISSUE TITLE
Shutdown Raspberry Pi from GUI

### ISSUE THREAD

**Issue by rhst1** [mynodebtc/mynode#7]
There are various reasons why someone may want or need to shut down a Raspberry Pi running myNode. This can be done using SSH, but it would be great to have a shut down "button" available from the mynode.local website - thank you

**Comment by tehelsper** [comment]
@rhst1 This has been added and is available on the Settings page in the latest version.

http://mynodebtc.com/guide/upgrading_your_device

**Comment by rhst1** [comment]
Download page only has version 1.43

Where is 1.46?

**Comment by tehelsper** [comment]
You can upgrade manually by using the GitHub project. See:
https://github.com/mynodebtc/mynode#developing-for-mynode

Otherwise, you can purchase the premium edition and upgrade by clicking the upgrade button on the Setting page.
https://mynodebtc.com/order/premium
