### ISSUE TITLE
REF: lnd major bug reported #7002 (affecting all nodes) - Unable to deserialize block: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]`

### ISSUE THREAD

**Issue by LightningLuke** [mynodebtc/mynode#702]
**Describe the bug**
`2022-10-09 16:04:09.544 [ERR] LNWL: Unable to deserialize block: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]`

Here's the link to the bug reported over on lnd. ALL 100% of nodes are affected and we'll need an update from myNode once btcd, and lnd have patches out.
#7002 over on lnd

**Expected behavior**
Will need myNode to make an update available asap

**Comment by otech47** [comment]
patches for

BTCD: https://github.com/btcsuite/btcd/pull/1896
LND: https://github.com/lightningnetwork/lnd/pull/7004

currently in review

**Comment by 0xEDD135** [comment]
My node is affected. Do I need to stop my node and wait for the fix? What is the best way to handle this?

**Comment by LightningLuke** [comment]
totally fine to leave your node running..... lightning just won't be able to sync to chain until you apply the necessary update they release. I see there is a PR fix available and Roasbeef said "we'll be cherry picking this PR onto a new 0.15.2 release (branched off from 0.15.1) which'll backport the fix." 

Just not sure if that means we can upgrade to 0.15.1 if on a previous version and that will apply the fix or not...?

**Comment by otech47** [comment]
probably best to leave node online and wait for a fix, then update ASAP

your node will be out of sync with the chaintip until then but risk seems low at the moment... worst case you will have to reopen channels

**Comment by LightningLuke** [comment]
closing this now....just upgrade to latest myNode release and you're good to go.
