### ISSUE TITLE
LNbits not starting since v0.3.02

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#703]
**Describe the bug**

With the upgrade to v0.3.02 and the Dockerisation of LNbits the result has been:
```
Oct 10 19:08:01 myNode systemd[1]: Started LNBits.
Oct 10 19:08:01 myNode lnbits[3284]: Unable to find image 'lnbits-legend:latest' locally
Oct 10 19:08:05 myNode lnbits[3284]: docker: Error response from daemon: pull access denied for lnbits-legend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
Oct 10 19:08:05 myNode lnbits[3284]: See 'docker run --help'.
Oct 10 19:08:05 myNode systemd[1]: lnbits.service: Main process exited, code=exited, status=125/n/a
Oct 10 19:08:05 myNode systemd[1]: lnbits.service: Failed with result 'exit-code'.
```
**Expected behavior**

LNbits to run and appear on ports 5000 and 5001

**Desktop (please complete the following information):**
 - Browser Google Chrome 
 - Version 105.0.5195.127 (Official Build) (64-bit)

**MyNode hardware (please complete the following information):**
 - Device: Raspi4
 - Version B

**Additional context**
There has been a minor customisation (of `https_lnbits`) to provide a valid non-self-signed certificate (via Let's Encrypt) but otherwise it is a vanilla installation.

**Comment by HamishMacEwan** [comment]
Thanks, this is likely the cause.

I just wonder if it might be better to put this section right at the top of the page so that people like me, who forget what they have done, can find these little quirks just a tiny bit quicker 😖

![image](https://user-images.githubusercontent.com/388061/194820185-7830665b-a1ef-45bc-b69d-2572710e2304.png)

**Comment by john-zaprite** [comment]
What's happening here? 
My LNbits won't load after the recent update either.
What is the screenshot above referring to? Any other context?

**Comment by HamishMacEwan** [comment]
Attempts to upgrade an app while the version is locked in the "Legacy Custom Applications Versions" list fail.  As they should, that's what the list is intended to do.

You may have another problem with LNbits in the latest versions (0.3.02, and 0.3.03) there's a description here; https://github.com/lnbits/lnbits/issues/1050

**Comment by john-zaprite** [comment]
That's great info thanks. It helps get me closer.
My "Legacy Custom Applications Versions" section is empty, so I don't think that's the issue. But my LNbits log file is showing this repeatedly:
`Oct 12 09:41:52 myNode lnbits[15735]: 2022-10-12 14:41:52.75 | INFO | Retrying connection to backend in 5 seconds...`
So I think your link above might help with that.
