### ISSUE TITLE
Stay on the Manage Applications page after action selected if possible

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#707]
**Is your content request related to a problem? Please describe.**
Not a problem, but a quality of life improvement when using the [Manage Applications](http://mynode.local/apps) page.

**Describe the solution you'd like**
Presently, after selecting to **enable** or **disable** an app (and perhaps other actions), the page reloads the home page.  

This is not necessary, nor particularly expected.  During debugging and diagnosis of problems, it is often useful to enable and disable an app (LNbits for example) a number of times, and having to back the browser to the **Manage Applications** page is annoying.

There's home page removes the option for further management and the status on the **Manage Applications** page is enough to determine success or failure.  

The user can easily choose to return to the home page with the icon available at the top left of the page.

**Additional context**

- [ ✔] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Just committed a change that should resolve this for enable/disable.

https://github.com/mynodebtc/mynode/commit/1602c8ccd2024c5b7509fb4b49c04c0ca9ce4444

**Comment by HamishMacEwan** [comment]
Thanks very much Taylor.  Small thing, but it is much appreciated.
