### ISSUE TITLE
mynode v0.3.03: bos needs to be upgraded to 13.1.4 to work with telegram

### ISSUE THREAD

**Issue by sparcsun** [mynodebtc/mynode#709]
**Describe the bug**
bos telegram bot does not sync (other functionalities work) returns error message -> "Invalid or unexpected token"

**MyNode hardware:**
 - Device: Raspi4
 - Version 0.3.03

**Solution**
Upgrade bos via npm fixed the problem

**Comment by tehelsper** [comment]
OK, I'll be sure to upgrade bos for the next release.

**Comment by sparcsun** [comment]
thank you ... new release contains the latest bos
