### ISSUE TITLE
SSD Connected But Still Receiving "Looking for Drive" Message

### ISSUE THREAD

**Issue by esprograms** [mynodebtc/mynode#72]
As the subject says, I've connected an SSD (1TB Crucial), but myNode is still looking for it. At one point, it started the QuickSync, but then it suddenly stopped after about 2% download and gave me the "Looking for Drive" message again. I've tried using different power supplies and running it with and without a fan (in each instance I've left it outside of the case). I have a Raspberry Pi 4 with 4 GB of RAM. The SSD was new (I point that out in case I was supposed to do something to it before first use).

Also, not sure if this helps, but when I check in SSH if the drive exists, I can't see it:

![image](https://user-images.githubusercontent.com/5482511/69206041-7b043400-0b00-11ea-8743-36dba2532dde.png)

Thanks

**Comment by tehelsper** [comment]
Which USB3 -> SATA adapter are you using?

**Comment by esprograms** [comment]
UGREEN USB C Hard Drive Enclosure USB 3.1 Gen 1 Type C to SATA External Hard Drive Disk Case Adapter Housing for 9.5mm 7mm 2.5 Inch SATA I II III, PS4, HDD, SSD, 6Gbps Fast Speed UASP Tool Free

**Comment by esprograms** [comment]
Since this is my first time using a Raspberry Pi, to see if there was something wrong with a piece of the hardware, I decided to go through the "getting started" series and loaded Raspbian (by way of NOOBS). Getting the Raspbian desktop running worked fine (yay!), but the SDD was a bit fidgety (boo!): it would be recognized and then it was as if I had unsafely removed it. I had to place the cord from the UGREEN perfectly or it wouldn't work. Once I identified that it "could" work, I went back to the myNode. This time it recognized my drive. I restarted the QuickSync, and it worked for about thirty minutes, then no longer. Frustrated, I purchased a new UGREEN USB C adapter. This didn't help. So I purchased a new Raspberry Pi. This didn't help either. I'm considering purchasing a Samsung SSD that doesn't require an adapter instead of my Crucial MX500 1TB 3D NAND SATA 2.5 Inch Internal SSD (does that sound like a good next step?). If that doesn't work, I'm wondering if it's related to my house's electricity. Ugh.

**Comment by tehelsper** [comment]
Sorry you are having trouble. You may want to also ask what other adapters people have had success with so you can go back to USB 3 if you want.

I think several have had success with this case:

https://www.amazon.com/dp/B01N48791I/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B01N48791I&pd_rd_w=VoZB2&pf_rd_p=45a72588-80f7-4414-9851-786f6c16d42b&pd_rd_wg=wHJ3b&pf_rd_r=AC3ZPD55E83MHVKY5GBB&pd_rd_r=678e89b5-0715-45c6-8521-c8a3daae8afa&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyTVVZOTBOWFJDWkJZJmVuY3J5cHRlZElkPUExMDE1MTA5MVhHM1dXRzBJSExKNSZlbmNyeXB0ZWRBZElkPUEwMDQyMzgwMUI1QkFBVVQ0TUhIRCZ3aWRnZXROYW1lPXNwX2RldGFpbCZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

**Comment by esprograms** [comment]
The new adapter fixed the problem. Thank you!
