### ISSUE TITLE
Bug: electrs failed Caused by: receiving on an empty and disconnected channel

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#725]
Details here:

https://github.com/romanz/electrs/issues/803

**Comment by HamishMacEwan** [comment]
This seems to relate to `maxconnections` being set too low and `electrs` missing out on one, it's [recommended](https://github.com/romanz/electrs/blob/master/doc/config.md#bitcoind-configuration) that `maxconnections` be set to at least 12, and now with `maxconnections=15` `electrs` seems to work again.

**Comment by tehelsper** [comment]
Interesting. Do you have a custom Bitcoin config? maxconnections should be set to 40 by default.

**Comment by HamishMacEwan** [comment]
Yes, for a very long time and for purposes that might now be more standard.  Giving thought to the idea of resetting both `lnd` and `bitcoind` configurations.

Still having problems with `electrs` being a little unstable, but it's going now, so I'll leave it be.
