### ISSUE TITLE
Electrs failed: Sync failed, failed to get block, receiving on an empty and disconnected channel

### ISSUE THREAD

**Issue by jtnode93** [mynodebtc/mynode#728]
Dec 01 15:03:56 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Dec 01 15:03:56 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 15:03:56 myNode electrs[12078]:     2: receiving on an empty and disconnected channel
Dec 01 15:03:56 myNode electrs[12078]:     1: failed to get block 0000000000000000000a1e0af24066eb9c665bedd65ab66ff73e66a2bea17394
Dec 01 15:03:56 myNode electrs[12078]:     0: sync failed
Dec 01 15:03:56 myNode electrs[12078]: Caused by:
Dec 01 15:03:56 myNode electrs[12078]: Error: electrs failed
Dec 01 15:03:56 myNode electrs[12078]: [2022-12-01T21:03:56.192Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Dec 01 15:03:56 myNode electrs[12078]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 01 15:03:56 myNode electrs[12078]: thread 'p2p_loop' panicked at 'invalid message: ParseFailed("witness flag set but no witnesses present")', src/p2p.rs:250:70
Dec 01 15:03:51 myNode electrs[12078]: [2022-12-01T21:03:51.157Z INFO  electrs::index] indexing 2000 blocks: [601171..603170]
Dec 01 15:03:49 myNode electrs[12078]: [2022-12-01T21:03:49.281Z INFO  electrs::chain] chain updated: tip=00000000000000000013e8c229fa1e971ce0f0aeff92195a7f2494da2a615f83, height=601170
Dec 01 15:03:45 myNode electrs[12078]: [2022-12-01T21:03:45.429Z INFO  electrs::chain] loading 601170 headers, tip=00000000000000000013e8c229fa1e971ce0f0aeff92195a7f2494da2a615f83
Dec 01 15:03:40 myNode electrs[12078]: [2022-12-01T21:03:40.871Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1036 SST files, 32.449579507 GB, 2.668571773 Grows
Dec 01 15:03:29 myNode electrs[12078]: [2022-12-01T21:03:29.824Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Dec 01 15:03:29 myNode electrs[12078]: [2022-12-01T21:03:29.824Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Dec 01 15:03:29 myNode electrs[12078]: Starting electrs 0.9.9 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.9 (Electrum Rust Server)!", args: [] }
Dec 01 15:03:29 myNode electrs[12076]: + exit 0
Dec 01 15:03:29 myNode systemd[1]: Started myNode Electrum Server.
Dec 01 15:03:29 myNode electrs[12076]: }
Dec 01 15:03:29 myNode electrs[12076]:   "warnings": ""
Dec 01 15:03:29 myNode electrs[12076]:   "pruned": false,
Dec 01 15:03:29 myNode electrs[12076]:   "size_on_disk": 501193013774,
Dec 01 15:03:29 myNode electrs[12076]:   "chainwork": "00000000000000000000000000000000000000003a9de6d72d84f2e9faaedd43",
Dec 01 15:03:29 myNode electrs[12076]:   "initialblockdownload": false,
Dec 01 15:03:29 myNode electrs[12076]:   "verificationprogress": 0.99999786333692,
Dec 01 15:03:29 myNode electrs[12076]:   "mediantime": 1669925414,
Dec 01 15:03:29 myNode electrs[12076]:   "time": 1669928029,
Dec 01 15:03:29 myNode electrs[12076]:   "difficulty": 36950494067222.41,
Dec 01 15:03:29 myNode electrs[12076]:   "bestblockhash": "000000000000000000079b53cc2de7d352d7d9d0400c17fe6a94eb9d906562af",
Dec 01 15:03:29 myNode electrs[12076]:   "headers": 765514,
Dec 01 15:03:29 myNode electrs[12076]:   "blocks": 765514,
Dec 01 15:03:29 myNode electrs[12076]:   "chain": "main",
Dec 01 15:03:29 myNode electrs[12076]: {
Dec 01 15:03:29 myNode electrs[12076]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Dec 01 15:03:29 myNode electrs[12076]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Dec 01 15:03:29 myNode electrs[12076]: Checking if Bitcoin is synced...
Dec 01 15:03:29 myNode electrs[12076]: + echo 'Checking if Bitcoin is synced...'
Dec 01 15:03:29 myNode electrs[12076]: + set -e
Dec 01 15:03:29 myNode electrs[12075]: Not shutting down!
Dec 01 15:03:29 myNode electrs[12075]: Checking if device is shutting down...
Dec 01 15:03:29 myNode systemd[1]: Starting myNode Electrum Server...

**MyNode hardware (please complete the following information):**
 - Device: raspi4 64-bit
 - Version: 0.3.05
 - Electrs version: v0.9.9

**Additional context**
I've tried restarting the whole sync, same problem. Gets stuck at 78.53%.
I tried this https://github.com/mynodebtc/mynode/issues/718#issuecomment-1314771490
No luck.

**Comment by jtnode93** [comment]
Going to try resetting the blockchain data

**Comment by tehelsper** [comment]
Yeah, try resetting both the blockchain and the existing electrs data. I've not see that before except in rare cases where that was corruption inside the btc blockchain that had not been seen via Bitcoin errors.

**Comment by raytorres280** [comment]
both resetting and https://github.com/mynodebtc/mynode/issues/718#issuecomment-1314771490 did not work for me sadly. and trying the comment has me with error `/usr/bin/electrs: cannot execute binary file: Exec format error`

**Comment by raytorres280** [comment]
same error after trying https://github.com/mynodebtc/mynode/issues/718#issuecomment-1314771490 with correct 32 bit version: `electrs.service: Failed to execute command: Exec format error`

**Comment by raytorres280** [comment]
https://github.com/mynodebtc/mynode/issues/718#issuecomment-1314771490 fixed it for me

**Comment by jtnode93** [comment]
36% done so far... I'll check back in about 60 days

**Comment by tehelsper** [comment]
It shouldn't be that slow. You may want to check out the tips in our guide:

https://mynodebtc.github.io/troubleshooting/bitcoin-sync-slow.html

**Comment by jtnode93** [comment]
😮‍💨 after reading that, I realized the SSD was plugged into USB2. It's in USB3 now and should be done in about a week. Thanks for that post!

**Comment by jtnode93** [comment]
Okay. The sync is done. Electrum fully synced and is running properly. Looks it was corrupt blockchain data. Thanks for the help!
