### ISSUE TITLE
LNbits Customisation and Upgrade not working

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#729]
**Describe the bug**
Setting a customised version of LNbits and upgrading/reinstalling isn't working.  After performing the steps below, sometimes LNbits is not installed and won't start.

**Expected behavior**
1. Set a different commit/tag for LNbits on http://mynode.local/apps/customize-app-versions
2. Upgrade/reinstall from http://mynode.local/apps
3. Customised version available

**MyNode hardware:**
 - Raspi4 64-bit
 - Version	0.3.05	

**Additional context**
The only place I could find that installs/upgrades LNbits is `mynode_docker_images.sh` but that script doesn't appear to be r[eferenced anywhere](https://github.com/mynodebtc/mynode/search?q=mynode_docker_images.sh).  These are the containers:

```
docker container ls
CONTAINER ID   IMAGE                               COMMAND                  CREATED        STATUS       PORTS                    NAMES
2616d3341999   lnbits-legend                       "sh -c 'poetry run l…"   5 hours ago    Up 5 hours   0.0.0.0:5000->5000/tcp   lnbits-legend
70806df4a064   webssh2                             "/bin/sh -c 'npm run…"   6 hours ago    Up 6 hours   0.0.0.0:2222->2222/tcp   webssh2
56ddfb60de24   samouraiwallet/dojo-nginx:1.7.0     "/docker-entrypoint.…"   4 months ago   Up 6 hours   80/tcp, 9080/tcp         nginx
f2a7df6cfccd   samouraiwallet/dojo-nodejs:1.15.0   "docker-entrypoint.s…"   4 months ago   Up 6 hours   8080-8082/tcp            nodejs
2a4b56f8e53f   samouraiwallet/dojo-db:1.5.0        "docker-entrypoint.s…"   4 months ago   Up 6 hours   3306/tcp                 db
3a2d4d291816   samouraiwallet/dojo-tor:1.12.0      "/restart.sh"            4 months ago   Up 6 hours                            tor
```
Not at all sure what the samouraiwallet/dojo images are doing there, the app has never been installed.

These are the images:

```
docker image ls
REPOSITORY                              TAG             IMAGE ID       CREATED         SIZE
lnbits-legend                           latest          c82b954392e0   5 hours ago     1.02GB
<none>                                  <none>          79667cc52236   6 hours ago     1.1GB
btcpayserver/docker-compose-generator   latest          98f7cd187583   5 weeks ago     189MB
python                                  3.9-slim        9c38ec1b7eb3   8 weeks ago     116MB
samouraiwallet/dojo-tor                 1.12.0          654b96e5a04e   4 months ago    111MB
samouraiwallet/dojo-nodejs              1.15.0          e015f4e63615   4 months ago    249MB
<none>                                  <none>          72665e977345   4 months ago    863MB
<none>                                  <none>          2d5193058892   4 months ago    460MB
samouraiwallet/dojo-db                  1.5.0           fbe9a55fec34   4 months ago    306MB
samouraiwallet/dojo-nginx               1.7.0           f20af376d5d2   4 months ago    21.6MB
webssh2                                 latest          afa3842b53a1   4 months ago    639MB
node                                    14-alpine       a86dbced6fe4   4 months ago    118MB
debian                                  buster-slim     b5c67df084c3   4 months ago    63.5MB
mempool/frontend                        v2.4.0          67451ab87001   5 months ago    299MB
mempool/backend                         v2.4.0          8e9c670b1d78   5 months ago    326MB
mariadb                                 latest          ecc004eed0c2   6 months ago    306MB
netdata/netdata                         v1.32.1         7b5dfab20af6   11 months ago   361MB
nginx                                   1.21.3-alpine   2e723ef9408f   14 months ago   21.6MB
golang                                  1.16.6-buster   fab6a1960e25   16 months ago   728MB
node                                    8.6             e4cc1ad991ff   5 years ago     620MB
```
And puzzled here by the presence of Samourai realted images.

If there's other information that would help explain the behaviour, please advise.

**Comment by tehelsper** [comment]
What version did you customize? The docker install steps (which lnbits is now a part of) is in the script you found. It runs once at boot and then again every 24 hours, but the subsequent runs shouldn't actually do anything except verify the docker apps were properly installed.

https://github.com/mynodebtc/mynode/blob/cd65818a7204aa3098c6d299e9202f34829ff543/rootfs/standard/etc/systemd/system/docker_images.service

For Dojo, I think it is a default app, which you may have uninstalled. It may not be removing all the old Dojo images on uninstall, but that shouldn't really affect anything except disk space as long as they are not running.

**Comment by HamishMacEwan** [comment]
The LNbits installed version was [0.9.4](https://github.com/lnbits/lnbits/releases/tag/0.9.4) and the desired commit was `223c980710e31ae19170b91174254a426bc7bda2`

Still puzzled that the github search doesn't find `mynode_docker_images.sh`  in that service unit.  That `systemd` is the method of invocation probably explains why no sign of the reinstall appears in [`reinstall_lnbits.txt`](https://github.com/mynodebtc/mynode/files/10147306/submitredactedlog.txt).    Not sure what's running it every 24 hours, but what does it do if the verification of the docker apps install fails?

Having found `sudo journalctl -u docker_images` has some interesting details in it, I'll see if it gives any hints.  Would you like to see it?

LIke I say, never liked, and never installed Samourai, nor uninstalled it.  As to "as long as they are not running," doesn't the `Up 6 hours` status indicate those containers are active?

**Comment by HamishMacEwan** [comment]
Ah…

`+ sleep 1d`

"every 24 hours" 😁

Attached the output:

[`sudo journalctl -u docker_images`](https://github.com/mynodebtc/mynode/files/10147336/docker_images.journal.txt)

**Comment by tehelsper** [comment]
Yeah, that search is unusual. If you search on the name without the ".sh" I think it finds it. It tried again just in case it was a networking issue or something that caused it the first time.

That log appears successful. Is lnbits not running properly?

Sorry, I missed the docker ps output. Dojo is installed by default, which explains the containers existing, but if you never enabled it or especially if you've uninstalled it, I'm not sure why it's running. I have seen this once before. A temporary workaround is to enable Dojo and then re-disable it IIRC, but it may come back. My theory is that the docker-compose stuff it making it run automatically even if the dojo service is disabled.

Can you run "sudo systemctl status dojo"?

**Comment by HamishMacEwan** [comment]
```
$ sudo systemctl status dojo
[sudo] password for admin:
● dojo.service - Dojo
   Loaded: loaded (/etc/systemd/system/dojo.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2022-12-03 07:34:44 NZDT; 2 days ago
    Tasks: 0 (limit: 4225)
   CGroup: /system.slice/dojo.service

Dec 03 07:34:37 flat6 wait_on_docker_image_install.sh[13893]: + '[' -f /tmp/installing_docker_images ']'
Dec 03 07:34:37 flat6 wait_on_docker_image_install.sh[13893]: + exit 0
Dec 03 07:34:38 flat6 dojo.sh[14514]: Starting Dojo. Please wait.
Dec 03 07:34:41 flat6 dojo.sh[14514]: tor is up-to-date
Dec 03 07:34:41 flat6 dojo.sh[14514]: Starting db ...
Dec 03 07:34:43 flat6 dojo.sh[14514]: Starting db ... done
Dec 03 07:34:43 flat6 dojo.sh[14514]: nodejs is up-to-date
Dec 03 07:34:43 flat6 dojo.sh[14514]: Starting nginx ...
Dec 03 07:34:44 flat6 dojo.sh[14514]: Starting nginx ... done
Dec 03 07:34:44 flat6 systemd[1]: Started Dojo.
```

**Comment by tehelsper** [comment]
OK, the service is enabled. Do you see the Dojo icon on the home page or on the Manage Apps page? It looks like it may have been re-installed but either wasn't disabled or was re-enabled inadvertently at some point.

Either way, you should be able to run "sudo systemctl stop dojo" and "sudo systemctl disable dojo" to resolve.

**Comment by HamishMacEwan** [comment]
Well, recognising myNode is stubborn, I followed the instructions and:

`Removed /etc/systemd/system/multi-user.target.wants/dojo.service.`

And 

```
$ docker container ls
CONTAINER ID   IMAGE           COMMAND                  CREATED      STATUS      PORTS                    NAMES
2616d3341999   lnbits-legend   "sh -c 'poetry run l…"   3 days ago   Up 3 days   0.0.0.0:5000->5000/tcp   lnbits-legend
70806df4a064   webssh2         "/bin/sh -c 'npm run…"   3 days ago   Up 3 days   0.0.0.0:2222->2222/tcp   webssh2
```
🤞

Despite this, home page has:
![image](https://user-images.githubusercontent.com/388061/205807647-9a29db05-2e57-4694-b41e-13191b82cf3b.png)
which is fine because it ain't going to get Electrum.

The LNbits situation may be about presence/version consistency.  When I couldn't verify the install in the logs, and had situations where it was unclear if I should reinstall or upgrade.  There were certainly times when there was no Docker container at all.

I'll try another LNbitscommit upgrade soon and see if anything sticks out.

**Comment by tehelsper** [comment]
OK, to get Dojo off the home page, you need to uninstall it. There should be a button on the manage apps page to remove it.

Yeah, for lnbits, the container wont exist while it's building so it may not show up for a bit after rebooting when it's in the "Docker Installing Images" phase. This is done because initial device setup can write to the SD card, but not the external drive since it doesn't exist. Since docker containers are large, they get stored on the data drive so they have to be setup at runtime, which is why they run in a script after reboot and after the external drive is attached.

**Comment by HamishMacEwan** [comment]
OK, well I'm ready to try a new customised version of LNbits:

On http://flat6.local/apps/customize-app-versions the following is set for LNBits:

![image](https://user-images.githubusercontent.com/388061/206565624-cdf7d9bb-b14e-4074-b493-7eb69a0a64db.png)

Here's some output of the values in the system:
```
bitcoin@flat6:~/.mynode $ ./LNBitsVersionStatus.bash
Sourcing /usr/share/mynode/mynode_app_versions.sh
get_app_version is version=$(cat /mnt/hdd/mynode/settings/lnbits_version_latest_custom)
LNBITS_VERSION=$(get_app_version "$LNBITS_VERSION" "lnbits")
LNBITS_VERSION="386e1ec4d98001804df6290454ee2c96468c9618"
LNBITS_VERSION_FILE=/home/bitcoin/.mynode/lnbits_version
LNBITS_LATEST_VERSION_FILE=/home/bitcoin/.mynode/lnbits_version_latest

In /home/bitcoin/.mynode
lnbits_version
223c980710e31ae19170b91174254a426bc7bda2
lnbits_version_latest
386e1ec4d98001804df6290454ee2c96468c9618
lnbits_version_latest_custom
386e1ec4d98001804df6290454ee2c96468c9618
```

But when `[/usr/bin/mynode_docker_images.sh](https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/usr/bin/mynode_docker_images.sh)` ran this morning, no upgrade occurred:

```
Dec 09 07:34:25 flat6 mynode_docker_images[3975]: + LNBITS_UPGRADE_URL=https://github.com/lnbits/lnbits/archive/223c980710e31ae19170b91174254a426bc7bda2.tar.gz
Dec 09 07:34:25 flat6 mynode_docker_images[3975]: + CURRENT=
Dec 09 07:34:25 flat6 mynode_docker_images[3975]: + '[' -f /home/bitcoin/.mynode/lnbits_version ']'
Dec 09 07:34:25 flat6 mynode_docker_images[3975]: ++ cat /home/bitcoin/.mynode/lnbits_version
Dec 09 07:34:25 flat6 mynode_docker_images[3975]: + CURRENT=223c980710e31ae19170b91174254a426bc7bda2
Dec 09 07:34:25 flat6 mynode_docker_images[3975]: + '[' 223c980710e31ae19170b91174254a426bc7bda2 '!=' 223c980710e31ae19170b91174254a426bc7bda2 ']'
```
Now from http://flat6.local/apps:
![image](https://user-images.githubusercontent.com/388061/206566062-358bea66-acde-4130-b32f-3b4a66d8402a.png)
Clicking `Upgrade`
```
Dec 09 10:09:29 flat6 mynode_docker_images[3858]: Successfully built a94849c82a45
Dec 09 10:09:29 flat6 mynode_docker_images[3858]: Successfully tagged lnbits-legend:latest
Dec 09 10:09:29 flat6 mynode_docker_images[3858]: + echo 386e1ec4d98001804df6290454ee2c96468c9618
```
So great, the system works, if you're patient.

The system rebooted and came all the way up (I think it waits for bitcoind to sync) and LNbits was on the main page with a red dot, because it was still being built, and indeed it did not appear on the main page in green for some time after the log above.

But when the red dot appears, it appears there has been a failure and so rushed in to see what had gone wrong, which was difficult to tell because the logging isn't obvious and what there is appears to be ephemeral as myNode erases a lot of logging on reboot or upgrade.

All that aside, the reason for, and what has made this effort worthwhile, is the extension after `Boltz` and before `Discord server`
![image](https://user-images.githubusercontent.com/388061/206573086-4ae7c2d8-c8b3-424e-8218-202e446fa1c5.png)

**Comment by tehelsper** [comment]
Thanks for the info. The upgrade/reboot after customizing is required because that's when the new versions really get loaded for potential upgrades. Just waiting won't trigger a new docker container update.

I found an issue with lnbits which explains the red dot. It should have been yellow saying "Waiting on Docker" during it's upgrade process and I can fix that.

**Comment by HamishMacEwan** [comment]
Awesome.  Yes, if there'd been some telemetry on what had happened, or in this case invisibly happening.  Can completion trigger a home screen refresh?

When you said it ran every 24 hours, I took that to mean the whole process, but as you say it's only interested in maintaining the environment it woke up in, rather than any upgrade awkwardness.  So, it waits for a reboot.

Had it come up yellow with the Docker message, I'd have sighed with relief rather than panic posting and headrolling.  Thanks for all you do @tehelsper

**Comment by HamishMacEwan** [comment]
PS.

```
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + echo 'Waiting on bitcoin to sync so drive usage is lower...'
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: Waiting on bitcoin to sync so drive usage is lower...
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + /usr/bin/wait_on_bitcoin.sh
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + set -e
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + echo 'Checking if Bitcoin is synced...'
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: Checking if Bitcoin is synced...
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + echo 'BTC not synced, sleeping 30s'
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: BTC not synced, sleeping 30s
Dec 10 15:56:21 flat6 mynode_docker_images[3980]: + /bin/sleep 30s
```
Could be some time in certain circumstances.

**Comment by tehelsper** [comment]
Yeah, depending on the drive / SSD, it can definitely take a a couple minutes before the initial startup scripts + Bitcoin has fully launched before it lets other apps start running.
