### ISSUE TITLE
upgrade to v0.1.68 not fully completed

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#73]
on rpi4

sudo apt-get update
sudo apt-get upgrade

and then after a long upgrade (30 minutes with 2 reboots) it appears this:

![68](https://user-images.githubusercontent.com/16525337/69316510-45169b00-0c39-11ea-9cc6-d8ce3c8bac95.jpg)

 no Joinmarket directory into /opt/mynode/

**Comment by Amiga500** [comment]
pressed on Retry Upgrade, (one reboot) and now it appears the dir of Joinmarket :)

**Comment by Amiga500** [comment]
I let bug opened in case someone have same issue.. and can workaround it ;)

**Comment by Amiga500** [comment]
on rpi3

on first reboot installed Joinmarket, but it appears again that update that wasn't completed correctly.. so i pressed "Retry Update" and all is gone nice, about one hour to complete all

**Comment by g0mp** [comment]
same issue here on a rpi4. You suggest to manually install joinmarket to get rid of the red error message? I did push the Retry Upgrade button a couple of times (resulting in an equal amount of reboots ofcourse), but that didn't solve things...

**Comment by g0mp** [comment]
Now it's ok on my settings page too.
I too did the sudo apt-get update and upgrade, but that did not directly help.
It seems the update requires more reboots and some items take longer to install or so. 
My mynode suddenly rebooted while being fully online and operational, and after that reboot the red message on the settings page was gone...
hope all is ok now :P

**Comment by Amiga500** [comment]
Good! No i didn't suggested to install joinmarket, i said only that after upgrade there isn't any directory of joinmarket as joinmarket is a feature od this release
