### ISSUE TITLE
Feature: LNTOP

### ISSUE THREAD

**Issue by InsaneSplash** [mynodebtc/mynode#736]
With GO being added to the next release (looking at the commits), would it be possible to include lntop in the next release?

https://github.com/edouardparis/lntop

As the version being installed, go, it meets the requirements to also install lntop.

- [ X] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Good catch. That was easy to add! Just pushed a commit with lntop.

**Comment by InsaneSplash** [comment]
I see its in 3.0.8 :) nice!
