### ISSUE TITLE
Electrum no more connect to mynode

### ISSUE THREAD

**Issue by quarreller** [mynodebtc/mynode#737]
**Describe the bug**
My Electrum desktop wallet is no more connecting to mynode

**Expected behavior**
It works again

**MyNode hardware (please complete the following information):**
 - Device:  Raspi4,
 - Version 3.0.8

**Additional context**
For over a year it works...now after 4 weeks not used it dont.Dot is red=not connected
I try again mynode ip xxx.xxx.x.xxx:50002 or 50001 dont work.
Installed electrum on my smartphone...the same dont work...try with tor connection dont work.
But my zap wallet is still connecting to mynode.
Anybody can help or have the same problem?

Thank you

**Comment by tehelsper** [comment]
This would probably be better as a support ticket. Here are solutions to the most common Electrum Server issues.

https://mynodebtc.github.io/troubleshooting/electrum-connection-error.html

**Comment by quarreller** [comment]
Thank you for the link.
Did all the  solutions but did not help---there is again no connection.
So can you or anybody tell me that you have no problems to  connect electrum wallett to mynode....so the problem is on my side.....if so....what can i do?
I

**Comment by tehelsper** [comment]
If you log a support ticket, we can look more into your details and take a look at your specific logs.

https://mynodebtc.com/premium_support

**Comment by quarreller** [comment]
Dont know if it was the problem at the end,,,,but 
i reset electrum server data.....after new syncing....
i regenerate electrum server certificate......
and did a reboot....
Now my electrum wallet is connecting to mynode again.
