### ISSUE TITLE
FEATURE: add option to enable/disable each feature

### ISSUE THREAD

**Issue by Amiga500** [mynodebtc/mynode#75]
I was thinking about to put into a field on the main page (or settings) an option where are listed ALL features of myNode with a switch that permits to enable/disable each feature

Bitcoin Core         x | y (probably Bitcoin Core can be let so.. without disable it.. as the core function)
Lightning LND     x | y
Electrs                  x | y
...
Glances                x | y
Netdata                x | y

What do you think about? it would be more easily to handle it.. and very useful for rPi3 ...

**Comment by tehelsper** [comment]
Enabled for most features.
