### ISSUE TITLE
High CPU Use - dockerd

### ISSUE THREAD

**Issue by oldgeezy** [mynodebtc/mynode#754]
**Describe the bug**

`docker stats`
Reports only minimal CPU usage:
![image](https://user-images.githubusercontent.com/26230753/222803214-cc2f2d87-0a3b-4741-9d98-1e98a6d79a57.png)

However, Glances indicates dockerd is using substantial CPU resources.

![image](https://user-images.githubusercontent.com/26230753/222802991-dab8d0c3-0ccd-422c-b2fa-e64ecd8ca208.png)

**Expected behavior**
Probably not a bug with mynodebtc.  I'm just wondering if anyone else noticed the same behavior.  Or if there's any additional troubleshooting I could try to figure out which container is tying up the CPU and why.  WebGUI has really bogged down lately.

**Desktop (please complete the following information):**
 - Running in a VM with 2 CPU cores from an Atom C3438, 8gb ram.

**MyNode hardware (please complete the following information):**
 - Device: VM
 - Version 0.3.11

**Comment by tehelsper** [comment]
The most recent docker updates have cause some unusual behaviors, but I have not seen high CPU usage. Has it gone down? Does it get better after a reboot?

**Comment by oldgeezy** [comment]
Yeah seems to have been a temporary issue.  I'd restarted a lot lately while messing around with other configuration changes.  Fully shutting down the VM and then powering it back on has sorted it out.

Thanks!
