### ISSUE TITLE
Reset Tor Connections setting has incorrect dialog

### ISSUE THREAD

**Issue by MWDJ** [mynodebtc/mynode#758]
When selecting the Reset Tor Connections setting in MyNode 0.3.12 (arm64) the dialog shows the following:

"Resetting the Lightning watchtower will erase watchtower settings and restart LND. Would you still like to reset Lightning watchtower?"

It is unclear if the confirmation would reset watchtower or Tor as intended.

**Comment by tehelsper** [comment]
Thanks. That will be fixed next release and it will reset the tor data even though the warning message is wrong.

**Comment by MWDJ** [comment]
Original issue appears fixed in 3.13, dialog now says: 
Resetting Tor Connections will erase "the" reset the current tor data and reboot.
Presume "the" should be "and" or "then".

Thank you.

**Comment by tehelsper** [comment]
Ah, fixed that as well. thanks
