### ISSUE TITLE
JAM: "No connection to backend: Method Not Allowed." after update

### ISSUE THREAD

**Issue by code-or-script** [mynodebtc/mynode#774]
**Describe the bug**
 I get "No connection to backend: Method Not Allowed."

**Expected behavior**
Connection to the backend

**Screenshots**
![image](https://github.com/mynodebtc/mynode/assets/133288861/29bfb42c-512f-4eb1-b1d2-ed345a89b562)

**Desktop (please complete the following information):**
 - Browser Chrome

**MyNode hardware (please complete the following information):**
 - Device: Server PC with disk image
 - Version 0.3.16 from one-click-update

**Additional context**
It was fully working (orderbook, maker, and coinjoin sends) prior to updating from the stock image (0.3.0.5) on the website.  I believe some changes to the joinmarket config in the latest release might be the cause.

I removed mention of some context that was caused by troubleshooting I was doing and is not present on with the typical installation.

**Comment by tehelsper** [comment]
Do any logs help indicate what the issue is? The latest config update only changed to the most recent default from JM.

**Comment by code-or-script** [comment]
Thanks for the reply.  Nothing pops out at me as an error in the logs in mynode:

`-- Logs begin at Sun 2023-05-14 20:16:56 CDT, end at Mon 2023-05-15 14:00:11 CDT. --
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: start worker process 40
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: start worker process 39
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: start worker process 38
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: start worker process 37
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: start worker processes
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: OS: Linux 5.10.0-0.deb10.16-amd64
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219)
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: nginx/1.23.1
May 15 13:57:18 myNode jam[5295]: 2023/05/15 18:57:18 [notice] 1#1: using the "epoll" event method
May 15 13:57:18 myNode jam[5295]: /docker-entrypoint.sh: Configuration complete; ready for start up
May 15 13:57:18 myNode jam[5295]: /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
May 15 13:57:18 myNode jam[5295]: 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
May 15 13:57:18 myNode jam[5295]: /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
May 15 13:57:18 myNode jam[5295]: 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
May 15 13:57:18 myNode jam[5295]: 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
May 15 13:57:18 myNode jam[5295]: /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
May 15 13:57:18 myNode jam[5295]: /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
May 15 13:57:18 myNode jam[5295]: /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
May 15 13:57:18 myNode jam[5295]: Will proxy requests for /obwatch/* to host.docker.internal:62601/
May 15 13:57:18 myNode jam[5295]: Will proxy requests for /jmws to host.docker.internal:27183/
May 15 13:57:18 myNode jam[5295]: Will proxy requests for /api/* to host.docker.internal:28183/api/*
May 15 13:57:14 myNode systemd[1]: Started jam.
May 15 13:57:14 myNode jam[5292]: Not shutting down!
May 15 13:57:14 myNode jam[5292]: Checking if device is shutting down...
May 15 13:57:14 myNode systemd[1]: Starting jam...`

If there is somewhere that I can get the full JAM logs, or front end logs, please let me know where to look.  Just before this: I enabled JAM in mynode, and opened the page to get the error in OP.

**Comment by code-or-script** [comment]
I'm not available to troubleshoot this anymore so I am closing.

**Comment by code-or-script** [comment]
I'm not available to troubleshoot this anymore so I am closing.
