### ISSUE TITLE
MyNode has not just been installed

### ISSUE THREAD

**Issue by westsobe** [mynodebtc/mynode#790]
Hello,
 I am trying to install myNode from the "Install on Existing System (beta)" option but it has not just installed correctly on Debian 11. When the installation process is finished (not complete), I can do a reboot and the User and Password window appears, but the browser does not start with the myNode initial screen. Could someone tell me what's going wrong? 
Attached two screenshots, one in which it shows in the state that the installation remains, and another with the screen access with the username and password.
Thanks!!
<img width="912" alt="Captura de Pantalla 2023-05-22 a las 15 48 35" src="https://github.com/mynodebtc/mynode/assets/133909730/7f07b50c-474e-4109-90b9-b2eb943145d3">
<img width="912" alt="Captura de Pantalla 2023-05-22 a las 15 50 11" src="https://github.com/mynodebtc/mynode/assets/133909730/8af41680-bd6b-4553-9133-ff443b82a1b3">

**Comment by lasermind** [comment]
It's probably the same bug as in issue https://github.com/mynodebtc/mynode/issues/788. The webserver doesn't seem to start and thus does not serve the pages for the MyNode GUI.

Congratulations, you're the third user now who's experiencing this trouble. ;)

**Comment by tehelsper** [comment]
This is different. For some reason, the signature check on bitcoin seems to have failed and stopped the installation. The script didn't complete (it should end with a success message).

**Comment by westsobe** [comment]
Exactly, in my case the installation is not finished. I don't know if it's a general problem or it's a particular problem.

**Comment by tehelsper** [comment]
If you re-run the setup_device.sh script, does it stop in the same spot?

**Comment by westsobe** [comment]
Yes, I have relaunched it several times and always stops in the same spot.

**Comment by tehelsper** [comment]
Ha, OK, I think it's a language thing. The script checks for "good signature" but yours is saying "la suma coincide" which means the same thing, but it's making the script fail. Can you possibly try changing the language to English?

**Comment by westsobe** [comment]
Hello!! Changing the language has worked! But now I have another problem. Now when I put the username and password after the reboot, the browser opens but can not connect to the localhost. 
Through Terminal via SSH I can connect, but via web I can not.

**Comment by lasermind** [comment]
Well, **this** now does sound like issue #788, right? 😉 Should really be addressed next.

**Comment by tehelsper** [comment]
Ha, yes, it does now seem to be the same as the other issue which is related to a new flask version that removed some features. I just pushed a commit that will hopefully resolve it.

**Comment by westsobe** [comment]
Perfect, thank you very much for the help! I will be attentive to the solution of bug #788.

**Comment by tehelsper** [comment]
Closing, this will be resolved once v0.3.18 is released.
