### ISSUE TITLE
Suspicion: Dojo keeps default passwords at fresh installation (image flashing)

### ISSUE THREAD

**Issue by lasermind** [mynodebtc/mynode#794]
**Describe the bug**
Maybe it's not a bug, it's currently the suspicion of a quirky behaviour ― as follows: When flashing a fresh MyNode image, there are certain software packages pre-installed. The user then needs to enable these packages via the "Enable" button in the MyNode GUI. Dojo is one of these packages. When enabling Dojo after a fresh flash of a MyNode image, Dojo starts to sync its indexer and is then ready to run. **But:** it does keep the default passwords/keys in its `docker-node.conf` file. This should **not** be the case.

Only after a wilfully executed reinstall via the Application Manager, Dojo is triggered to create strong passwords and writes them to its `docker-node.conf` file.

**Expected behavior**
When enabling Dojo for the first time, strong passwords are created automatically and written to the corresponding `docker-node.conf` file.

**Screenshots**
![mynode-Dojo-DefaultPws](https://github.com/mynodebtc/mynode/assets/126513496/f46ba1f6-3f7b-4f28-8689-7834f6382004)

**MyNode hardware**
 - Device: Intel NUC x86
 - Version: 0.3.05 and updated to 0.3.17
  
**Additional context**
I observed and checked this behaviour on the current PC image (mynode_amd64_0-3-05_uefi.img.gz), but I have the strong suspicion that this behaviour of Dojo is present on **all** platform images.

**Comment by tehelsper** [comment]
Are you saying Dojo starts failing every time a new SD card is flashed? It should work alright due to it being stored on the external drive. After re-flashing, did you need to re-install Dojo or just enable it?

**Comment by lasermind** [comment]
No, Dojo is not failing, it works – but somehow it kept the default passwords from day 1 and never created new ones.

Yes, after flashing a new system image, Dojo just needed to be "enabled" – and not "installed".

**Comment by lasermind** [comment]
Can not reproduce this any longer. How ever this did happen, it seems a thing of the past now.

I tried a fresh flash of the PC image v0.3.18 on a completely new machine that has never seen MyNode before. After Dojo was installed, the `docker-node.conf` had strong passwords generated in it.

So, it actually seems to work – closing here.
