### ISSUE TITLE
Bitcoin shows 795819 and LND stuck at "waiting" or "syncing"

### ISSUE THREAD

**Issue by Noderunner2009** [mynodebtc/mynode#801]
Labels
[bug]
Background
Please help me.
Bitcoin node is green and synced but LND all of a sudden has stopped showing lightning wallet and is stuck at status either "syncing" or "waiting" - Have tried multiple reboots and even upgrading node to no avail. Latest try has been online for 11 days but still no change. I have not been able to see off-chain nor on-chain balance for the last month.

Your environment
LND version 0.16.3
I believe before upgrade it was 0.16.2 I think
linux x86
RAM 4gb
cpu usage: 78%
ram usage: 43%

Log paste dump:
-- Logs begin at Sat 2023-07-15 14:45:18 CDT, end at Sat 2023-07-15 16:58:43 CDT. --
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.895 [INF] LTND: Waiting for chain backend to finish sync, start_height=795819
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.893 [INF] LTND: We're not running within systemd or the service type is not 'notify'
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.891 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.890 [INF] LTND: Channel backup proxy channel notifier starting
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.881 [INF] HSWC: Trimming open circuits for chan_id=741926:1718:1, start_htlc_id=15
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.880 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.879 [INF] HSWC: Restoring in-memory circuit state from disk
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.879 [INF] HSWC: Finished cleaning: num_closed_channel=1, num_circuits=0, num_keystone=0
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.878 [INF] HSWC: Cleaning circuits from disk for closed channels
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.722 [INF] TORC: Starting tor controller
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.721 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=true)! NOTE: Ensure the backend node is proxying over Tor as well
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.715 [INF] CHRE: LightningWallet opened
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.710 [INF] LNWL: The wallet has been unlocked without a time limit
Jul 15 16:57:59 mynode lnd[3143]: 2023-07-15 16:57:59.023 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: the RPC server is in the process of starting up, but not yet ready to accept calls
Jul 15 16:57:58 mynode lnd[3143]: 2023-07-15 16:57:58.419 [INF] LNWL: Started polling mempool to cache new transactions
Jul 15 16:57:58 mynode lnd[3143]: 2023-07-15 16:57:58.418 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 127.0.0.1:28333
Jul 15 16:57:58 mynode lnd[3143]: 2023-07-15 16:57:58.415 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 127.0.0.1:28332
Jul 15 16:57:58 mynode lnd[3143]: 2023-07-15 16:57:58.414 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
Jul 15 16:57:58 mynode systemd[1]: Started LND Lightning Daemon.
Jul 15 16:57:58 mynode lnd[3143]: 2023-07-15 16:57:58.361 [INF] CHRE: Primary chain is set to: bitcoin
Jul 15 16:57:58 mynode lnd[3143]: 2023-07-15 16:57:58.210 [INF] LNWL: Opened wallet
Jul 15 16:57:55 mynode lnd[3143]: 2023-07-15 16:57:55.609 [INF] LTND: Attempting automatic wallet unlock with password provided in file
Jul 15 16:57:55 mynode lnd[3143]: 2023-07-15 16:57:55.609 [INF] LTND: Database(s) now open (time_to_open=6.883434629s)!
Jul 15 16:57:55 mynode lnd[3143]: 2023-07-15 16:57:55.609 [INF] CHDB: Checking for optional update: prune_revocation_log=false, db_version=empty
Jul 15 16:57:55 mynode lnd[3143]: 2023-07-15 16:57:55.609 [INF] CHDB: Checking for schema update: latest_version=29, db_version=29
Jul 15 16:57:54 mynode lnd[3143]: 2023-07-15 16:57:54.794 [INF] LTND: Creating local graph and channel state DB instances
Jul 15 16:57:54 mynode lnd[3143]: 2023-07-15 16:57:54.793 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/sphinxreplay.db, it was last compacted at 2023-07-10 08:20:02.522938064 -0500 CDT (128h37m52s ago), min age is set to 168h0m0s
Jul 15 16:57:54 mynode lnd[3143]: 2023-07-15 16:57:54.790 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/chain/bitcoin/mainnet/macaroons.db, it was last compacted at 2023-07-10 08:20:02.506577955 -0500 CDT (128h37m52s ago), min age is set to 168h0m0s
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.726 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/channel.db, it was last compacted at 2023-07-10 08:20:02.456828264 -0500 CDT (128h37m46s ago), min age is set to 168h0m0s
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.725 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.725 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.724 [INF] RPCS: gRPC proxy started at 0.0.0.0:10080
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.614 [INF] RPCS: RPC server listening on 0.0.0.0:10009
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.604 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 15 16:57:48 mynode lnd[3143]: 2023-07-15 16:57:48.604 [INF] LTND: Version: 0.16.3-beta commit=v0.16.3-beta, build=production, logging=default, debuglevel=info
Jul 15 16:57:48 mynode lnd[3143]: Automatically obtained bitcoind's RPC credentials
Jul 15 16:57:48 mynode lnd[3143]: Attempting automatic RPC configuration to bitcoind
Jul 15 16:57:48 mynode lnd[3133]: + exit 0
Jul 15 16:57:48 mynode lnd[3133]: }
Jul 15 16:57:48 mynode lnd[3133]: "warnings": ""
Jul 15 16:57:48 mynode lnd[3133]: "pruned": false,
Jul 15 16:57:48 mynode lnd[3133]: "size_on_disk": 557385786335,
Jul 15 16:57:48 mynode lnd[3133]: "chainwork": "00000000000000000000000000000000000000004cc1b5619622cf63d88894b4",
Jul 15 16:57:48 mynode lnd[3133]: "initialblockdownload": true,
Jul 15 16:57:48 mynode lnd[3133]: "verificationprogress": 0.9924327005575559,
Jul 15 16:57:48 mynode lnd[3133]: "mediantime": 1687676077,
Jul 15 16:57:48 mynode lnd[3133]: "time": 1687680428,
Jul 15 16:57:48 mynode lnd[3133]: "difficulty": 52350439455487.47,
Jul 15 16:57:48 mynode lnd[3133]: "bestblockhash": "00000000000000000002fe975aa5bb4e197fab49385b75a3f19a5eee78f0c598",
Jul 15 16:57:48 mynode lnd[3133]: "headers": 795819,
Jul 15 16:57:48 mynode lnd[3133]: "blocks": 795819,
Jul 15 16:57:48 mynode lnd[3133]: "chain": "main",
Jul 15 16:57:48 mynode lnd[3133]: {
Jul 15 16:57:48 mynode lnd[3133]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Jul 15 16:57:48 mynode lnd[3133]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Jul 15 16:57:48 mynode lnd[3133]: Checking if Bitcoin is synced...
Jul 15 16:57:48 mynode lnd[3133]: + echo 'Checking if Bitcoin is synced...'
Jul 15 16:57:48 mynode lnd[3133]: + set -e
Jul 15 16:57:48 mynode lnd[3130]: Not shutting down!
Jul 15 16:57:48 mynode lnd[3130]: Checking if device is shutting down...
Jul 15 16:57:48 mynode systemd[1]: Starting LND Lightning Daemon...
Jul 15 16:57:48 mynode systemd[1]: Stopped LND Lightning Daemon.
Jul 15 16:57:48 mynode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 65.
Jul 15 16:57:48 mynode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Jul 15 16:57:47 mynode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 15 16:57:47 mynode systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 15 16:57:47 mynode lnd[26929]: net/http/transport.go:1765 +0x16ea
Jul 15 16:57:47 mynode lnd[26929]: created by net/http.(*Transport).dialConn
Jul 15 16:57:47 mynode lnd[26929]: net/http/transport.go:2122 +0x3aa
Jul 15 16:57:47 mynode lnd[26929]: net/http.(*persistConn).readLoop(0xc0064b9c20)
Jul 15 16:57:47 mynode lnd[26929]: net/http/transport.go:2300 +0xda
Jul 15 16:57:47 mynode lnd[26929]: net/http.(*persistConn).readResponse(0xc0064b9c20, {{}, 0xc000e5c900, {0xc000e5c800}, 0xc000de5aa0, 0x1, 0x0, 0xc000de5a40}, 0x0)
Jul 15 16:57:47 mynode lnd[26929]: net/http/response.go:161 +0xa6
Jul 15 16:57:47 mynode lnd[26929]: net/http.ReadResponse(0xc001da88a0, 0xc000e5c900)
Jul 15 16:57:47 mynode lnd[26929]: net/textproto/reader.go:39
Jul 15 16:57:47 mynode lnd[26929]: net/textproto.(*Reader).ReadLine(...)
Jul 15 16:57:47 mynode lnd[26929]: net/textproto/reader.go:53 +0x1b4
Jul 15 16:57:47 mynode lnd[26929]: net/textproto.(*Reader).readLineSlice(0xc001aa5c88)
Jul 15 16:57:47 mynode lnd[26929]: net/textproto/reader.go:417
Jul 15 16:57:47 mynode lnd[26929]: net/textproto.(*Reader).closeDot(...)
Jul 15 16:57:47 mynode lnd[26929]: net/textproto/reader.go:332 +0x27
Jul 15 16:57:47 mynode lnd[26929]: net/textproto.(*dotReader).Read(0x40, {0xc001aa5b38, 0x80, 0xc001aa5b20?})
Jul 15 16:57:47 mynode lnd[26929]: goroutine 959808 [running]:
Jul 15 16:57:47 mynode lnd[26929]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x662fc7]
Jul 15 16:57:47 mynode lnd[26929]: panic: runtime error: invalid memory address or nil pointer dereference

Steps to reproduce
Perhaps improper reboot on node

Expected behaviour
After reboot, LND should connect & show off-chain & onchain balance upon bitcoin sync.

Actual behaviour
LND doesn't show wallet balances and is stuck alternating between "syncing" and "waiting"

**Comment by Noderunner2009** [comment]
MyNode version 0.3.18
Bitcoin log seems normal with current blockheight HOWEVER the gui shows blcoks & headers & transactions stuck at 795819 and mempool size 0.0mb

**Comment by tehelsper** [comment]
You can log a support ticket and we can take a further look at the LND and Bitcoin logs. For this issue, I would re-flash the OS image. Looks like corruption with the LND binary or LND data causing a segfault.

Jul 15 16:57:47 mynode lnd[26929]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x662fc7]

**Comment by Noderunner2009** [comment]
> You can log a support ticket and we can take a further look at the LND and Bitcoin logs. For this issue, I would re-flash the OS image. Looks like corruption with the LND binary or LND data causing a segfault.
> 
> Jul 15 16:57:47 mynode lnd[26929]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x662fc7]

Thank you for taking time to reply but (1) how do i log a support ticket, are 'issues' not that? and (2) are my off-chain & onchain funds presumably safe if I reflash the OS image? and (3) how do i or how should I reflash the OS image?

**Comment by tehelsper** [comment]
You can log a support ticket by visiting [mynodebtc.com/support](https://mynodebtc.com/premium_support) and registering an account with your product key.

Yes, you can reflash. All LND data is stored on the data drive. Here's a guide:

https://mynodebtc.github.io/advanced/flash-sd-card.html
