### ISSUE TITLE
QR code for pairing wallet is not shown for Lightning pairing options 

### ISSUE THREAD

**Issue by tukac** [mynodebtc/mynode#804]
After recent upgrades QR codes are not shown for pairing wallet using Lightning (gRPC/REST + Local IP/Tor) and Zap (Local IP/Tor) options. QR codes for BlueWallet are shown ok.

MacOS Ventura 13.4.1
Browsers latest Chrome, Firefox and Safari
Device: RPi4 8Gb, 1Tb SSD

Some people have reported same issue on Telegram channel.

**Comment by sinkerballer** [comment]
Same issue here

MacOS Ventura 13.2.1
Latest Chrome
RPi4 4GB, 1TB SSD

**Comment by tehelsper** [comment]
If it's just the QR code, you may just need to reboot the device or force refresh your browser window to clear the cache. You can also use the text below the image.

**Comment by tukac** [comment]
> If it's just the QR code, you may just need to reboot the device or force refresh your browser window to clear the cache. You can also use the text below the image.

I refreshed browsers and rebooted both Mac and Mynode, no improvements.

Text bellow empty frame is "EXCEPTION".

**Comment by tukac** [comment]
My last upgrade didn't complete well, so I figured it might be the reason. I tried every option in Settings to re-install, nothing helped.

I tried:
```
sudo apt-get update
```
but it didn't complete due to this error 
`Problem with MergeList /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_i18n_Translation-en`

Then I run:
```
sudo rm -vf /var/lib/apt/lists/*
sudo apt-get update
sudo apt-get upgrade
```
It took a lot of time but finished ok. After reboot I retried in Settings `Re-install latest version` and this time it completed well, together with all apps being updated.

However the original issue remained. I still can't get QR codes and text bellow is `EXCEPTION`.

**Comment by tehelsper** [comment]
That's unusual and makes me think the SD card may have some corrupt data. This command may show more helpful info and we can take a look at the logs if you open a support ticket. There doesn't seem to be a software issue.

sudo systemctl status lndconnect.service

**Comment by tehelsper** [comment]
Oh wow, thanks for the info! Lndconnect is only enabled once during initial setup. I'm not sure how it got disabled, but I can add a re-enable to the upgrade script to resolve the issue automatically for anyone else who had issues.
