### ISSUE TITLE
Bump btc-rpc-explorer

### ISSUE THREAD

**Issue by ok300** [mynodebtc/mynode#810]
Please upgrade btc-rpc-explorer to the latest v3.4.0.

For it to work, it needs nodejs to be upgraded to v16.x.

I've been running this setup for a while and haven't seen any problems.

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Thanks for letting me know it works well. A new release is about to be posted with an update to NodeJS v18.x and and the latest btc rpc explorer. Let me know if it works!

**Comment by ok300** [comment]
Done in v0.3.20, thanks.
