### ISSUE TITLE
Docker missing after upgrade

### ISSUE THREAD

**Issue by BTCxZelko** [mynodebtc/mynode#82]
I upgraded from 0.16.8 to 0.17.0 and docker was no longer installed. The docker.service file was still there but was not running.

Currently re-installing now

**Comment by tehelsper** [comment]
Any update? What does "sudo systemctl status docker" say?

It may be as simple as "sudo systemctl status enable" but that is supposed to happen at the end of the upgrade.

**Comment by BTCxZelko** [comment]
Tried both. Docker wasnot installed after upgrade. I installed using the docker script and rebooted. All worked after that.
