### ISSUE TITLE
Installation stuck and cannot continue

### ISSUE THREAD

**Issue by jiaxinonly** [mynodebtc/mynode#834]
**Describe the bug**
sudo bash ./mynode_setup.sh online
Installation stuck and cannot continue
![image](https://github.com/mynodebtc/mynode/assets/57223696/4ec95f5f-26cf-4512-b244-a8ec2f99c985)
I don't know what's going on, it keeps going here without any progress, does it require me to configure something?
This is my system
![image](https://github.com/mynodebtc/mynode/assets/57223696/e4029d53-442b-4ea4-938a-8aee74c6235b)

**Comment by tehelsper** [comment]
It could be the language. Some scripts rely on the OS settings being in English or output is not processed properly.

**Comment by jiaxinonly** [comment]
I am indeed using the Chinese system language. Maybe that is the problem. I have not verified it. I have installed it in the virtual machine using the img image.
