### ISSUE TITLE
allow PCIe NVMe on Raspberry Pi 5

### ISSUE THREAD

**Issue by svrgnty** [mynodebtc/mynode#856]
With the availability of hats that allow to use NVMe on a Raspberry Pi 5,  like Pineberry Pi or Pimoroni, it would be nice to have support for the use of an NVMe.
Currently, it does not seem fully supported.

**Comment by hugues-michel** [comment]
I have a Rasberry Pi5 which boots very well on the M2.NVMe. (Without SD card of course)

I tested the installation of "Raspberry Pi OS" based on Debian Bookworm, which works very well. Using the "dd" command, I write the file "2023-12-05-raspios-bookworm-arm64.img" directly to the M2.NVMe connected to a USB3 adapter. Then I connect the NVMe to the hat. I turn on power On and it installs correctly.

I did the same thing with MyNode Raspberry Pi 5 v0.3.24 beta
"mynode_raspi45_0-3-24.img"
System installation is correct and very fast.
My problem is: "Looking for Drive - Please attach a drive to your MyNode" !!!

I did :
admin@mynode:~ $ lsblk -f
NAME        FSTYPE FSVER LABEL  UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
nvme0n1                                                                             
├─nvme0n1p1 vfat   FAT32 bootfs 5DF9-E225                             448.1M    12% /boot/firmware
└─nvme0n1p2 ext4   1.0   rootfs 3b614a3f-4a65-4480-876a-8a998e01ac9b    1.8T     0% /var/hdd.log
                                                                                    /


I'll try resizing the partition file system "nvme0n1p2" with resize2fs ...

I'll come back here to let you know if it works

**Comment by tehelsper** [comment]
Oh, you will still need two drives due to the design of keeping the OS and data separate. Both drives should be able to be nvme.

**Comment by svrgnty** [comment]
Ok, that was the issue. I was doing the same with one MVME. I had tried to boot from SD and use NVMe for data. but was getting the "looking for drive" message. Thought that was and error, did not wait for it to mount the drive. Now that it's mounted, all works

**Comment by hugues-michel** [comment]
@tehelsper 
All right, I understand the need to separate the OS from the data. I've been using the Rasberry Pi for a very long time and I've always had problems with SD cards at one time or another. Sometimes it takes years, but SD cards always die, even the best ones.
I'm going to follow the lead of 2 x M2.NVME. Some HAT card manufacturers will offer 2 slots.

Thanks for your reply, have a nice day.
