### ISSUE TITLE
Problem on Raspi5 initial login

### ISSUE THREAD

**Issue by Chemaclass** [mynodebtc/mynode#859]
**Describe the bug**

I freshly installed Raspberry Pi 5 | [Download v0.3.24](https://mynodebtc.com/device/mynode_images/mynode_raspi45_0-3-24.img.gz) (beta) in my new raspi5. However, when I try to log in, it seems there is an error when using the default password `bolt`

https://github.com/mynodebtc/mynode/assets/5256287/e95bce08-0d64-4425-9c3e-fee01d92f49f

Here, changing the input type from `password` to `text`, to make sure I am using the right characters:

https://github.com/mynodebtc/mynode/assets/5256287/6eb48095-9fb1-4a50-9ba0-b75cdf95bad3

**Expected behavior**
The default password `bolt` should work on the very first initial setup when using a new raspi5 and a new ssd disk.

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version: 1.64.116 `Chromium: 123.0.6312.105 (Official Build) (arm64)`

**MyNode hardware (please complete the following information):**
 - Device: Raspi5
 - Version [v0.3.24](https://mynodebtc.com/device/mynode_images/mynode_raspi45_0-3-24.img.gz) (beta)

**Comment by tehelsper** [comment]
Can you try re-flashing the SD card again? There may have been an issue with the download as well. That image has been tested on several raspi 5s, so I doubt its a problem with the image itself.

If you connect with SSH, does admin / bolt work as a login?

**Comment by Chemaclass** [comment]
Thanks for the feedback! It worked after re-flashing.
