### ISSUE TITLE
Change the size in MyNode . OVA OS Disk

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [mynodebtc/mynode#860]
**Is your content request related to a problem? Please describe.**
We need OS Disk on 01.vdi SATA 0 a change of size by default.

**Describe the solution you'd like**
Now 16GB, change it to 32GB.

**Additional context**
OS Disk Usage | 100%
Data Disk Usage | 15% 

Thanks in advance.

**Comment by SatoshiNakamotoBitcoin** [comment]
Temporary Solution.

Virtual Box - Tools - Disks
Double Click mynodevm01disk.vdi
Change size 16GB to 32GB.
Run Mynode . ova Machine again.

**Comment by tehelsper** [comment]
New versions of the VM image have a 32GB OS drive. Did you start with the v0.3.24 image or a previous one?

**Comment by SatoshiNakamotoBitcoin** [comment]
OGs you know...

Since first OVA to now updating.

:/
