### ISSUE TITLE
Uppercase I vs lowercase l vs #1

### ISSUE THREAD

**Issue by Rampelflik** [mynodebtc/mynode#87]
Would propose a different font.
Something so we can easily differentiate between uppercase I (i) vs lowercase l (L) and the number 1.

Currently, mistakes are easily made as I & l look alike. 

A font that would work extremely well: 
Solway

i (i) - I (i) - l (L) - L (L) - 1 looks like this in Solway:
![image](https://user-images.githubusercontent.com/43671869/70053350-8c0b7580-15d5-11ea-83f3-476377de4139.png)

Currently Arial and Helvetica are default and i (i) - I (i) - l (L) - L (L) - 1 looks like this:
![image](https://user-images.githubusercontent.com/43671869/70053537-eefd0c80-15d5-11ea-9caa-aa8d0bc0db78.png)
![image](https://user-images.githubusercontent.com/43671869/70053578-04723680-15d6-11ea-91d2-e867941ddf4b.png)

**Comment by Amiga500** [comment]
Interesting..

**Comment by tehelsper** [comment]
Aging out.
