### ISSUE TITLE
Request list of firewall ports opened by default

### ISSUE THREAD

**Issue by naphelge** [mynodebtc/mynode#876]
**Is your content request related to a problem? No problem**
I would like to know what all the open ports in the firewall are for so I can delete what rules are not needed

**Describe the solution you'd like**
I searched for a list of the the default firewall ports with description, so I could delete the rules that do not need to be opened in order to lock things down a little tighter

**Additional context**

- [ ] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Here's the list.
https://github.com/mynodebtc/mynode/blob/master/rootfs/standard/usr/bin/mynode_firewall.sh
