### ISSUE TITLE
PGP verification of critical applications

### ISSUE THREAD

**Issue by openoms** [mynodebtc/mynode#9]
Hi, I really like your project especially that your code is fully available and that there is a DIY option.
Would like to have a suggestion which would make me more comfortable trying out the software.

Just like you are providing it for the SDcard images Bitcoin and LND offers PGP signatures (and sha256 hashes) to verify the downloaded packages against tampering or corruption. The checks could run automatically in https://github.com/mynodebtc/mynode/blob/master/setup/setup_device.sh which would make the manual setup and SDcard images more robust.

**Comment by tehelsper** [comment]
LND and Bitcoin Core both automatically verify PGP keys! Check out version 0.1.53+.
